
var jxl_dec = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(jxl_dec) {
  jxl_dec = jxl_dec || {};


var e;e||(e=typeof jxl_dec !== 'undefined' ? jxl_dec : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var r={},w;for(w in e)e.hasOwnProperty(w)&&(r[w]=e[w]);var ca="./this.program",da=!1,x=!1,ea=!1,fa=!1;da="object"===typeof window;x="function"===typeof importScripts;ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;fa=!da&&!ea&&!x;var z="",ia,A,ja,ka;
if(ea)z=x?require("path").dirname(z)+"/":__dirname+"/",ia=function(a,b){ja||(ja=require("fs"));ka||(ka=require("path"));a=ka.normalize(a);return ja.readFileSync(a,b?null:"utf8")},A=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||B("Assertion failed: undefined");return a},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",B),e.inspect=function(){return"[Emscripten Module object]"};
else if(fa)"undefined"!=typeof read&&(ia=function(a){return read(a)}),A=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||B("Assertion failed: undefined");return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(da||x)x?z=self.location.href:document.currentScript&&(z=document.currentScript.src),_scriptDir&&
(z=_scriptDir),0!==z.indexOf("blob:")?z=z.substr(0,z.lastIndexOf("/")+1):z="",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},x&&(A=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var la=e.print||console.log.bind(console),E=e.printErr||console.warn.bind(console);for(w in r)r.hasOwnProperty(w)&&(e[w]=r[w]);r=null;e.thisProgram&&(ca=e.thisProgram);var F;
e.wasmBinary&&(F=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&B("no native wasm support detected");var G,ma=new WebAssembly.Table({initial:564,maximum:564,element:"anyfunc"}),na=!1,oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function pa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&oa)return oa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function qa(a,b,c){var d=H;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function sa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ta[c];)++c;c<<=1;if(32<c-a&&ra)return ra.decode(H.subarray(a,c));c=0;for(d="";;){var f=I[a+2*c>>1];if(0==f||c==b/2)return d;++c;d+=String.fromCharCode(f)}}function ua(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)I[b>>1]=a.charCodeAt(f),b+=2;I[b>>1]=0;return b-d}function va(a){return 2*a.length}
function wa(a,b){for(var c=0,d="";!(c>=b/4);){var f=J[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function xa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}J[b>>2]=g;b+=4;if(b+4>c)break}J[b>>2]=0;return b-d}
function ya(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var K,L,H,I,ta,J,M,za,Aa;function Ba(a){K=a;e.HEAP8=L=new Int8Array(a);e.HEAP16=I=new Int16Array(a);e.HEAP32=J=new Int32Array(a);e.HEAPU8=H=new Uint8Array(a);e.HEAPU16=ta=new Uint16Array(a);e.HEAPU32=M=new Uint32Array(a);e.HEAPF32=za=new Float32Array(a);e.HEAPF64=Aa=new Float64Array(a)}var Ca=e.INITIAL_MEMORY||16777216;e.wasmMemory?G=e.wasmMemory:G=new WebAssembly.Memory({initial:Ca/65536,maximum:32768});
G&&(K=G.buffer);Ca=K.byteLength;Ba(K);J[58052]=5475248;function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.wa;"number"===typeof c?void 0===b.oa?e.dynCall_v(c):e.dynCall_vi(c,b.oa):c(void 0===b.oa?null:b.oa)}}}var Ea=[],Fa=[],Ga=[],Ha=[];function Ia(){var a=e.preRun.shift();Ea.unshift(a)}var Ja=Math.ceil,Ka=Math.floor,N=0,La=null,Ma=null;e.preloadedImages={};e.preloadedAudios={};
function B(a){if(e.onAbort)e.onAbort(a);E(a);na=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Na(a){var b=O;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Oa(){return Na("data:application/octet-stream;base64,")}var O="jxl_dec.wasm";if(!Oa()){var Pa=O;O=e.locateFile?e.locateFile(Pa,z):z+Pa}
function Qa(){try{if(F)return new Uint8Array(F);if(A)return A(O);throw"both async and sync fetching of the wasm failed";}catch(a){B(a)}}function Ra(){return F||!da&&!x||"function"!==typeof fetch||Na("file://")?new Promise(function(a){a(Qa())}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Qa()})}Fa.push({wa:function(){Sa()}});function Ta(){return 0<Ta.ja}
function Ua(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Va=void 0;function P(a){for(var b="";H[a];)b+=Va[H[a++]];return b}var Q={},R={},Wa={};function Xa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Ya(a,b){a=Xa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Za(a){var b=Error,c=Ya(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var $a=void 0;function S(a){throw new $a(a);}var ab=void 0;function bb(a){throw new ab(a);}function cb(a,b,c){function d(k){k=c(k);k.length!==a.length&&bb("Mismatched type converter count");for(var h=0;h<a.length;++h)T(a[h],k[h])}a.forEach(function(k){Wa[k]=b});var f=Array(b.length),g=[],l=0;b.forEach(function(k,h){R.hasOwnProperty(k)?f[h]=R[k]:(g.push(k),Q.hasOwnProperty(k)||(Q[k]=[]),Q[k].push(function(){f[h]=R[k];++l;l===g.length&&d(f)}))});0===g.length&&d(f)}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(c.za)return;S("Cannot register type '"+d+"' twice")}R[a]=b;delete Wa[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(function(f){f()}))}function db(a){return{count:a.count,ia:a.ia,ka:a.ka,Y:a.Y,$:a.$,aa:a.aa,ba:a.ba}}
function eb(a){S(a.X.$.Z.name+" instance already deleted")}var fb=!1;function gb(){}function hb(a){--a.count.value;0===a.count.value&&(a.aa?a.ba.ha(a.aa):a.$.Z.ha(a.Y))}function ib(a){if("undefined"===typeof FinalizationGroup)return ib=function(b){return b},a;fb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Y?hb(c):console.warn("object already deleted: "+c.Y)});ib=function(b){fb.register(b,b.X,b.X);return b};gb=function(b){fb.unregister(b.X)};return ib(a)}
var jb=void 0,kb=[];function lb(){for(;kb.length;){var a=kb.pop();a.X.ia=!1;a["delete"]()}}function U(){}var mb={};function nb(a,b){var c=e;if(void 0===c[a].ea){var d=c[a];c[a]=function(){c[a].ea.hasOwnProperty(arguments.length)||S("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].ea+")!");return c[a].ea[arguments.length].apply(this,arguments)};c[a].ea=[];c[a].ea[d.ta]=d}}
function ob(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].ea&&void 0!==e[a].ea[c])&&S("Cannot register public name '"+a+"' twice"),nb(a,a),e.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].ea[c]=b):(e[a]=b,void 0!==c&&(e[a].Fa=c))}function pb(a,b,c,d,f,g,l,k){this.name=a;this.constructor=b;this.ga=c;this.ha=d;this.da=f;this.xa=g;this.la=l;this.va=k}
function qb(a,b,c){for(;b!==c;)b.la||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.la(a),b=b.da;return a}function rb(a,b){if(null===b)return this.pa&&S("null is not a valid "+this.name),0;b.X||S('Cannot pass "'+V(b)+'" as a '+this.name);b.X.Y||S("Cannot pass deleted object as a pointer of type "+this.name);return qb(b.X.Y,b.X.$.Z,this.Z)}
function sb(a,b){if(null===b){this.pa&&S("null is not a valid "+this.name);if(this.na){var c=this.Ba();null!==a&&a.push(this.ha,c);return c}return 0}b.X||S('Cannot pass "'+V(b)+'" as a '+this.name);b.X.Y||S("Cannot pass deleted object as a pointer of type "+this.name);!this.ma&&b.X.$.ma&&S("Cannot convert argument of type "+(b.X.ba?b.X.ba.name:b.X.$.name)+" to parameter type "+this.name);c=qb(b.X.Y,b.X.$.Z,this.Z);if(this.na)switch(void 0===b.X.aa&&S("Passing raw pointer to smart pointer is illegal"),
this.Da){case 0:b.X.ba===this?c=b.X.aa:S("Cannot convert argument of type "+(b.X.ba?b.X.ba.name:b.X.$.name)+" to parameter type "+this.name);break;case 1:c=b.X.aa;break;case 2:if(b.X.ba===this)c=b.X.aa;else{var d=b.clone();c=this.Ca(c,tb(function(){d["delete"]()}));null!==a&&a.push(this.ha,c)}break;default:S("Unsupporting sharing policy")}return c}
function ub(a,b){if(null===b)return this.pa&&S("null is not a valid "+this.name),0;b.X||S('Cannot pass "'+V(b)+'" as a '+this.name);b.X.Y||S("Cannot pass deleted object as a pointer of type "+this.name);b.X.$.ma&&S("Cannot convert argument of type "+b.X.$.name+" to parameter type "+this.name);return qb(b.X.Y,b.X.$.Z,this.Z)}function vb(a){return this.fromWireType(M[a>>2])}function wb(a,b,c){if(b===c)return a;if(void 0===c.da)return null;a=wb(a,b,c.da);return null===a?null:c.va(a)}var xb={};
function zb(a,b){for(void 0===b&&S("ptr should not be undefined");a.da;)b=a.la(b),a=a.da;return xb[b]}function Ab(a,b){b.$&&b.Y||bb("makeClassHandle requires ptr and ptrType");!!b.ba!==!!b.aa&&bb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ib(Object.create(a,{X:{value:b}}))}
function W(a,b,c,d){this.name=a;this.Z=b;this.pa=c;this.ma=d;this.na=!1;this.ha=this.Ca=this.Ba=this.sa=this.Da=this.Aa=void 0;void 0!==b.da?this.toWireType=sb:(this.toWireType=d?rb:ub,this.fa=null)}function Bb(a,b,c){e.hasOwnProperty(a)||bb("Replacing nonexistant public symbol");void 0!==e[a].ea&&void 0!==c?e[a].ea[c]=b:(e[a]=b,e[a].ta=c)}
function X(a,b){a=P(a);var c=e["dynCall_"+a];for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Cb=void 0;function Db(a){a=Eb(a);var b=P(a);Y(a);return b}
function Fb(a,b){function c(g){f[g]||R[g]||(Wa[g]?Wa[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Cb(a+": "+d.map(Db).join([", "]));}function Gb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Hb(a,b,c){a instanceof Object||S(c+' with invalid "this": '+a);a instanceof b.Z.constructor||S(c+' incompatible with "this" of type '+a.constructor.name);a.X.Y||S("cannot call emscripten binding method "+c+" on deleted object");return qb(a.X.Y,a.X.$.Z,b.Z)}
var Ib=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Jb(a){4<a&&0===--Z[a].qa&&(Z[a]=void 0,Ib.push(a))}function tb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ib.length?Ib.pop():Z.length;Z[b]={qa:1,value:a};return b}}function V(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Kb(a,b){switch(b){case 2:return function(c){return this.fromWireType(za[c>>2])};case 3:return function(c){return this.fromWireType(Aa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Lb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ya(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Mb(a,b){for(var c=[],d=0;d<a;d++)c.push(J[(b>>2)+d]);return c}function Nb(a,b,c){switch(b){case 0:return c?function(d){return L[d]}:function(d){return H[d]};case 1:return c?function(d){return I[d>>1]}:function(d){return ta[d>>1]};case 2:return c?function(d){return J[d>>2]}:function(d){return M[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Ob={};
function Pb(){if(!Qb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Ob)a[b]=Ob[b];var c=[];for(b in a)c.push(b+"="+a[b]);Qb=c}return Qb}for(var Qb,Rb=[null,[],[]],Sb=Array(256),Tb=0;256>Tb;++Tb)Sb[Tb]=String.fromCharCode(Tb);Va=Sb;$a=e.BindingError=Za("BindingError");ab=e.InternalError=Za("InternalError");
U.prototype.isAliasOf=function(a){if(!(this instanceof U&&a instanceof U))return!1;var b=this.X.$.Z,c=this.X.Y,d=a.X.$.Z;for(a=a.X.Y;b.da;)c=b.la(c),b=b.da;for(;d.da;)a=d.la(a),d=d.da;return b===d&&c===a};U.prototype.clone=function(){this.X.Y||eb(this);if(this.X.ka)return this.X.count.value+=1,this;var a=ib(Object.create(Object.getPrototypeOf(this),{X:{value:db(this.X)}}));a.X.count.value+=1;a.X.ia=!1;return a};
U.prototype["delete"]=function(){this.X.Y||eb(this);this.X.ia&&!this.X.ka&&S("Object already scheduled for deletion");gb(this);hb(this.X);this.X.ka||(this.X.aa=void 0,this.X.Y=void 0)};U.prototype.isDeleted=function(){return!this.X.Y};U.prototype.deleteLater=function(){this.X.Y||eb(this);this.X.ia&&!this.X.ka&&S("Object already scheduled for deletion");kb.push(this);1===kb.length&&jb&&jb(lb);this.X.ia=!0;return this};W.prototype.ya=function(a){this.sa&&(a=this.sa(a));return a};
W.prototype.ra=function(a){this.ha&&this.ha(a)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=vb;W.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
W.prototype.fromWireType=function(a){function b(){return this.na?Ab(this.Z.ga,{$:this.Aa,Y:c,ba:this,aa:a}):Ab(this.Z.ga,{$:this,Y:a})}var c=this.ya(a);if(!c)return this.ra(a),null;var d=zb(this.Z,c);if(void 0!==d){if(0===d.X.count.value)return d.X.Y=c,d.X.aa=a,d.clone();d=d.clone();this.ra(a);return d}d=this.Z.xa(c);d=mb[d];if(!d)return b.call(this);d=this.ma?d.ua:d.pointerType;var f=wb(c,this.Z,d.Z);return null===f?b.call(this):this.na?Ab(d.Z.ga,{$:d,Y:f,ba:this,aa:a}):Ab(d.Z.ga,{$:d,Y:f})};
e.getInheritedInstanceCount=function(){return Object.keys(xb).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in xb)xb.hasOwnProperty(b)&&a.push(xb[b]);return a};e.flushPendingDeletes=lb;e.setDelayFunction=function(a){jb=a;kb.length&&jb&&jb(lb)};Cb=e.UnboundTypeError=Za("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Vb={A:function(a){return Ub(a)},z:function(a){"uncaught_exception"in Ta?Ta.ja++:Ta.ja=1;throw a;},y:function(a,b,c,d,f){var g=Ua(c);b=P(b);T(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=L;else if(2===c)k=I;else if(4===c)k=J;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>g])},fa:null})},p:function(a,b,c,d,f,g,l,k,h,p,m,q,t){m=P(m);g=X(f,g);k&&(k=X(l,
k));p&&(p=X(h,p));t=X(q,t);var u=Xa(m);ob(u,function(){Fb("Cannot construct "+m+" due to unbound types",[d])});cb([a,b,c],d?[d]:[],function(n){n=n[0];if(d){var D=n.Z;var v=D.ga}else v=U.prototype;n=Ya(u,function(){if(Object.getPrototypeOf(this)!==y)throw new $a("Use 'new' to construct "+m);if(void 0===C.ja)throw new $a(m+" has no accessible constructor");var yb=C.ja[arguments.length];if(void 0===yb)throw new $a("Tried to invoke ctor of "+m+" with invalid number of parameters ("+arguments.length+") - expected ("+
Object.keys(C.ja).toString()+") parameters instead!");return yb.apply(this,arguments)});var y=Object.create(v,{constructor:{value:n}});n.prototype=y;var C=new pb(m,n,y,t,D,g,k,p);D=new W(m,C,!0,!1);v=new W(m+"*",C,!1,!1);var ha=new W(m+" const*",C,!1,!0);mb[a]={pointerType:v,ua:ha};Bb(u,n);return[D,v,ha]})},d:function(a,b,c,d,f,g,l,k,h,p){b=P(b);f=X(d,f);cb([],[a],function(m){m=m[0];var q=m.name+"."+b,t={get:function(){Fb("Cannot access "+q+" due to unbound types",[c,l])},enumerable:!0,configurable:!0};
h?t.set=function(){Fb("Cannot access "+q+" due to unbound types",[c,l])}:t.set=function(){S(q+" is a read-only property")};Object.defineProperty(m.Z.ga,b,t);cb([],h?[c,l]:[c],function(u){var n=u[0],D={get:function(){var y=Hb(this,m,q+" getter");return n.fromWireType(f(g,y))},enumerable:!0};if(h){h=X(k,h);var v=u[1];D.set=function(y){var C=Hb(this,m,q+" setter"),ha=[];h(p,C,v.toWireType(ha,y));Gb(ha)}}Object.defineProperty(m.Z.ga,b,D);return[]});return[]})},x:function(a,b){b=P(b);T(a,{name:b,fromWireType:function(c){var d=
Z[c].value;Jb(c);return d},toWireType:function(c,d){return tb(d)},argPackAdvance:8,readValueFromPointer:vb,fa:null})},m:function(a,b,c){c=Ua(c);b=P(b);T(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+V(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Kb(b,c),fa:null})},g:function(a,b,c,d,f,g){var l=Mb(b,c);a=P(a);f=X(d,f);ob(a,function(){Fb("Cannot call "+a+" due to unbound types",
l)},b-1);cb([],l,function(k){var h=[k[0],null].concat(k.slice(1)),p=k=a,m=f,q=h.length;2>q&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var t=null!==h[1]&&!1,u=!1,n=1;n<h.length;++n)if(null!==h[n]&&void 0===h[n].fa){u=!0;break}var D="void"!==h[0].name,v="",y="";for(n=0;n<q-2;++n)v+=(0!==n?", ":"")+"arg"+n,y+=(0!==n?", ":"")+"arg"+n+"Wired";p="return function "+Xa(p)+"("+v+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+
(q-2)+" args!');\n}\n";u&&(p+="var destructors = [];\n");var C=u?"destructors":"null";v="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[S,m,g,Gb,h[0],h[1]];t&&(p+="var thisWired = classParam.toWireType("+C+", this);\n");for(n=0;n<q-2;++n)p+="var arg"+n+"Wired = argType"+n+".toWireType("+C+", arg"+n+"); // "+h[n+2].name+"\n",v.push("argType"+n),m.push(h[n+2]);t&&(y="thisWired"+(0<y.length?", ":"")+y);p+=(D?"var rv = ":"")+"invoker(fn"+(0<y.length?", ":"")+y+");\n";if(u)p+=
"runDestructors(destructors);\n";else for(n=t?1:2;n<h.length;++n)q=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==h[n].fa&&(p+=q+"_dtor("+q+"); // "+h[n].name+"\n",v.push(q+"_dtor"),m.push(h[n].fa));D&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");v.push(p+"}\n");h=Lb(v).apply(null,m);Bb(k,h,b-1);return[]})},b:function(a,b,c,d,f){function g(p){return p}b=P(b);-1===f&&(f=4294967295);var l=Ua(c);if(0===d){var k=32-8*c;g=function(p){return p<<k>>>k}}var h=-1!=b.indexOf("unsigned");T(a,{name:b,
fromWireType:g,toWireType:function(p,m){if("number"!==typeof m&&"boolean"!==typeof m)throw new TypeError('Cannot convert "'+V(m)+'" to '+this.name);if(m<d||m>f)throw new TypeError('Passing a number "'+V(m)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return h?m>>>0:m|0},argPackAdvance:8,readValueFromPointer:Nb(b,l,0!==d),fa:null})},a:function(a,b,c){function d(g){g>>=2;var l=M;return new f(K,l[g+1],l[g])}var f=[Int8Array,Uint8Array,
Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{za:!0})},n:function(a,b){b=P(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var f=M[d>>2];if(c)for(var g=d+4,l=0;l<=f;++l){var k=d+4+l;if(l==f||0==H[k]){g=g?pa(H,g,k-g):"";if(void 0===h)var h=g;else h+=String.fromCharCode(0),h+=g;g=k+1}}else{h=Array(f);for(l=0;l<f;++l)h[l]=String.fromCharCode(H[d+4+l]);h=h.join("")}Y(d);return h},
toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||S("Cannot pass non-string to std::string");var l=(c&&g?function(){for(var p=0,m=0;m<f.length;++m){var q=f.charCodeAt(m);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|f.charCodeAt(++m)&1023);127>=q?++p:p=2047>=q?p+2:65535>=q?p+3:p+4}return p}:function(){return f.length})(),k=Ub(4+l+1);M[k>>2]=l;if(c&&g)qa(f,k+4,l+1);else if(g)for(g=
0;g<l;++g){var h=f.charCodeAt(g);255<h&&(Y(k),S("String has UTF-16 code units that do not fit in 8 bits"));H[k+4+g]=h}else for(g=0;g<l;++g)H[k+4+g]=f[g];null!==d&&d.push(Y,k);return k},argPackAdvance:8,readValueFromPointer:vb,fa:function(d){Y(d)}})},e:function(a,b,c){c=P(c);if(2===b){var d=sa;var f=ua;var g=va;var l=function(){return ta};var k=1}else 4===b&&(d=wa,f=xa,g=ya,l=function(){return M},k=2);T(a,{name:c,fromWireType:function(h){for(var p=M[h>>2],m=l(),q,t=h+4,u=0;u<=p;++u){var n=h+4+u*b;
if(u==p||0==m[n>>k])t=d(t,n-t),void 0===q?q=t:(q+=String.fromCharCode(0),q+=t),t=n+b}Y(h);return q},toWireType:function(h,p){"string"!==typeof p&&S("Cannot pass non-string to C++ string type "+c);var m=g(p),q=Ub(4+m+b);M[q>>2]=m>>k;f(p,q+4,m+b);null!==h&&h.push(Y,q);return q},argPackAdvance:8,readValueFromPointer:vb,fa:function(h){Y(h)}})},o:function(a,b){b=P(b);T(a,{Ea:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},h:Jb,q:function(a){4<a&&(Z[a].qa+=1)},j:function(a,
b){var c=R[a];void 0===c&&S("_emval_take_value has unknown type "+Db(a));a=c.readValueFromPointer(b);return tb(a)},f:function(){B()},t:function(a,b,c){H.copyWithin(a,b,b+c)},c:function(a){a>>>=0;var b=H.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{G.grow(Math.min(2147483648,d)-K.byteLength+65535>>>16);Ba(G.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},u:function(a,
b){var c=0;Pb().forEach(function(d,f){var g=b+c;f=J[a+4*f>>2]=g;for(g=0;g<d.length;++g)L[f++>>0]=d.charCodeAt(g);L[f>>0]=0;c+=d.length+1});return 0},v:function(a,b){var c=Pb();J[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});J[b>>2]=d;return 0},w:function(){return 0},r:function(){},l:function(a,b,c,d){for(var f=0,g=0;g<c;g++){for(var l=J[b+8*g>>2],k=J[b+(8*g+4)>>2],h=0;h<k;h++){var p=H[l+h],m=Rb[a];0===p||10===p?((1===a?la:E)(pa(m,0)),m.length=0):m.push(p)}f+=k}J[d>>2]=f;return 0},memory:G,
i:function(a){a=+a;return 0<=a?+Ka(a+.5):+Ja(a-.5)},k:function(a){a=+a;return 0<=a?+Ka(a+.5):+Ja(a-.5)},s:function(){},table:ma};
(function(){function a(f){e.asm=f.exports;N--;e.monitorRunDependencies&&e.monitorRunDependencies(N);0==N&&(null!==La&&(clearInterval(La),La=null),Ma&&(f=Ma,Ma=null,f()))}function b(f){a(f.instance)}function c(f){return Ra().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){E("failed to asynchronously prepare wasm: "+g);B(g)})}var d={a:Vb};N++;e.monitorRunDependencies&&e.monitorRunDependencies(N);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return E("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(F||"function"!==typeof WebAssembly.instantiateStreaming||Oa()||Na("file://")||"function"!==typeof fetch)return c(b);fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){E("wasm streaming compile failed: "+g);E("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Sa=e.___wasm_call_ctors=function(){return(Sa=e.___wasm_call_ctors=e.asm.B).apply(null,arguments)},Ub=e._malloc=function(){return(Ub=e._malloc=e.asm.C).apply(null,arguments)},Y=e._free=function(){return(Y=e._free=e.asm.D).apply(null,arguments)},Eb=e.___getTypeName=function(){return(Eb=e.___getTypeName=e.asm.E).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.F).apply(null,arguments)};
e.dynCall_ii=function(){return(e.dynCall_ii=e.asm.G).apply(null,arguments)};e.dynCall_vi=function(){return(e.dynCall_vi=e.asm.H).apply(null,arguments)};e.dynCall_iii=function(){return(e.dynCall_iii=e.asm.I).apply(null,arguments)};e.dynCall_viii=function(){return(e.dynCall_viii=e.asm.J).apply(null,arguments)};e.dynCall_vii=function(){return(e.dynCall_vii=e.asm.K).apply(null,arguments)};e.dynCall_v=function(){return(e.dynCall_v=e.asm.L).apply(null,arguments)};
e.dynCall_iidiiii=function(){return(e.dynCall_iidiiii=e.asm.M).apply(null,arguments)};e.dynCall_iiiiiii=function(){return(e.dynCall_iiiiiii=e.asm.N).apply(null,arguments)};e.dynCall_viiiiiii=function(){return(e.dynCall_viiiiiii=e.asm.O).apply(null,arguments)};e.dynCall_iiii=function(){return(e.dynCall_iiii=e.asm.P).apply(null,arguments)};e.dynCall_iiiii=function(){return(e.dynCall_iiiii=e.asm.Q).apply(null,arguments)};e.dynCall_iiji=function(){return(e.dynCall_iiji=e.asm.R).apply(null,arguments)};
e.dynCall_iifi=function(){return(e.dynCall_iifi=e.asm.S).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.T).apply(null,arguments)};e.dynCall_viiiiii=function(){return(e.dynCall_viiiiii=e.asm.U).apply(null,arguments)};e.dynCall_viiiii=function(){return(e.dynCall_viiiii=e.asm.V).apply(null,arguments)};e.dynCall_viiii=function(){return(e.dynCall_viiii=e.asm.W).apply(null,arguments)};var Wb;Ma=function Xb(){Wb||Yb();Wb||(Ma=Xb)};
function Yb(){function a(){if(!Wb&&(Wb=!0,e.calledRun=!0,!na)){Da(Fa);Da(Ga);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Ha.unshift(b)}Da(Ha)}}if(!(0<N)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ia();Da(Ea);0<N||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
e.run=Yb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;Yb();


  return jxl_dec.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = jxl_dec;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return jxl_dec; });
    else if (typeof exports === 'object')
      exports["jxl_dec"] = jxl_dec;
    