
var jxl_dec = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(jxl_dec) {
  jxl_dec = jxl_dec || {};


var f;f||(f=typeof jxl_dec !== 'undefined' ? jxl_dec : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},l;for(l in f)f.hasOwnProperty(l)&&(ca[l]=f[l]);var da="./this.program",ea=!1,t=!1,fa=!1,ha=!1;ea="object"===typeof window;t="function"===typeof importScripts;fa="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ha=!ea&&!fa&&!t;var u="",ia,ja,ka,la;
if(fa)u=t?require("path").dirname(u)+"/":__dirname+"/",ia=function(a,b){ka||(ka=require("fs"));la||(la=require("path"));a=la.normalize(a);return ka.readFileSync(a,b?null:"utf8")},ja=function(a){a=ia(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",x),f.inspect=function(){return"[Emscripten Module object]"};else if(ha)"undefined"!=
typeof read&&(ia=function(a){return read(a)}),ja=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ea||t)t?u=self.location.href:document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,
u.lastIndexOf("/")+1):u="",ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ma=f.print||console.log.bind(console),A=f.printErr||console.warn.bind(console);for(l in ca)ca.hasOwnProperty(l)&&(f[l]=ca[l]);ca=null;f.thisProgram&&(da=f.thisProgram);var na;f.wasmBinary&&(na=f.wasmBinary);var noExitRuntime;
f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&x("no native wasm support detected");var C,oa=new WebAssembly.Table({initial:1141,maximum:1141,element:"anyfunc"}),pa=!1;function assert(a,b){a||x("Assertion failed: "+b)}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function sa(a,b){return a?ra(D,a,b):""}
function ta(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var k=a.charCodeAt(g);if(55296<=k&&57343>=k){var n=a.charCodeAt(++g);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function wa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&xa[c];)++c;c<<=1;if(32<c-a&&va)return va.decode(D.subarray(a,c));c=0;for(d="";;){var e=za[a+2*c>>1];if(0==e||c==b/2)return d;++c;d+=String.fromCharCode(e)}}
function Aa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)za[b>>1]=a.charCodeAt(e),b+=2;za[b>>1]=0;return b-d}function Ba(a){return 2*a.length}function Ca(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Da(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var k=a.charCodeAt(++e);g=65536+((g&1023)<<10)|k&1023}E[b>>2]=g;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}function Ea(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var F,G,D,za,xa,E,H,Fa,Ga;
function Ha(a){F=a;f.HEAP8=G=new Int8Array(a);f.HEAP16=za=new Int16Array(a);f.HEAP32=E=new Int32Array(a);f.HEAPU8=D=new Uint8Array(a);f.HEAPU16=xa=new Uint16Array(a);f.HEAPU32=H=new Uint32Array(a);f.HEAPF32=Fa=new Float32Array(a);f.HEAPF64=Ga=new Float64Array(a)}var Ia=f.INITIAL_MEMORY||16777216;f.wasmMemory?C=f.wasmMemory:C=new WebAssembly.Memory({initial:Ia/65536,maximum:32768});C&&(F=C.buffer);Ia=F.byteLength;Ha(F);E[60808]=5486272;
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.wb;"number"===typeof c?void 0===b.ab?f.dynCall_v(c):f.dynCall_vi(c,b.ab):c(void 0===b.ab?null:b.ab)}}}var Ka=[],La=[],Ma=[],Na=[];function Oa(){var a=f.preRun.shift();Ka.unshift(a)}var Pa=Math.abs,Qa=Math.ceil,Ra=Math.floor,Sa=Math.min,I=0,Ta=null,Ua=null;f.preloadedImages={};f.preloadedAudios={};
function x(a){if(f.onAbort)f.onAbort(a);A(a);pa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Va(a){var b=K;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Wa(){return Va("data:application/octet-stream;base64,")}var K="jxl_dec.wasm";if(!Wa()){var Xa=K;K=f.locateFile?f.locateFile(Xa,u):u+Xa}
function Ya(){try{if(na)return new Uint8Array(na);if(ja)return ja(K);throw"both async and sync fetching of the wasm failed";}catch(a){x(a)}}function Za(){return na||!ea&&!t||"function"!==typeof fetch||Va("file://")?new Promise(function(a){a(Ya())}):fetch(K,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+K+"'";return a.arrayBuffer()}).catch(function(){return Ya()})}var $a,ab;La.push({wb:function(){bb()}});function cb(){return 0<cb.Ka}
function db(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function eb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=db(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function fb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function gb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function hb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=db(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var ib=[];function jb(a,b){ib[a]={input:[],output:[],Pa:b};kb(a,lb)}
var lb={open:function(a){var b=ib[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.Pa.flush(a.tty)},flush:function(a){a.tty.Pa.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Pa.nb)throw new L(60);for(var e=0,g=0;g<d;g++){try{var k=a.tty.Pa.nb(a.tty)}catch(n){throw new L(29);}if(void 0===k&&0===e)throw new L(6);if(null===k||void 0===k)break;e++;b[c+g]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.Pa.eb)throw new L(60);
try{for(var e=0;e<d;e++)a.tty.Pa.eb(a.tty,b[c+e])}catch(g){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},nb={nb:function(a){if(!a.input.length){var b=null;if(fa){var c=Buffer.Ka?Buffer.Ka(256):new Buffer(256),d=0;try{d=ka.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=mb(b,!0)}return a.input.shift()},eb:function(a,b){null===b||10===b?(ma(ra(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ma(ra(a.output,0)),a.output=[])}},ob={eb:function(a,b){null===b||10===b?(A(ra(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(A(ra(a.output,0)),a.output=[])}},M={Ca:null,Ga:function(){return M.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.Ca||(M.Ca={dir:{node:{Ha:M.qa.Ha,Ea:M.qa.Ea,lookup:M.qa.lookup,Wa:M.qa.Wa,rename:M.qa.rename,unlink:M.qa.unlink,rmdir:M.qa.rmdir,readdir:M.qa.readdir,symlink:M.qa.symlink},stream:{Ja:M.ra.Ja}},file:{node:{Ha:M.qa.Ha,Ea:M.qa.Ea},stream:{Ja:M.ra.Ja,read:M.ra.read,write:M.ra.write,hb:M.ra.hb,ob:M.ra.ob,Xa:M.ra.Xa}},link:{node:{Ha:M.qa.Ha,Ea:M.qa.Ea,readlink:M.qa.readlink},stream:{}},ib:{node:{Ha:M.qa.Ha,
Ea:M.qa.Ea},stream:pb}});c=qb(a,b,c,d);16384===(c.mode&61440)?(c.qa=M.Ca.dir.node,c.ra=M.Ca.dir.stream,c.pa={}):32768===(c.mode&61440)?(c.qa=M.Ca.file.node,c.ra=M.Ca.file.stream,c.ua=0,c.pa=null):40960===(c.mode&61440)?(c.qa=M.Ca.link.node,c.ra=M.Ca.link.stream):8192===(c.mode&61440)&&(c.qa=M.Ca.ib.node,c.ra=M.Ca.ib.stream);c.timestamp=Date.now();a&&(a.pa[b]=c);return c},Nb:function(a){if(a.pa&&a.pa.subarray){for(var b=[],c=0;c<a.ua;++c)b.push(a.pa[c]);return b}return a.pa},Ob:function(a){return a.pa?
a.pa.subarray?a.pa.subarray(0,a.ua):new Uint8Array(a.pa):new Uint8Array(0)},kb:function(a,b){var c=a.pa?a.pa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.pa,a.pa=new Uint8Array(b),0<a.ua&&a.pa.set(c.subarray(0,a.ua),0))},Fb:function(a,b){if(a.ua!=b)if(0==b)a.pa=null,a.ua=0;else{if(!a.pa||a.pa.subarray){var c=a.pa;a.pa=new Uint8Array(b);c&&a.pa.set(c.subarray(0,Math.min(b,a.ua)))}else if(a.pa||(a.pa=[]),a.pa.length>b)a.pa.length=b;else for(;a.pa.length<b;)a.pa.push(0);
a.ua=b}},qa:{Ha:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.ua:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.tb=4096;b.blocks=Math.ceil(b.size/b.tb);return b},Ea:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==
b.size&&M.Fb(a,b.size)},lookup:function(){throw rb[44];},Wa:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=N(b,c)}catch(g){}if(d)for(var e in d.pa)throw new L(55);}delete a.parent.pa[a.name];a.name=c;b.pa[c]=a;a.parent=b},unlink:function(a,b){delete a.pa[b]},rmdir:function(a,b){var c=N(a,b),d;for(d in c.pa)throw new L(55);delete a.pa[b]},readdir:function(a){var b=[".",".."],c;for(c in a.pa)a.pa.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,
b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},ra:{read:function(a,b,c,d,e){var g=a.node.pa;if(e>=a.node.ua)return 0;a=Math.min(a.node.ua-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===G.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.pa||a.pa.subarray)){if(g)return a.pa=b.subarray(c,c+d),a.ua=d;
if(0===a.ua&&0===e)return a.pa=b.slice(c,c+d),a.ua=d;if(e+d<=a.ua)return a.pa.set(b.subarray(c,c+d),e),d}M.kb(a,e+d);if(a.pa.subarray&&b.subarray)a.pa.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.pa[e+g]=b[c+g];a.ua=Math.max(a.ua,e+d);return d},Ja:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ua);if(0>b)throw new L(28);return b},hb:function(a,b,c){M.kb(a.node,b+c);a.node.ua=Math.max(a.node.ua,b+c)},ob:function(a,b,c,d,e,g){assert(0===b);if(32768!==(a.node.mode&
61440))throw new L(43);a=a.node.pa;if(g&2||a.buffer!==F){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=sb(g);c<g;)G[b+c++]=0;c=b;if(!c)throw new L(48);G.set(a,c)}else d=!1,c=a.byteOffset;return{sa:c,rb:d}},Xa:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.ra.write(a,b,0,d,c,!1);return 0}}},tb=null,ub={},vb=[],wb=1,O=null,xb=!0,P={},L=null,rb={};
function Q(a,b){a=hb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={mb:!0,fb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.fb)throw new L(32);a=db(a.split("/").filter(function(k){return!!k}),!1);var e=tb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=N(e,a[d]);c=eb(c+"/"+a[d]);e.Na&&(!g||g&&b.mb)&&(e=e.Na.root);if(!g||b.lb)for(g=0;40960===(e.mode&61440);)if(e=yb(c),c=hb(fb(c),e),e=Q(c,{fb:b.fb}).node,40<g++)throw new L(32);}return{path:c,node:e}}
function zb(a){for(var b;;){if(a===a.parent)return a=a.Ga.pb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length}function Bb(a){var b=Ab(a.parent.id,a.name);if(O[b]===a)O[b]=a.Oa;else for(b=O[b];b;){if(b.Oa===a){b.Oa=a.Oa;break}b=b.Oa}}
function N(a,b){var c;if(c=(c=Cb(a,"x"))?c:a.qa.lookup?0:2)throw new L(c,a);for(c=O[Ab(a.id,b)];c;c=c.Oa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.qa.lookup(a,b)}function qb(a,b,c,d){a=new Db(a,b,c,d);b=Ab(a.parent.id,a.name);a.Oa=O[b];return O[b]=a}var Eb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Fb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Cb(a,b){if(xb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Gb(a,b){try{return N(a,b),20}catch(c){}return Cb(a,"wx")}function Hb(a,b,c){try{var d=N(a,b)}catch(e){return e.Ba}if(a=Cb(a,"wx"))return a;if(c){if(16384!==(d.mode&61440))return 54;if(d===d.parent||"/"===zb(d))return 10}else if(16384===(d.mode&61440))return 31;return 0}
function Ib(){var a=4096;for(var b=0;b<=a;b++)if(!vb[b])return b;throw new L(33);}function Jb(a){Kb||(Kb=function(){},Kb.prototype={});var b=new Kb,c;for(c in a)b[c]=a[c];a=b;b=Ib();a.fd=b;return vb[b]=a}var pb={open:function(a){a.ra=ub[a.node.rdev].ra;a.ra.open&&a.ra.open(a)},Ja:function(){throw new L(70);}};function kb(a,b){ub[a]={ra:b}}
function Lb(a,b){var c="/"===b,d=!b;if(c&&tb)throw new L(10);if(!c&&!d){var e=Q(b,{mb:!1});b=e.path;e=e.node;if(e.Na)throw new L(10);if(16384!==(e.mode&61440))throw new L(54);}b={type:a,Tb:{},pb:b,Bb:[]};a=a.Ga(b);a.Ga=b;b.root=a;c?tb=a:e&&(e.Na=b,e.Ga&&e.Ga.Bb.push(b))}function Mb(a,b,c){var d=Q(a,{parent:!0}).node;a=gb(a);if(!a||"."===a||".."===a)throw new L(28);var e=Gb(d,a);if(e)throw new L(e);if(!d.qa.Wa)throw new L(63);return d.qa.Wa(d,a,b,c)}function R(a){Mb(a,16895,0)}
function Nb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Mb(a,b|8192,c)}function Ob(a,b){if(!hb(a))throw new L(44);var c=Q(b,{parent:!0}).node;if(!c)throw new L(44);b=gb(b);var d=Gb(c,b);if(d)throw new L(d);if(!c.qa.symlink)throw new L(63);c.qa.symlink(c,b,a)}function yb(a){a=Q(a).node;if(!a)throw new L(44);if(!a.qa.readlink)throw new L(28);return hb(zb(a.parent),a.qa.readlink(a))}
function Pb(a,b,c){if(""===a)throw new L(44);if("string"===typeof b){var d=Eb[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var e=a;else{a=eb(a);try{e=Q(a,{lb:!(b&131072)}).node}catch(k){}}d=!1;if(b&64)if(e){if(b&128)throw new L(20);}else e=Mb(a,c,0),d=!0;if(!e)throw new L(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new L(54);if(!d&&(c=e?40960===(e.mode&61440)?32:
16384===(e.mode&61440)&&("r"!==Fb(b)||b&512)?31:Cb(e,Fb(b)):44))throw new L(c);if(b&512){c=e;var g;"string"===typeof c?g=Q(c,{lb:!0}).node:g=c;if(!g.qa.Ea)throw new L(63);if(16384===(g.mode&61440))throw new L(31);if(32768!==(g.mode&61440))throw new L(28);if(c=Cb(g,"w"))throw new L(c);g.qa.Ea(g,{size:0,timestamp:Date.now()})}b&=-131713;e=Jb({node:e,path:zb(e),flags:b,seekable:!0,position:0,ra:e.ra,Mb:[],error:!1});e.ra.open&&e.ra.open(e);!f.logReadFiles||b&1||(Qb||(Qb={}),a in Qb||(Qb[a]=1,A("FS.trackingDelegate error on read file: "+
a)));try{P.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),P.onOpenFile(a,g))}catch(k){A("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return e}function Rb(a,b,c){if(null===a.fd)throw new L(8);if(!a.seekable||!a.ra.Ja)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.ra.Ja(a,b,c);a.Mb=[]}
function Sb(){L||(L=function(a,b){this.node=b;this.Gb=function(c){this.Ba=c};this.Gb(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){rb[a]=new L(a);rb[a].stack="<generic error, no stack>"}))}var Tb;function Ub(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Vb(a,b,c){a=eb("/dev/"+a);var d=Ub(!!b,!!c);Wb||(Wb=64);var e=Wb++<<8|0;kb(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,k,n,p){for(var r=0,q=0;q<p;q++){try{var v=b()}catch(y){throw new L(29);}if(void 0===v&&0===r)throw new L(6);if(null===v||void 0===v)break;r++;k[n+q]=v}r&&(g.node.timestamp=Date.now());return r},write:function(g,k,n,p){for(var r=0;r<p;r++)try{c(k[n+r])}catch(q){throw new L(29);}p&&(g.node.timestamp=Date.now());return r}});
Nb(a,d,e)}var Wb,S={},Kb,Qb,Xb={},Yb=void 0;function Zb(){Yb+=4;return E[Yb-4>>2]}function $b(a){a=vb[a];if(!a)throw new L(8);return a}function ac(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var bc=void 0;function T(a){for(var b="";D[a];)b+=bc[D[a++]];return b}var cc={},dc={},ec={};
function fc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function hc(a,b){a=fc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function ic(a){var b=Error,c=hc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var jc=void 0;function U(a){throw new jc(a);}var kc=void 0;function lc(a){throw new kc(a);}
function mc(a,b,c){function d(n){n=c(n);n.length!==a.length&&lc("Mismatched type converter count");for(var p=0;p<a.length;++p)V(a[p],n[p])}a.forEach(function(n){ec[n]=b});var e=Array(b.length),g=[],k=0;b.forEach(function(n,p){dc.hasOwnProperty(n)?e[p]=dc[n]:(g.push(n),cc.hasOwnProperty(n)||(cc[n]=[]),cc[n].push(function(){e[p]=dc[n];++k;k===g.length&&d(e)}))});0===g.length&&d(e)}
function V(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||U('type "'+d+'" must have a positive integer typeid pointer');if(dc.hasOwnProperty(a)){if(c.zb)return;U("Cannot register type '"+d+"' twice")}dc[a]=b;delete ec[a];cc.hasOwnProperty(a)&&(b=cc[a],delete cc[a],b.forEach(function(e){e()}))}function nc(a){return{count:a.count,Ma:a.Ma,Ra:a.Ra,sa:a.sa,va:a.va,ya:a.ya,za:a.za}}
function oc(a){U(a.oa.va.ta.name+" instance already deleted")}var pc=!1;function qc(){}function rc(a){--a.count.value;0===a.count.value&&(a.ya?a.za.La(a.ya):a.va.ta.La(a.sa))}
function sc(a){if("undefined"===typeof FinalizationGroup)return sc=function(b){return b},a;pc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.sa?rc(c):console.warn("object already deleted: "+c.sa)});sc=function(b){pc.register(b,b.oa,b.oa);return b};qc=function(b){pc.unregister(b.oa)};return sc(a)}var tc=void 0,uc=[];function vc(){for(;uc.length;){var a=uc.pop();a.oa.Ma=!1;a["delete"]()}}function W(){}var wc={};
function xc(a,b){var c=f;if(void 0===c[a].Da){var d=c[a];c[a]=function(){c[a].Da.hasOwnProperty(arguments.length)||U("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Da+")!");return c[a].Da[arguments.length].apply(this,arguments)};c[a].Da=[];c[a].Da[d.sb]=d}}
function yc(a,b,c){f.hasOwnProperty(a)?((void 0===c||void 0!==f[a].Da&&void 0!==f[a].Da[c])&&U("Cannot register public name '"+a+"' twice"),xc(a,a),f.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),f[a].Da[c]=b):(f[a]=b,void 0!==c&&(f[a].Sb=c))}function zc(a,b,c,d,e,g,k,n){this.name=a;this.constructor=b;this.Ia=c;this.La=d;this.Aa=e;this.xb=g;this.Ta=k;this.vb=n}
function Ac(a,b,c){for(;b!==c;)b.Ta||U("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Ta(a),b=b.Aa;return a}function Bc(a,b){if(null===b)return this.cb&&U("null is not a valid "+this.name),0;b.oa||U('Cannot pass "'+Cc(b)+'" as a '+this.name);b.oa.sa||U("Cannot pass deleted object as a pointer of type "+this.name);return Ac(b.oa.sa,b.oa.va.ta,this.ta)}
function Dc(a,b){if(null===b){this.cb&&U("null is not a valid "+this.name);if(this.Va){var c=this.Db();null!==a&&a.push(this.La,c);return c}return 0}b.oa||U('Cannot pass "'+Cc(b)+'" as a '+this.name);b.oa.sa||U("Cannot pass deleted object as a pointer of type "+this.name);!this.Ua&&b.oa.va.Ua&&U("Cannot convert argument of type "+(b.oa.za?b.oa.za.name:b.oa.va.name)+" to parameter type "+this.name);c=Ac(b.oa.sa,b.oa.va.ta,this.ta);if(this.Va)switch(void 0===b.oa.ya&&U("Passing raw pointer to smart pointer is illegal"),
this.Hb){case 0:b.oa.za===this?c=b.oa.ya:U("Cannot convert argument of type "+(b.oa.za?b.oa.za.name:b.oa.va.name)+" to parameter type "+this.name);break;case 1:c=b.oa.ya;break;case 2:if(b.oa.za===this)c=b.oa.ya;else{var d=b.clone();c=this.Eb(c,Fc(function(){d["delete"]()}));null!==a&&a.push(this.La,c)}break;default:U("Unsupporting sharing policy")}return c}
function Gc(a,b){if(null===b)return this.cb&&U("null is not a valid "+this.name),0;b.oa||U('Cannot pass "'+Cc(b)+'" as a '+this.name);b.oa.sa||U("Cannot pass deleted object as a pointer of type "+this.name);b.oa.va.Ua&&U("Cannot convert argument of type "+b.oa.va.name+" to parameter type "+this.name);return Ac(b.oa.sa,b.oa.va.ta,this.ta)}function Hc(a){return this.fromWireType(H[a>>2])}function Ic(a,b,c){if(b===c)return a;if(void 0===c.Aa)return null;a=Ic(a,b,c.Aa);return null===a?null:c.vb(a)}
var Jc={};function Kc(a,b){for(void 0===b&&U("ptr should not be undefined");a.Aa;)b=a.Ta(b),a=a.Aa;return Jc[b]}function Lc(a,b){b.va&&b.sa||lc("makeClassHandle requires ptr and ptrType");!!b.za!==!!b.ya&&lc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return sc(Object.create(a,{oa:{value:b}}))}
function X(a,b,c,d){this.name=a;this.ta=b;this.cb=c;this.Ua=d;this.Va=!1;this.La=this.Eb=this.Db=this.qb=this.Hb=this.Cb=void 0;void 0!==b.Aa?this.toWireType=Dc:(this.toWireType=d?Bc:Gc,this.Fa=null)}function Mc(a,b,c){f.hasOwnProperty(a)||lc("Replacing nonexistant public symbol");void 0!==f[a].Da&&void 0!==c?f[a].Da[c]=b:(f[a]=b,f[a].sb=c)}
function Nc(a,b){a=T(a);var c=f["dynCall_"+a];for(var d=[],e=1;e<a.length;++e)d.push("a"+e);e="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";e+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",e+"};\n"))(c,b);"function"!==typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var Oc=void 0;function Pc(a){a=Qc(a);var b=T(a);Y(a);return b}
function Rc(a,b){function c(g){e[g]||dc[g]||(ec[g]?ec[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Oc(a+": "+d.map(Pc).join([", "]));}function Sc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Tc(a,b,c){a instanceof Object||U(c+' with invalid "this": '+a);a instanceof b.ta.constructor||U(c+' incompatible with "this" of type '+a.constructor.name);a.oa.sa||U("cannot call emscripten binding method "+c+" on deleted object");return Ac(a.oa.sa,a.oa.va.ta,b.ta)}
var Uc=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Vc(a){4<a&&0===--Z[a].gb&&(Z[a]=void 0,Uc.push(a))}function Fc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Uc.length?Uc.pop():Z.length;Z[b]={gb:1,value:a};return b}}function Cc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Wc(a,b){switch(b){case 2:return function(c){return this.fromWireType(Fa[c>>2])};case 3:return function(c){return this.fromWireType(Ga[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Xc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=hc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Yc(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}function Zc(a,b,c){switch(b){case 0:return c?function(d){return G[d]}:function(d){return D[d]};case 1:return c?function(d){return za[d>>1]}:function(d){return xa[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return H[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var $c={};
function ad(){if(!bd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in $c)a[b]=$c[b];var c=[];for(b in a)c.push(b+"="+a[b]);bd=c}return bd}var bd;ta("GMT",D,243296,4);function cd(a){return 0===a%4&&(0!==a%100||0===a%400)}function dd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var ed=[31,29,31,30,31,30,31,31,30,31,30,31],fd=[31,28,31,30,31,30,31,31,30,31,30,31];function gd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(cd(a.getFullYear())?ed:fd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function hd(a,b,c,d){function e(h,m,w){for(h="number"===typeof h?h.toString():h||"";h.length<m;)h=w[0]+h;return h}function g(h,m){return e(h,m,"0")}function k(h,m){function w(B){return 0>B?-1:0<B?1:0}var z;0===(z=w(h.getFullYear()-m.getFullYear()))&&0===(z=w(h.getMonth()-m.getMonth()))&&(z=w(h.getDate()-m.getDate()));return z}function n(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function p(h){h=gd(new Date(h.wa+1900,0,1),h.$a);var m=new Date(h.getFullYear()+1,0,4),w=n(new Date(h.getFullYear(),0,4));m=n(m);return 0>=k(w,h)?0>=k(m,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var r=E[d+40>>2];d={Kb:E[d>>2],Jb:E[d+4>>2],Ya:E[d+8>>2],Sa:E[d+12>>2],Qa:E[d+16>>2],wa:E[d+20>>2],Za:E[d+24>>2],$a:E[d+28>>2],Vb:E[d+32>>2],Ib:E[d+
36>>2],Lb:r?sa(r):""};c=sa(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in r)c=c.replace(new RegExp(q,"g"),r[q]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
y="January February March April May June July August September October November December".split(" ");r={"%a":function(h){return v[h.Za].substring(0,3)},"%A":function(h){return v[h.Za]},"%b":function(h){return y[h.Qa].substring(0,3)},"%B":function(h){return y[h.Qa]},"%C":function(h){return g((h.wa+1900)/100|0,2)},"%d":function(h){return g(h.Sa,2)},"%e":function(h){return e(h.Sa,2," ")},"%g":function(h){return p(h).toString().substring(2)},"%G":function(h){return p(h)},"%H":function(h){return g(h.Ya,
2)},"%I":function(h){h=h.Ya;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.Sa+dd(cd(h.wa+1900)?ed:fd,h.Qa-1),3)},"%m":function(h){return g(h.Qa+1,2)},"%M":function(h){return g(h.Jb,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.Ya&&12>h.Ya?"AM":"PM"},"%S":function(h){return g(h.Kb,2)},"%t":function(){return"\t"},"%u":function(h){return h.Za||7},"%U":function(h){var m=new Date(h.wa+1900,0,1),w=0===m.getDay()?m:gd(m,7-m.getDay());h=new Date(h.wa+1900,h.Qa,h.Sa);return 0>
k(w,h)?g(Math.ceil((31-w.getDate()+(dd(cd(h.getFullYear())?ed:fd,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(w,m)?"01":"00"},"%V":function(h){var m=new Date(h.wa+1901,0,4),w=n(new Date(h.wa+1900,0,4));m=n(m);var z=gd(new Date(h.wa+1900,0,1),h.$a);return 0>k(z,w)?"53":0>=k(m,z)?"01":g(Math.ceil((w.getFullYear()<h.wa+1900?h.$a+32-w.getDate():h.$a+1-w.getDate())/7),2)},"%w":function(h){return h.Za},"%W":function(h){var m=new Date(h.wa,0,1),w=1===m.getDay()?m:gd(m,0===m.getDay()?1:7-m.getDay()+1);h=
new Date(h.wa+1900,h.Qa,h.Sa);return 0>k(w,h)?g(Math.ceil((31-w.getDate()+(dd(cd(h.getFullYear())?ed:fd,h.getMonth()-1)-31)+h.getDate())/7),2):0===k(w,m)?"01":"00"},"%y":function(h){return(h.wa+1900).toString().substring(2)},"%Y":function(h){return h.wa+1900},"%z":function(h){h=h.Ib;var m=0<=h;h=Math.abs(h)/60;return(m?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Lb},"%%":function(){return"%"}};for(q in r)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),r[q](d)));q=
mb(c,!1);if(q.length>b)return 0;G.set(q,a);return q.length-1}function Db(a,b,c,d){a||(a=this);this.parent=a;this.Ga=a.Ga;this.Na=null;this.id=wb++;this.name=b;this.mode=c;this.qa={};this.ra={};this.rdev=d}Object.defineProperties(Db.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Sb();O=Array(4096);Lb(M,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");kb(259,{read:function(){return 0},write:function(d,e,g,k){return k}});Nb("/dev/null",259);jb(1280,nb);jb(1536,ob);Nb("/dev/tty",1280);Nb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(fa)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){x("random_device")});Vb("random",b);Vb("urandom",b);R("/dev/shm");
R("/dev/shm/tmp")})();R("/proc");R("/proc/self");R("/proc/self/fd");Lb({Ga:function(){var a=qb("/proc/self","fd",16895,73);a.qa={lookup:function(b,c){var d=vb[+c];if(!d)throw new L(8);b={parent:null,Ga:{pb:"fake"},qa:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");for(var id=Array(256),jd=0;256>jd;++jd)id[jd]=String.fromCharCode(jd);bc=id;jc=f.BindingError=ic("BindingError");kc=f.InternalError=ic("InternalError");
W.prototype.isAliasOf=function(a){if(!(this instanceof W&&a instanceof W))return!1;var b=this.oa.va.ta,c=this.oa.sa,d=a.oa.va.ta;for(a=a.oa.sa;b.Aa;)c=b.Ta(c),b=b.Aa;for(;d.Aa;)a=d.Ta(a),d=d.Aa;return b===d&&c===a};W.prototype.clone=function(){this.oa.sa||oc(this);if(this.oa.Ra)return this.oa.count.value+=1,this;var a=sc(Object.create(Object.getPrototypeOf(this),{oa:{value:nc(this.oa)}}));a.oa.count.value+=1;a.oa.Ma=!1;return a};
W.prototype["delete"]=function(){this.oa.sa||oc(this);this.oa.Ma&&!this.oa.Ra&&U("Object already scheduled for deletion");qc(this);rc(this.oa);this.oa.Ra||(this.oa.ya=void 0,this.oa.sa=void 0)};W.prototype.isDeleted=function(){return!this.oa.sa};W.prototype.deleteLater=function(){this.oa.sa||oc(this);this.oa.Ma&&!this.oa.Ra&&U("Object already scheduled for deletion");uc.push(this);1===uc.length&&tc&&tc(vc);this.oa.Ma=!0;return this};X.prototype.yb=function(a){this.qb&&(a=this.qb(a));return a};
X.prototype.jb=function(a){this.La&&this.La(a)};X.prototype.argPackAdvance=8;X.prototype.readValueFromPointer=Hc;X.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
X.prototype.fromWireType=function(a){function b(){return this.Va?Lc(this.ta.Ia,{va:this.Cb,sa:c,za:this,ya:a}):Lc(this.ta.Ia,{va:this,sa:a})}var c=this.yb(a);if(!c)return this.jb(a),null;var d=Kc(this.ta,c);if(void 0!==d){if(0===d.oa.count.value)return d.oa.sa=c,d.oa.ya=a,d.clone();d=d.clone();this.jb(a);return d}d=this.ta.xb(c);d=wc[d];if(!d)return b.call(this);d=this.Ua?d.ub:d.pointerType;var e=Ic(c,this.ta,d.ta);return null===e?b.call(this):this.Va?Lc(d.ta.Ia,{va:d,sa:e,za:this,ya:a}):Lc(d.ta.Ia,
{va:d,sa:e})};f.getInheritedInstanceCount=function(){return Object.keys(Jc).length};f.getLiveInheritedInstances=function(){var a=[],b;for(b in Jc)Jc.hasOwnProperty(b)&&a.push(Jc[b]);return a};f.flushPendingDeletes=vc;f.setDelayFunction=function(a){tc=a;uc.length&&tc&&tc(vc)};Oc=f.UnboundTypeError=ic("UnboundTypeError");f.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
function mb(a,b){var c=Array(ua(a)+1);a=ta(a,c,0,c.length);b&&(c.length=a);return c}
var ld={K:function(a){return sb(a)},J:function(a){"uncaught_exception"in cb?cb.Ka++:cb.Ka=1;throw a;},x:function(){E[kd()>>2]=63;return-1},B:function(a,b,c){Yb=c;try{var d=$b(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=Zb();return E[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Zb();if(!d.ra.Ab)throw new L(59);return d.ra.Ab(d,b,a);case 21523:return d.tty?0:
-59;case 21524:return d.tty?0:-59;default:x("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof S&&g instanceof L||x(g),-g.Ba}},v:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=Xb[a];if(d&&b===d.Qb){var e=vb[d.fd];if(d.Ub&2){var g=d.flags,k=d.offset,n=D.slice(a,a+b);e&&e.ra.Xa&&e.ra.Xa(e,n,k,b,g)}Xb[a]=null;d.rb&&Y(d.Rb)}c=0}return c}catch(p){return"undefined"!==typeof S&&p instanceof L||x(p),-p.Ba}},C:function(a,b,c){Yb=c;try{var d=sa(a),e=Zb();return Pb(d,b,e).fd}catch(g){return"undefined"!==
typeof S&&g instanceof L||x(g),-g.Ba}},D:function(a){try{a=sa(a);var b=Q(a,{parent:!0}).node,c=gb(a),d=N(b,c),e=Hb(b,c,!0);if(e)throw new L(e);if(!b.qa.rmdir)throw new L(63);if(d.Na)throw new L(10);try{P.willDeletePath&&P.willDeletePath(a)}catch(g){A("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.qa.rmdir(b,c);Bb(d);try{if(P.onDeletePath)P.onDeletePath(a)}catch(g){A("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}return 0}catch(g){return"undefined"!==
typeof S&&g instanceof L||x(g),-g.Ba}},E:function(a){try{a=sa(a);var b=Q(a,{parent:!0}).node,c=gb(a),d=N(b,c),e=Hb(b,c,!1);if(e)throw new L(e);if(!b.qa.unlink)throw new L(63);if(d.Na)throw new L(10);try{P.willDeletePath&&P.willDeletePath(a)}catch(g){A("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+g.message)}b.qa.unlink(b,c);Bb(d);try{if(P.onDeletePath)P.onDeletePath(a)}catch(g){A("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+g.message)}return 0}catch(g){return"undefined"!==
typeof S&&g instanceof L||x(g),-g.Ba}},G:function(a,b,c,d,e){var g=ac(c);b=T(b);V(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,n){return n?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var n=G;else if(2===c)n=za;else if(4===c)n=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(n[k>>g])},Fa:null})},q:function(a,b,c,d,e,g,k,n,p,r,q,v,y){q=T(q);g=Nc(e,g);n&&(n=Nc(k,n));r&&(r=Nc(p,r));y=Nc(v,y);var h=fc(q);yc(h,function(){Rc("Cannot construct "+
q+" due to unbound types",[d])});mc([a,b,c],d?[d]:[],function(m){m=m[0];if(d){var w=m.ta;var z=w.Ia}else z=W.prototype;m=hc(h,function(){if(Object.getPrototypeOf(this)!==B)throw new jc("Use 'new' to construct "+q);if(void 0===J.Ka)throw new jc(q+" has no accessible constructor");var Ec=J.Ka[arguments.length];if(void 0===Ec)throw new jc("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(J.Ka).toString()+") parameters instead!");return Ec.apply(this,
arguments)});var B=Object.create(z,{constructor:{value:m}});m.prototype=B;var J=new zc(q,m,B,y,w,g,n,r);w=new X(q,J,!0,!1);z=new X(q+"*",J,!1,!1);var ya=new X(q+" const*",J,!1,!0);wc[a]={pointerType:z,ub:ya};Mc(h,m);return[w,z,ya]})},e:function(a,b,c,d,e,g,k,n,p,r){b=T(b);e=Nc(d,e);mc([],[a],function(q){q=q[0];var v=q.name+"."+b,y={get:function(){Rc("Cannot access "+v+" due to unbound types",[c,k])},enumerable:!0,configurable:!0};p?y.set=function(){Rc("Cannot access "+v+" due to unbound types",[c,
k])}:y.set=function(){U(v+" is a read-only property")};Object.defineProperty(q.ta.Ia,b,y);mc([],p?[c,k]:[c],function(h){var m=h[0],w={get:function(){var B=Tc(this,q,v+" getter");return m.fromWireType(e(g,B))},enumerable:!0};if(p){p=Nc(n,p);var z=h[1];w.set=function(B){var J=Tc(this,q,v+" setter"),ya=[];p(r,J,z.toWireType(ya,B));Sc(ya)}}Object.defineProperty(q.ta.Ia,b,w);return[]});return[]})},F:function(a,b){b=T(b);V(a,{name:b,fromWireType:function(c){var d=Z[c].value;Vc(c);return d},toWireType:function(c,
d){return Fc(d)},argPackAdvance:8,readValueFromPointer:Hc,Fa:null})},n:function(a,b,c){c=ac(c);b=T(b);V(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Cc(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Wc(b,c),Fa:null})},i:function(a,b,c,d,e,g){var k=Yc(b,c);a=T(a);e=Nc(d,e);yc(a,function(){Rc("Cannot call "+a+" due to unbound types",k)},b-1);mc([],k,function(n){var p=[n[0],
null].concat(n.slice(1)),r=n=a,q=e,v=p.length;2>v&&U("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var y=null!==p[1]&&!1,h=!1,m=1;m<p.length;++m)if(null!==p[m]&&void 0===p[m].Fa){h=!0;break}var w="void"!==p[0].name,z="",B="";for(m=0;m<v-2;++m)z+=(0!==m?", ":"")+"arg"+m,B+=(0!==m?", ":"")+"arg"+m+"Wired";r="return function "+fc(r)+"("+z+") {\nif (arguments.length !== "+(v-2)+") {\nthrowBindingError('function "+r+" called with ' + arguments.length + ' arguments, expected "+
(v-2)+" args!');\n}\n";h&&(r+="var destructors = [];\n");var J=h?"destructors":"null";z="throwBindingError invoker fn runDestructors retType classParam".split(" ");q=[U,q,g,Sc,p[0],p[1]];y&&(r+="var thisWired = classParam.toWireType("+J+", this);\n");for(m=0;m<v-2;++m)r+="var arg"+m+"Wired = argType"+m+".toWireType("+J+", arg"+m+"); // "+p[m+2].name+"\n",z.push("argType"+m),q.push(p[m+2]);y&&(B="thisWired"+(0<B.length?", ":"")+B);r+=(w?"var rv = ":"")+"invoker(fn"+(0<B.length?", ":"")+B+");\n";if(h)r+=
"runDestructors(destructors);\n";else for(m=y?1:2;m<p.length;++m)v=1===m?"thisWired":"arg"+(m-2)+"Wired",null!==p[m].Fa&&(r+=v+"_dtor("+v+"); // "+p[m].name+"\n",z.push(v+"_dtor"),q.push(p[m].Fa));w&&(r+="var ret = retType.fromWireType(rv);\nreturn ret;\n");z.push(r+"}\n");p=Xc(z).apply(null,q);Mc(n,p,b-1);return[]})},b:function(a,b,c,d,e){function g(r){return r}b=T(b);-1===e&&(e=4294967295);var k=ac(c);if(0===d){var n=32-8*c;g=function(r){return r<<n>>>n}}var p=-1!=b.indexOf("unsigned");V(a,{name:b,
fromWireType:g,toWireType:function(r,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Cc(q)+'" to '+this.name);if(q<d||q>e)throw new TypeError('Passing a number "'+Cc(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return p?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Zc(b,k,0!==d),Fa:null})},a:function(a,b,c){function d(g){g>>=2;var k=H;return new e(F,k[g+1],k[g])}var e=[Int8Array,Uint8Array,
Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=T(c);V(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{zb:!0})},o:function(a,b){b=T(b);var c="std::string"===b;V(a,{name:b,fromWireType:function(d){var e=H[d>>2];if(c)for(var g=d+4,k=0;k<=e;++k){var n=d+4+k;if(k==e||0==D[n]){g=sa(g,n-g);if(void 0===p)var p=g;else p+=String.fromCharCode(0),p+=g;g=n+1}}else{p=Array(e);for(k=0;k<e;++k)p[k]=String.fromCharCode(D[d+4+k]);p=p.join("")}Y(d);return p},toWireType:function(d,
e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||U("Cannot pass non-string to std::string");var k=(c&&g?function(){return ua(e)}:function(){return e.length})(),n=sb(4+k+1);H[n>>2]=k;if(c&&g)ta(e,D,n+4,k+1);else if(g)for(g=0;g<k;++g){var p=e.charCodeAt(g);255<p&&(Y(n),U("String has UTF-16 code units that do not fit in 8 bits"));D[n+4+g]=p}else for(g=0;g<k;++g)D[n+4+g]=e[g];null!==d&&d.push(Y,
n);return n},argPackAdvance:8,readValueFromPointer:Hc,Fa:function(d){Y(d)}})},h:function(a,b,c){c=T(c);if(2===b){var d=wa;var e=Aa;var g=Ba;var k=function(){return xa};var n=1}else 4===b&&(d=Ca,e=Da,g=Ea,k=function(){return H},n=2);V(a,{name:c,fromWireType:function(p){for(var r=H[p>>2],q=k(),v,y=p+4,h=0;h<=r;++h){var m=p+4+h*b;if(h==r||0==q[m>>n])y=d(y,m-y),void 0===v?v=y:(v+=String.fromCharCode(0),v+=y),y=m+b}Y(p);return v},toWireType:function(p,r){"string"!==typeof r&&U("Cannot pass non-string to C++ string type "+
c);var q=g(r),v=sb(4+q+b);H[v>>2]=q>>n;e(r,v+4,q+b);null!==p&&p.push(Y,v);return v},argPackAdvance:8,readValueFromPointer:Hc,Fa:function(p){Y(p)}})},H:function(a,b){b=T(b);V(a,{Pb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},j:Vc,w:function(a){4<a&&(Z[a].gb+=1)},m:function(a,b){var c=dc[a];void 0===c&&U("_emval_take_value has unknown type "+Pc(a));a=c.readValueFromPointer(b);return Fc(a)},d:function(){x()},t:function(a,b,c){D.copyWithin(a,b,b+c)},c:function(a){a>>>=
0;var b=D.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{C.grow(Math.min(2147483648,d)-F.byteLength+65535>>>16);Ha(C.buffer);var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},y:function(a,b){var c=0;ad().forEach(function(d,e){var g=b+c;e=E[a+4*e>>2]=g;for(g=0;g<d.length;++g)G[e++>>0]=d.charCodeAt(g);G[e>>0]=0;c+=d.length+1});return 0},z:function(a,b){var c=ad();E[a>>2]=c.length;
var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0},l:function(a){try{var b=$b(a);if(null===b.fd)throw new L(8);b.bb&&(b.bb=null);try{b.ra.close&&b.ra.close(b)}catch(c){throw c;}finally{vb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof S&&c instanceof L||x(c),c.Ba}},A:function(a,b,c,d){try{a:{for(var e=$b(a),g=a=0;g<c;g++){var k=E[b+(8*g+4)>>2],n=e,p=E[b+8*g>>2],r=k,q=void 0,v=G;if(0>r||0>q)throw new L(28);if(null===n.fd)throw new L(8);if(1===(n.flags&2097155))throw new L(8);
if(16384===(n.node.mode&61440))throw new L(31);if(!n.ra.read)throw new L(28);var y="undefined"!==typeof q;if(!y)q=n.position;else if(!n.seekable)throw new L(70);var h=n.ra.read(n,v,p,r,q);y||(n.position+=h);var m=h;if(0>m){var w=-1;break a}a+=m;if(m<k)break}w=a}E[d>>2]=w;return 0}catch(z){return"undefined"!==typeof S&&z instanceof L||x(z),z.Ba}},r:function(a,b,c,d,e){try{var g=$b(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Rb(g,a,d);ab=[g.position>>>0,($a=g.position,
1<=+Pa($a)?0<$a?(Sa(+Ra($a/4294967296),4294967295)|0)>>>0:~~+Qa(($a-+(~~$a>>>0))/4294967296)>>>0:0)];E[e>>2]=ab[0];E[e+4>>2]=ab[1];g.bb&&0===a&&0===d&&(g.bb=null);return 0}catch(k){return"undefined"!==typeof S&&k instanceof L||x(k),k.Ba}},k:function(a,b,c,d){try{a:{for(var e=$b(a),g=a=0;g<c;g++){var k=e,n=E[b+8*g>>2],p=E[b+(8*g+4)>>2],r=void 0,q=G;if(0>p||0>r)throw new L(28);if(null===k.fd)throw new L(8);if(0===(k.flags&2097155))throw new L(8);if(16384===(k.node.mode&61440))throw new L(31);if(!k.ra.write)throw new L(28);
k.seekable&&k.flags&1024&&Rb(k,0,2);var v="undefined"!==typeof r;if(!v)r=k.position;else if(!k.seekable)throw new L(70);var y=k.ra.write(k,q,n,p,r,void 0);v||(k.position+=y);try{if(k.path&&P.onWriteToFile)P.onWriteToFile(k.path)}catch(w){A("FS.trackingDelegate['onWriteToFile']('"+k.path+"') threw an exception: "+w.message)}var h=y;if(0>h){var m=-1;break a}a+=h}m=a}E[d>>2]=m;return 0}catch(w){return"undefined"!==typeof S&&w instanceof L||x(w),w.Ba}},I:function(a){a=new Date(1E3*E[a>>2]);E[60812]=a.getUTCSeconds();
E[60813]=a.getUTCMinutes();E[60814]=a.getUTCHours();E[60815]=a.getUTCDate();E[60816]=a.getUTCMonth();E[60817]=a.getUTCFullYear()-1900;E[60818]=a.getUTCDay();E[60821]=0;E[60820]=0;E[60819]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;E[60822]=243296;return 243248},memory:C,f:function(a){a=+a;return 0<=a?+Ra(a+.5):+Qa(a-.5)},g:function(a){a=+a;return 0<=a?+Ra(a+.5):+Qa(a-.5)},s:function(){},u:function(a,b,c,d){return hd(a,b,c,d)},table:oa,p:function(a){var b=Date.now()/1E3|0;a&&(E[a>>
2]=b);return b}};
(function(){function a(e){f.asm=e.exports;I--;f.monitorRunDependencies&&f.monitorRunDependencies(I);0==I&&(null!==Ta&&(clearInterval(Ta),Ta=null),Ua&&(e=Ua,Ua=null,e()))}function b(e){a(e.instance)}function c(e){return Za().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){A("failed to asynchronously prepare wasm: "+g);x(g)})}var d={a:ld};I++;f.monitorRunDependencies&&f.monitorRunDependencies(I);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),
!1}(function(){if(na||"function"!==typeof WebAssembly.instantiateStreaming||Wa()||Va("file://")||"function"!==typeof fetch)return c(b);fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){A("wasm streaming compile failed: "+g);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var bb=f.___wasm_call_ctors=function(){return(bb=f.___wasm_call_ctors=f.asm.L).apply(null,arguments)},sb=f._malloc=function(){return(sb=f._malloc=f.asm.M).apply(null,arguments)},Y=f._free=function(){return(Y=f._free=f.asm.N).apply(null,arguments)},kd=f.___errno_location=function(){return(kd=f.___errno_location=f.asm.O).apply(null,arguments)},Qc=f.___getTypeName=function(){return(Qc=f.___getTypeName=f.asm.P).apply(null,arguments)};
f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.Q).apply(null,arguments)};f.dynCall_ii=function(){return(f.dynCall_ii=f.asm.R).apply(null,arguments)};f.dynCall_vi=function(){return(f.dynCall_vi=f.asm.S).apply(null,arguments)};f.dynCall_iii=function(){return(f.dynCall_iii=f.asm.T).apply(null,arguments)};f.dynCall_viii=function(){return(f.dynCall_viii=f.asm.U).apply(null,arguments)};
f.dynCall_vii=function(){return(f.dynCall_vii=f.asm.V).apply(null,arguments)};f.dynCall_v=function(){return(f.dynCall_v=f.asm.W).apply(null,arguments)};f.dynCall_iidiiii=function(){return(f.dynCall_iidiiii=f.asm.X).apply(null,arguments)};f.dynCall_iiiiiii=function(){return(f.dynCall_iiiiiii=f.asm.Y).apply(null,arguments)};f.dynCall_iiii=function(){return(f.dynCall_iiii=f.asm.Z).apply(null,arguments)};f.dynCall_iiiii=function(){return(f.dynCall_iiiii=f.asm._).apply(null,arguments)};
f.dynCall_iiiiii=function(){return(f.dynCall_iiiiii=f.asm.$).apply(null,arguments)};f.dynCall_viiiiii=function(){return(f.dynCall_viiiiii=f.asm.aa).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.ba).apply(null,arguments)};f.dynCall_viiiiiii=function(){return(f.dynCall_viiiiiii=f.asm.ca).apply(null,arguments)};f.dynCall_diid=function(){return(f.dynCall_diid=f.asm.da).apply(null,arguments)};f.dynCall_iiiiiiii=function(){return(f.dynCall_iiiiiiii=f.asm.ea).apply(null,arguments)};
f.dynCall_idi=function(){return(f.dynCall_idi=f.asm.fa).apply(null,arguments)};f.dynCall_viijii=function(){return(f.dynCall_viijii=f.asm.ga).apply(null,arguments)};f.dynCall_viiii=function(){return(f.dynCall_viiii=f.asm.ha).apply(null,arguments)};f.dynCall_iiiiiiiii=function(){return(f.dynCall_iiiiiiiii=f.asm.ia).apply(null,arguments)};f.dynCall_iiiiiijj=function(){return(f.dynCall_iiiiiijj=f.asm.ja).apply(null,arguments)};f.dynCall_iiiiij=function(){return(f.dynCall_iiiiij=f.asm.ka).apply(null,arguments)};
f.dynCall_iiiiid=function(){return(f.dynCall_iiiiid=f.asm.la).apply(null,arguments)};f.dynCall_iiiiijj=function(){return(f.dynCall_iiiiijj=f.asm.ma).apply(null,arguments)};f.dynCall_viiiii=function(){return(f.dynCall_viiiii=f.asm.na).apply(null,arguments)};var md;Ua=function nd(){md||od();md||(Ua=nd)};
function od(){function a(){if(!md&&(md=!0,f.calledRun=!0,!pa)){f.noFSInit||Tb||(Tb=!0,Sb(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Vb("stdin",f.stdin):Ob("/dev/tty","/dev/stdin"),f.stdout?Vb("stdout",null,f.stdout):Ob("/dev/tty","/dev/stdout"),f.stderr?Vb("stderr",null,f.stderr):Ob("/dev/tty1","/dev/stderr"),Pb("/dev/stdin","r"),Pb("/dev/stdout","w"),Pb("/dev/stderr","w"));Ja(La);xb=!1;Ja(Ma);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Na.unshift(b)}Ja(Na)}}if(!(0<I)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Oa();Ja(Ka);0<I||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=od;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();noExitRuntime=!0;od();


  return jxl_dec.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = jxl_dec;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return jxl_dec; });
    else if (typeof exports === 'object')
      exports["jxl_dec"] = jxl_dec;
    