
var avif_node_dec = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(avif_node_dec) {
  avif_node_dec = avif_node_dec || {};


var e;e||(e=typeof avif_node_dec !== 'undefined' ? avif_node_dec : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var r={},t;for(t in e)e.hasOwnProperty(t)&&(r[t]=e[t]);var ca="",da,ea,fa,ha;ca=__dirname+"/";da=function(a){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,null)};ea=function(a){a=da(a);a.buffer||(a=new Uint8Array(a));a.buffer||u("Assertion failed: undefined");return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");
process.argv.slice(2);process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",u);e.inspect=function(){return"[Emscripten Module object]"};var ia=e.print||console.log.bind(console),v=e.printErr||console.warn.bind(console);for(t in r)r.hasOwnProperty(t)&&(e[t]=r[t]);r=null;var ja=0,w;e.wasmBinary&&(w=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&u("no native wasm support detected");var y,ka=!1,la=new TextDecoder("utf8");
function ma(a,b,c){var d=z;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var na=new TextDecoder("utf-16le");
function oa(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&A[c];)++c;return na.decode(z.subarray(a,c<<1))}function pa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)B[b>>1]=a.charCodeAt(f),b+=2;B[b>>1]=0;return b-d}function qa(a){return 2*a.length}function ra(a,b){for(var c=0,d="";!(c>=b/4);){var f=D[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}
function sa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}D[b>>2]=g;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d}function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var E,ua,z,B,A,D,F,va,wa;
function xa(a){E=a;e.HEAP8=ua=new Int8Array(a);e.HEAP16=B=new Int16Array(a);e.HEAP32=D=new Int32Array(a);e.HEAPU8=z=new Uint8Array(a);e.HEAPU16=A=new Uint16Array(a);e.HEAPU32=F=new Uint32Array(a);e.HEAPF32=va=new Float32Array(a);e.HEAPF64=wa=new Float64Array(a)}var ya=e.INITIAL_MEMORY||16777216;e.wasmMemory?y=e.wasmMemory:y=new WebAssembly.Memory({initial:ya/65536,maximum:32768});y&&(E=y.buffer);ya=E.byteLength;xa(E);var G,za=[],Aa=[],Ba=[],Ca=[];
function Da(){var a=e.preRun.shift();za.unshift(a)}var H=0,Ea=null,J=null;e.preloadedImages={};e.preloadedAudios={};function u(a){if(e.onAbort)e.onAbort(a);v(a);ka=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Fa(){var a=K;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var K="avif_node_dec.wasm";
if(!Fa()){var Ga=K;K=e.locateFile?e.locateFile(Ga,ca):ca+Ga}function Ha(){try{if(w)return new Uint8Array(w);if(ea)return ea(K);throw"both async and sync fetching of the wasm failed";}catch(a){u(a)}}function L(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.T;"number"===typeof c?void 0===b.P?G.get(c)():G.get(c)(b.P):c(void 0===b.P?null:b.P)}}}
function Ia(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ja=void 0;function N(a){for(var b="";z[a];)b+=Ja[z[a++]];return b}var O={},P={},Q={};function Ka(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function La(a,b){a=Ka(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ma(a){var b=Error,c=La(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Na=void 0;function R(a){throw new Na(a);}var Oa=void 0;function Pa(a,b){function c(k){k=b(k);if(k.length!==d.length)throw new Oa("Mismatched type converter count");for(var l=0;l<d.length;++l)S(d[l],k[l])}var d=[];d.forEach(function(k){Q[k]=a});var f=Array(a.length),g=[],h=0;a.forEach(function(k,l){P.hasOwnProperty(k)?f[l]=P[k]:(g.push(k),O.hasOwnProperty(k)||(O[k]=[]),O[k].push(function(){f[l]=P[k];++h;h===g.length&&c(f)}))});0===g.length&&c(f)}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||R('type "'+d+'" must have a positive integer typeid pointer');if(P.hasOwnProperty(a)){if(c.U)return;R("Cannot register type '"+d+"' twice")}P[a]=b;delete Q[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(function(f){f()}))}var Qa=[],T=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Ta(a){4<a&&0===--T[a].R&&(T[a]=void 0,Qa.push(a))}function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Qa.length?Qa.pop():T.length;T[b]={R:1,value:a};return b}}function Ua(a){return this.fromWireType(F[a>>2])}function Va(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Wa(a,b){switch(b){case 2:return function(c){return this.fromWireType(va[c>>2])};case 3:return function(c){return this.fromWireType(wa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Xa(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=La(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Ya(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Za(a,b){var c=e;if(void 0===c[a].N){var d=c[a];c[a]=function(){c[a].N.hasOwnProperty(arguments.length)||R("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].N+")!");return c[a].N[arguments.length].apply(this,arguments)};c[a].N=[];c[a].N[d.S]=d}}
function $a(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].N&&void 0!==e[a].N[c])&&R("Cannot register public name '"+a+"' twice"),Za(a,a),e.hasOwnProperty(c)&&R("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].N[c]=b):(e[a]=b,void 0!==c&&(e[a].W=c))}function ab(a,b){for(var c=[],d=0;d<a;d++)c.push(D[(b>>2)+d]);return c}
function bb(a,b){0<=a.indexOf("j")||u("Assertion failed: getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var f;-1!=a.indexOf("j")?f=c&&c.length?e["dynCall_"+a].apply(null,[b].concat(c)):e["dynCall_"+a].call(null,b):f=G.get(b).apply(null,c);return f}}
function cb(a,b){a=N(a);var c=-1!=a.indexOf("j")?bb(a,b):G.get(b);"function"!==typeof c&&R("unknown function pointer with signature "+a+": "+b);return c}var db=void 0;function eb(a){a=fb(a);var b=N(a);V(a);return b}function gb(a,b){function c(g){f[g]||P[g]||(Q[g]?Q[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new db(a+": "+d.map(eb).join([", "]));}
function hb(a,b,c){switch(b){case 0:return c?function(d){return ua[d]}:function(d){return z[d]};case 1:return c?function(d){return B[d>>1]}:function(d){return A[d>>1]};case 2:return c?function(d){return D[d>>2]}:function(d){return F[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var ib={};function jb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function kb(a,b){var c=P[a];void 0===c&&R(b+" has unknown type "+eb(a));return c}
for(var lb={},mb=[null,[],[]],nb=Array(256),W=0;256>W;++W)nb[W]=String.fromCharCode(W);Ja=nb;Na=e.BindingError=Ma("BindingError");Oa=e.InternalError=Ma("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<T.length;++b)void 0!==T[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<T.length;++a)if(void 0!==T[a])return T[a];return null};db=e.UnboundTypeError=Ma("UnboundTypeError");Aa.push({T:function(){ob()}});
var ub={l:function(){},t:function(a,b,c,d,f){var g=Ia(c);b=N(b);S(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var k=ua;else if(2===c)k=B;else if(4===c)k=D;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[h>>g])},O:null})},B:function(a,b){b=N(b);S(a,{name:b,fromWireType:function(c){var d=T[c].value;Ta(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,
readValueFromPointer:Ua,O:null})},s:function(a,b,c){c=Ia(c);b=N(b);S(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Va(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Wa(b,c),O:null})},v:function(a,b,c,d,f,g){var h=ab(b,c);a=N(a);f=cb(d,f);$a(a,function(){gb("Cannot call "+a+" due to unbound types",h)},b-1);Pa(h,function(k){var l=[k[0],null].concat(k.slice(1)),m=k=a,n=f,
p=l.length;2>p&&R("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==l[1]&&!1,C=!1,q=1;q<l.length;++q)if(null!==l[q]&&void 0===l[q].O){C=!0;break}var Ra="void"!==l[0].name,I="",M="";for(q=0;q<p-2;++q)I+=(0!==q?", ":"")+"arg"+q,M+=(0!==q?", ":"")+"arg"+q+"Wired";m="return function "+Ka(m)+"("+I+") {\nif (arguments.length !== "+(p-2)+") {\nthrowBindingError('function "+m+" called with ' + arguments.length + ' arguments, expected "+(p-2)+" args!');\n}\n";
C&&(m+="var destructors = [];\n");var Sa=C?"destructors":"null";I="throwBindingError invoker fn runDestructors retType classParam".split(" ");n=[R,n,g,Ya,l[0],l[1]];x&&(m+="var thisWired = classParam.toWireType("+Sa+", this);\n");for(q=0;q<p-2;++q)m+="var arg"+q+"Wired = argType"+q+".toWireType("+Sa+", arg"+q+"); // "+l[q+2].name+"\n",I.push("argType"+q),n.push(l[q+2]);x&&(M="thisWired"+(0<M.length?", ":"")+M);m+=(Ra?"var rv = ":"")+"invoker(fn"+(0<M.length?", ":"")+M+");\n";if(C)m+="runDestructors(destructors);\n";
else for(q=x?1:2;q<l.length;++q)p=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==l[q].O&&(m+=p+"_dtor("+p+"); // "+l[q].name+"\n",I.push(p+"_dtor"),n.push(l[q].O));Ra&&(m+="var ret = retType.fromWireType(rv);\nreturn ret;\n");I.push(m+"}\n");l=Xa(I).apply(null,n);q=b-1;if(!e.hasOwnProperty(k))throw new Oa("Replacing nonexistant public symbol");void 0!==e[k].N&&void 0!==q?e[k].N[q]=l:(e[k]=l,e[k].S=q);return[]})},f:function(a,b,c,d,f){function g(m){return m}b=N(b);-1===f&&(f=4294967295);var h=Ia(c);
if(0===d){var k=32-8*c;g=function(m){return m<<k>>>k}}var l=-1!=b.indexOf("unsigned");S(a,{name:b,fromWireType:g,toWireType:function(m,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+Va(n)+'" to '+this.name);if(n<d||n>f)throw new TypeError('Passing a number "'+Va(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return l?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:hb(b,h,0!==d),O:null})},
e:function(a,b,c){function d(g){g>>=2;var h=F;return new f(E,h[g+1],h[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=N(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{U:!0})},n:function(a,b){b=N(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var f=F[d>>2];if(c)for(var g=d+4,h=0;h<=f;++h){var k=d+4+h;if(h==f||0==z[k]){if(g){for(var l=g+(k-g),m=g;!(m>=l)&&z[m];)++m;g=la.decode(z.subarray(g,m))}else g=
"";if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=k+1}}else{n=Array(f);for(h=0;h<f;++h)n[h]=String.fromCharCode(z[d+4+h]);n=n.join("")}V(d);return n},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||R("Cannot pass non-string to std::string");var h=(c&&g?function(){for(var m=0,n=0;n<f.length;++n){var p=f.charCodeAt(n);55296<=p&&57343>=p&&(p=65536+((p&1023)<<
10)|f.charCodeAt(++n)&1023);127>=p?++m:m=2047>=p?m+2:65535>=p?m+3:m+4}return m}:function(){return f.length})(),k=pb(4+h+1);F[k>>2]=h;if(c&&g)ma(f,k+4,h+1);else if(g)for(g=0;g<h;++g){var l=f.charCodeAt(g);255<l&&(V(k),R("String has UTF-16 code units that do not fit in 8 bits"));z[k+4+g]=l}else for(g=0;g<h;++g)z[k+4+g]=f[g];null!==d&&d.push(V,k);return k},argPackAdvance:8,readValueFromPointer:Ua,O:function(d){V(d)}})},m:function(a,b,c){c=N(c);if(2===b){var d=oa;var f=pa;var g=qa;var h=function(){return A};
var k=1}else 4===b&&(d=ra,f=sa,g=ta,h=function(){return F},k=2);S(a,{name:c,fromWireType:function(l){for(var m=F[l>>2],n=h(),p,x=l+4,C=0;C<=m;++C){var q=l+4+C*b;if(C==m||0==n[q>>k])x=d(x,q-x),void 0===p?p=x:(p+=String.fromCharCode(0),p+=x),x=q+b}V(l);return p},toWireType:function(l,m){"string"!==typeof m&&R("Cannot pass non-string to C++ string type "+c);var n=g(m),p=pb(4+n+b);F[p>>2]=n>>k;f(m,p+4,n+b);null!==l&&l.push(V,p);return p},argPackAdvance:8,readValueFromPointer:Ua,O:function(l){V(l)}})},
u:function(a,b){b=N(b);S(a,{V:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},j:Ta,k:function(a){if(0===a)return U(jb());var b=ib[a];a=void 0===b?N(a):b;return U(jb()[a])},o:function(a){4<a&&(T[a].R+=1)},p:function(a,b,c,d){a||R("Cannot use deleted val. handle = "+a);a=T[a].value;var f=lb[b];if(!f){f="";for(var g=0;g<b;++g)f+=(0!==g?", ":"")+"arg"+g;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(g=0;g<b;++g)h+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+
g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";f=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+f+");\nreturn __emval_register(obj);\n}\n")))(kb,e,U);lb[b]=f}return f(a,c,d)},d:function(){u()},i:function(a,b){X(a,b||1);throw"longjmp";},z:function(a,b,c){z.copyWithin(a,b,b+c)},h:function(a){a>>>=0;var b=z.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+
.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{y.grow(Math.min(2147483648,d)-E.byteLength+65535>>>16);xa(y.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},A:function(){return 0},w:function(){},r:function(a,b,c,d){for(var f=0,g=0;g<c;g++){for(var h=D[b+8*g>>2],k=D[b+(8*g+4)>>2],l=0;l<k;l++){var m=z[h+l],n=mb[a];if(0===m||10===m){m=1===a?ia:v;var p;for(p=0;n[p]&&!(NaN<=p);)++p;p=la.decode(n.subarray?n.subarray(0,p):new Uint8Array(n.slice(0,
p)));m(p);n.length=0}else n.push(m)}f+=k}D[d>>2]=f;return 0},b:function(){return ja|0},g:qb,x:rb,q:sb,y:tb,a:y,c:function(a){ja=a|0}};
(function(){function a(f){e.asm=f.exports;G=e.asm.C;H--;e.monitorRunDependencies&&e.monitorRunDependencies(H);0==H&&(null!==Ea&&(clearInterval(Ea),Ea=null),J&&(f=J,J=null,f()))}function b(f){a(f.instance)}function c(f){return Promise.resolve().then(Ha).then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){v("failed to asynchronously prepare wasm: "+g);u(g)})}var d={a:ub};H++;e.monitorRunDependencies&&e.monitorRunDependencies(H);if(e.instantiateWasm)try{return e.instantiateWasm(d,
a)}catch(f){return v("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return w||"function"!==typeof WebAssembly.instantiateStreaming||Fa()||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){v("wasm streaming compile failed: "+g);v("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
var ob=e.___wasm_call_ctors=function(){return(ob=e.___wasm_call_ctors=e.asm.D).apply(null,arguments)},pb=e._malloc=function(){return(pb=e._malloc=e.asm.E).apply(null,arguments)},V=e._free=function(){return(V=e._free=e.asm.F).apply(null,arguments)},fb=e.___getTypeName=function(){return(fb=e.___getTypeName=e.asm.G).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.H).apply(null,arguments)};
var Y=e.stackSave=function(){return(Y=e.stackSave=e.asm.I).apply(null,arguments)},Z=e.stackRestore=function(){return(Z=e.stackRestore=e.asm.J).apply(null,arguments)},X=e._setThrew=function(){return(X=e._setThrew=e.asm.K).apply(null,arguments)};e.dynCall_iiijii=function(){return(e.dynCall_iiijii=e.asm.L).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.M).apply(null,arguments)};
function tb(a,b,c,d,f,g,h,k){var l=Y();try{G.get(a)(b,c,d,f,g,h,k)}catch(m){Z(l);if(m!==m+0&&"longjmp"!==m)throw m;X(1,0)}}function sb(a,b,c,d,f){var g=Y();try{G.get(a)(b,c,d,f)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}function qb(a,b,c){var d=Y();try{return G.get(a)(b,c)}catch(f){Z(d);if(f!==f+0&&"longjmp"!==f)throw f;X(1,0)}}function rb(a,b,c,d,f){var g=Y();try{return G.get(a)(b,c,d,f)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}var vb;
J=function wb(){vb||xb();vb||(J=wb)};
function xb(){function a(){if(!vb&&(vb=!0,e.calledRun=!0,!ka)){L(Aa);L(Ba);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Ca.unshift(b)}L(Ca)}}if(!(0<H)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Da();L(za);0<H||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
e.run=xb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;xb();


  return avif_node_dec.ready
}
);
})();
export default avif_node_dec;