
var avif_dec = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(avif_dec) {
  avif_dec = avif_dec || {};


var e;e||(e=typeof avif_dec !== 'undefined' ? avif_dec : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},m;for(m in e)e.hasOwnProperty(m)&&(ca[m]=e[m]);var da=!1,t=!1,ea=!1,fa=!1;da="object"===typeof window;t="function"===typeof importScripts;ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;fa=!da&&!ea&&!t;var u="",ha,ia,ja,ka;
if(ea)u=t?require("path").dirname(u)+"/":__dirname+"/",ha=function(a,b){ja||(ja=require("fs"));ka||(ka=require("path"));a=ka.normalize(a);return ja.readFileSync(a,b?null:"utf8")},ia=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",x),e.inspect=function(){return"[Emscripten Module object]"};else if(fa)"undefined"!=
typeof read&&(ha=function(a){return read(a)}),ia=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(da||t)t?u=self.location.href:document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,
u.lastIndexOf("/")+1):u="",ha=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(ia=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var la=e.print||console.log.bind(console),A=e.printErr||console.warn.bind(console);for(m in ca)ca.hasOwnProperty(m)&&(e[m]=ca[m]);ca=null;var ma=0,na;e.wasmBinary&&(na=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);
"object"!==typeof WebAssembly&&x("no native wasm support detected");var B,oa=new WebAssembly.Table({initial:2119,maximum:2119,element:"anyfunc"}),pa=!1;function assert(a,b){a||x("Assertion failed: "+b)}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function sa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var k=a.charCodeAt(++g);h=65536+((h&1023)<<10)|k&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var ua="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function va(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&wa[c];)++c;c<<=1;if(32<c-a&&ua)return ua.decode(C.subarray(a,c));c=0;for(d="";;){var f=D[a+2*c>>1];if(0==f||c==b/2)return d;++c;d+=String.fromCharCode(f)}}
function xa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)D[b>>1]=a.charCodeAt(f),b+=2;D[b>>1]=0;return b-d}function ya(a){return 2*a.length}function za(a,b){for(var c=0,d="";!(c>=b/4);){var f=F[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}
function Ba(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}F[b>>2]=g;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var G,H,C,D,wa,F,I,Da,Ea;
function Fa(a){G=a;e.HEAP8=H=new Int8Array(a);e.HEAP16=D=new Int16Array(a);e.HEAP32=F=new Int32Array(a);e.HEAPU8=C=new Uint8Array(a);e.HEAPU16=wa=new Uint16Array(a);e.HEAPU32=I=new Uint32Array(a);e.HEAPF32=Da=new Float32Array(a);e.HEAPF64=Ea=new Float64Array(a)}var Ga=e.INITIAL_MEMORY||16777216;e.wasmMemory?B=e.wasmMemory:B=new WebAssembly.Memory({initial:Ga/65536,maximum:32768});B&&(G=B.buffer);Ga=G.byteLength;Fa(G);F[224100]=6139440;
function Ha(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.Kb;"number"===typeof c?void 0===b.pb?e.dynCall_v(c):e.dynCall_vi(c,b.pb):c(void 0===b.pb?null:b.pb)}}}var Ia=[],Ja=[],Ka=[],La=[];function Ma(){var a=e.preRun.shift();Ia.unshift(a)}var Na=Math.abs,Oa=Math.ceil,Pa=Math.floor,Qa=Math.min,K=0,Ra=null,Sa=null;e.preloadedImages={};e.preloadedAudios={};
function x(a){if(e.onAbort)e.onAbort(a);A(a);pa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ta(a){var b=L;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Ua(){return Ta("data:application/octet-stream;base64,")}var L="avif_dec.wasm";if(!Ua()){var Va=L;L=e.locateFile?e.locateFile(Va,u):u+Va}
function Wa(){try{if(na)return new Uint8Array(na);if(ia)return ia(L);throw"both async and sync fetching of the wasm failed";}catch(a){x(a)}}function Xa(){return na||!da&&!t||"function"!==typeof fetch||Ta("file://")?new Promise(function(a){a(Wa())}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Wa()})}var Ya,Za;Ja.push({Kb:function(){$a()}});function ab(){return 0<ab.bb}
function bb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function cb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=bb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function db(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function eb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function fb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=bb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var gb=[];function hb(a,b){gb[a]={input:[],output:[],ib:b};ib(a,jb)}
var jb={open:function(a){var b=gb[a.node.rdev];if(!b)throw new M(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.ib.flush(a.tty)},flush:function(a){a.tty.ib.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.ib.Bb)throw new M(60);for(var f=0,g=0;g<d;g++){try{var h=a.tty.ib.Bb(a.tty)}catch(k){throw new M(29);}if(void 0===h&&0===f)throw new M(6);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.ib.sb)throw new M(60);
try{for(var f=0;f<d;f++)a.tty.ib.sb(a.tty,b[c+f])}catch(g){throw new M(29);}d&&(a.node.timestamp=Date.now());return f}},kb={Bb:function(a){if(!a.input.length){var b=null;if(ea){var c=Buffer.bb?Buffer.bb(256):new Buffer(256),d=0;try{d=ja.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(-1!=f.toString().indexOf("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;c=Array(ta(b)+1);b=sa(b,c,0,c.length);c.length=b;a.input=c}return a.input.shift()},sb:function(a,b){null===b||10===b?(la(ra(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(la(ra(a.output,0)),a.output=[])}},lb={sb:function(a,b){null===b||10===b?(A(ra(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(A(ra(a.output,0)),a.output=[])}},
N={Wa:null,$a:function(){return N.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new M(63);N.Wa||(N.Wa={dir:{node:{ab:N.Na.ab,Ya:N.Na.Ya,lookup:N.Na.lookup,nb:N.Na.nb,rename:N.Na.rename,unlink:N.Na.unlink,rmdir:N.Na.rmdir,readdir:N.Na.readdir,symlink:N.Na.symlink},stream:{fb:N.Oa.fb}},file:{node:{ab:N.Na.ab,Ya:N.Na.Ya},stream:{fb:N.Oa.fb,read:N.Oa.read,write:N.Oa.write,vb:N.Oa.vb,Cb:N.Oa.Cb,Eb:N.Oa.Eb}},link:{node:{ab:N.Na.ab,Ya:N.Na.Ya,readlink:N.Na.readlink},
stream:{}},wb:{node:{ab:N.Na.ab,Ya:N.Na.Ya},stream:mb}});c=nb(a,b,c,d);16384===(c.mode&61440)?(c.Na=N.Wa.dir.node,c.Oa=N.Wa.dir.stream,c.Ma={}):32768===(c.mode&61440)?(c.Na=N.Wa.file.node,c.Oa=N.Wa.file.stream,c.Ra=0,c.Ma=null):40960===(c.mode&61440)?(c.Na=N.Wa.link.node,c.Oa=N.Wa.link.stream):8192===(c.mode&61440)&&(c.Na=N.Wa.wb.node,c.Oa=N.Wa.wb.stream);c.timestamp=Date.now();a&&(a.Ma[b]=c);return c},$b:function(a){if(a.Ma&&a.Ma.subarray){for(var b=[],c=0;c<a.Ra;++c)b.push(a.Ma[c]);return b}return a.Ma},
ac:function(a){return a.Ma?a.Ma.subarray?a.Ma.subarray(0,a.Ra):new Uint8Array(a.Ma):new Uint8Array(0)},yb:function(a,b){var c=a.Ma?a.Ma.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Ma,a.Ma=new Uint8Array(b),0<a.Ra&&a.Ma.set(c.subarray(0,a.Ra),0))},Vb:function(a,b){if(a.Ra!=b)if(0==b)a.Ma=null,a.Ra=0;else{if(!a.Ma||a.Ma.subarray){var c=a.Ma;a.Ma=new Uint8Array(b);c&&a.Ma.set(c.subarray(0,Math.min(b,a.Ra)))}else if(a.Ma||(a.Ma=[]),a.Ma.length>b)a.Ma.length=b;
else for(;a.Ma.length<b;)a.Ma.push(0);a.Ra=b}},Na:{ab:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ra:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Hb=4096;b.blocks=Math.ceil(b.size/b.Hb);return b},Ya:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&
(a.timestamp=b.timestamp);void 0!==b.size&&N.Vb(a,b.size)},lookup:function(){throw ob[44];},nb:function(a,b,c,d){return N.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=pb(b,c)}catch(g){}if(d)for(var f in d.Ma)throw new M(55);}delete a.parent.Ma[a.name];a.name=c;b.Ma[c]=a;a.parent=b},unlink:function(a,b){delete a.Ma[b]},rmdir:function(a,b){var c=pb(a,b),d;for(d in c.Ma)throw new M(55);delete a.Ma[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Ma)a.Ma.hasOwnProperty(c)&&
b.push(c);return b},symlink:function(a,b,c){a=N.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new M(28);return a.link}},Oa:{read:function(a,b,c,d,f){var g=a.node.Ma;if(f>=a.node.Ra)return 0;a=Math.min(a.node.Ra-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){b.buffer===H.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ma||a.Ma.subarray)){if(g)return a.Ma=
b.subarray(c,c+d),a.Ra=d;if(0===a.Ra&&0===f)return a.Ma=b.slice(c,c+d),a.Ra=d;if(f+d<=a.Ra)return a.Ma.set(b.subarray(c,c+d),f),d}N.yb(a,f+d);if(a.Ma.subarray&&b.subarray)a.Ma.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Ma[f+g]=b[c+g];a.Ra=Math.max(a.Ra,f+d);return d},fb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ra);if(0>b)throw new M(28);return b},vb:function(a,b,c){N.yb(a.node,b+c);a.node.Ra=Math.max(a.node.Ra,b+c)},Cb:function(a,b,c,d,f,g){assert(0===
b);if(32768!==(a.node.mode&61440))throw new M(43);a=a.node.Ma;if(g&2||a.buffer!==G){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;g=16384*Math.ceil(c/16384);for(b=qb(g);c<g;)H[b+c++]=0;c=b;if(!c)throw new M(48);H.set(a,c)}else d=!1,c=a.byteOffset;return{Pa:c,Zb:d}},Eb:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new M(43);if(f&2)return 0;N.Oa.write(a,b,0,d,c,!1);return 0}}},rb=null,sb={},tb=[],ub=1,vb=null,wb=!0,xb={},M=null,ob={};
function O(a,b){a=fb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Ab:!0,tb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.tb)throw new M(32);a=bb(a.split("/").filter(function(h){return!!h}),!1);var f=rb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=pb(f,a[d]);c=cb(c+"/"+a[d]);f.ob&&(!g||g&&b.Ab)&&(f=f.ob.root);if(!g||b.zb)for(g=0;40960===(f.mode&61440);)if(f=yb(c),c=fb(db(c),f),f=O(c,{tb:b.tb}).node,40<g++)throw new M(32);}return{path:c,node:f}}
function zb(a){for(var b;;){if(a===a.parent)return a=a.$a.Db,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%vb.length}function pb(a,b){var c;if(c=(c=Bb(a,"x"))?c:a.Na.lookup?0:2)throw new M(c,a);for(c=vb[Ab(a.id,b)];c;c=c.Rb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Na.lookup(a,b)}
function nb(a,b,c,d){a=new Cb(a,b,c,d);b=Ab(a.parent.id,a.name);a.Rb=vb[b];return vb[b]=a}var Db={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Eb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Bb(a,b){if(wb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Fb(a,b){try{return pb(a,b),20}catch(c){}return Bb(a,"wx")}function Gb(a){var b=4096;for(a=a||0;a<=b;a++)if(!tb[a])return a;throw new M(33);}function Hb(a,b){Ib||(Ib=function(){},Ib.prototype={});var c=new Ib,d;for(d in a)c[d]=a[d];a=c;b=Gb(b);a.fd=b;return tb[b]=a}var mb={open:function(a){a.Oa=sb[a.node.rdev].Oa;a.Oa.open&&a.Oa.open(a)},fb:function(){throw new M(70);}};function ib(a,b){sb[a]={Oa:b}}
function Jb(a,b){var c="/"===b,d=!b;if(c&&rb)throw new M(10);if(!c&&!d){var f=O(b,{Ab:!1});b=f.path;f=f.node;if(f.ob)throw new M(10);if(16384!==(f.mode&61440))throw new M(54);}b={type:a,cc:{},Db:b,Qb:[]};a=a.$a(b);a.$a=b;b.root=a;c?rb=a:f&&(f.ob=b,f.$a&&f.$a.Qb.push(b))}function Kb(a,b,c){var d=O(a,{parent:!0}).node;a=eb(a);if(!a||"."===a||".."===a)throw new M(28);var f=Fb(d,a);if(f)throw new M(f);if(!d.Na.nb)throw new M(63);return d.Na.nb(d,a,b,c)}function P(a){Kb(a,16895,0)}
function Lb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Kb(a,b|8192,c)}function Mb(a,b){if(!fb(a))throw new M(44);var c=O(b,{parent:!0}).node;if(!c)throw new M(44);b=eb(b);var d=Fb(c,b);if(d)throw new M(d);if(!c.Na.symlink)throw new M(63);c.Na.symlink(c,b,a)}function yb(a){a=O(a).node;if(!a)throw new M(44);if(!a.Na.readlink)throw new M(28);return fb(zb(a.parent),a.Na.readlink(a))}
function Nb(a,b,c,d){if(""===a)throw new M(44);if("string"===typeof b){var f=Db[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=cb(a);try{g=O(a,{zb:!(b&131072)}).node}catch(k){}}f=!1;if(b&64)if(g){if(b&128)throw new M(20);}else g=Kb(a,c,0),f=!0;if(!g)throw new M(44);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&16384!==(g.mode&61440))throw new M(54);if(!f&&(c=g?40960===(g.mode&61440)?
32:16384===(g.mode&61440)&&("r"!==Eb(b)||b&512)?31:Bb(g,Eb(b)):44))throw new M(c);if(b&512){c=g;var h;"string"===typeof c?h=O(c,{zb:!0}).node:h=c;if(!h.Na.Ya)throw new M(63);if(16384===(h.mode&61440))throw new M(31);if(32768!==(h.mode&61440))throw new M(28);if(c=Bb(h,"w"))throw new M(c);h.Na.Ya(h,{size:0,timestamp:Date.now()})}b&=-131713;d=Hb({node:g,path:zb(g),flags:b,seekable:!0,position:0,Oa:g.Oa,Yb:[],error:!1},d);d.Oa.open&&d.Oa.open(d);!e.logReadFiles||b&1||(Ob||(Ob={}),a in Ob||(Ob[a]=1,A("FS.trackingDelegate error on read file: "+
a)));try{xb.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),xb.onOpenFile(a,g))}catch(k){A("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function Pb(a,b,c){if(null===a.fd)throw new M(8);if(!a.seekable||!a.Oa.fb)throw new M(70);if(0!=c&&1!=c&&2!=c)throw new M(28);a.position=a.Oa.fb(a,b,c);a.Yb=[]}
function Qb(){M||(M=function(a,b){this.node=b;this.Wb=function(c){this.cb=c};this.Wb(a);this.message="FS error"},M.prototype=Error(),M.prototype.constructor=M,[44].forEach(function(a){ob[a]=new M(a);ob[a].stack="<generic error, no stack>"}))}var Rb;function Sb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Tb(a,b,c){a=cb("/dev/"+a);var d=Sb(!!b,!!c);Ub||(Ub=64);var f=Ub++<<8|0;ib(f,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,h,k,l){for(var n=0,p=0;p<l;p++){try{var r=b()}catch(v){throw new M(29);}if(void 0===r&&0===n)throw new M(6);if(null===r||void 0===r)break;n++;h[k+p]=r}n&&(g.node.timestamp=Date.now());return n},write:function(g,h,k,l){for(var n=0;n<l;n++)try{c(h[k+n])}catch(p){throw new M(29);}l&&(g.node.timestamp=Date.now());return n}});
Lb(a,d,f)}var Ub,Vb={},Ib,Ob,Wb=void 0;function Xb(){Wb+=4;return F[Wb-4>>2]}function Yb(a){a=tb[a];if(!a)throw new M(8);return a}function Zb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var $b=void 0;function Q(a){for(var b="";C[a];)b+=$b[C[a++]];return b}var ac={},bc={},cc={};function dc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function ec(a,b){a=dc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function fc(a){var b=Error,c=ec(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var hc=void 0;function R(a){throw new hc(a);}var ic=void 0;function jc(a){throw new ic(a);}function kc(a,b,c){function d(k){k=c(k);k.length!==a.length&&jc("Mismatched type converter count");for(var l=0;l<a.length;++l)S(a[l],k[l])}a.forEach(function(k){cc[k]=b});var f=Array(b.length),g=[],h=0;b.forEach(function(k,l){bc.hasOwnProperty(k)?f[l]=bc[k]:(g.push(k),ac.hasOwnProperty(k)||(ac[k]=[]),ac[k].push(function(){f[l]=bc[k];++h;h===g.length&&d(f)}))});0===g.length&&d(f)}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||R('type "'+d+'" must have a positive integer typeid pointer');if(bc.hasOwnProperty(a)){if(c.Nb)return;R("Cannot register type '"+d+"' twice")}bc[a]=b;delete cc[a];ac.hasOwnProperty(a)&&(b=ac[a],delete ac[a],b.forEach(function(f){f()}))}function lc(a){return{count:a.count,hb:a.hb,jb:a.jb,Pa:a.Pa,Sa:a.Sa,Ta:a.Ta,Ua:a.Ua}}
function mc(a){R(a.La.Sa.Qa.name+" instance already deleted")}var nc=!1;function oc(){}function pc(a){--a.count.value;0===a.count.value&&(a.Ta?a.Ua.gb(a.Ta):a.Sa.Qa.gb(a.Pa))}
function qc(a){if("undefined"===typeof FinalizationGroup)return qc=function(b){return b},a;nc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Pa?pc(c):console.warn("object already deleted: "+c.Pa)});qc=function(b){nc.register(b,b.La,b.La);return b};oc=function(b){nc.unregister(b.La)};return qc(a)}var rc=void 0,sc=[];function tc(){for(;sc.length;){var a=sc.pop();a.La.hb=!1;a["delete"]()}}function T(){}var uc={};
function vc(a,b){var c=e;if(void 0===c[a].Xa){var d=c[a];c[a]=function(){c[a].Xa.hasOwnProperty(arguments.length)||R("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Xa+")!");return c[a].Xa[arguments.length].apply(this,arguments)};c[a].Xa=[];c[a].Xa[d.Gb]=d}}
function wc(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].Xa&&void 0!==e[a].Xa[c])&&R("Cannot register public name '"+a+"' twice"),vc(a,a),e.hasOwnProperty(c)&&R("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].Xa[c]=b):(e[a]=b,void 0!==c&&(e[a].bc=c))}function yc(a,b,c,d,f,g,h,k){this.name=a;this.constructor=b;this.eb=c;this.gb=d;this.Va=f;this.Lb=g;this.kb=h;this.Jb=k}
function zc(a,b,c){for(;b!==c;)b.kb||R("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.kb(a),b=b.Va;return a}function Ac(a,b){if(null===b)return this.rb&&R("null is not a valid "+this.name),0;b.La||R('Cannot pass "'+Bc(b)+'" as a '+this.name);b.La.Pa||R("Cannot pass deleted object as a pointer of type "+this.name);return zc(b.La.Pa,b.La.Sa.Qa,this.Qa)}
function Cc(a,b){if(null===b){this.rb&&R("null is not a valid "+this.name);if(this.mb){var c=this.Tb();null!==a&&a.push(this.gb,c);return c}return 0}b.La||R('Cannot pass "'+Bc(b)+'" as a '+this.name);b.La.Pa||R("Cannot pass deleted object as a pointer of type "+this.name);!this.lb&&b.La.Sa.lb&&R("Cannot convert argument of type "+(b.La.Ua?b.La.Ua.name:b.La.Sa.name)+" to parameter type "+this.name);c=zc(b.La.Pa,b.La.Sa.Qa,this.Qa);if(this.mb)switch(void 0===b.La.Ta&&R("Passing raw pointer to smart pointer is illegal"),
this.Xb){case 0:b.La.Ua===this?c=b.La.Ta:R("Cannot convert argument of type "+(b.La.Ua?b.La.Ua.name:b.La.Sa.name)+" to parameter type "+this.name);break;case 1:c=b.La.Ta;break;case 2:if(b.La.Ua===this)c=b.La.Ta;else{var d=b.clone();c=this.Ub(c,Dc(function(){d["delete"]()}));null!==a&&a.push(this.gb,c)}break;default:R("Unsupporting sharing policy")}return c}
function Ec(a,b){if(null===b)return this.rb&&R("null is not a valid "+this.name),0;b.La||R('Cannot pass "'+Bc(b)+'" as a '+this.name);b.La.Pa||R("Cannot pass deleted object as a pointer of type "+this.name);b.La.Sa.lb&&R("Cannot convert argument of type "+b.La.Sa.name+" to parameter type "+this.name);return zc(b.La.Pa,b.La.Sa.Qa,this.Qa)}function Fc(a){return this.fromWireType(I[a>>2])}function Gc(a,b,c){if(b===c)return a;if(void 0===c.Va)return null;a=Gc(a,b,c.Va);return null===a?null:c.Jb(a)}
var Hc={};function Ic(a,b){for(void 0===b&&R("ptr should not be undefined");a.Va;)b=a.kb(b),a=a.Va;return Hc[b]}function Jc(a,b){b.Sa&&b.Pa||jc("makeClassHandle requires ptr and ptrType");!!b.Ua!==!!b.Ta&&jc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return qc(Object.create(a,{La:{value:b}}))}
function U(a,b,c,d){this.name=a;this.Qa=b;this.rb=c;this.lb=d;this.mb=!1;this.gb=this.Ub=this.Tb=this.Fb=this.Xb=this.Sb=void 0;void 0!==b.Va?this.toWireType=Cc:(this.toWireType=d?Ac:Ec,this.Za=null)}function Kc(a,b,c){e.hasOwnProperty(a)||jc("Replacing nonexistant public symbol");void 0!==e[a].Xa&&void 0!==c?e[a].Xa[c]=b:(e[a]=b,e[a].Gb=c)}
function Lc(a,b){a=Q(a);var c=e["dynCall_"+a];for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&R("unknown function pointer with signature "+a+": "+b);return c}var Mc=void 0;function Nc(a){a=Oc(a);var b=Q(a);V(a);return b}
function Pc(a,b){function c(g){f[g]||bc[g]||(cc[g]?cc[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Mc(a+": "+d.map(Nc).join([", "]));}function Qc(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Rc(a,b,c){a instanceof Object||R(c+' with invalid "this": '+a);a instanceof b.Qa.constructor||R(c+' incompatible with "this" of type '+a.constructor.name);a.La.Pa||R("cannot call emscripten binding method "+c+" on deleted object");return zc(a.La.Pa,a.La.Sa.Qa,b.Qa)}
var Sc=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Tc(a){4<a&&0===--W[a].ub&&(W[a]=void 0,Sc.push(a))}function Dc(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Sc.length?Sc.pop():W.length;W[b]={ub:1,value:a};return b}}function Bc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Uc(a,b){switch(b){case 2:return function(c){return this.fromWireType(Da[c>>2])};case 3:return function(c){return this.fromWireType(Ea[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Vc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=ec(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Wc(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}function Xc(a,b,c){switch(b){case 0:return c?function(d){return H[d]}:function(d){return C[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return wa[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Yc={},Zc=[];function $c(a){var b=Zc.length;Zc.push(a);return b}
function ad(a,b){var c=bc[a];void 0===c&&R(b+" has unknown type "+Nc(a));return c}function bd(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=ad(F[(b>>2)+d],"parameter "+d);return c}function Cb(a,b,c,d){a||(a=this);this.parent=a;this.$a=a.$a;this.ob=null;this.id=ub++;this.name=b;this.mode=c;this.Na={};this.Oa={};this.rdev=d}
Object.defineProperties(Cb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Qb();vb=Array(4096);Jb(N,"/");P("/tmp");P("/home");P("/home/web_user");
(function(){P("/dev");ib(259,{read:function(){return 0},write:function(d,f,g,h){return h}});Lb("/dev/null",259);hb(1280,kb);hb(1536,lb);Lb("/dev/tty",1280);Lb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ea)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){x("random_device")});Tb("random",b);Tb("urandom",b);P("/dev/shm");
P("/dev/shm/tmp")})();P("/proc");P("/proc/self");P("/proc/self/fd");Jb({$a:function(){var a=nb("/proc/self","fd",16895,73);a.Na={lookup:function(b,c){var d=tb[+c];if(!d)throw new M(8);b={parent:null,$a:{Db:"fake"},Na:{readlink:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");for(var cd=Array(256),dd=0;256>dd;++dd)cd[dd]=String.fromCharCode(dd);$b=cd;hc=e.BindingError=fc("BindingError");ic=e.InternalError=fc("InternalError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.La.Sa.Qa,c=this.La.Pa,d=a.La.Sa.Qa;for(a=a.La.Pa;b.Va;)c=b.kb(c),b=b.Va;for(;d.Va;)a=d.kb(a),d=d.Va;return b===d&&c===a};T.prototype.clone=function(){this.La.Pa||mc(this);if(this.La.jb)return this.La.count.value+=1,this;var a=qc(Object.create(Object.getPrototypeOf(this),{La:{value:lc(this.La)}}));a.La.count.value+=1;a.La.hb=!1;return a};
T.prototype["delete"]=function(){this.La.Pa||mc(this);this.La.hb&&!this.La.jb&&R("Object already scheduled for deletion");oc(this);pc(this.La);this.La.jb||(this.La.Ta=void 0,this.La.Pa=void 0)};T.prototype.isDeleted=function(){return!this.La.Pa};T.prototype.deleteLater=function(){this.La.Pa||mc(this);this.La.hb&&!this.La.jb&&R("Object already scheduled for deletion");sc.push(this);1===sc.length&&rc&&rc(tc);this.La.hb=!0;return this};U.prototype.Mb=function(a){this.Fb&&(a=this.Fb(a));return a};
U.prototype.xb=function(a){this.gb&&this.gb(a)};U.prototype.argPackAdvance=8;U.prototype.readValueFromPointer=Fc;U.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
U.prototype.fromWireType=function(a){function b(){return this.mb?Jc(this.Qa.eb,{Sa:this.Sb,Pa:c,Ua:this,Ta:a}):Jc(this.Qa.eb,{Sa:this,Pa:a})}var c=this.Mb(a);if(!c)return this.xb(a),null;var d=Ic(this.Qa,c);if(void 0!==d){if(0===d.La.count.value)return d.La.Pa=c,d.La.Ta=a,d.clone();d=d.clone();this.xb(a);return d}d=this.Qa.Lb(c);d=uc[d];if(!d)return b.call(this);d=this.lb?d.Ib:d.pointerType;var f=Gc(c,this.Qa,d.Qa);return null===f?b.call(this):this.mb?Jc(d.Qa.eb,{Sa:d,Pa:f,Ua:this,Ta:a}):Jc(d.Qa.eb,
{Sa:d,Pa:f})};e.getInheritedInstanceCount=function(){return Object.keys(Hc).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in Hc)Hc.hasOwnProperty(b)&&a.push(Hc[b]);return a};e.flushPendingDeletes=tc;e.setDelayFunction=function(a){rc=a;sc.length&&rc&&rc(tc)};Mc=e.UnboundTypeError=fc("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};
var rd={z:function(a){return qb(a)},T:function(a){"uncaught_exception"in ab?ab.bb++:ab.bb=1;throw a;},q:function(a,b,c){Wb=c;try{var d=Yb(a);switch(b){case 0:var f=Xb();return 0>f?-28:Nb(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=Xb(),d.flags|=f,0;case 12:return f=Xb(),D[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return F[ed()>>2]=28,-1;default:return-28}}catch(g){return"undefined"!==typeof Vb&&g instanceof M||x(g),-g.cb}},O:function(a,
b,c){Wb=c;try{var d=Yb(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=Xb();return F[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=f=Xb();if(!d.Oa.Ob)throw new M(59);return d.Oa.Ob(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:x("bad ioctl syscall "+b)}}catch(g){return"undefined"!==typeof Vb&&g instanceof M||x(g),-g.cb}},P:function(a,b,
c){Wb=c;try{var d=a?ra(C,a,void 0):"",f=Xb();return Nb(d,b,f).fd}catch(g){return"undefined"!==typeof Vb&&g instanceof M||x(g),-g.cb}},R:function(a,b,c,d,f){var g=Zb(c);b=Q(b);S(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var k=H;else if(2===c)k=D;else if(4===c)k=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[h>>g])},Za:null})},B:function(a,b,c,d,f,g,h,k,l,n,p,
r,v){p=Q(p);g=Lc(f,g);k&&(k=Lc(h,k));n&&(n=Lc(l,n));v=Lc(r,v);var w=dc(p);wc(w,function(){Pc("Cannot construct "+p+" due to unbound types",[d])});kc([a,b,c],d?[d]:[],function(q){q=q[0];if(d){var y=q.Qa;var z=y.eb}else z=T.prototype;q=ec(w,function(){if(Object.getPrototypeOf(this)!==E)throw new hc("Use 'new' to construct "+p);if(void 0===J.bb)throw new hc(p+" has no accessible constructor");var xc=J.bb[arguments.length];if(void 0===xc)throw new hc("Tried to invoke ctor of "+p+" with invalid number of parameters ("+
arguments.length+") - expected ("+Object.keys(J.bb).toString()+") parameters instead!");return xc.apply(this,arguments)});var E=Object.create(z,{constructor:{value:q}});q.prototype=E;var J=new yc(p,q,E,v,y,g,k,n);y=new U(p,J,!0,!1);z=new U(p+"*",J,!1,!1);var Aa=new U(p+" const*",J,!1,!0);uc[a]={pointerType:z,Ib:Aa};Kc(w,q);return[y,z,Aa]})},n:function(a,b,c,d,f,g,h,k,l,n){b=Q(b);f=Lc(d,f);kc([],[a],function(p){p=p[0];var r=p.name+"."+b,v={get:function(){Pc("Cannot access "+r+" due to unbound types",
[c,h])},enumerable:!0,configurable:!0};l?v.set=function(){Pc("Cannot access "+r+" due to unbound types",[c,h])}:v.set=function(){R(r+" is a read-only property")};Object.defineProperty(p.Qa.eb,b,v);kc([],l?[c,h]:[c],function(w){var q=w[0],y={get:function(){var E=Rc(this,p,r+" getter");return q.fromWireType(f(g,E))},enumerable:!0};if(l){l=Lc(k,l);var z=w[1];y.set=function(E){var J=Rc(this,p,r+" setter"),Aa=[];l(n,J,z.toWireType(Aa,E));Qc(Aa)}}Object.defineProperty(p.Qa.eb,b,y);return[]});return[]})},
Q:function(a,b){b=Q(b);S(a,{name:b,fromWireType:function(c){var d=W[c].value;Tc(c);return d},toWireType:function(c,d){return Dc(d)},argPackAdvance:8,readValueFromPointer:Fc,Za:null})},u:function(a,b,c){c=Zb(c);b=Q(b);S(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Bc(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Uc(b,c),Za:null})},A:function(a,b,c,d,f,g){var h=Wc(b,c);
a=Q(a);f=Lc(d,f);wc(a,function(){Pc("Cannot call "+a+" due to unbound types",h)},b-1);kc([],h,function(k){var l=[k[0],null].concat(k.slice(1)),n=k=a,p=f,r=l.length;2>r&&R("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var v=null!==l[1]&&!1,w=!1,q=1;q<l.length;++q)if(null!==l[q]&&void 0===l[q].Za){w=!0;break}var y="void"!==l[0].name,z="",E="";for(q=0;q<r-2;++q)z+=(0!==q?", ":"")+"arg"+q,E+=(0!==q?", ":"")+"arg"+q+"Wired";n="return function "+dc(n)+"("+z+") {\nif (arguments.length !== "+
(r-2)+") {\nthrowBindingError('function "+n+" called with ' + arguments.length + ' arguments, expected "+(r-2)+" args!');\n}\n";w&&(n+="var destructors = [];\n");var J=w?"destructors":"null";z="throwBindingError invoker fn runDestructors retType classParam".split(" ");p=[R,p,g,Qc,l[0],l[1]];v&&(n+="var thisWired = classParam.toWireType("+J+", this);\n");for(q=0;q<r-2;++q)n+="var arg"+q+"Wired = argType"+q+".toWireType("+J+", arg"+q+"); // "+l[q+2].name+"\n",z.push("argType"+q),p.push(l[q+2]);v&&(E=
"thisWired"+(0<E.length?", ":"")+E);n+=(y?"var rv = ":"")+"invoker(fn"+(0<E.length?", ":"")+E+");\n";if(w)n+="runDestructors(destructors);\n";else for(q=v?1:2;q<l.length;++q)r=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==l[q].Za&&(n+=r+"_dtor("+r+"); // "+l[q].name+"\n",z.push(r+"_dtor"),p.push(l[q].Za));y&&(n+="var ret = retType.fromWireType(rv);\nreturn ret;\n");z.push(n+"}\n");l=Vc(z).apply(null,p);Kc(k,l,b-1);return[]})},i:function(a,b,c,d,f){function g(n){return n}b=Q(b);-1===f&&(f=4294967295);
var h=Zb(c);if(0===d){var k=32-8*c;g=function(n){return n<<k>>>k}}var l=-1!=b.indexOf("unsigned");S(a,{name:b,fromWireType:g,toWireType:function(n,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+Bc(p)+'" to '+this.name);if(p<d||p>f)throw new TypeError('Passing a number "'+Bc(p)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return l?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:Xc(b,h,0!==d),
Za:null})},f:function(a,b,c){function d(g){g>>=2;var h=I;return new f(G,h[g+1],h[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=Q(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Nb:!0})},v:function(a,b){b=Q(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var f=I[d>>2];if(c)for(var g=d+4,h=0;h<=f;++h){var k=d+4+h;if(h==f||0==C[k]){g=g?ra(C,g,k-g):"";if(void 0===l)var l=g;else l+=String.fromCharCode(0),
l+=g;g=k+1}}else{l=Array(f);for(h=0;h<f;++h)l[h]=String.fromCharCode(C[d+4+h]);l=l.join("")}V(d);return l},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||R("Cannot pass non-string to std::string");var h=(c&&g?function(){return ta(f)}:function(){return f.length})(),k=qb(4+h+1);I[k>>2]=h;if(c&&g)sa(f,C,k+4,h+1);else if(g)for(g=0;g<h;++g){var l=f.charCodeAt(g);255<l&&
(V(k),R("String has UTF-16 code units that do not fit in 8 bits"));C[k+4+g]=l}else for(g=0;g<h;++g)C[k+4+g]=f[g];null!==d&&d.push(V,k);return k},argPackAdvance:8,readValueFromPointer:Fc,Za:function(d){V(d)}})},o:function(a,b,c){c=Q(c);if(2===b){var d=va;var f=xa;var g=ya;var h=function(){return wa};var k=1}else 4===b&&(d=za,f=Ba,g=Ca,h=function(){return I},k=2);S(a,{name:c,fromWireType:function(l){for(var n=I[l>>2],p=h(),r,v=l+4,w=0;w<=n;++w){var q=l+4+w*b;if(w==n||0==p[q>>k])v=d(v,q-v),void 0===
r?r=v:(r+=String.fromCharCode(0),r+=v),v=q+b}V(l);return r},toWireType:function(l,n){"string"!==typeof n&&R("Cannot pass non-string to C++ string type "+c);var p=g(n),r=qb(4+p+b);I[r>>2]=p>>k;f(n,r+4,p+b);null!==l&&l.push(V,r);return r},argPackAdvance:8,readValueFromPointer:Fc,Za:function(l){V(l)}})},S:function(a,b){b=Q(b);S(a,{Pb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},L:function(a,b,c,d,f){a=Zc[a];b||R("Cannot use deleted val. handle = "+b);b=W[b].value;var g=
Yc[c];c=void 0===g?Q(c):g;g=[];F[d>>2]=Dc(g);return a(b,c,g,f)},t:Tc,I:function(a,b){b=bd(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(n){return n.name}).join("_")+"$",f=["retType"],g=[c],h="",k=0;k<a-1;++k)h+=(0!==k?", ":"")+"arg"+k,f.push("argType"+k),g.push(b[1+k]);d="return function "+dc("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var l=0;for(k=0;k<a-1;++k)d+="    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(l?"+"+l:"")+");\n",l+=b[k+1].argPackAdvance;d+=
"    var rv = handle[name]("+h+");\n";for(k=0;k<a-1;++k)b[k+1].deleteObject&&(d+="    argType"+k+".deleteObject(arg"+k+");\n");c.Pb||(d+="    return retType.toWireType(destructors, rv);\n");f.push(d+"};\n");a=Vc(f).apply(null,g);return $c(a)},x:function(a){4<a&&(W[a].ub+=1)},C:function(a){Qc(W[a].value);Tc(a)},y:function(a,b){a=ad(a,"_emval_take_value");a=a.readValueFromPointer(b);return Dc(a)},w:function(){x()},d:function(a,b){X(a,b||1);throw"longjmp";},M:function(a,b,c){C.copyWithin(a,b,b+c)},j:function(a){a>>>=
0;var b=C.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{B.grow(Math.min(2147483648,d)-G.byteLength+65535>>>16);Fa(B.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},s:function(a){try{var b=Yb(a);if(null===b.fd)throw new M(8);b.qb&&(b.qb=null);try{b.Oa.close&&b.Oa.close(b)}catch(c){throw c;}finally{tb[b.fd]=null}b.fd=null;return 0}catch(c){return"undefined"!==typeof Vb&&
c instanceof M||x(c),c.cb}},N:function(a,b,c,d){try{a:{for(var f=Yb(a),g=a=0;g<c;g++){var h=F[b+(8*g+4)>>2],k=f,l=F[b+8*g>>2],n=h,p=void 0,r=H;if(0>n||0>p)throw new M(28);if(null===k.fd)throw new M(8);if(1===(k.flags&2097155))throw new M(8);if(16384===(k.node.mode&61440))throw new M(31);if(!k.Oa.read)throw new M(28);var v="undefined"!==typeof p;if(!v)p=k.position;else if(!k.seekable)throw new M(70);var w=k.Oa.read(k,r,l,n,p);v||(k.position+=w);var q=w;if(0>q){var y=-1;break a}a+=q;if(q<h)break}y=
a}F[d>>2]=y;return 0}catch(z){return"undefined"!==typeof Vb&&z instanceof M||x(z),z.cb}},G:function(a,b,c,d,f){try{var g=Yb(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Pb(g,a,d);Za=[g.position>>>0,(Ya=g.position,1<=+Na(Ya)?0<Ya?(Qa(+Pa(Ya/4294967296),4294967295)|0)>>>0:~~+Oa((Ya-+(~~Ya>>>0))/4294967296)>>>0:0)];F[f>>2]=Za[0];F[f+4>>2]=Za[1];g.qb&&0===a&&0===d&&(g.qb=null);return 0}catch(h){return"undefined"!==typeof Vb&&h instanceof M||x(h),h.cb}},r:function(a,
b,c,d){try{a:{for(var f=Yb(a),g=a=0;g<c;g++){var h=f,k=F[b+8*g>>2],l=F[b+(8*g+4)>>2],n=void 0,p=H;if(0>l||0>n)throw new M(28);if(null===h.fd)throw new M(8);if(0===(h.flags&2097155))throw new M(8);if(16384===(h.node.mode&61440))throw new M(31);if(!h.Oa.write)throw new M(28);h.seekable&&h.flags&1024&&Pb(h,0,2);var r="undefined"!==typeof n;if(!r)n=h.position;else if(!h.seekable)throw new M(70);var v=h.Oa.write(h,p,k,l,n,void 0);r||(h.position+=v);try{if(h.path&&xb.onWriteToFile)xb.onWriteToFile(h.path)}catch(y){A("FS.trackingDelegate['onWriteToFile']('"+
h.path+"') threw an exception: "+y.message)}var w=v;if(0>w){var q=-1;break a}a+=w}q=a}F[d>>2]=q;return 0}catch(y){return"undefined"!==typeof Vb&&y instanceof M||x(y),y.cb}},a:function(){return ma|0},m:fd,e:gd,J:hd,p:id,H:jd,E:kd,D:ld,F:md,K:nd,k:od,l:pd,c:qd,memory:B,g:function(a){a=+a;return 0<=a?+Pa(a+.5):+Oa(a-.5)},h:function(a){a=+a;return 0<=a?+Pa(a+.5):+Oa(a-.5)},b:function(a){ma=a|0},table:oa};
(function(){function a(f){e.asm=f.exports;K--;e.monitorRunDependencies&&e.monitorRunDependencies(K);0==K&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa&&(f=Sa,Sa=null,f()))}function b(f){a(f.instance)}function c(f){return Xa().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){A("failed to asynchronously prepare wasm: "+g);x(g)})}var d={a:rd};K++;e.monitorRunDependencies&&e.monitorRunDependencies(K);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return A("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(na||"function"!==typeof WebAssembly.instantiateStreaming||Ua()||Ta("file://")||"function"!==typeof fetch)return c(b);fetch(L,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){A("wasm streaming compile failed: "+g);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var $a=e.___wasm_call_ctors=function(){return($a=e.___wasm_call_ctors=e.asm.U).apply(null,arguments)},qb=e._malloc=function(){return(qb=e._malloc=e.asm.V).apply(null,arguments)},V=e._free=function(){return(V=e._free=e.asm.W).apply(null,arguments)},Oc=e.___getTypeName=function(){return(Oc=e.___getTypeName=e.asm.X).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.Y).apply(null,arguments)};
var ed=e.___errno_location=function(){return(ed=e.___errno_location=e.asm.Z).apply(null,arguments)},X=e._setThrew=function(){return(X=e._setThrew=e.asm._).apply(null,arguments)},Y=e.stackSave=function(){return(Y=e.stackSave=e.asm.$).apply(null,arguments)},Z=e.stackRestore=function(){return(Z=e.stackRestore=e.asm.aa).apply(null,arguments)},sd=e.dynCall_v=function(){return(sd=e.dynCall_v=e.asm.ba).apply(null,arguments)},td=e.dynCall_vi=function(){return(td=e.dynCall_vi=e.asm.ca).apply(null,arguments)},
ud=e.dynCall_vii=function(){return(ud=e.dynCall_vii=e.asm.da).apply(null,arguments)};e.dynCall_viii=function(){return(e.dynCall_viii=e.asm.ea).apply(null,arguments)};var vd=e.dynCall_viiii=function(){return(vd=e.dynCall_viiii=e.asm.fa).apply(null,arguments)},wd=e.dynCall_ii=function(){return(wd=e.dynCall_ii=e.asm.ga).apply(null,arguments)},xd=e.dynCall_iii=function(){return(xd=e.dynCall_iii=e.asm.ha).apply(null,arguments)};e.dynCall_iiii=function(){return(e.dynCall_iiii=e.asm.ia).apply(null,arguments)};
var yd=e.dynCall_iiiii=function(){return(yd=e.dynCall_iiiii=e.asm.ja).apply(null,arguments)},zd=e.dynCall_iiiiiiiii=function(){return(zd=e.dynCall_iiiiiiiii=e.asm.ka).apply(null,arguments)},Ad=e.dynCall_iiiiiiiiii=function(){return(Ad=e.dynCall_iiiiiiiiii=e.asm.la).apply(null,arguments)},Bd=e.dynCall_iiiijj=function(){return(Bd=e.dynCall_iiiijj=e.asm.ma).apply(null,arguments)},Cd=e.dynCall_ij=function(){return(Cd=e.dynCall_ij=e.asm.na).apply(null,arguments)},Dd=e.dynCall_jjij=function(){return(Dd=
e.dynCall_jjij=e.asm.oa).apply(null,arguments)};e.dynCall_viiiiii=function(){return(e.dynCall_viiiiii=e.asm.pa).apply(null,arguments)};e.dynCall_viiiii=function(){return(e.dynCall_viiiii=e.asm.qa).apply(null,arguments)};e.dynCall_viiiiiiii=function(){return(e.dynCall_viiiiiiii=e.asm.ra).apply(null,arguments)};e.dynCall_viiiiiiiiiii=function(){return(e.dynCall_viiiiiiiiiii=e.asm.sa).apply(null,arguments)};e.dynCall_viiiiiiiiiiii=function(){return(e.dynCall_viiiiiiiiiiii=e.asm.ta).apply(null,arguments)};
e.dynCall_viiiiiii=function(){return(e.dynCall_viiiiiii=e.asm.ua).apply(null,arguments)};e.dynCall_viiiiiiiii=function(){return(e.dynCall_viiiiiiiii=e.asm.va).apply(null,arguments)};e.dynCall_iiiiii=function(){return(e.dynCall_iiiiii=e.asm.wa).apply(null,arguments)};e.dynCall_jiiiiiiiii=function(){return(e.dynCall_jiiiiiiiii=e.asm.xa).apply(null,arguments)};e.dynCall_iiiiiii=function(){return(e.dynCall_iiiiiii=e.asm.ya).apply(null,arguments)};
e.dynCall_iiiiiiii=function(){return(e.dynCall_iiiiiiii=e.asm.za).apply(null,arguments)};e.dynCall_iiiiiiiiiiii=function(){return(e.dynCall_iiiiiiiiiiii=e.asm.Aa).apply(null,arguments)};e.dynCall_iidiiii=function(){return(e.dynCall_iidiiii=e.asm.Ba).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.Ca).apply(null,arguments)};e.dynCall_i=function(){return(e.dynCall_i=e.asm.Da).apply(null,arguments)};
e.dynCall_viiiiiiiiii=function(){return(e.dynCall_viiiiiiiiii=e.asm.Ea).apply(null,arguments)};e.dynCall_viiiiiiiiiiiii=function(){return(e.dynCall_viiiiiiiiiiiii=e.asm.Fa).apply(null,arguments)};e.dynCall_jiiiiiiii=function(){return(e.dynCall_jiiiiiiii=e.asm.Ga).apply(null,arguments)};e.dynCall_ff=function(){return(e.dynCall_ff=e.asm.Ha).apply(null,arguments)};e.dynCall_jiiiiii=function(){return(e.dynCall_jiiiiii=e.asm.Ia).apply(null,arguments)};
e.dynCall_jiiiii=function(){return(e.dynCall_jiiiii=e.asm.Ja).apply(null,arguments)};e.dynCall_iiijii=function(){return(e.dynCall_iiijii=e.asm.Ka).apply(null,arguments)};function pd(a,b,c){var d=Y();try{ud(a,b,c)}catch(f){Z(d);if(f!==f+0&&"longjmp"!==f)throw f;X(1,0)}}function qd(a,b,c,d,f){var g=Y();try{vd(a,b,c,d,f)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}function gd(a,b,c){var d=Y();try{return xd(a,b,c)}catch(f){Z(d);if(f!==f+0&&"longjmp"!==f)throw f;X(1,0)}}
function od(a,b){var c=Y();try{td(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;X(1,0)}}function nd(a){var b=Y();try{sd(a)}catch(c){Z(b);if(c!==c+0&&"longjmp"!==c)throw c;X(1,0)}}function fd(a,b){var c=Y();try{return wd(a,b)}catch(d){Z(c);if(d!==d+0&&"longjmp"!==d)throw d;X(1,0)}}function hd(a,b,c,d,f){var g=Y();try{return yd(a,b,c,d,f)}catch(h){Z(g);if(h!==h+0&&"longjmp"!==h)throw h;X(1,0)}}
function jd(a,b,c,d,f,g,h,k,l,n){var p=Y();try{return Ad(a,b,c,d,f,g,h,k,l,n)}catch(r){Z(p);if(r!==r+0&&"longjmp"!==r)throw r;X(1,0)}}function id(a,b,c,d,f,g,h,k,l){var n=Y();try{return zd(a,b,c,d,f,g,h,k,l)}catch(p){Z(n);if(p!==p+0&&"longjmp"!==p)throw p;X(1,0)}}function md(a,b,c,d,f,g){var h=Y();try{return Dd(a,b,c,d,f,g)}catch(k){Z(h);if(k!==k+0&&"longjmp"!==k)throw k;X(1,0)}}
function kd(a,b,c,d,f,g,h,k){var l=Y();try{return Bd(a,b,c,d,f,g,h,k)}catch(n){Z(l);if(n!==n+0&&"longjmp"!==n)throw n;X(1,0)}}function ld(a,b,c){var d=Y();try{return Cd(a,b,c)}catch(f){Z(d);if(f!==f+0&&"longjmp"!==f)throw f;X(1,0)}}var Ed;Sa=function Fd(){Ed||Gd();Ed||(Sa=Fd)};
function Gd(){function a(){if(!Ed&&(Ed=!0,e.calledRun=!0,!pa)){e.noFSInit||Rb||(Rb=!0,Qb(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?Tb("stdin",e.stdin):Mb("/dev/tty","/dev/stdin"),e.stdout?Tb("stdout",null,e.stdout):Mb("/dev/tty","/dev/stdout"),e.stderr?Tb("stderr",null,e.stderr):Mb("/dev/tty1","/dev/stderr"),Nb("/dev/stdin","r"),Nb("/dev/stdout","w"),Nb("/dev/stderr","w"));Ha(Ja);wb=!1;Ha(Ka);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==
typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();La.unshift(b)}Ha(La)}}if(!(0<K)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ma();Ha(Ia);0<K||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=Gd;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;Gd();


  return avif_dec.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = avif_dec;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return avif_dec; });
    else if (typeof exports === 'object')
      exports["avif_dec"] = avif_dec;
    