
var avif_node_dec = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(avif_node_dec) {
  avif_node_dec = avif_node_dec || {};


var d;d||(d=typeof avif_node_dec !== 'undefined' ? avif_node_dec : {});var aa,q;d.ready=new Promise(function(a,b){aa=a;q=b});var r={},t;for(t in d)d.hasOwnProperty(t)&&(r[t]=d[t]);var u="",ba,v,w,x;u=__dirname+"/";ba=function(a){w||(w=require("fs"));x||(x=require("path"));a=x.normalize(a);return w.readFileSync(a,null)};v=function(a){a=ba(a);a.buffer||(a=new Uint8Array(a));a.buffer||y("Assertion failed: undefined");return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);
process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",y);d.inspect=function(){return"[Emscripten Module object]"};d.print||console.log.bind(console);var z=d.printErr||console.warn.bind(console);for(t in r)r.hasOwnProperty(t)&&(d[t]=r[t]);r=null;var A;d.wasmBinary&&(A=d.wasmBinary);var noExitRuntime;d.noExitRuntime&&(noExitRuntime=d.noExitRuntime);"object"!==typeof WebAssembly&&y("no native wasm support detected");var B,ca=!1,da=new TextDecoder("utf8");
function fa(a,b,c){var e=D;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}if(127>=g){if(b>=c)break;e[b++]=g}else{if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63}e[b++]=128|g>>6&63}e[b++]=128|g&63}}e[b]=0}}var ha=new TextDecoder("utf-16le");
function ia(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&E[c];)++c;return ha.decode(D.subarray(a,c<<1))}function ja(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var e=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)F[b>>1]=a.charCodeAt(f),b+=2;F[b>>1]=0;return b-e}function ka(a){return 2*a.length}function la(a,b){for(var c=0,e="";!(c>=b/4);){var f=G[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e}
function ma(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var h=a.charCodeAt(++f);g=65536+((g&1023)<<10)|h&1023}G[b>>2]=g;b+=4;if(b+4>c)break}G[b>>2]=0;return b-e}function na(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b}var H,I,D,F,E,G,J,oa,pa;
function qa(a){H=a;d.HEAP8=I=new Int8Array(a);d.HEAP16=F=new Int16Array(a);d.HEAP32=G=new Int32Array(a);d.HEAPU8=D=new Uint8Array(a);d.HEAPU16=E=new Uint16Array(a);d.HEAPU32=J=new Uint32Array(a);d.HEAPF32=oa=new Float32Array(a);d.HEAPF64=pa=new Float64Array(a)}var ra=d.INITIAL_MEMORY||16777216;d.wasmMemory?B=d.wasmMemory:B=new WebAssembly.Memory({initial:ra/65536,maximum:32768});B&&(H=B.buffer);ra=H.byteLength;qa(H);var K,sa=[],ta=[],ua=[],va=[];
function wa(){var a=d.preRun.shift();sa.unshift(a)}var L=0,M=null,N=null;d.preloadedImages={};d.preloadedAudios={};function y(a){if(d.onAbort)d.onAbort(a);z(a);ca=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");q(a);throw a;}function xa(){var a=P;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var P="avif_node_dec.wasm";
if(!xa()){var ya=P;P=d.locateFile?d.locateFile(ya,u):u+ya}function za(){try{if(A)return new Uint8Array(A);if(v)return v(P);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}function Q(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.v;"number"===typeof c?void 0===b.u?K.get(c)():K.get(c)(b.u):c(void 0===b.u?null:b.u)}}}
function R(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Aa=void 0;function S(a){for(var b="";D[a];)b+=Aa[D[a++]];return b}var T={},Ba={},Ca={};function Da(a,b){if(void 0===a)a="_unknown";else{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var c=a.charCodeAt(0);a=48<=c&&57>=c?"_"+a:a}return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ea(a){var b=Error,c=Da(a,function(e){this.name=a;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Fa=void 0;function U(a){throw new Fa(a);}
function V(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||U('type "'+e+'" must have a positive integer typeid pointer');if(Ba.hasOwnProperty(a)){if(c.A)return;U("Cannot register type '"+e+"' twice")}Ba[a]=b;delete Ca[a];T.hasOwnProperty(a)&&(b=T[a],delete T[a],b.forEach(function(f){f()}))}var Ga=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Ha(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ga.length?Ga.pop():W.length;W[b]={B:1,value:a};return b}}function Ia(a){return this.fromWireType(J[a>>2])}function Ja(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Ka(a,b){switch(b){case 2:return function(c){return this.fromWireType(oa[c>>2])};case 3:return function(c){return this.fromWireType(pa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function La(a,b,c){switch(b){case 0:return c?function(e){return I[e]}:function(e){return D[e]};case 1:return c?function(e){return F[e>>1]}:function(e){return E[e>>1]};case 2:return c?function(e){return G[e>>2]}:function(e){return J[e>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var Ma=Array(256),X=0;256>X;++X)Ma[X]=String.fromCharCode(X);Aa=Ma;Fa=d.BindingError=Ea("BindingError");d.InternalError=Ea("InternalError");
d.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};d.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};ta.push({v:function(){Na()}});
var Pa={j:function(a,b,c,e,f){var g=R(c);b=S(b);V(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?e:f},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=I;else if(2===c)l=F;else if(4===c)l=G;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>g])},s:null})},i:function(a,b){b=S(b);V(a,{name:b,fromWireType:function(c){var e=W[c].value;4<c&&0===--W[c].B&&(W[c]=void 0,Ga.push(c));return e},toWireType:function(c,e){return Ha(e)},
argPackAdvance:8,readValueFromPointer:Ia,s:null})},f:function(a,b,c){c=R(c);b=S(b);V(a,{name:b,fromWireType:function(e){return e},toWireType:function(e,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Ja(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Ka(b,c),s:null})},c:function(a,b,c,e,f){function g(m){return m}b=S(b);-1===f&&(f=4294967295);var h=R(c);if(0===e){var l=32-8*c;g=function(m){return m<<l>>>l}}var p=-1!=b.indexOf("unsigned");
V(a,{name:b,fromWireType:g,toWireType:function(m,k){if("number"!==typeof k&&"boolean"!==typeof k)throw new TypeError('Cannot convert "'+Ja(k)+'" to '+this.name);if(k<e||k>f)throw new TypeError('Passing a number "'+Ja(k)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return p?k>>>0:k|0},argPackAdvance:8,readValueFromPointer:La(b,h,0!==e),s:null})},b:function(a,b,c){function e(g){g>>=2;var h=J;return new f(H,h[g+1],h[g])}var f=[Int8Array,
Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);V(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{A:!0})},g:function(a,b){b=S(b);var c="std::string"===b;V(a,{name:b,fromWireType:function(e){var f=J[e>>2];if(c)for(var g=e+4,h=0;h<=f;++h){var l=e+4+h;if(h==f||0==D[l]){if(g){for(var p=g+(l-g),m=g;!(m>=p)&&D[m];)++m;g=da.decode(D.subarray(g,m))}else g="";if(void 0===k)var k=g;else k+=String.fromCharCode(0),k+=g;g=l+1}}else{k=Array(f);for(h=
0;h<f;++h)k[h]=String.fromCharCode(D[e+4+h]);k=k.join("")}Y(e);return k},toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||U("Cannot pass non-string to std::string");var h=(c&&g?function(){for(var m=0,k=0;k<f.length;++k){var n=f.charCodeAt(k);55296<=n&&57343>=n&&(n=65536+((n&1023)<<10)|f.charCodeAt(++k)&1023);127>=n?++m:m=2047>=n?m+2:65535>=n?m+3:m+4}return m}:function(){return f.length})(),
l=Oa(4+h+1);J[l>>2]=h;if(c&&g)fa(f,l+4,h+1);else if(g)for(g=0;g<h;++g){var p=f.charCodeAt(g);255<p&&(Y(l),U("String has UTF-16 code units that do not fit in 8 bits"));D[l+4+g]=p}else for(g=0;g<h;++g)D[l+4+g]=f[g];null!==e&&e.push(Y,l);return l},argPackAdvance:8,readValueFromPointer:Ia,s:function(e){Y(e)}})},e:function(a,b,c){c=S(c);if(2===b){var e=ia;var f=ja;var g=ka;var h=function(){return E};var l=1}else 4===b&&(e=la,f=ma,g=na,h=function(){return J},l=2);V(a,{name:c,fromWireType:function(p){for(var m=
J[p>>2],k=h(),n,C=p+4,O=0;O<=m;++O){var ea=p+4+O*b;if(O==m||0==k[ea>>l])C=e(C,ea-C),void 0===n?n=C:(n+=String.fromCharCode(0),n+=C),C=ea+b}Y(p);return n},toWireType:function(p,m){"string"!==typeof m&&U("Cannot pass non-string to C++ string type "+c);var k=g(m),n=Oa(4+k+b);J[n>>2]=k>>l;f(m,n+4,k+b);null!==p&&p.push(Y,n);return n},argPackAdvance:8,readValueFromPointer:Ia,s:function(p){Y(p)}})},k:function(a,b){b=S(b);V(a,{C:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},
h:function(a,b,c){D.copyWithin(a,b,b+c)},d:function(a){a>>>=0;var b=D.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(16777216,a,e);0<e%65536&&(e+=65536-e%65536);a:{try{B.grow(Math.min(2147483648,e)-H.byteLength+65535>>>16);qa(B.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},a:B};
(function(){function a(f){d.asm=f.exports;K=d.asm.l;L--;d.monitorRunDependencies&&d.monitorRunDependencies(L);0==L&&(null!==M&&(clearInterval(M),M=null),N&&(f=N,N=null,f()))}function b(f){a(f.instance)}function c(f){return Promise.resolve().then(za).then(function(g){return WebAssembly.instantiate(g,e)}).then(f,function(g){z("failed to asynchronously prepare wasm: "+g);y(g)})}var e={a:Pa};L++;d.monitorRunDependencies&&d.monitorRunDependencies(L);if(d.instantiateWasm)try{return d.instantiateWasm(e,
a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return A||"function"!==typeof WebAssembly.instantiateStreaming||xa()||"function"!==typeof fetch?c(b):fetch(P,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){z("wasm streaming compile failed: "+g);z("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(q);return{}})();
var Na=d.___wasm_call_ctors=function(){return(Na=d.___wasm_call_ctors=d.asm.m).apply(null,arguments)};d.___getTypeName=function(){return(d.___getTypeName=d.asm.n).apply(null,arguments)};d.___embind_register_native_and_builtin_types=function(){return(d.___embind_register_native_and_builtin_types=d.asm.o).apply(null,arguments)};var Oa=d._malloc=function(){return(Oa=d._malloc=d.asm.p).apply(null,arguments)},Y=d._free=function(){return(Y=d._free=d.asm.q).apply(null,arguments)},Z;
N=function Qa(){Z||Ra();Z||(N=Qa)};
function Ra(){function a(){if(!Z&&(Z=!0,d.calledRun=!0,!ca)){Q(ta);Q(ua);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();va.unshift(b)}Q(va)}}if(!(0<L)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)wa();Q(sa);0<L||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}
d.run=Ra;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();noExitRuntime=!0;Ra();


  return avif_node_dec.ready
}
);
})();
export default avif_node_dec;