
var avif_dec = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(avif_dec) {
  avif_dec = avif_dec || {};


var e;e||(e=typeof avif_dec !== 'undefined' ? avif_dec : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var r={},t;for(t in e)e.hasOwnProperty(t)&&(r[t]=e[t]);var u="",ca;u=self.location.href;_scriptDir&&(u=_scriptDir);0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="";ca=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var da=e.print||console.log.bind(console),v=e.printErr||console.warn.bind(console);
for(t in r)r.hasOwnProperty(t)&&(e[t]=r[t]);r=null;var ea=0,w;e.wasmBinary&&(w=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&y("no native wasm support detected");var z,fa=!1,ha=new TextDecoder("utf8");
function ia(a,b,c){var d=A;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var ja=new TextDecoder("utf-16le");
function ka(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&B[c];)++c;return ja.decode(A.subarray(a,c<<1))}function la(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)C[b>>1]=a.charCodeAt(f),b+=2;C[b>>1]=0;return b-d}function ma(a){return 2*a.length}function na(a,b){for(var c=0,d="";!(c>=b/4);){var f=E[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}
function oa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}E[b>>2]=g;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var F,qa,A,C,B,E,G,ra,sa;
function ta(a){F=a;e.HEAP8=qa=new Int8Array(a);e.HEAP16=C=new Int16Array(a);e.HEAP32=E=new Int32Array(a);e.HEAPU8=A=new Uint8Array(a);e.HEAPU16=B=new Uint16Array(a);e.HEAPU32=G=new Uint32Array(a);e.HEAPF32=ra=new Float32Array(a);e.HEAPF64=sa=new Float64Array(a)}var ua=e.INITIAL_MEMORY||16777216;e.wasmMemory?z=e.wasmMemory:z=new WebAssembly.Memory({initial:ua/65536,maximum:32768});z&&(F=z.buffer);ua=F.byteLength;ta(F);var H,va=[],wa=[],xa=[],ya=[];
function za(){var a=e.preRun.shift();va.unshift(a)}var I=0,Aa=null,K=null;e.preloadedImages={};e.preloadedAudios={};function y(a){if(e.onAbort)e.onAbort(a);v(a);fa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ba(){var a=L;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var L="avif_dec.wasm";
if(!Ba()){var Ca=L;L=e.locateFile?e.locateFile(Ca,u):u+Ca}function Da(){try{if(w)return new Uint8Array(w);if(ca)return ca(L);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}function Ea(){return w||"function"!==typeof fetch?Promise.resolve().then(Da):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return Da()})}
function M(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.T;"number"===typeof c?void 0===b.P?H.get(c)():H.get(c)(b.P):c(void 0===b.P?null:b.P)}}}function Fa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ga=void 0;function O(a){for(var b="";A[a];)b+=Ga[A[a++]];return b}var P={},Q={},R={};
function Ha(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ia(a,b){a=Ha(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ja(a){var b=Error,c=Ia(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ka=void 0;function S(a){throw new Ka(a);}var La=void 0;
function Ma(a,b){function c(h){h=b(h);if(h.length!==d.length)throw new La("Mismatched type converter count");for(var n=0;n<d.length;++n)T(d[n],h[n])}var d=[];d.forEach(function(h){R[h]=a});var f=Array(a.length),g=[],k=0;a.forEach(function(h,n){Q.hasOwnProperty(h)?f[n]=Q[h]:(g.push(h),P.hasOwnProperty(h)||(P[h]=[]),P[h].push(function(){f[n]=Q[h];++k;k===g.length&&c(f)}))});0===g.length&&c(f)}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(Q.hasOwnProperty(a)){if(c.U)return;S("Cannot register type '"+d+"' twice")}Q[a]=b;delete R[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(function(f){f()}))}var Na=[],U=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Oa(a){4<a&&0===--U[a].R&&(U[a]=void 0,Na.push(a))}function V(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Na.length?Na.pop():U.length;U[b]={R:1,value:a};return b}}function Ra(a){return this.fromWireType(G[a>>2])}function Sa(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Ta(a,b){switch(b){case 2:return function(c){return this.fromWireType(ra[c>>2])};case 3:return function(c){return this.fromWireType(sa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Ua(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ia(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Va(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Wa(a,b){var c=e;if(void 0===c[a].N){var d=c[a];c[a]=function(){c[a].N.hasOwnProperty(arguments.length)||S("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].N+")!");return c[a].N[arguments.length].apply(this,arguments)};c[a].N=[];c[a].N[d.S]=d}}
function Xa(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].N&&void 0!==e[a].N[c])&&S("Cannot register public name '"+a+"' twice"),Wa(a,a),e.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].N[c]=b):(e[a]=b,void 0!==c&&(e[a].W=c))}function Ya(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}
function Za(a,b){0<=a.indexOf("j")||y("Assertion failed: getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var f;-1!=a.indexOf("j")?f=c&&c.length?e["dynCall_"+a].apply(null,[b].concat(c)):e["dynCall_"+a].call(null,b):f=H.get(b).apply(null,c);return f}}
function $a(a,b){a=O(a);var c=-1!=a.indexOf("j")?Za(a,b):H.get(b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var ab=void 0;function bb(a){a=cb(a);var b=O(a);W(a);return b}function db(a,b){function c(g){f[g]||Q[g]||(R[g]?R[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new ab(a+": "+d.map(bb).join([", "]));}
function eb(a,b,c){switch(b){case 0:return c?function(d){return qa[d]}:function(d){return A[d]};case 1:return c?function(d){return C[d>>1]}:function(d){return B[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return G[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var fb={};function gb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function hb(a,b){var c=Q[a];void 0===c&&S(b+" has unknown type "+bb(a));return c}
for(var ib={},jb=[null,[],[]],kb=Array(256),lb=0;256>lb;++lb)kb[lb]=String.fromCharCode(lb);Ga=kb;Ka=e.BindingError=Ja("BindingError");La=e.InternalError=Ja("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<U.length;++b)void 0!==U[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<U.length;++a)if(void 0!==U[a])return U[a];return null};ab=e.UnboundTypeError=Ja("UnboundTypeError");wa.push({T:function(){mb()}});
var sb={l:function(){},t:function(a,b,c,d,f){var g=Fa(c);b=O(b);T(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:f},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=qa;else if(2===c)h=C;else if(4===c)h=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[k>>g])},O:null})},B:function(a,b){b=O(b);T(a,{name:b,fromWireType:function(c){var d=U[c].value;Oa(c);return d},toWireType:function(c,d){return V(d)},argPackAdvance:8,
readValueFromPointer:Ra,O:null})},s:function(a,b,c){c=Fa(c);b=O(b);T(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Sa(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Ta(b,c),O:null})},v:function(a,b,c,d,f,g){var k=Ya(b,c);a=O(a);f=$a(d,f);Xa(a,function(){db("Cannot call "+a+" due to unbound types",k)},b-1);Ma(k,function(h){var n=a,l=a;h=[h[0],null].concat(h.slice(1));var m=
f,q=h.length;2>q&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==h[1]&&!1,D=!1,p=1;p<h.length;++p)if(null!==h[p]&&void 0===h[p].O){D=!0;break}var Pa="void"!==h[0].name,J="",N="";for(p=0;p<q-2;++p)J+=(0!==p?", ":"")+"arg"+p,N+=(0!==p?", ":"")+"arg"+p+"Wired";l="return function "+Ha(l)+"("+J+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+l+" called with ' + arguments.length + ' arguments, expected "+(q-2)+" args!');\n}\n";
D&&(l+="var destructors = [];\n");var Qa=D?"destructors":"null";J="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[S,m,g,Va,h[0],h[1]];x&&(l+="var thisWired = classParam.toWireType("+Qa+", this);\n");for(p=0;p<q-2;++p)l+="var arg"+p+"Wired = argType"+p+".toWireType("+Qa+", arg"+p+"); // "+h[p+2].name+"\n",J.push("argType"+p),m.push(h[p+2]);x&&(N="thisWired"+(0<N.length?", ":"")+N);l+=(Pa?"var rv = ":"")+"invoker(fn"+(0<N.length?", ":"")+N+");\n";if(D)l+="runDestructors(destructors);\n";
else for(p=x?1:2;p<h.length;++p)q=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==h[p].O&&(l+=q+"_dtor("+q+"); // "+h[p].name+"\n",J.push(q+"_dtor"),m.push(h[p].O));Pa&&(l+="var ret = retType.fromWireType(rv);\nreturn ret;\n");J.push(l+"}\n");h=Ua(J).apply(null,m);p=b-1;if(!e.hasOwnProperty(n))throw new La("Replacing nonexistant public symbol");void 0!==e[n].N&&void 0!==p?e[n].N[p]=h:(e[n]=h,e[n].S=p);return[]})},f:function(a,b,c,d,f){function g(l){return l}b=O(b);-1===f&&(f=4294967295);var k=Fa(c);
if(0===d){var h=32-8*c;g=function(l){return l<<h>>>h}}var n=-1!=b.indexOf("unsigned");T(a,{name:b,fromWireType:g,toWireType:function(l,m){if("number"!==typeof m&&"boolean"!==typeof m)throw new TypeError('Cannot convert "'+Sa(m)+'" to '+this.name);if(m<d||m>f)throw new TypeError('Passing a number "'+Sa(m)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return n?m>>>0:m|0},argPackAdvance:8,readValueFromPointer:eb(b,k,0!==d),O:null})},
e:function(a,b,c){function d(g){g>>=2;var k=G;return new f(F,k[g+1],k[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=O(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{U:!0})},n:function(a,b){b=O(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var f=G[d>>2];if(c)for(var g=d+4,k=0;k<=f;++k){var h=d+4+k;if(k==f||0==A[h]){if(g){for(var n=g+(h-g),l=g;!(l>=n)&&A[l];)++l;g=ha.decode(A.subarray(g,l))}else g=
"";if(void 0===m)var m=g;else m+=String.fromCharCode(0),m+=g;g=h+1}}else{m=Array(f);for(k=0;k<f;++k)m[k]=String.fromCharCode(A[d+4+k]);m=m.join("")}W(d);return m},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||S("Cannot pass non-string to std::string");var k=(c&&g?function(){for(var l=0,m=0;m<f.length;++m){var q=f.charCodeAt(m);55296<=q&&57343>=q&&(q=65536+((q&1023)<<
10)|f.charCodeAt(++m)&1023);127>=q?++l:l=2047>=q?l+2:65535>=q?l+3:l+4}return l}:function(){return f.length})(),h=nb(4+k+1);G[h>>2]=k;if(c&&g)ia(f,h+4,k+1);else if(g)for(g=0;g<k;++g){var n=f.charCodeAt(g);255<n&&(W(h),S("String has UTF-16 code units that do not fit in 8 bits"));A[h+4+g]=n}else for(g=0;g<k;++g)A[h+4+g]=f[g];null!==d&&d.push(W,h);return h},argPackAdvance:8,readValueFromPointer:Ra,O:function(d){W(d)}})},m:function(a,b,c){c=O(c);if(2===b){var d=ka;var f=la;var g=ma;var k=function(){return B};
var h=1}else 4===b&&(d=na,f=oa,g=pa,k=function(){return G},h=2);T(a,{name:c,fromWireType:function(n){for(var l=G[n>>2],m=k(),q,x=n+4,D=0;D<=l;++D){var p=n+4+D*b;if(D==l||0==m[p>>h])x=d(x,p-x),void 0===q?q=x:(q+=String.fromCharCode(0),q+=x),x=p+b}W(n);return q},toWireType:function(n,l){"string"!==typeof l&&S("Cannot pass non-string to C++ string type "+c);var m=g(l),q=nb(4+m+b);G[q>>2]=m>>h;f(l,q+4,m+b);null!==n&&n.push(W,q);return q},argPackAdvance:8,readValueFromPointer:Ra,O:function(n){W(n)}})},
u:function(a,b){b=O(b);T(a,{V:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},j:Oa,k:function(a){if(0===a)return V(gb());var b=fb[a];a=void 0===b?O(a):b;return V(gb()[a])},o:function(a){4<a&&(U[a].R+=1)},p:function(a,b,c,d){a||S("Cannot use deleted val. handle = "+a);a=U[a].value;var f=ib[b];if(!f){f="";for(var g=0;g<b;++g)f+=(0!==g?", ":"")+"arg"+g;var k="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(g=0;g<b;++g)k+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+
g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";f=(new Function("requireRegisteredType","Module","__emval_register",k+("var obj = new constructor("+f+");\nreturn __emval_register(obj);\n}\n")))(hb,e,V);ib[b]=f}return f(a,c,d)},d:function(){y()},i:function(a,b){X(a,b||1);throw"longjmp";},z:function(a,b,c){A.copyWithin(a,b,b+c)},h:function(a){a>>>=0;var b=A.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+
.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{z.grow(Math.min(2147483648,d)-F.byteLength+65535>>>16);ta(z.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},A:function(){return 0},w:function(){},r:function(a,b,c,d){for(var f=0,g=0;g<c;g++){for(var k=E[b+8*g>>2],h=E[b+(8*g+4)>>2],n=0;n<h;n++){var l=A[k+n],m=jb[a];if(0===l||10===l){for(l=0;m[l]&&!(NaN<=l);)++l;l=ha.decode(m.subarray?m.subarray(0,l):new Uint8Array(m.slice(0,l)));(1===a?
da:v)(l);m.length=0}else m.push(l)}f+=h}E[d>>2]=f;return 0},b:function(){return ea|0},g:ob,x:pb,q:qb,y:rb,a:z,c:function(a){ea=a|0}};
(function(){function a(f){e.asm=f.exports;H=e.asm.C;I--;e.monitorRunDependencies&&e.monitorRunDependencies(I);0==I&&(null!==Aa&&(clearInterval(Aa),Aa=null),K&&(f=K,K=null,f()))}function b(f){a(f.instance)}function c(f){return Ea().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){v("failed to asynchronously prepare wasm: "+g);y(g)})}var d={a:sb};I++;e.monitorRunDependencies&&e.monitorRunDependencies(I);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return v("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return w||"function"!==typeof WebAssembly.instantiateStreaming||Ba()||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){v("wasm streaming compile failed: "+g);v("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
var mb=e.___wasm_call_ctors=function(){return(mb=e.___wasm_call_ctors=e.asm.D).apply(null,arguments)},nb=e._malloc=function(){return(nb=e._malloc=e.asm.E).apply(null,arguments)},W=e._free=function(){return(W=e._free=e.asm.F).apply(null,arguments)},cb=e.___getTypeName=function(){return(cb=e.___getTypeName=e.asm.G).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.H).apply(null,arguments)};
var Y=e.stackSave=function(){return(Y=e.stackSave=e.asm.I).apply(null,arguments)},Z=e.stackRestore=function(){return(Z=e.stackRestore=e.asm.J).apply(null,arguments)},X=e._setThrew=function(){return(X=e._setThrew=e.asm.K).apply(null,arguments)};e.dynCall_iiijii=function(){return(e.dynCall_iiijii=e.asm.L).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.M).apply(null,arguments)};
function rb(a,b,c,d,f,g,k,h){var n=Y();try{H.get(a)(b,c,d,f,g,k,h)}catch(l){Z(n);if(l!==l+0&&"longjmp"!==l)throw l;X(1,0)}}function qb(a,b,c,d,f){var g=Y();try{H.get(a)(b,c,d,f)}catch(k){Z(g);if(k!==k+0&&"longjmp"!==k)throw k;X(1,0)}}function ob(a,b,c){var d=Y();try{return H.get(a)(b,c)}catch(f){Z(d);if(f!==f+0&&"longjmp"!==f)throw f;X(1,0)}}function pb(a,b,c,d,f){var g=Y();try{return H.get(a)(b,c,d,f)}catch(k){Z(g);if(k!==k+0&&"longjmp"!==k)throw k;X(1,0)}}var tb;
K=function ub(){tb||vb();tb||(K=ub)};
function vb(){function a(){if(!tb&&(tb=!0,e.calledRun=!0,!fa)){M(wa);M(xa);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();ya.unshift(b)}M(ya)}}if(!(0<I)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)za();M(va);0<I||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
e.run=vb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;vb();


  return avif_dec.ready
}
);
})();
export default avif_dec;