
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var r={},t;for(t in e)e.hasOwnProperty(t)&&(r[t]=e[t]);var u="",ca;u=self.location.href;_scriptDir&&(u=_scriptDir);0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="";ca=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var da=e.print||console.log.bind(console),v=e.printErr||console.warn.bind(console);
for(t in r)r.hasOwnProperty(t)&&(e[t]=r[t]);r=null;var w;e.wasmBinary&&(w=e.wasmBinary);var noExitRuntime;e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&y("no native wasm support detected");var z,ea=!1,fa=new TextDecoder("utf8");function A(a,b){if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&B[c];)++c;return fa.decode(B.subarray(a,c))}
function ha(a,b,c){var d=B;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var ia=new TextDecoder("utf-16le");
function ja(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&D[c];)++c;return ia.decode(B.subarray(a,c<<1))}function ka(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)E[b>>1]=a.charCodeAt(f),b+=2;E[b>>1]=0;return b-d}function la(a){return 2*a.length}function ma(a,b){for(var c=0,d="";!(c>=b/4);){var f=F[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}
function na(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}F[b>>2]=g;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function oa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var G,H,B,E,D,F,J,pa,qa;
function ra(a){G=a;e.HEAP8=H=new Int8Array(a);e.HEAP16=E=new Int16Array(a);e.HEAP32=F=new Int32Array(a);e.HEAPU8=B=new Uint8Array(a);e.HEAPU16=D=new Uint16Array(a);e.HEAPU32=J=new Uint32Array(a);e.HEAPF32=pa=new Float32Array(a);e.HEAPF64=qa=new Float64Array(a)}var sa=e.INITIAL_MEMORY||16777216;e.wasmMemory?z=e.wasmMemory:z=new WebAssembly.Memory({initial:sa/65536,maximum:32768});z&&(G=z.buffer);sa=G.byteLength;ra(G);var K,ta=[],ua=[],va=[],wa=[];
function xa(){var a=e.preRun.shift();ta.unshift(a)}var L=0,ya=null,M=null;e.preloadedImages={};e.preloadedAudios={};function y(a){if(e.onAbort)e.onAbort(a);v(a);ea=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function za(){var a=O;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var O="basis_dec.wasm";
if(!za()){var Aa=O;O=e.locateFile?e.locateFile(Aa,u):u+Aa}function Ba(){try{if(w)return new Uint8Array(w);if(ca)return ca(O);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}function Ca(){return w||"function"!==typeof fetch?Promise.resolve().then(Ba):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Ba()})}
function P(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.O;"number"===typeof c?void 0===b.K?K.get(c)():K.get(c)(b.K):c(void 0===b.K?null:b.K)}}}function Da(a){this.J=a-16;this.W=function(b){F[this.J+8>>2]=b};this.T=function(b){F[this.J+0>>2]=b};this.U=function(){F[this.J+4>>2]=0};this.S=function(){H[this.J+12>>0]=0};this.V=function(){H[this.J+13>>0]=0};this.R=function(b,c){this.W(b);this.T(c);this.U();this.S();this.V()}}function Q(){return 0<Q.M}
function Ea(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Fa=void 0;function R(a){for(var b="";B[a];)b+=Fa[B[a++]];return b}var S={},T={},U={};function Ga(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Ha(a,b){a=Ga(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ia(a){var b=Error,c=Ha(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Ja=void 0;function V(a){throw new Ja(a);}var Ka=void 0;function La(a,b){function c(h){h=b(h);if(h.length!==d.length)throw new Ka("Mismatched type converter count");for(var m=0;m<d.length;++m)W(d[m],h[m])}var d=[];d.forEach(function(h){U[h]=a});var f=Array(a.length),g=[],k=0;a.forEach(function(h,m){T.hasOwnProperty(h)?f[m]=T[h]:(g.push(h),S.hasOwnProperty(h)||(S[h]=[]),S[h].push(function(){f[m]=T[h];++k;k===g.length&&c(f)}))});0===g.length&&c(f)}
function W(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(T.hasOwnProperty(a)){if(c.P)return;V("Cannot register type '"+d+"' twice")}T[a]=b;delete U[a];S.hasOwnProperty(a)&&(b=S[a],delete S[a],b.forEach(function(f){f()}))}var Ma=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Na(a){4<a&&0===--X[a].L&&(X[a]=void 0,Ma.push(a))}function Y(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ma.length?Ma.pop():X.length;X[b]={L:1,value:a};return b}}function Qa(a){return this.fromWireType(J[a>>2])}function Ra(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Sa(a,b){switch(b){case 2:return function(c){return this.fromWireType(pa[c>>2])};case 3:return function(c){return this.fromWireType(qa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Ta(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ha(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Ua(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Va(a,b){var c=e;if(void 0===c[a].H){var d=c[a];c[a]=function(){c[a].H.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].H+")!");return c[a].H[arguments.length].apply(this,arguments)};c[a].H=[];c[a].H[d.N]=d}}
function Wa(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].H&&void 0!==e[a].H[c])&&V("Cannot register public name '"+a+"' twice"),Va(a,a),e.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].H[c]=b):(e[a]=b,void 0!==c&&(e[a].Y=c))}function Xa(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function Ya(a,b){0<=a.indexOf("j")||y("Assertion failed: getDynCaller should only be called with i64 sigs");var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];var f;-1!=a.indexOf("j")?f=c&&c.length?e["dynCall_"+a].apply(null,[b].concat(c)):e["dynCall_"+a].call(null,b):f=K.get(b).apply(null,c);return f}}
function Za(a,b){a=R(a);var c=-1!=a.indexOf("j")?Ya(a,b):K.get(b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var $a=void 0;function ab(a){a=bb(a);var b=R(a);Z(a);return b}function cb(a,b){function c(g){f[g]||T[g]||(U[g]?U[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new $a(a+": "+d.map(ab).join([", "]));}
function db(a,b,c){switch(b){case 0:return c?function(d){return H[d]}:function(d){return B[d]};case 1:return c?function(d){return E[d>>1]}:function(d){return D[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return J[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var eb={};function fb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function gb(a,b){var c=T[a];void 0===c&&V(b+" has unknown type "+ab(a));return c}
for(var hb={},ib=[null,[],[]],jb=Array(256),kb=0;256>kb;++kb)jb[kb]=String.fromCharCode(kb);Fa=jb;Ja=e.BindingError=Ia("BindingError");Ka=e.InternalError=Ia("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};$a=e.UnboundTypeError=Ia("UnboundTypeError");ua.push({O:function(){lb()}});
var nb={b:function(a,b,c,d){y("Assertion failed: "+A(a)+", at: "+[b?A(b):"unknown filename",c,d?A(d):"unknown function"])},z:function(a){return mb(a+16)+16},i:function(){},t:function(a,b,c){(new Da(a)).R(b,c);"uncaught_exception"in Q?Q.M++:Q.M=1;throw a;},w:function(a,b,c,d,f){var g=Ea(c);b=R(b);W(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:f},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=H;else if(2===c)h=E;else if(4===c)h=F;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(h[k>>g])},I:null})},v:function(a,b){b=R(b);W(a,{name:b,fromWireType:function(c){var d=X[c].value;Na(c);return d},toWireType:function(c,d){return Y(d)},argPackAdvance:8,readValueFromPointer:Qa,I:null})},n:function(a,b,c){c=Ea(c);b=R(b);W(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+Ra(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Sa(b,c),I:null})},
y:function(a,b,c,d,f,g){var k=Xa(b,c);a=R(a);f=Za(d,f);Wa(a,function(){cb("Cannot call "+a+" due to unbound types",k)},b-1);La(k,function(h){var m=a,l=a;h=[h[0],null].concat(h.slice(1));var p=f,q=h.length;2>q&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==h[1]&&!1,C=!1,n=1;n<h.length;++n)if(null!==h[n]&&void 0===h[n].I){C=!0;break}var Oa="void"!==h[0].name,I="",N="";for(n=0;n<q-2;++n)I+=(0!==n?", ":"")+"arg"+n,N+=(0!==n?", ":"")+"arg"+n+"Wired";
l="return function "+Ga(l)+"("+I+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+l+" called with ' + arguments.length + ' arguments, expected "+(q-2)+" args!');\n}\n";C&&(l+="var destructors = [];\n");var Pa=C?"destructors":"null";I="throwBindingError invoker fn runDestructors retType classParam".split(" ");p=[V,p,g,Ua,h[0],h[1]];x&&(l+="var thisWired = classParam.toWireType("+Pa+", this);\n");for(n=0;n<q-2;++n)l+="var arg"+n+"Wired = argType"+n+".toWireType("+Pa+", arg"+
n+"); // "+h[n+2].name+"\n",I.push("argType"+n),p.push(h[n+2]);x&&(N="thisWired"+(0<N.length?", ":"")+N);l+=(Oa?"var rv = ":"")+"invoker(fn"+(0<N.length?", ":"")+N+");\n";if(C)l+="runDestructors(destructors);\n";else for(n=x?1:2;n<h.length;++n)q=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==h[n].I&&(l+=q+"_dtor("+q+"); // "+h[n].name+"\n",I.push(q+"_dtor"),p.push(h[n].I));Oa&&(l+="var ret = retType.fromWireType(rv);\nreturn ret;\n");I.push(l+"}\n");h=Ta(I).apply(null,p);n=b-1;if(!e.hasOwnProperty(m))throw new Ka("Replacing nonexistant public symbol");
void 0!==e[m].H&&void 0!==n?e[m].H[n]=h:(e[m]=h,e[m].N=n);return[]})},d:function(a,b,c,d,f){function g(l){return l}b=R(b);-1===f&&(f=4294967295);var k=Ea(c);if(0===d){var h=32-8*c;g=function(l){return l<<h>>>h}}var m=-1!=b.indexOf("unsigned");W(a,{name:b,fromWireType:g,toWireType:function(l,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+Ra(p)+'" to '+this.name);if(p<d||p>f)throw new TypeError('Passing a number "'+Ra(p)+'" from JS side to C/C++ side to an argument of type "'+
b+'", which is outside the valid range ['+d+", "+f+"]!");return m?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:db(b,k,0!==d),I:null})},c:function(a,b,c){function d(g){g>>=2;var k=J;return new f(G,k[g+1],k[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);W(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{P:!0})},o:function(a,b){b=R(b);var c="std::string"===b;W(a,{name:b,fromWireType:function(d){var f=J[d>>2];if(c)for(var g=
d+4,k=0;k<=f;++k){var h=d+4+k;if(k==f||0==B[h]){g=A(g,h-g);if(void 0===m)var m=g;else m+=String.fromCharCode(0),m+=g;g=h+1}}else{m=Array(f);for(k=0;k<f;++k)m[k]=String.fromCharCode(B[d+4+k]);m=m.join("")}Z(d);return m},toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||V("Cannot pass non-string to std::string");var k=(c&&g?function(){for(var l=0,p=0;p<f.length;++p){var q=
f.charCodeAt(p);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|f.charCodeAt(++p)&1023);127>=q?++l:l=2047>=q?l+2:65535>=q?l+3:l+4}return l}:function(){return f.length})(),h=mb(4+k+1);J[h>>2]=k;if(c&&g)ha(f,h+4,k+1);else if(g)for(g=0;g<k;++g){var m=f.charCodeAt(g);255<m&&(Z(h),V("String has UTF-16 code units that do not fit in 8 bits"));B[h+4+g]=m}else for(g=0;g<k;++g)B[h+4+g]=f[g];null!==d&&d.push(Z,h);return h},argPackAdvance:8,readValueFromPointer:Qa,I:function(d){Z(d)}})},j:function(a,b,c){c=R(c);
if(2===b){var d=ja;var f=ka;var g=la;var k=function(){return D};var h=1}else 4===b&&(d=ma,f=na,g=oa,k=function(){return J},h=2);W(a,{name:c,fromWireType:function(m){for(var l=J[m>>2],p=k(),q,x=m+4,C=0;C<=l;++C){var n=m+4+C*b;if(C==l||0==p[n>>h])x=d(x,n-x),void 0===q?q=x:(q+=String.fromCharCode(0),q+=x),x=n+b}Z(m);return q},toWireType:function(m,l){"string"!==typeof l&&V("Cannot pass non-string to C++ string type "+c);var p=g(l),q=mb(4+p+b);J[q>>2]=p>>h;f(l,q+4,p+b);null!==m&&m.push(Z,q);return q},
argPackAdvance:8,readValueFromPointer:Qa,I:function(m){Z(m)}})},x:function(a,b){b=R(b);W(a,{X:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},f:Na,h:function(a){if(0===a)return Y(fb());var b=eb[a];a=void 0===b?R(a):b;return Y(fb()[a])},k:function(a){4<a&&(X[a].L+=1)},l:function(a,b,c,d){a||V("Cannot use deleted val. handle = "+a);a=X[a].value;var f=hb[b];if(!f){f="";for(var g=0;g<b;++g)f+=(0!==g?", ":"")+"arg"+g;var k="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";
for(g=0;g<b;++g)k+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";f=(new Function("requireRegisteredType","Module","__emval_register",k+("var obj = new constructor("+f+");\nreturn __emval_register(obj);\n}\n")))(gb,e,Y);hb[b]=f}return f(a,c,d)},p:function(a,b){a=gb(a,"_emval_take_value");a=a.readValueFromPointer(b);return Y(a)},g:function(){y()},
s:function(a,b,c){B.copyWithin(a,b,b+c)},e:function(a){a>>>=0;var b=B.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{z.grow(Math.min(2147483648,d)-G.byteLength+65535>>>16);ra(z.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},u:function(){return 0},q:function(){},m:function(a,b,c,d){for(var f=0,g=0;g<c;g++){for(var k=F[b+8*g>>2],h=F[b+(8*g+4)>>2],m=0;m<h;m++){var l=B[k+
m],p=ib[a];if(0===l||10===l){for(l=0;p[l]&&!(NaN<=l);)++l;l=fa.decode(p.subarray?p.subarray(0,l):new Uint8Array(p.slice(0,l)));(1===a?da:v)(l);p.length=0}else p.push(l)}f+=h}F[d>>2]=f;return 0},a:z,r:function(){}};
(function(){function a(f){e.asm=f.exports;K=e.asm.A;L--;e.monitorRunDependencies&&e.monitorRunDependencies(L);0==L&&(null!==ya&&(clearInterval(ya),ya=null),M&&(f=M,M=null,f()))}function b(f){a(f.instance)}function c(f){return Ca().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){v("failed to asynchronously prepare wasm: "+g);y(g)})}var d={a:nb};L++;e.monitorRunDependencies&&e.monitorRunDependencies(L);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return v("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){return w||"function"!==typeof WebAssembly.instantiateStreaming||za()||"function"!==typeof fetch?c(b):fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){v("wasm streaming compile failed: "+g);v("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
var lb=e.___wasm_call_ctors=function(){return(lb=e.___wasm_call_ctors=e.asm.B).apply(null,arguments)},Z=e._free=function(){return(Z=e._free=e.asm.C).apply(null,arguments)},mb=e._malloc=function(){return(mb=e._malloc=e.asm.D).apply(null,arguments)},bb=e.___getTypeName=function(){return(bb=e.___getTypeName=e.asm.E).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.F).apply(null,arguments)};
e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.G).apply(null,arguments)};var ob;M=function pb(){ob||qb();ob||(M=pb)};
function qb(){function a(){if(!ob&&(ob=!0,e.calledRun=!0,!ea)){P(ua);P(va);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();wa.unshift(b)}P(wa)}}if(!(0<L)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)xa();P(ta);0<L||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
e.run=qb;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;qb();


  return Module.ready
}
);
})();
export default Module;