
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var r={},t;for(t in g)g.hasOwnProperty(t)&&(r[t]=g[t]);var u="",da;u=self.location.href;_scriptDir&&(u=_scriptDir);0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="";da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var ea=g.print||console.log.bind(console),v=g.printErr||console.warn.bind(console);
for(t in r)r.hasOwnProperty(t)&&(g[t]=r[t]);r=null;var w;g.wasmBinary&&(w=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var fa,ha=!1,ia=new TextDecoder("utf8");function B(a,b){if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&C[c];)++c;return ia.decode(C.subarray(a,c))}
function ja(a,b,c){var d=C;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var m=a.charCodeAt(++e);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}}var ka=new TextDecoder("utf-16le");
function la(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&D[c];)++c;return ka.decode(C.subarray(a,c<<1))}function ma(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)F[b>>1]=a.charCodeAt(e),b+=2;F[b>>1]=0;return b-d}function na(a){return 2*a.length}function oa(a,b){for(var c=0,d="";!(c>=b/4);){var e=G[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function pa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var m=a.charCodeAt(++e);f=65536+((f&1023)<<10)|m&1023}G[b>>2]=f;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d}function qa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ra,H,C,F,D,G,I,sa,ta;
function ua(){var a=fa.buffer;ra=a;g.HEAP8=H=new Int8Array(a);g.HEAP16=F=new Int16Array(a);g.HEAP32=G=new Int32Array(a);g.HEAPU8=C=new Uint8Array(a);g.HEAPU16=D=new Uint16Array(a);g.HEAPU32=I=new Uint32Array(a);g.HEAPF32=sa=new Float32Array(a);g.HEAPF64=ta=new Float64Array(a)}var J,va=[],wa=[],xa=[];function ya(){var a=g.preRun.shift();va.unshift(a)}var K=0,za=null,L=null;g.preloadedImages={};g.preloadedAudios={};
function A(a){if(g.onAbort)g.onAbort(a);v(a);ha=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}var M=(new URL("wp2_enc.wasm",import.meta.url)).toString();function Aa(){try{if(M==M&&w)return new Uint8Array(w);if(da)return da(M);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}
function Ba(){return w||"function"!==typeof fetch?Promise.resolve().then(function(){return Aa()}):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Aa()})}function Ca(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.ha;"number"===typeof c?void 0===b.N?J.get(c)():J.get(c)(b.N):c(void 0===b.N?null:b.N)}}}
function Da(a){this.M=a-16;this.da=function(b){G[this.M+8>>2]=b};this.aa=function(b){G[this.M+0>>2]=b};this.ba=function(){G[this.M+4>>2]=0};this.$=function(){H[this.M+12>>0]=0};this.ca=function(){H[this.M+13>>0]=0};this.X=function(b,c){this.da(b);this.aa(c);this.ba();this.$();this.ca()}}var Ea=0,N={};function Fa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function O(a){return this.fromWireType(I[a>>2])}var P={},Q={},R={};
function Ga(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ha(a,b){a=Ga(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ia(a){var b=Error,c=Ha(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ja=void 0;
function Ka(a,b,c){function d(h){h=c(h);if(h.length!==a.length)throw new Ja("Mismatched type converter count");for(var k=0;k<a.length;++k)S(a[k],h[k])}a.forEach(function(h){R[h]=b});var e=Array(b.length),f=[],m=0;b.forEach(function(h,k){Q.hasOwnProperty(h)?e[k]=Q[h]:(f.push(h),P.hasOwnProperty(h)||(P[h]=[]),P[h].push(function(){e[k]=Q[h];++m;m===f.length&&d(e)}))});0===f.length&&d(e)}
function La(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ma=void 0;function U(a){for(var b="";C[a];)b+=Ma[C[a++]];return b}var Na=void 0;function V(a){throw new Na(a);}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(Q.hasOwnProperty(a)){if(c.W)return;V("Cannot register type '"+d+"' twice")}Q[a]=b;delete R[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(function(e){e()}))}var Oa=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Pa(a){4<a&&0===--W[a].O&&(W[a]=void 0,Oa.push(a))}function X(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Oa.length?Oa.pop():W.length;W[b]={O:1,value:a};return b}}function Qa(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Ra(a,b){switch(b){case 2:return function(c){return this.fromWireType(sa[c>>2])};case 3:return function(c){return this.fromWireType(ta[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Sa(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ha(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Ta(a,b){var c=g;if(void 0===c[a].K){var d=c[a];c[a]=function(){c[a].K.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].K+")!");return c[a].K[arguments.length].apply(this,arguments)};c[a].K=[];c[a].K[d.R]=d}}
function Ua(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].K&&void 0!==g[a].K[c])&&V("Cannot register public name '"+a+"' twice"),Ta(a,a),g.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].K[c]=b):(g[a]=b,void 0!==c&&(g[a].ja=c))}function Va(a,b){for(var c=[],d=0;d<a;d++)c.push(G[(b>>2)+d]);return c}
function Wa(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=J.get(b).apply(null,c);return d}}function Y(a,b){a=U(a);var c=a.includes("j")?Wa(a,b):J.get(b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var Xa=void 0;function Ya(a){a=Za(a);var b=U(a);Z(a);return b}
function $a(a,b){function c(f){e[f]||Q[f]||(R[f]?R[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Xa(a+": "+d.map(Ya).join([", "]));}function ab(a,b,c){switch(b){case 0:return c?function(d){return H[d]}:function(d){return C[d]};case 1:return c?function(d){return F[d>>1]}:function(d){return D[d>>1]};case 2:return c?function(d){return G[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var bb={};
function cb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function db(a,b){var c=Q[a];void 0===c&&V(b+" has unknown type "+Ya(a));return c}var eb={},fb=[null,[],[]];Ja=g.InternalError=Ia("InternalError");for(var gb=Array(256),hb=0;256>hb;++hb)gb[hb]=String.fromCharCode(hb);Ma=gb;Na=g.BindingError=Ia("BindingError");g.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};
g.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};Xa=g.UnboundTypeError=Ia("UnboundTypeError");
var jb={o:function(a,b,c,d){A("Assertion failed: "+B(a)+", at: "+[b?B(b):"unknown filename",c,d?B(d):"unknown function"])},z:function(a){return ib(a+16)+16},B:function(){},y:function(a,b,c){(new Da(a)).X(b,c);Ea++;throw a;},l:function(a){var b=N[a];delete N[a];var c=b.Y,d=b.Z,e=b.P,f=e.map(function(m){return m.V}).concat(e.map(function(m){return m.fa}));Ka([a],f,function(m){var h={};e.forEach(function(k,l){var n=m[l],q=k.T,x=k.U,y=m[l+e.length],p=k.ea,ca=k.ga;h[k.S]={read:function(z){return n.fromWireType(q(x,
z))},write:function(z,E){var T=[];p(ca,z,y.toWireType(T,E));Fa(T)}}});return[{name:b.name,fromWireType:function(k){var l={},n;for(n in h)l[n]=h[n].read(k);d(k);return l},toWireType:function(k,l){for(var n in h)if(!(n in l))throw new TypeError('Missing field:  "'+n+'"');var q=c();for(n in h)h[n].write(q,l[n]);null!==k&&k.push(d,q);return q},argPackAdvance:8,readValueFromPointer:O,L:d}]})},q:function(){},w:function(a,b,c,d,e){var f=La(c);b=U(b);S(a,{name:b,fromWireType:function(m){return!!m},toWireType:function(m,
h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(m){if(1===c)var h=H;else if(2===c)h=F;else if(4===c)h=G;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[m>>f])},L:null})},v:function(a,b){b=U(b);S(a,{name:b,fromWireType:function(c){var d=W[c].value;Pa(c);return d},toWireType:function(c,d){return X(d)},argPackAdvance:8,readValueFromPointer:O,L:null})},h:function(a,b,c){c=La(c);b=U(b);S(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,
e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Qa(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Ra(b,c),L:null})},k:function(a,b,c,d,e,f){var m=Va(b,c);a=U(a);e=Y(d,e);Ua(a,function(){$a("Cannot call "+a+" due to unbound types",m)},b-1);Ka([],m,function(h){var k=a,l=a;h=[h[0],null].concat(h.slice(1));var n=e,q=h.length;2>q&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==h[1]&&!1,y=
!1,p=1;p<h.length;++p)if(null!==h[p]&&void 0===h[p].L){y=!0;break}var ca="void"!==h[0].name,z="",E="";for(p=0;p<q-2;++p)z+=(0!==p?", ":"")+"arg"+p,E+=(0!==p?", ":"")+"arg"+p+"Wired";l="return function "+Ga(l)+"("+z+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+l+" called with ' + arguments.length + ' arguments, expected "+(q-2)+" args!');\n}\n";y&&(l+="var destructors = [];\n");var T=y?"destructors":"null";z="throwBindingError invoker fn runDestructors retType classParam".split(" ");
n=[V,n,f,Fa,h[0],h[1]];x&&(l+="var thisWired = classParam.toWireType("+T+", this);\n");for(p=0;p<q-2;++p)l+="var arg"+p+"Wired = argType"+p+".toWireType("+T+", arg"+p+"); // "+h[p+2].name+"\n",z.push("argType"+p),n.push(h[p+2]);x&&(E="thisWired"+(0<E.length?", ":"")+E);l+=(ca?"var rv = ":"")+"invoker(fn"+(0<E.length?", ":"")+E+");\n";if(y)l+="runDestructors(destructors);\n";else for(p=x?1:2;p<h.length;++p)q=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==h[p].L&&(l+=q+"_dtor("+q+"); // "+h[p].name+"\n",
z.push(q+"_dtor"),n.push(h[p].L));ca&&(l+="var ret = retType.fromWireType(rv);\nreturn ret;\n");z.push(l+"}\n");h=Sa(z).apply(null,n);p=b-1;if(!g.hasOwnProperty(k))throw new Ja("Replacing nonexistant public symbol");void 0!==g[k].K&&void 0!==p?g[k].K[p]=h:(g[k]=h,g[k].R=p);return[]})},c:function(a,b,c,d,e){function f(l){return l}b=U(b);-1===e&&(e=4294967295);var m=La(c);if(0===d){var h=32-8*c;f=function(l){return l<<h>>>h}}var k=b.includes("unsigned");S(a,{name:b,fromWireType:f,toWireType:function(l,
n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+Qa(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+Qa(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return k?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:ab(b,m,0!==d),L:null})},a:function(a,b,c){function d(f){f>>=2;var m=I;return new e(ra,m[f+1],m[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=U(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{W:!0})},i:function(a,b){b=U(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var e=I[d>>2];if(c)for(var f=d+4,m=0;m<=e;++m){var h=d+4+m;if(m==e||0==C[h]){f=B(f,h-f);if(void 0===k)var k=f;else k+=String.fromCharCode(0),k+=f;f=h+1}}else{k=Array(e);for(m=0;m<e;++m)k[m]=String.fromCharCode(C[d+4+m]);k=k.join("")}Z(d);return k},toWireType:function(d,e){e instanceof ArrayBuffer&&
(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||V("Cannot pass non-string to std::string");var m=(c&&f?function(){for(var l=0,n=0;n<e.length;++n){var q=e.charCodeAt(n);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|e.charCodeAt(++n)&1023);127>=q?++l:l=2047>=q?l+2:65535>=q?l+3:l+4}return l}:function(){return e.length})(),h=ib(4+m+1);I[h>>2]=m;if(c&&f)ja(e,h+4,m+1);else if(f)for(f=0;f<m;++f){var k=e.charCodeAt(f);255<k&&
(Z(h),V("String has UTF-16 code units that do not fit in 8 bits"));C[h+4+f]=k}else for(f=0;f<m;++f)C[h+4+f]=e[f];null!==d&&d.push(Z,h);return h},argPackAdvance:8,readValueFromPointer:O,L:function(d){Z(d)}})},e:function(a,b,c){c=U(c);if(2===b){var d=la;var e=ma;var f=na;var m=function(){return D};var h=1}else 4===b&&(d=oa,e=pa,f=qa,m=function(){return I},h=2);S(a,{name:c,fromWireType:function(k){for(var l=I[k>>2],n=m(),q,x=k+4,y=0;y<=l;++y){var p=k+4+y*b;if(y==l||0==n[p>>h])x=d(x,p-x),void 0===q?q=
x:(q+=String.fromCharCode(0),q+=x),x=p+b}Z(k);return q},toWireType:function(k,l){"string"!==typeof l&&V("Cannot pass non-string to C++ string type "+c);var n=f(l),q=ib(4+n+b);I[q>>2]=n>>h;e(l,q+4,n+b);null!==k&&k.push(Z,q);return q},argPackAdvance:8,readValueFromPointer:O,L:function(k){Z(k)}})},m:function(a,b,c,d,e,f){N[a]={name:U(b),Y:Y(c,d),Z:Y(e,f),P:[]}},b:function(a,b,c,d,e,f,m,h,k,l){N[a].P.push({S:U(b),V:c,T:Y(d,e),U:f,fa:m,ea:Y(h,k),ga:l})},x:function(a,b){b=U(b);S(a,{ia:!0,name:b,argPackAdvance:0,
fromWireType:function(){},toWireType:function(){}})},g:Pa,A:function(a){if(0===a)return X(cb());var b=bb[a];a=void 0===b?U(a):b;return X(cb()[a])},j:function(a){4<a&&(W[a].O+=1)},n:function(a,b,c,d){a||V("Cannot use deleted val. handle = "+a);a=W[a].value;var e=eb[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var m="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)m+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+
f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",m+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(db,g,X);eb[b]=e}return e(a,c,d)},f:function(){A()},s:function(a,b,c){C.copyWithin(a,b,b+c)},d:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,
d);0<d%65536&&(d+=65536-d%65536);a:{try{fa.grow(Math.min(2147483648,d)-ra.byteLength+65535>>>16);ua();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},u:function(){return 0},p:function(){},t:function(a,b,c,d){for(var e=0,f=0;f<c;f++){for(var m=G[b+8*f>>2],h=G[b+(8*f+4)>>2],k=0;k<h;k++){var l=C[m+k],n=fb[a];if(0===l||10===l){for(l=0;n[l]&&!(NaN<=l);)++l;l=ia.decode(n.subarray?n.subarray(0,l):new Uint8Array(n.slice(0,l)));(1===a?ea:v)(l);n.length=0}else n.push(l)}e+=h}G[d>>2]=e;return 0},
r:function(){}};
(function(){function a(e){g.asm=e.exports;fa=g.asm.C;ua();J=g.asm.I;wa.unshift(g.asm.D);K--;g.monitorRunDependencies&&g.monitorRunDependencies(K);0==K&&(null!==za&&(clearInterval(za),za=null),L&&(e=L,L=null,e()))}function b(e){a(e.instance)}function c(e){return Ba().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){v("failed to asynchronously prepare wasm: "+f);A(f)})}var d={a:jb};K++;g.monitorRunDependencies&&g.monitorRunDependencies(K);if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return v("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return w||"function"!==typeof WebAssembly.instantiateStreaming||M.startsWith("data:application/octet-stream;base64,")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){v("wasm streaming compile failed: "+f);v("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.D).apply(null,arguments)};
var Z=g._free=function(){return(Z=g._free=g.asm.E).apply(null,arguments)},ib=g._malloc=function(){return(ib=g._malloc=g.asm.F).apply(null,arguments)},Za=g.___getTypeName=function(){return(Za=g.___getTypeName=g.asm.G).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.H).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.J).apply(null,arguments)};var kb;
L=function lb(){kb||mb();kb||(L=lb)};
function mb(){function a(){if(!kb&&(kb=!0,g.calledRun=!0,!ha)){Ca(wa);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();xa.unshift(b)}Ca(xa)}}if(!(0<K)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ya();Ca(va);0<K||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=mb;
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();mb();


  return Module.ready
}
);
})();
export default Module;