
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


function e(){l.buffer!=n&&t(l.buffer);return aa}function u(){l.buffer!=n&&t(l.buffer);return ca}function v(){l.buffer!=n&&t(l.buffer);return da}function ea(){l.buffer!=n&&t(l.buffer);return fa}function x(){l.buffer!=n&&t(l.buffer);return ha}function y(){l.buffer!=n&&t(l.buffer);return ia}function ja(){l.buffer!=n&&t(l.buffer);return ka}var z;z||(z=typeof Module !== 'undefined' ? Module : {});var la,ma;z.ready=new Promise(function(a,b){la=a;ma=b});var A={},B;
for(B in z)z.hasOwnProperty(B)&&(A[B]=z[B]);function oa(a,b){throw b;}var C=z.ENVIRONMENT_IS_PTHREAD||!1,D="",pa;D=self.location.href;_scriptDir&&(D=_scriptDir);0!==D.indexOf("blob:")?D=D.substr(0,D.lastIndexOf("/")+1):D="";pa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var qa=z.print||console.log.bind(console),H=z.printErr||console.warn.bind(console);for(B in A)A.hasOwnProperty(B)&&(z[B]=A[B]);A=null;
z.quit&&(oa=z.quit);var I;z.wasmBinary&&(I=z.wasmBinary);var noExitRuntime=z.noExitRuntime||!0;"object"!==typeof WebAssembly&&J("no native wasm support detected");var l,ra,sa=!1;
function ta(a,b,c){c=b+c;for(var d="";!(b>=c);){var f=a[b++];if(!f)break;if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function K(a,b){return a?ta(u(),a,b):""}
function ua(a,b,c){var d=u();if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function wa(a,b){for(var c="",d=0;!(d>=b/2);++d){var f=v()[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}function xa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f){var g=a.charCodeAt(f);v()[b>>1]=g;b+=2}v()[b>>1]=0;return b-d}
function ya(a){return 2*a.length}function za(a,b){for(var c=0,d="";!(c>=b/4);){var f=x()[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function Aa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}x()[b>>2]=g;b+=4;if(b+4>c)break}x()[b>>2]=0;return b-d}
function Ba(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var n,aa,ca,da,fa,ha,ia,Ca,ka;C&&(n=z.buffer);function t(a){n=a;z.HEAP8=aa=new Int8Array(a);z.HEAP16=da=new Int16Array(a);z.HEAP32=ha=new Int32Array(a);z.HEAPU8=ca=new Uint8Array(a);z.HEAPU16=fa=new Uint16Array(a);z.HEAPU32=ia=new Uint32Array(a);z.HEAPF32=Ca=new Float32Array(a);z.HEAPF64=ka=new Float64Array(a)}var Da=z.INITIAL_MEMORY||16777216;
if(C)l=z.wasmMemory,n=z.buffer;else if(z.wasmMemory)l=z.wasmMemory;else if(l=new WebAssembly.Memory({initial:Da/65536,maximum:32768,shared:!0}),!(l.buffer instanceof SharedArrayBuffer))throw H("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),Error("bad memory");l&&(n=l.buffer);Da=n.byteLength;t(n);var L,Ea=[],Fa=[],Ga=[];
function Ha(){var a=z.preRun.shift();Ea.unshift(a)}var M=0,Ia=null,O=null;z.preloadedImages={};z.preloadedAudios={};function J(a){if(z.onAbort)z.onAbort(a);C&&console.error("Pthread aborting at "+Error().stack);H(a);sa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ma(a);throw a;}var P=(new URL("wp2_enc_mt_simd.wasm",import.meta.url)).toString();
function Ja(){try{if(P==P&&I)return new Uint8Array(I);if(pa)return pa(P);throw"both async and sync fetching of the wasm failed";}catch(a){J(a)}}function Ka(){return I||"function"!==typeof fetch?Promise.resolve().then(function(){return Ja()}):fetch(P,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+P+"'";return a.arrayBuffer()}).catch(function(){return Ja()})}
var Ma={112528:function(){throw"Canceled!";},112546:function(a,b){setTimeout(function(){La(a,b)},0)}};function Na(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(z);else{var c=b.Ib;"number"===typeof c?void 0===b.Aa?L.get(c)():L.get(c)(b.Aa):c(void 0===b.Aa?null:b.Aa)}}}
function Oa(a,b){if(0>=a||a>e().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(x(),Pa>>2),d=0;if(c==a&&Atomics.compareExchange(x(),Pa>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(x(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}z._emscripten_futex_wake=Oa;
function Qa(a){if(C)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=Q.ua[a];b&&(x()[a+12>>2]=0,Q.Ha(b.worker))}
var Q={sa:[],xa:[],Ma:[],gb:function(){for(var a=navigator.hardwareConcurrency,b=0;b<a;++b)Q.Na()},hb:function(){for(var a=R(228),b=0;57>b;++b)y()[a/4+b]=0;x()[a+12>>2]=a;b=a+152;x()[b>>2]=b;var c=R(512);for(b=0;128>b;++b)y()[c/4+b]=0;Atomics.store(y(),a+100>>2,c);Atomics.store(y(),a+40>>2,a);Ra(a,!1,1);Sa(a)},ib:function(){Q.receiveObjectTransfer=Q.mb;Q.threadInit=Q.Cb;Q.threadCancel=Q.Ab;Q.threadExit=Q.Bb;Q.setExitStatus=Q.pb},ua:{},La:[],nb:function(){for(;0<Q.La.length;)Q.La.pop()();C&&S()&&Ta()},
Ua:function(a,b){Atomics.store(y(),a+56>>2,1);Atomics.store(y(),a+60>>2,0);Q.nb();Atomics.store(y(),a+4>>2,b);Atomics.store(y(),a+0>>2,1);Oa(a+0,2147483647);Ra(0,0,0)},pb:function(){},Bb:function(a){var b=S();b&&(Q.Ua(b,a),C&&postMessage({cmd:"exit"}))},Ab:function(){Q.Ua(S(),-1);postMessage({cmd:"cancelDone"})},zb:function(){for(var a in Q.ua){var b=Q.ua[a];b&&b.worker&&Q.Ha(b.worker)}Q.ua={};for(a=0;a<Q.sa.length;++a){var c=Q.sa[a];c.terminate()}Q.sa=[];for(a=0;a<Q.xa.length;++a)c=Q.xa[a],b=c.ra,
Q.Ja(b),c.terminate();Q.xa=[]},Ja:function(a){if(a){if(a.va){var b=x()[a.va+100>>2];x()[a.va+100>>2]=0;T(b);T(a.va)}a.va=0;a.Ia&&a.ya&&T(a.ya);a.ya=0;a.worker&&(a.worker.ra=null)}},Ha:function(a){Q.ob(function(){delete Q.ua[a.ra.va];Q.sa.push(a);Q.xa.splice(Q.xa.indexOf(a),1);Q.Ja(a.ra);a.ra=void 0})},ob:function(a){x()[Ua>>2]=0;try{a()}finally{x()[Ua>>2]=1}},mb:function(){},Cb:function(){for(var a in Q.Ma)Q.Ma[a]()},Sa:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.ra&&(Q.Wa=a.ra.va);
if(d.targetThread&&d.targetThread!=S()){var g=Q.ua[d.Qb];g?g.worker.postMessage(c.data,d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)Va();else if("spawnThread"===f)Wa(c.data);else if("cleanupThread"===f)Qa(d.thread);else if("killThread"===f){c=d.thread;if(C)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";
x()[c+12>>2]=0;c=Q.ua[c];c.worker.terminate();Q.Ja(c);Q.xa.splice(Q.xa.indexOf(c.worker),1);c.worker.ra=void 0}else if("cancelThread"===f){c=d.thread;if(C)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";Q.ua[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===f)a.loaded=!0,b&&b(a),a.Ca&&(a.Ca(),delete a.Ca);else if("print"===f)qa("Thread "+d.threadId+": "+d.text);else if("printErr"===f)H("Thread "+
d.threadId+": "+d.text);else if("alert"===f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.ra&&Atomics.load(y(),a.ra.va+64>>2)&&Q.Ha(a);else if("exitProcess"===f)try{g=d.returnCode;if(C)throw postMessage({cmd:"exitProcess",returnCode:g}),new Xa(g);if(!Ya()){Q.zb();if(z.onExit)z.onExit(g);sa=!0}oa(g,new Xa(g))}catch(k){if(k instanceof Xa)return;throw k;}else"cancelDone"===f?Q.Ha(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):H("worker sent an unknown command "+
f));Q.Wa=void 0};a.onerror=function(c){H("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};a.postMessage({cmd:"load",urlOrBlob:z.mainScriptUrlOrBlob,wasmMemory:l,wasmModule:ra})},Na:function(){if(z.locateFile){var a=z.locateFile?z.locateFile("wp2_enc_mt_simd.worker.js",D):D+"wp2_enc_mt_simd.worker.js";Q.sa.push(new Worker(a))}else Q.sa.push(new Worker(new URL("wp2_enc_mt_simd.worker.js",import.meta.url)))},Za:function(){0==Q.sa.length&&(Q.Na(),Q.Sa(Q.sa[0]));return Q.sa.pop()},
Eb:function(a){for(a=performance.now()+a;performance.now()<a;);}};z.establishStackSpace=function(a,b){Za(a,b);$a(a)};z.invokeEntryPoint=function(a,b){return L.get(a)(b)};var ab=0;function Ya(){return noExitRuntime||0<ab}z.keepRuntimeAlive=Ya;var bb;bb=C?function(){return performance.now()-z.__performance_now_clock_drift}:function(){return performance.now()};function cb(a,b){Q.La.push(function(){L.get(a)(b)})}
function db(a){this.Ba=a-16;this.ub=function(b){x()[this.Ba+8>>2]=b};this.rb=function(b){x()[this.Ba+0>>2]=b};this.sb=function(){x()[this.Ba+4>>2]=0};this.qb=function(){var b=0;e()[this.Ba+12>>0]=b};this.tb=function(){var b=0;e()[this.Ba+13>>0]=b};this.eb=function(b,c){this.ub(b);this.rb(c);this.sb();this.qb();this.tb()}}var eb=0,fb={};function gb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function hb(a){return this.fromWireType(y()[a>>2])}var U={},V={},ib={};
function jb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function kb(a,b){a=jb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function lb(a){var b=Error,c=kb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var mb=void 0;
function nb(a,b,c){function d(h){h=c(h);if(h.length!==a.length)throw new mb("Mismatched type converter count");for(var m=0;m<a.length;++m)W(a[m],h[m])}a.forEach(function(h){ib[h]=b});var f=Array(b.length),g=[],k=0;b.forEach(function(h,m){V.hasOwnProperty(h)?f[m]=V[h]:(g.push(h),U.hasOwnProperty(h)||(U[h]=[]),U[h].push(function(){f[m]=V[h];++k;k===g.length&&d(f)}))});0===g.length&&d(f)}
function ob(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var pb=void 0;function X(a){for(var b="";u()[a];)b+=pb[u()[a++]];return b}var qb=void 0;function Y(a){throw new qb(a);}
function W(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Y('type "'+d+'" must have a positive integer typeid pointer');if(V.hasOwnProperty(a)){if(c.cb)return;Y("Cannot register type '"+d+"' twice")}V[a]=b;delete ib[a];U.hasOwnProperty(a)&&(b=U[a],delete U[a],b.forEach(function(f){f()}))}var rb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function sb(a){4<a&&0===--Z[a].Ka&&(Z[a]=void 0,rb.push(a))}function tb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=rb.length?rb.pop():Z.length;Z[b]={Ka:1,value:a};return b}}function ub(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function vb(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;l.buffer!=n&&t(l.buffer);return d.call(this,Ca[c>>2])};case 3:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function wb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=kb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function xb(a,b){var c=z;if(void 0===c[a].ta){var d=c[a];c[a]=function(){c[a].ta.hasOwnProperty(arguments.length)||Y("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].ta+")!");return c[a].ta[arguments.length].apply(this,arguments)};c[a].ta=[];c[a].ta[d.Va]=d}}
function yb(a,b,c){z.hasOwnProperty(a)?((void 0===c||void 0!==z[a].ta&&void 0!==z[a].ta[c])&&Y("Cannot register public name '"+a+"' twice"),xb(a,a),z.hasOwnProperty(c)&&Y("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),z[a].ta[c]=b):(z[a]=b,void 0!==c&&(z[a].Nb=c))}function zb(a,b){for(var c=[],d=0;d<a;d++)c.push(x()[(b>>2)+d]);return c}
function Ab(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=z["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=L.get(b).apply(null,c);return d}}function Bb(a,b){a=X(a);var c=a.includes("j")?Ab(a,b):L.get(b);"function"!==typeof c&&Y("unknown function pointer with signature "+a+": "+b);return c}var Cb=void 0;function Db(a){a=Eb(a);var b=X(a);T(a);return b}
function Fb(a,b){function c(g){f[g]||V[g]||(ib[g]?ib[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Cb(a+": "+d.map(Db).join([", "]));}function Gb(a,b,c){switch(b){case 0:return c?function(d){return e()[d]}:function(d){return u()[d]};case 1:return c?function(d){return v()[d>>1]}:function(d){return ea()[d>>1]};case 2:return c?function(d){return x()[d>>2]}:function(d){return y()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Hb={};
function Ib(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Jb(a,b){var c=V[a];void 0===c&&Y(b+" has unknown type "+Db(a));return c}var Kb={},Lb=[];function Mb(a,b,c){if(0>=a||a>e().length||a&1)return-28;a=Atomics.wait(x(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+a;}
function Nb(a,b){for(var c=arguments.length-2,d=Ob(),f=Pb(8*c),g=f>>3,k=0;k<c;k++){var h=arguments[2+k];ja()[g+k]=h}c=Qb(a,c,f,b);$a(d);return c}var Rb=[],Sb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Tb(a){a=2<a?K(a):a;return Sb[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Ub(a,b,c){var d=Tb(a);if(!d)return-4;d.Fa&&(x()[d.Fa>>2]=b,x()[d.Fa+4>>2]=c);if(d.Ta||!d.Gb)d.Ta&&(d=d.Ta),a=!1,d.Ea&&d.Ea.Da&&(a=d.Ea.Da.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Ea.Da.viewport(0,0,b,c);else{if(d.Fa){d=x()[d.Fa+8>>2];a=a?K(a):"";var f=Ob(),g=Pb(12),k=0;if(a){k=va(a)+1;var h=R(k);ua(a,h,k);k=h}x()[g>>2]=k;x()[g+4>>2]=b;x()[g+8>>2]=c;Vb(0,d,657457152,0,k,g);$a(f);return 1}return-4}return 0}
function Wb(a,b,c){return C?Nb(1,1,a,b,c):Ub(a,b,c)}function Xb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,k){b.drawElementsInstancedANGLE(c,d,f,g,k)})}
function Yb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Zb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function $b(a,b){a.Ra||(a.Ra=a.getContext,a.getContext=function(d,f){f=a.Ra(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?ac(c,b):0}function ac(a,b){var c=R(8);x()[c+4>>2]=S();var d={Jb:c,attributes:b,version:b.jb,Da:a};a.canvas&&(a.canvas.Ea=d);("undefined"===typeof b.Pa||b.Pa)&&bc(d);return c}
function bc(a){a||(a=cc);if(!a.fb){a.fb=!0;var b=a.Da;Xb(b);Yb(b);Zb(b);b.Hb=b.getExtension("EXT_disjoint_timer_query");b.Mb=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var cc,dc=["default","low-power","high-performance"],ec=[null,[],[]];function fc(a){return C?Nb(2,1,a):0}function gc(a,b,c,d,f){if(C)return Nb(3,1,a,b,c,d,f)}
function hc(a,b,c,d){if(C)return Nb(4,1,a,b,c,d);for(var f=0,g=0;g<c;g++){for(var k=x()[b+8*g>>2],h=x()[b+(8*g+4)>>2],m=0;m<h;m++){var p=u()[k+m],r=ec[a];0===p||10===p?((1===a?qa:H)(ta(r,0)),r.length=0):r.push(p)}f+=h}x()[d>>2]=f;return 0}
function Wa(a){if(C)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=Q.Za();if(!b)return 6;if(void 0!==b.ra)throw"Internal error!";if(!a.Ga)throw"Internal error, no pthread ptr!";Q.xa.push(b);for(var c=R(512),d=0;128>d;++d)x()[c+4*d>>2]=0;var f=a.ya+a.za;d=Q.ua[a.Ga]={worker:b,ya:a.ya,za:a.za,Ia:a.Ia,va:a.Ga};var g=d.va>>2;Atomics.store(y(),g+16,a.Oa);Atomics.store(y(),g+25,c);Atomics.store(y(),g+10,d.va);Atomics.store(y(),g+20,a.za);Atomics.store(y(),
g+19,f);Atomics.store(y(),g+26,a.za);Atomics.store(y(),g+28,f);Atomics.store(y(),g+29,a.Oa);c=ic()+40;Atomics.store(y(),g+43,c);b.ra=d;var k={cmd:"run",start_routine:a.yb,arg:a.Aa,threadInfoStruct:a.Ga,stackBase:a.ya,stackSize:a.za};b.Ca=function(){k.time=performance.now();b.postMessage(k,a.Db)};b.loaded&&(b.Ca(),delete b.Ca);return 0}
function jc(a,b){if(!a)return H("pthread_join attempted on a null thread pointer!"),71;if(C&&S()==a)return H("PThread "+a+" is attempting to join to itself!"),16;if(!C&&kc()==a)return H("Main thread "+a+" is attempting to join to itself!"),16;if(x()[a+12>>2]!==a)return H("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(y(),a+64>>2))return H("Attempted to join thread "+a+", which was already detached!"),28;for(;;){var c=
Atomics.load(y(),a+0>>2);if(1==c)return c=Atomics.load(y(),a+4>>2),b&&(x()[b>>2]=c),Atomics.store(y(),a+64>>2,1),C?postMessage({cmd:"cleanupThread",thread:a}):Qa(a),0;if(C){var d=S();if(d&&!Atomics.load(y(),d+56>>2)&&2==Atomics.load(y(),d+0>>2))throw"Canceled!";}C||Va();Mb(a+0,c,C?100:1)}}C||Q.gb();mb=z.InternalError=lb("InternalError");for(var lc=Array(256),mc=0;256>mc;++mc)lc[mc]=String.fromCharCode(mc);pb=lc;qb=z.BindingError=lb("BindingError");
z.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};z.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};Cb=z.UnboundTypeError=lb("UnboundTypeError");
var nc=[null,Wb,fc,gc,hc],qc={d:function(a,b,c,d){J("Assertion failed: "+K(a)+", at: "+[b?K(b):"unknown filename",c,d?K(d):"unknown function"])},O:function(a){return R(a+16)+16},s:function(a,b){return cb(a,b)},N:function(a,b,c){(new db(a)).eb(b,c);eb++;throw a;},u:function(a){var b=fb[a];delete fb[a];var c=b.kb,d=b.lb,f=b.Qa,g=f.map(function(k){return k.bb}).concat(f.map(function(k){return k.wb}));nb([a],g,function(k){var h={};f.forEach(function(m,p){var r=k[p],w=m.$a,E=m.ab,F=k[p+f.length],q=m.vb,
na=m.xb;h[m.Ya]={read:function(G){return r.fromWireType(w(E,G))},write:function(G,N){var ba=[];q(na,G,F.toWireType(ba,N));gb(ba)}}});return[{name:b.name,fromWireType:function(m){var p={},r;for(r in h)p[r]=h[r].read(m);d(m);return p},toWireType:function(m,p){for(var r in h)if(!(r in p))throw new TypeError('Missing field:  "'+r+'"');var w=c();for(r in h)h[r].write(w,p[r]);null!==m&&m.push(d,w);return w},argPackAdvance:8,readValueFromPointer:hb,wa:d}]})},y:function(){},L:function(a,b,c,d,f){var g=ob(c);
b=X(b);W(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:f},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=e();else if(2===c)h=v();else if(4===c)h=x();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[k>>g])},wa:null})},K:function(a,b){b=X(b);W(a,{name:b,fromWireType:function(c){var d=Z[c].value;sb(c);return d},toWireType:function(c,d){return tb(d)},argPackAdvance:8,readValueFromPointer:hb,wa:null})},p:function(a,
b,c){c=ob(c);b=X(b);W(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+ub(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:vb(b,c),wa:null})},t:function(a,b,c,d,f,g){var k=zb(b,c);a=X(a);f=Bb(d,f);yb(a,function(){Fb("Cannot call "+a+" due to unbound types",k)},b-1);nb([],k,function(h){var m=a,p=a;h=[h[0],null].concat(h.slice(1));var r=f,w=h.length;2>w&&Y("argTypes array size mismatch! Must at least get return value and 'this' types!");
for(var E=null!==h[1]&&!1,F=!1,q=1;q<h.length;++q)if(null!==h[q]&&void 0===h[q].wa){F=!0;break}var na="void"!==h[0].name,G="",N="";for(q=0;q<w-2;++q)G+=(0!==q?", ":"")+"arg"+q,N+=(0!==q?", ":"")+"arg"+q+"Wired";p="return function "+jb(p)+"("+G+") {\nif (arguments.length !== "+(w-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+(w-2)+" args!');\n}\n";F&&(p+="var destructors = [];\n");var ba=F?"destructors":"null";G="throwBindingError invoker fn runDestructors retType classParam".split(" ");
r=[Y,r,g,gb,h[0],h[1]];E&&(p+="var thisWired = classParam.toWireType("+ba+", this);\n");for(q=0;q<w-2;++q)p+="var arg"+q+"Wired = argType"+q+".toWireType("+ba+", arg"+q+"); // "+h[q+2].name+"\n",G.push("argType"+q),r.push(h[q+2]);E&&(N="thisWired"+(0<N.length?", ":"")+N);p+=(na?"var rv = ":"")+"invoker(fn"+(0<N.length?", ":"")+N+");\n";if(F)p+="runDestructors(destructors);\n";else for(q=E?1:2;q<h.length;++q)w=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==h[q].wa&&(p+=w+"_dtor("+w+"); // "+h[q].name+
"\n",G.push(w+"_dtor"),r.push(h[q].wa));na&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");G.push(p+"}\n");h=wb(G).apply(null,r);q=b-1;if(!z.hasOwnProperty(m))throw new mb("Replacing nonexistant public symbol");void 0!==z[m].ta&&void 0!==q?z[m].ta[q]=h:(z[m]=h,z[m].Va=q);return[]})},e:function(a,b,c,d,f){function g(p){return p}b=X(b);-1===f&&(f=4294967295);var k=ob(c);if(0===d){var h=32-8*c;g=function(p){return p<<h>>>h}}var m=b.includes("unsigned");W(a,{name:b,fromWireType:g,toWireType:function(p,
r){if("number"!==typeof r&&"boolean"!==typeof r)throw new TypeError('Cannot convert "'+ub(r)+'" to '+this.name);if(r<d||r>f)throw new TypeError('Passing a number "'+ub(r)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return m?r>>>0:r|0},argPackAdvance:8,readValueFromPointer:Gb(b,k,0!==d),wa:null})},b:function(a,b,c){function d(g){g>>=2;var k=y();return new f(n,k[g+1],k[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=X(c);W(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{cb:!0})},q:function(a,b){b=X(b);var c="std::string"===b;W(a,{name:b,fromWireType:function(d){var f=y()[d>>2];if(c)for(var g=d+4,k=0;k<=f;++k){var h=d+4+k;if(k==f||0==u()[h]){g=K(g,h-g);if(void 0===m)var m=g;else m+=String.fromCharCode(0),m+=g;g=h+1}}else{m=Array(f);for(k=0;k<f;++k)m[k]=String.fromCharCode(u()[d+4+k]);m=m.join("")}T(d);return m},toWireType:function(d,f){f instanceof
ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||Y("Cannot pass non-string to std::string");var k=(c&&g?function(){return va(f)}:function(){return f.length})(),h=R(4+k+1);y()[h>>2]=k;if(c&&g)ua(f,h+4,k+1);else if(g)for(g=0;g<k;++g){var m=f.charCodeAt(g);255<m&&(T(h),Y("String has UTF-16 code units that do not fit in 8 bits"));u()[h+4+g]=m}else for(g=0;g<k;++g)u()[h+4+g]=f[g];null!==d&&d.push(T,h);return h},
argPackAdvance:8,readValueFromPointer:hb,wa:function(d){T(d)}})},j:function(a,b,c){c=X(c);if(2===b){var d=wa;var f=xa;var g=ya;var k=function(){return ea()};var h=1}else 4===b&&(d=za,f=Aa,g=Ba,k=function(){return y()},h=2);W(a,{name:c,fromWireType:function(m){for(var p=y()[m>>2],r=k(),w,E=m+4,F=0;F<=p;++F){var q=m+4+F*b;if(F==p||0==r[q>>h])E=d(E,q-E),void 0===w?w=E:(w+=String.fromCharCode(0),w+=E),E=q+b}T(m);return w},toWireType:function(m,p){"string"!==typeof p&&Y("Cannot pass non-string to C++ string type "+
c);var r=g(p),w=R(4+r+b);y()[w>>2]=r>>h;f(p,w+4,r+b);null!==m&&m.push(T,w);return w},argPackAdvance:8,readValueFromPointer:hb,wa:function(m){T(m)}})},v:function(a,b,c,d,f,g){fb[a]={name:X(b),kb:Bb(c,d),lb:Bb(f,g),Qa:[]}},c:function(a,b,c,d,f,g,k,h,m,p){fb[a].Qa.push({Ya:X(b),bb:c,$a:Bb(d,f),ab:g,wb:k,vb:Bb(h,m),xb:p})},M:function(a,b){b=X(b);W(a,{Kb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},G:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});
else if(C)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=Q.ua[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},m:sb,J:function(a){if(0===a)return tb(Ib());var b=Hb[a];a=void 0===b?X(a):b;return tb(Ib()[a])},Q:function(a){4<a&&(Z[a].Ka+=1)},w:function(a,b,c,d){a||Y("Cannot use deleted val. handle = "+a);a=Z[a].value;var f=Kb[b];if(!f){f="";for(var g=0;g<b;++g)f+=(0!==g?", ":"")+"arg"+g;var k="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";
for(g=0;g<b;++g)k+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";f=(new Function("requireRegisteredType","Module","__emval_register",k+("var obj = new constructor("+f+");\nreturn __emval_register(obj);\n}\n")))(Jb,z,tb);Kb[b]=f}return f(a,c,d)},k:function(){J()},o:function(a,b,c){Lb.length=0;var d;for(c>>=2;d=u()[b++];)(d=105>d)&&c&1&&c++,
Lb.push(d?ja()[c++>>1]:x()[c]),++c;return Ma[a].apply(null,Lb)},C:function(){},n:function(){},f:Mb,g:Oa,h:bb,A:function(a,b,c){u().copyWithin(a,b,b+c)},R:function(){return navigator.hardwareConcurrency},D:function(a,b,c){Rb.length=b;c>>=3;for(var d=0;d<b;d++)Rb[d]=ja()[c+d];return(0>a?Ma[-a-1]:nc[a]).apply(null,Rb)},B:function(a){var b=u().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{l.grow(Math.min(2147483648,
d)-n.byteLength+65535>>>16);t(l.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},E:function(a,b,c){return Tb(a)?Ub(a,b,c):Wb(a,b,c)},l:function(){},F:function(a,b){b>>=2;var c=x()[b+6];b={alpha:!!x()[b],depth:!!x()[b+1],stencil:!!x()[b+2],antialias:!!x()[b+3],premultipliedAlpha:!!x()[b+4],preserveDrawingBuffer:!!x()[b+5],powerPreference:dc[c],failIfMajorPerformanceCaveat:!!x()[b+7],jb:x()[b+8],Lb:x()[b+9],Pa:x()[b+10],Xa:x()[b+11],Ob:x()[b+12],Pb:x()[b+13]};a=Tb(a);return!a||b.Xa?
0:$b(a,b)},I:fc,x:gc,H:hc,z:function(){Q.hb()},a:l||z.wasmMemory,r:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return H("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return H("pthread_create called with a null thread pointer!"),28;var f=[];if(C&&0===f.length)return oc(687865856,a,b,c,d);var g=0,k=0;if(b&&-1!=b){var h=x()[b>>2];h+=81920;g=x()[b+8>>2];k=0!==x()[b+12>>2]}else h=2097152;(b=0==g)?g=pc(16,h):(g-=h,0<g||J("Assertion failed: undefined"));
for(var m=R(228),p=0;57>p;++p)y()[(m>>2)+p]=0;x()[a>>2]=m;x()[m+12>>2]=m;a=m+152;x()[a>>2]=a;c={ya:g,za:h,Ia:b,Oa:k,yb:c,Ga:m,Aa:d,Db:f};return C?(c.Fb="spawnThread",postMessage(c,f),0):Wa(c)},P:function(a,b){return jc(a,b)},i:function(){}};
(function(){function a(f,g){z.asm=f.exports;L=z.asm.W;Fa.unshift(z.asm.S);Q.Ma.push(z.asm.V);ra=g;if(!C){var k=Q.sa.length;Q.sa.forEach(function(h){Q.Sa(h,function(){if(!--k&&(M--,z.monitorRunDependencies&&z.monitorRunDependencies(M),0==M&&(null!==Ia&&(clearInterval(Ia),Ia=null),O))){var m=O;O=null;m()}})})}}function b(f){a(f.instance,f.module)}function c(f){return Ka().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){H("failed to asynchronously prepare wasm: "+g);J(g)})}
var d={a:qc};C||(!C||J("Assertion failed: addRunDependency cannot be used in a pthread worker"),M++,z.monitorRunDependencies&&z.monitorRunDependencies(M));if(z.instantiateWasm)try{return z.instantiateWasm(d,a)}catch(f){return H("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return I||"function"!==typeof WebAssembly.instantiateStreaming||P.startsWith("data:application/octet-stream;base64,")||"function"!==typeof fetch?c(b):fetch(P,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
d).then(b,function(g){H("wasm streaming compile failed: "+g);H("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ma);return{}})();z.___wasm_call_ctors=function(){return(z.___wasm_call_ctors=z.asm.S).apply(null,arguments)};var T=z._free=function(){return(T=z._free=z.asm.T).apply(null,arguments)},R=z._malloc=function(){return(R=z._malloc=z.asm.U).apply(null,arguments)};z._emscripten_tls_init=function(){return(z._emscripten_tls_init=z.asm.V).apply(null,arguments)};
var Eb=z.___getTypeName=function(){return(Eb=z.___getTypeName=z.asm.X).apply(null,arguments)};z.___embind_register_native_and_builtin_types=function(){return(z.___embind_register_native_and_builtin_types=z.asm.Y).apply(null,arguments)};z._emscripten_current_thread_process_queued_calls=function(){return(z._emscripten_current_thread_process_queued_calls=z.asm.Z).apply(null,arguments)};
var Sa=z._emscripten_register_main_browser_thread_id=function(){return(Sa=z._emscripten_register_main_browser_thread_id=z.asm._).apply(null,arguments)},kc=z._emscripten_main_browser_thread_id=function(){return(kc=z._emscripten_main_browser_thread_id=z.asm.$).apply(null,arguments)},La=z.__emscripten_do_dispatch_to_thread=function(){return(La=z.__emscripten_do_dispatch_to_thread=z.asm.aa).apply(null,arguments)},oc=z._emscripten_sync_run_in_main_thread_4=function(){return(oc=z._emscripten_sync_run_in_main_thread_4=
z.asm.ba).apply(null,arguments)},Va=z._emscripten_main_thread_process_queued_calls=function(){return(Va=z._emscripten_main_thread_process_queued_calls=z.asm.ca).apply(null,arguments)},Qb=z._emscripten_run_in_main_runtime_thread_js=function(){return(Qb=z._emscripten_run_in_main_runtime_thread_js=z.asm.da).apply(null,arguments)},Vb=z.__emscripten_call_on_thread=function(){return(Vb=z.__emscripten_call_on_thread=z.asm.ea).apply(null,arguments)},Ra=z.__emscripten_thread_init=function(){return(Ra=z.__emscripten_thread_init=
z.asm.fa).apply(null,arguments)},ic=z._emscripten_get_global_libc=function(){return(ic=z._emscripten_get_global_libc=z.asm.ga).apply(null,arguments)},S=z._pthread_self=function(){return(S=z._pthread_self=z.asm.ha).apply(null,arguments)},Ta=z.___pthread_tsd_run_dtors=function(){return(Ta=z.___pthread_tsd_run_dtors=z.asm.ia).apply(null,arguments)},Ob=z.stackSave=function(){return(Ob=z.stackSave=z.asm.ja).apply(null,arguments)},$a=z.stackRestore=function(){return($a=z.stackRestore=z.asm.ka).apply(null,
arguments)},Pb=z.stackAlloc=function(){return(Pb=z.stackAlloc=z.asm.la).apply(null,arguments)},Za=z._emscripten_stack_set_limits=function(){return(Za=z._emscripten_stack_set_limits=z.asm.ma).apply(null,arguments)},pc=z._memalign=function(){return(pc=z._memalign=z.asm.na).apply(null,arguments)};z.dynCall_jiii=function(){return(z.dynCall_jiii=z.asm.oa).apply(null,arguments)};z.dynCall_jiiiiii=function(){return(z.dynCall_jiiiiii=z.asm.pa).apply(null,arguments)};
z.dynCall_jiji=function(){return(z.dynCall_jiji=z.asm.qa).apply(null,arguments)};var Ua=z.__emscripten_allow_main_runtime_queued_calls=112520,Pa=z.__emscripten_main_thread_futex=123420;z.PThread=Q;z.PThread=Q;z.wasmMemory=l;z.ExitStatus=Xa;var rc;function Xa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}O=function sc(){rc||tc();rc||(O=sc)};
function tc(){function a(){if(!rc&&(rc=!0,z.calledRun=!0,!sa)){C||Na(Fa);la(z);if(z.onRuntimeInitialized)z.onRuntimeInitialized();if(!C){if(z.postRun)for("function"==typeof z.postRun&&(z.postRun=[z.postRun]);z.postRun.length;){var b=z.postRun.shift();Ga.unshift(b)}Na(Ga)}}}if(!(0<M))if(C)la(z),C||Na(Fa),postMessage({cmd:"loaded"});else{if(!C){if(z.preRun)for("function"==typeof z.preRun&&(z.preRun=[z.preRun]);z.preRun.length;)Ha();Na(Ea)}0<M||(z.setStatus?(z.setStatus("Running..."),setTimeout(function(){setTimeout(function(){z.setStatus("")},
1);a()},1)):a())}}z.run=tc;if(z.preInit)for("function"==typeof z.preInit&&(z.preInit=[z.preInit]);0<z.preInit.length;)z.preInit.pop()();C&&(noExitRuntime=!1,Q.ib());tc();


  return Module.ready
}
);
})();
export default Module;