
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa,ca;f.ready=new Promise(function(a,b){aa=a;ca=b});var r={},t;for(t in f)f.hasOwnProperty(t)&&(r[t]=f[t]);var da,ea,fa,ha;da=function(a){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,null)};ea=function(a){a=da(a);a.buffer||(a=new Uint8Array(a));a.buffer||u("Assertion failed: undefined");return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);
process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",u);f.inspect=function(){return"[Emscripten Module object]"};var ia=f.print||console.log.bind(console),v=f.printErr||console.warn.bind(console);for(t in r)r.hasOwnProperty(t)&&(f[t]=r[t]);r=null;var w;f.wasmBinary&&(w=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&u("no native wasm support detected");var ja,ka=!1,la=new TextDecoder("utf8");
function A(a,b){if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&B[c];)++c;return la.decode(B.subarray(a,c))}
function ma(a,b,c){var d=B;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var na=new TextDecoder("utf-16le");
function oa(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&C[c];)++c;return na.decode(B.subarray(a,c<<1))}function pa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function qa(a){return 2*a.length}function ra(a,b){for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function sa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}F[b>>2]=g;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function ta(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ua,G,B,D,C,F,H,va,wa;
function xa(){var a=ja.buffer;ua=a;f.HEAP8=G=new Int8Array(a);f.HEAP16=D=new Int16Array(a);f.HEAP32=F=new Int32Array(a);f.HEAPU8=B=new Uint8Array(a);f.HEAPU16=C=new Uint16Array(a);f.HEAPU32=H=new Uint32Array(a);f.HEAPF32=va=new Float32Array(a);f.HEAPF64=wa=new Float64Array(a)}var I,ya=[],za=[],Aa=[];function Ba(){var a=f.preRun.shift();ya.unshift(a)}var J=0,Ca=null,K=null;f.preloadedImages={};f.preloadedAudios={};
function u(a){if(f.onAbort)f.onAbort(a);v(a);ka=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ca(a);throw a;}var L=(new URL("wp2_node_enc.wasm",import.meta.url)).toString();function Da(){return Promise.resolve().then(function(){a:{try{if(L==L&&w){var a=new Uint8Array(w);break a}if(ea){a=ea(L);break a}throw"both async and sync fetching of the wasm failed";}catch(b){u(b)}a=void 0}return a})}
function Ea(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.ia;"number"===typeof c?void 0===b.N?I.get(c)():I.get(c)(b.N):c(void 0===b.N?null:b.N)}}}function Fa(a){this.M=a-16;this.ea=function(b){F[this.M+8>>2]=b};this.aa=function(b){F[this.M+0>>2]=b};this.ba=function(){F[this.M+4>>2]=0};this.$=function(){G[this.M+12>>0]=0};this.da=function(){G[this.M+13>>0]=0};this.X=function(b,c){this.ea(b);this.aa(c);this.ba();this.$();this.da()}}var Ga=0,M={};
function Ha(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function N(a){return this.fromWireType(H[a>>2])}var O={},P={},Q={};function Ia(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ja(a,b){a=Ia(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ka(a){var b=Error,c=Ja(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var La=void 0;
function Ma(a,b,c){function d(k){k=c(k);if(k.length!==a.length)throw new La("Mismatched type converter count");for(var h=0;h<a.length;++h)S(a[h],k[h])}a.forEach(function(k){Q[k]=b});var e=Array(b.length),g=[],l=0;b.forEach(function(k,h){P.hasOwnProperty(k)?e[h]=P[k]:(g.push(k),O.hasOwnProperty(k)||(O[k]=[]),O[k].push(function(){e[h]=P[k];++l;l===g.length&&d(e)}))});0===g.length&&d(e)}
function Na(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Oa=void 0;function T(a){for(var b="";B[a];)b+=Oa[B[a++]];return b}var Pa=void 0;function U(a){throw new Pa(a);}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||U('type "'+d+'" must have a positive integer typeid pointer');if(P.hasOwnProperty(a)){if(c.W)return;U("Cannot register type '"+d+"' twice")}P[a]=b;delete Q[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(function(e){e()}))}var Qa=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Ra(a){4<a&&0===--V[a].O&&(V[a]=void 0,Qa.push(a))}function W(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Qa.length?Qa.pop():V.length;V[b]={O:1,value:a};return b}}function Sa(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Ta(a,b){switch(b){case 2:return function(c){return this.fromWireType(va[c>>2])};case 3:return function(c){return this.fromWireType(wa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Ua(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ja(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Va(a,b){var c=f;if(void 0===c[a].K){var d=c[a];c[a]=function(){c[a].K.hasOwnProperty(arguments.length)||U("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].K+")!");return c[a].K[arguments.length].apply(this,arguments)};c[a].K=[];c[a].K[d.R]=d}}
function Wa(a,b,c){f.hasOwnProperty(a)?((void 0===c||void 0!==f[a].K&&void 0!==f[a].K[c])&&U("Cannot register public name '"+a+"' twice"),Va(a,a),f.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),f[a].K[c]=b):(f[a]=b,void 0!==c&&(f[a].ka=c))}function Xa(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function Ya(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=f["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=I.get(b).apply(null,c);return d}}function X(a,b){a=T(a);var c=a.includes("j")?Ya(a,b):I.get(b);"function"!==typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var Za=void 0;function $a(a){a=ab(a);var b=T(a);Y(a);return b}
function bb(a,b){function c(g){e[g]||P[g]||(Q[g]?Q[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Za(a+": "+d.map($a).join([", "]));}function cb(a,b,c){switch(b){case 0:return c?function(d){return G[d]}:function(d){return B[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return C[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return H[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var db={};
function eb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function fb(a,b){var c=P[a];void 0===c&&U(b+" has unknown type "+$a(a));return c}var gb={},hb=[null,[],[]];La=f.InternalError=Ka("InternalError");for(var ib=Array(256),Z=0;256>Z;++Z)ib[Z]=String.fromCharCode(Z);Oa=ib;Pa=f.BindingError=Ka("BindingError");f.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};
f.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};Za=f.UnboundTypeError=Ka("UnboundTypeError");
var kb={o:function(a,b,c,d){u("Assertion failed: "+A(a)+", at: "+[b?A(b):"unknown filename",c,d?A(d):"unknown function"])},z:function(a){return jb(a+16)+16},B:function(){},y:function(a,b,c){(new Fa(a)).X(b,c);Ga++;throw a;},l:function(a){var b=M[a];delete M[a];var c=b.Y,d=b.Z,e=b.P,g=e.map(function(l){return l.V}).concat(e.map(function(l){return l.ga}));Ma([a],g,function(l){var k={};e.forEach(function(h,m){var n=l[m],p=h.T,x=h.U,y=l[m+e.length],q=h.fa,ba=h.ha;k[h.S]={read:function(z){return n.fromWireType(p(x,
z))},write:function(z,E){var R=[];q(ba,z,y.toWireType(R,E));Ha(R)}}});return[{name:b.name,fromWireType:function(h){var m={},n;for(n in k)m[n]=k[n].read(h);d(h);return m},toWireType:function(h,m){for(var n in k)if(!(n in m))throw new TypeError('Missing field:  "'+n+'"');var p=c();for(n in k)k[n].write(p,m[n]);null!==h&&h.push(d,p);return p},argPackAdvance:8,readValueFromPointer:N,L:d}]})},q:function(){},w:function(a,b,c,d,e){var g=Na(c);b=T(b);S(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,
k){return k?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=G;else if(2===c)k=D;else if(4===c)k=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>g])},L:null})},v:function(a,b){b=T(b);S(a,{name:b,fromWireType:function(c){var d=V[c].value;Ra(c);return d},toWireType:function(c,d){return W(d)},argPackAdvance:8,readValueFromPointer:N,L:null})},h:function(a,b,c){c=Na(c);b=T(b);S(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,
e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Sa(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Ta(b,c),L:null})},k:function(a,b,c,d,e,g){var l=Xa(b,c);a=T(a);e=X(d,e);Wa(a,function(){bb("Cannot call "+a+" due to unbound types",l)},b-1);Ma([],l,function(k){var h=[k[0],null].concat(k.slice(1)),m=k=a,n=e,p=h.length;2>p&&U("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==h[1]&&!1,y=!1,q=
1;q<h.length;++q)if(null!==h[q]&&void 0===h[q].L){y=!0;break}var ba="void"!==h[0].name,z="",E="";for(q=0;q<p-2;++q)z+=(0!==q?", ":"")+"arg"+q,E+=(0!==q?", ":"")+"arg"+q+"Wired";m="return function "+Ia(m)+"("+z+") {\nif (arguments.length !== "+(p-2)+") {\nthrowBindingError('function "+m+" called with ' + arguments.length + ' arguments, expected "+(p-2)+" args!');\n}\n";y&&(m+="var destructors = [];\n");var R=y?"destructors":"null";z="throwBindingError invoker fn runDestructors retType classParam".split(" ");
n=[U,n,g,Ha,h[0],h[1]];x&&(m+="var thisWired = classParam.toWireType("+R+", this);\n");for(q=0;q<p-2;++q)m+="var arg"+q+"Wired = argType"+q+".toWireType("+R+", arg"+q+"); // "+h[q+2].name+"\n",z.push("argType"+q),n.push(h[q+2]);x&&(E="thisWired"+(0<E.length?", ":"")+E);m+=(ba?"var rv = ":"")+"invoker(fn"+(0<E.length?", ":"")+E+");\n";if(y)m+="runDestructors(destructors);\n";else for(q=x?1:2;q<h.length;++q)p=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==h[q].L&&(m+=p+"_dtor("+p+"); // "+h[q].name+"\n",
z.push(p+"_dtor"),n.push(h[q].L));ba&&(m+="var ret = retType.fromWireType(rv);\nreturn ret;\n");z.push(m+"}\n");h=Ua(z).apply(null,n);q=b-1;if(!f.hasOwnProperty(k))throw new La("Replacing nonexistant public symbol");void 0!==f[k].K&&void 0!==q?f[k].K[q]=h:(f[k]=h,f[k].R=q);return[]})},c:function(a,b,c,d,e){function g(m){return m}b=T(b);-1===e&&(e=4294967295);var l=Na(c);if(0===d){var k=32-8*c;g=function(m){return m<<k>>>k}}var h=b.includes("unsigned");S(a,{name:b,fromWireType:g,toWireType:function(m,
n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+Sa(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+Sa(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return h?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:cb(b,l,0!==d),L:null})},a:function(a,b,c){function d(g){g>>=2;var l=H;return new e(ua,l[g+1],l[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=T(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{W:!0})},i:function(a,b){b=T(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var e=H[d>>2];if(c)for(var g=d+4,l=0;l<=e;++l){var k=d+4+l;if(l==e||0==B[k]){g=A(g,k-g);if(void 0===h)var h=g;else h+=String.fromCharCode(0),h+=g;g=k+1}}else{h=Array(e);for(l=0;l<e;++l)h[l]=String.fromCharCode(B[d+4+l]);h=h.join("")}Y(d);return h},toWireType:function(d,e){e instanceof ArrayBuffer&&
(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||U("Cannot pass non-string to std::string");var l=(c&&g?function(){for(var m=0,n=0;n<e.length;++n){var p=e.charCodeAt(n);55296<=p&&57343>=p&&(p=65536+((p&1023)<<10)|e.charCodeAt(++n)&1023);127>=p?++m:m=2047>=p?m+2:65535>=p?m+3:m+4}return m}:function(){return e.length})(),k=jb(4+l+1);H[k>>2]=l;if(c&&g)ma(e,k+4,l+1);else if(g)for(g=0;g<l;++g){var h=e.charCodeAt(g);255<h&&
(Y(k),U("String has UTF-16 code units that do not fit in 8 bits"));B[k+4+g]=h}else for(g=0;g<l;++g)B[k+4+g]=e[g];null!==d&&d.push(Y,k);return k},argPackAdvance:8,readValueFromPointer:N,L:function(d){Y(d)}})},e:function(a,b,c){c=T(c);if(2===b){var d=oa;var e=pa;var g=qa;var l=function(){return C};var k=1}else 4===b&&(d=ra,e=sa,g=ta,l=function(){return H},k=2);S(a,{name:c,fromWireType:function(h){for(var m=H[h>>2],n=l(),p,x=h+4,y=0;y<=m;++y){var q=h+4+y*b;if(y==m||0==n[q>>k])x=d(x,q-x),void 0===p?p=
x:(p+=String.fromCharCode(0),p+=x),x=q+b}Y(h);return p},toWireType:function(h,m){"string"!==typeof m&&U("Cannot pass non-string to C++ string type "+c);var n=g(m),p=jb(4+n+b);H[p>>2]=n>>k;e(m,p+4,n+b);null!==h&&h.push(Y,p);return p},argPackAdvance:8,readValueFromPointer:N,L:function(h){Y(h)}})},m:function(a,b,c,d,e,g){M[a]={name:T(b),Y:X(c,d),Z:X(e,g),P:[]}},b:function(a,b,c,d,e,g,l,k,h,m){M[a].P.push({S:T(b),V:c,T:X(d,e),U:g,ga:l,fa:X(k,h),ha:m})},x:function(a,b){b=T(b);S(a,{ja:!0,name:b,argPackAdvance:0,
fromWireType:function(){},toWireType:function(){}})},g:Ra,A:function(a){if(0===a)return W(eb());var b=db[a];a=void 0===b?T(a):b;return W(eb()[a])},j:function(a){4<a&&(V[a].O+=1)},n:function(a,b,c,d){a||U("Cannot use deleted val. handle = "+a);a=V[a].value;var e=gb[b];if(!e){e="";for(var g=0;g<b;++g)e+=(0!==g?", ":"")+"arg"+g;var l="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(g=0;g<b;++g)l+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+
g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",l+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(fb,f,W);gb[b]=e}return e(a,c,d)},f:function(){u()},s:function(a,b,c){B.copyWithin(a,b,b+c)},d:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,
d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(2147483648,d)-ua.byteLength+65535>>>16);xa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},t:function(){return 0},p:function(){},u:function(a,b,c,d){for(var e=0,g=0;g<c;g++){for(var l=F[b+8*g>>2],k=F[b+(8*g+4)>>2],h=0;h<k;h++){var m=B[l+h],n=hb[a];if(0===m||10===m){m=1===a?ia:v;var p;for(p=0;n[p]&&!(NaN<=p);)++p;p=la.decode(n.subarray?n.subarray(0,p):new Uint8Array(n.slice(0,p)));m(p);n.length=0}else n.push(m)}e+=k}F[d>>2]=e;return 0},
r:function(){}};
(function(){function a(e){f.asm=e.exports;ja=f.asm.C;xa();I=f.asm.I;za.unshift(f.asm.D);J--;f.monitorRunDependencies&&f.monitorRunDependencies(J);0==J&&(null!==Ca&&(clearInterval(Ca),Ca=null),K&&(e=K,K=null,e()))}function b(e){a(e.instance)}function c(e){return Da().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){v("failed to asynchronously prepare wasm: "+g);u(g)})}var d={a:kb};J++;f.monitorRunDependencies&&f.monitorRunDependencies(J);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return v("Module.instantiateWasm callback failed with error: "+
e),!1}(function(){return w||"function"!==typeof WebAssembly.instantiateStreaming||L.startsWith("data:application/octet-stream;base64,")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){v("wasm streaming compile failed: "+g);v("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ca);return{}})();f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.D).apply(null,arguments)};
var Y=f._free=function(){return(Y=f._free=f.asm.E).apply(null,arguments)},jb=f._malloc=function(){return(jb=f._malloc=f.asm.F).apply(null,arguments)},ab=f.___getTypeName=function(){return(ab=f.___getTypeName=f.asm.G).apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.H).apply(null,arguments)};f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.J).apply(null,arguments)};var lb;
K=function mb(){lb||nb();lb||(K=mb)};
function nb(){function a(){if(!lb&&(lb=!0,f.calledRun=!0,!ka)){Ea(za);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Aa.unshift(b)}Ea(Aa)}}if(!(0<J)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ba();Ea(ya);0<J||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=nb;
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();nb();


  return Module.ready
}
);
})();
export default Module;