
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var e;e||(e=typeof Module !== 'undefined' ? Module : {});var aa,r;e.ready=new Promise(function(a,b){aa=a;r=b});var t={},u;for(u in e)e.hasOwnProperty(u)&&(t[u]=e[u]);var v="",w;v=self.location.href;_scriptDir&&(v=_scriptDir);0!==v.indexOf("blob:")?v=v.substr(0,v.lastIndexOf("/")+1):v="";w=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var ba=e.print||console.log.bind(console),y=e.printErr||console.warn.bind(console);
for(u in t)t.hasOwnProperty(u)&&(e[u]=t[u]);t=null;var z;e.wasmBinary&&(z=e.wasmBinary);var noExitRuntime=e.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var ca,da=!1,ea=new TextDecoder("utf8");
function fa(a,b,c){var d=C;if(0<c){c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}}var ha=new TextDecoder("utf-16le");
function ia(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&D[c];)++c;return ha.decode(C.subarray(a,c<<1))}function ja(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var g=0;g<c;++g)E[b>>1]=a.charCodeAt(g),b+=2;E[b>>1]=0;return b-d}function ka(a){return 2*a.length}function la(a,b){for(var c=0,d="";!(c>=b/4);){var g=F[a+4*c>>2];if(0==g)break;++c;65536<=g?(g-=65536,d+=String.fromCharCode(55296|g>>10,56320|g&1023)):d+=String.fromCharCode(g)}return d}
function ma(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var l=a.charCodeAt(++g);f=65536+((f&1023)<<10)|l&1023}F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function na(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var oa,G,C,E,D,F,I,pa,qa;
function ra(){var a=ca.buffer;oa=a;e.HEAP8=G=new Int8Array(a);e.HEAP16=E=new Int16Array(a);e.HEAP32=F=new Int32Array(a);e.HEAPU8=C=new Uint8Array(a);e.HEAPU16=D=new Uint16Array(a);e.HEAPU32=I=new Uint32Array(a);e.HEAPF32=pa=new Float32Array(a);e.HEAPF64=qa=new Float64Array(a)}var J,sa=[],ta=[],ua=[];function va(){var a=e.preRun.shift();sa.unshift(a)}var L=0,wa=null,M=null;e.preloadedImages={};e.preloadedAudios={};
function A(a){if(e.onAbort)e.onAbort(a);y(a);da=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");r(a);throw a;}var N=(new URL("wp2_dec.wasm",import.meta.url)).toString();function xa(){try{if(N==N&&z)return new Uint8Array(z);if(w)return w(N);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}
function ya(){return z||"function"!==typeof fetch?Promise.resolve().then(function(){return xa()}):fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return xa()})}function za(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.T;"number"===typeof c?void 0===b.I?J.get(c)():J.get(c)(b.I):c(void 0===b.I?null:b.I)}}}
function Aa(a){this.H=a-16;this.S=function(b){F[this.H+8>>2]=b};this.O=function(b){F[this.H+0>>2]=b};this.P=function(){F[this.H+4>>2]=0};this.N=function(){G[this.H+12>>0]=0};this.R=function(){G[this.H+13>>0]=0};this.M=function(b,c){this.S(b);this.O(c);this.P();this.N();this.R()}}var Ba=0;function Ca(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Da=void 0;
function O(a){for(var b="";C[a];)b+=Da[C[a++]];return b}var P={},Q={},R={};function Ea(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Fa(a,b){a=Ea(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ga(a){var b=Error,c=Fa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ja=void 0;function S(a){throw new Ja(a);}var Ka=void 0;
function La(a,b){function c(h){h=b(h);if(h.length!==d.length)throw new Ka("Mismatched type converter count");for(var p=0;p<d.length;++p)T(d[p],h[p])}var d=[];d.forEach(function(h){R[h]=a});var g=Array(a.length),f=[],l=0;a.forEach(function(h,p){Q.hasOwnProperty(h)?g[p]=Q[h]:(f.push(h),P.hasOwnProperty(h)||(P[h]=[]),P[h].push(function(){g[p]=Q[h];++l;l===f.length&&c(g)}))});0===f.length&&c(g)}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(Q.hasOwnProperty(a)){if(c.L)return;S("Cannot register type '"+d+"' twice")}Q[a]=b;delete R[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(function(g){g()}))}var Ma=[],U=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Na(a){4<a&&0===--U[a].J&&(U[a]=void 0,Ma.push(a))}function V(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ma.length?Ma.pop():U.length;U[b]={J:1,value:a};return b}}function Oa(a){return this.fromWireType(I[a>>2])}function Pa(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Qa(a,b){switch(b){case 2:return function(c){return this.fromWireType(pa[c>>2])};case 3:return function(c){return this.fromWireType(qa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Ra(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Fa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Sa(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ta(a,b){var c=e;if(void 0===c[a].F){var d=c[a];c[a]=function(){c[a].F.hasOwnProperty(arguments.length)||S("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].F+")!");return c[a].F[arguments.length].apply(this,arguments)};c[a].F=[];c[a].F[d.K]=d}}
function Ua(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].F&&void 0!==e[a].F[c])&&S("Cannot register public name '"+a+"' twice"),Ta(a,a),e.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].F[c]=b):(e[a]=b,void 0!==c&&(e[a].V=c))}function Va(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function Wa(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=e["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=J.get(b).apply(null,c);return d}}function Xa(a,b){a=O(a);var c=a.includes("j")?Wa(a,b):J.get(b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Ya=void 0;function Za(a){a=$a(a);var b=O(a);W(a);return b}
function ab(a,b){function c(f){g[f]||Q[f]||(R[f]?R[f].forEach(c):(d.push(f),g[f]=!0))}var d=[],g={};b.forEach(c);throw new Ya(a+": "+d.map(Za).join([", "]));}function bb(a,b,c){switch(b){case 0:return c?function(d){return G[d]}:function(d){return C[d]};case 1:return c?function(d){return E[d>>1]}:function(d){return D[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var cb={};
function db(){return"object"===typeof globalThis?globalThis:Function("return this")()}function eb(a,b){var c=Q[a];void 0===c&&S(b+" has unknown type "+Za(a));return c}for(var fb={},gb=[null,[],[]],hb=Array(256),X=0;256>X;++X)hb[X]=String.fromCharCode(X);Da=hb;Ja=e.BindingError=Ga("BindingError");Ka=e.InternalError=Ga("InternalError");e.count_emval_handles=function(){for(var a=0,b=5;b<U.length;++b)void 0!==U[b]&&++a;return a};
e.get_first_emval=function(){for(var a=5;a<U.length;++a)if(void 0!==U[a])return U[a];return null};Ya=e.UnboundTypeError=Ga("UnboundTypeError");
var ib={p:function(a){return Y(a+16)+16},e:function(){},o:function(a,b,c){(new Aa(a)).M(b,c);Ba++;throw a;},r:function(){},m:function(a,b,c,d,g){var f=Ca(c);b=O(b);T(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,h){return h?d:g},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var h=G;else if(2===c)h=E;else if(4===c)h=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[l>>f])},G:null})},v:function(a,b){b=O(b);T(a,{name:b,fromWireType:function(c){var d=
U[c].value;Na(c);return d},toWireType:function(c,d){return V(d)},argPackAdvance:8,readValueFromPointer:Oa,G:null})},k:function(a,b,c){c=Ca(c);b=O(b);T(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,g){if("number"!==typeof g&&"boolean"!==typeof g)throw new TypeError('Cannot convert "'+Pa(g)+'" to '+this.name);return g},argPackAdvance:8,readValueFromPointer:Qa(b,c),G:null})},q:function(a,b,c,d,g,f){var l=Va(b,c);a=O(a);g=Xa(d,g);Ua(a,function(){ab("Cannot call "+a+" due to unbound types",
l)},b-1);La(l,function(h){var p=a,k=a;h=[h[0],null].concat(h.slice(1));var m=g,q=h.length;2>q&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==h[1]&&!1,B=!1,n=1;n<h.length;++n)if(null!==h[n]&&void 0===h[n].G){B=!0;break}var Ha="void"!==h[0].name,H="",K="";for(n=0;n<q-2;++n)H+=(0!==n?", ":"")+"arg"+n,K+=(0!==n?", ":"")+"arg"+n+"Wired";k="return function "+Ea(k)+"("+H+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+k+" called with ' + arguments.length + ' arguments, expected "+
(q-2)+" args!');\n}\n";B&&(k+="var destructors = [];\n");var Ia=B?"destructors":"null";H="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[S,m,f,Sa,h[0],h[1]];x&&(k+="var thisWired = classParam.toWireType("+Ia+", this);\n");for(n=0;n<q-2;++n)k+="var arg"+n+"Wired = argType"+n+".toWireType("+Ia+", arg"+n+"); // "+h[n+2].name+"\n",H.push("argType"+n),m.push(h[n+2]);x&&(K="thisWired"+(0<K.length?", ":"")+K);k+=(Ha?"var rv = ":"")+"invoker(fn"+(0<K.length?", ":"")+K+");\n";
if(B)k+="runDestructors(destructors);\n";else for(n=x?1:2;n<h.length;++n)q=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==h[n].G&&(k+=q+"_dtor("+q+"); // "+h[n].name+"\n",H.push(q+"_dtor"),m.push(h[n].G));Ha&&(k+="var ret = retType.fromWireType(rv);\nreturn ret;\n");H.push(k+"}\n");h=Ra(H).apply(null,m);n=b-1;if(!e.hasOwnProperty(p))throw new Ka("Replacing nonexistant public symbol");void 0!==e[p].F&&void 0!==n?e[p].F[n]=h:(e[p]=h,e[p].K=n);return[]})},b:function(a,b,c,d,g){function f(k){return k}b=
O(b);-1===g&&(g=4294967295);var l=Ca(c);if(0===d){var h=32-8*c;f=function(k){return k<<h>>>h}}var p=b.includes("unsigned");T(a,{name:b,fromWireType:f,toWireType:function(k,m){if("number"!==typeof m&&"boolean"!==typeof m)throw new TypeError('Cannot convert "'+Pa(m)+'" to '+this.name);if(m<d||m>g)throw new TypeError('Passing a number "'+Pa(m)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+g+"]!");return p?m>>>0:m|0},argPackAdvance:8,readValueFromPointer:bb(b,
l,0!==d),G:null})},a:function(a,b,c){function d(f){f>>=2;var l=I;return new g(oa,l[f+1],l[f])}var g=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=O(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{L:!0})},l:function(a,b){b=O(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var g=I[d>>2];if(c)for(var f=d+4,l=0;l<=g;++l){var h=d+4+l;if(l==g||0==C[h]){if(f){for(var p=f+(h-f),k=f;!(k>=p)&&C[k];)++k;f=ea.decode(C.subarray(f,
k))}else f="";if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=h+1}}else{m=Array(g);for(l=0;l<g;++l)m[l]=String.fromCharCode(C[d+4+l]);m=m.join("")}W(d);return m},toWireType:function(d,g){g instanceof ArrayBuffer&&(g=new Uint8Array(g));var f="string"===typeof g;f||g instanceof Uint8Array||g instanceof Uint8ClampedArray||g instanceof Int8Array||S("Cannot pass non-string to std::string");var l=(c&&f?function(){for(var k=0,m=0;m<g.length;++m){var q=g.charCodeAt(m);55296<=q&&57343>=q&&(q=65536+
((q&1023)<<10)|g.charCodeAt(++m)&1023);127>=q?++k:k=2047>=q?k+2:65535>=q?k+3:k+4}return k}:function(){return g.length})(),h=Y(4+l+1);I[h>>2]=l;if(c&&f)fa(g,h+4,l+1);else if(f)for(f=0;f<l;++f){var p=g.charCodeAt(f);255<p&&(W(h),S("String has UTF-16 code units that do not fit in 8 bits"));C[h+4+f]=p}else for(f=0;f<l;++f)C[h+4+f]=g[f];null!==d&&d.push(W,h);return h},argPackAdvance:8,readValueFromPointer:Oa,G:function(d){W(d)}})},g:function(a,b,c){c=O(c);if(2===b){var d=ia;var g=ja;var f=ka;var l=function(){return D};
var h=1}else 4===b&&(d=la,g=ma,f=na,l=function(){return I},h=2);T(a,{name:c,fromWireType:function(p){for(var k=I[p>>2],m=l(),q,x=p+4,B=0;B<=k;++B){var n=p+4+B*b;if(B==k||0==m[n>>h])x=d(x,n-x),void 0===q?q=x:(q+=String.fromCharCode(0),q+=x),x=n+b}W(p);return q},toWireType:function(p,k){"string"!==typeof k&&S("Cannot pass non-string to C++ string type "+c);var m=f(k),q=Y(4+m+b);I[q>>2]=m>>h;g(k,q+4,m+b);null!==p&&p.push(W,q);return q},argPackAdvance:8,readValueFromPointer:Oa,G:function(p){W(p)}})},
n:function(a,b){b=O(b);T(a,{U:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},c:Na,d:function(a){if(0===a)return V(db());var b=cb[a];a=void 0===b?O(a):b;return V(db()[a])},h:function(a){4<a&&(U[a].J+=1)},i:function(a,b,c,d){a||S("Cannot use deleted val. handle = "+a);a=U[a].value;var g=fb[b];if(!g){g="";for(var f=0;f<b;++f)g+=(0!==f?", ":"")+"arg"+f;var l="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)l+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+
f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";g=(new Function("requireRegisteredType","Module","__emval_register",l+("var obj = new constructor("+g+");\nreturn __emval_register(obj);\n}\n")))(eb,e,V);fb[b]=g}return g(a,c,d)},j:function(){A()},t:function(a,b,c){C.copyWithin(a,b,b+c)},f:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,
d);0<d%65536&&(d+=65536-d%65536);a:{try{ca.grow(Math.min(2147483648,d)-oa.byteLength+65535>>>16);ra();var g=1;break a}catch(f){}g=void 0}if(g)return!0}return!1},u:function(a,b,c,d){for(var g=0,f=0;f<c;f++){for(var l=F[b+8*f>>2],h=F[b+(8*f+4)>>2],p=0;p<h;p++){var k=C[l+p],m=gb[a];if(0===k||10===k){for(k=0;m[k]&&!(NaN<=k);)++k;k=ea.decode(m.subarray?m.subarray(0,k):new Uint8Array(m.slice(0,k)));(1===a?ba:y)(k);m.length=0}else m.push(k)}g+=h}F[d>>2]=g;return 0},s:function(){}};
(function(){function a(g){e.asm=g.exports;ca=e.asm.w;ra();J=e.asm.C;ta.unshift(e.asm.x);L--;e.monitorRunDependencies&&e.monitorRunDependencies(L);0==L&&(null!==wa&&(clearInterval(wa),wa=null),M&&(g=M,M=null,g()))}function b(g){a(g.instance)}function c(g){return ya().then(function(f){return WebAssembly.instantiate(f,d)}).then(g,function(f){y("failed to asynchronously prepare wasm: "+f);A(f)})}var d={a:ib};L++;e.monitorRunDependencies&&e.monitorRunDependencies(L);if(e.instantiateWasm)try{return e.instantiateWasm(d,
a)}catch(g){return y("Module.instantiateWasm callback failed with error: "+g),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||N.startsWith("data:application/octet-stream;base64,")||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(g){return WebAssembly.instantiateStreaming(g,d).then(b,function(f){y("wasm streaming compile failed: "+f);y("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(r);return{}})();
e.___wasm_call_ctors=function(){return(e.___wasm_call_ctors=e.asm.x).apply(null,arguments)};var W=e._free=function(){return(W=e._free=e.asm.y).apply(null,arguments)},Y=e._malloc=function(){return(Y=e._malloc=e.asm.z).apply(null,arguments)},$a=e.___getTypeName=function(){return($a=e.___getTypeName=e.asm.A).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.B).apply(null,arguments)};
e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.D).apply(null,arguments)};var Z;M=function jb(){Z||kb();Z||(M=jb)};
function kb(){function a(){if(!Z&&(Z=!0,e.calledRun=!0,!da)){za(ta);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();ua.unshift(b)}za(ua)}}if(!(0<L)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)va();za(sa);0<L||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=kb;
if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();kb();


  return Module.ready
}
);
})();
export default Module;