
var wp2_dec = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(wp2_dec) {
  wp2_dec = wp2_dec || {};


var e;e||(e=typeof wp2_dec !== 'undefined' ? wp2_dec : {});var aa,ba;e.ready=new Promise(function(a,b){aa=a;ba=b});var r={},w;for(w in e)e.hasOwnProperty(w)&&(r[w]=e[w]);var ca=!1,y=!1,da=!1,ea=!1;ca="object"===typeof window;y="function"===typeof importScripts;da="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ea=!ca&&!da&&!y;var z="",ha,A,ia,ja;
if(da)z=y?require("path").dirname(z)+"/":__dirname+"/",ha=function(a,b){ia||(ia=require("fs"));ja||(ja=require("path"));a=ja.normalize(a);return ia.readFileSync(a,b?null:"utf8")},A=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||B("Assertion failed: undefined");return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",B),e.inspect=function(){return"[Emscripten Module object]"};
else if(ea)"undefined"!=typeof read&&(ha=function(a){return read(a)}),A=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||B("Assertion failed: undefined");return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ca||y)y?z=self.location.href:document.currentScript&&(z=document.currentScript.src),_scriptDir&&
(z=_scriptDir),0!==z.indexOf("blob:")?z=z.substr(0,z.lastIndexOf("/")+1):z="",ha=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},y&&(A=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ka=e.print||console.log.bind(console),E=e.printErr||console.warn.bind(console);for(w in r)r.hasOwnProperty(w)&&(e[w]=r[w]);r=null;var F;e.wasmBinary&&(F=e.wasmBinary);var noExitRuntime;
e.noExitRuntime&&(noExitRuntime=e.noExitRuntime);"object"!==typeof WebAssembly&&B("no native wasm support detected");var G,la=new WebAssembly.Table({initial:278,maximum:278,element:"anyfunc"}),ma=!1,na="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&na)return na.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}
function pa(a,b,c){var d=H;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function ra(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&sa[c];)++c;c<<=1;if(32<c-a&&qa)return qa.decode(H.subarray(a,c));c=0;for(d="";;){var f=I[a+2*c>>1];if(0==f||c==b/2)return d;++c;d+=String.fromCharCode(f)}}function ta(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)I[b>>1]=a.charCodeAt(f),b+=2;I[b>>1]=0;return b-d}function ua(a){return 2*a.length}
function va(a,b){for(var c=0,d="";!(c>=b/4);){var f=J[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function wa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}J[b>>2]=g;b+=4;if(b+4>c)break}J[b>>2]=0;return b-d}
function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var K,ya,H,I,sa,J,L,za,Aa;function Ba(a){K=a;e.HEAP8=ya=new Int8Array(a);e.HEAP16=I=new Int16Array(a);e.HEAP32=J=new Int32Array(a);e.HEAPU8=H=new Uint8Array(a);e.HEAPU16=sa=new Uint16Array(a);e.HEAPU32=L=new Uint32Array(a);e.HEAPF32=za=new Float32Array(a);e.HEAPF64=Aa=new Float64Array(a)}var Ca=e.INITIAL_MEMORY||16777216;
e.wasmMemory?G=e.wasmMemory:G=new WebAssembly.Memory({initial:Ca/65536,maximum:32768});G&&(K=G.buffer);Ca=K.byteLength;Ba(K);J[33036]=5375184;function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(e);else{var c=b.xa;"number"===typeof c?void 0===b.pa?e.dynCall_v(c):e.dynCall_vi(c,b.pa):c(void 0===b.pa?null:b.pa)}}}var Ea=[],Fa=[],Ga=[],Ha=[];function Ia(){var a=e.preRun.shift();Ea.unshift(a)}var Ja=Math.ceil,Ka=Math.floor,M=0,La=null,N=null;e.preloadedImages={};
e.preloadedAudios={};function B(a){if(e.onAbort)e.onAbort(a);E(a);ma=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ma(a){var b=O;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Na(){return Ma("data:application/octet-stream;base64,")}var O="wp2_dec.wasm";if(!Na()){var Oa=O;O=e.locateFile?e.locateFile(Oa,z):z+Oa}
function Pa(){try{if(F)return new Uint8Array(F);if(A)return A(O);throw"both async and sync fetching of the wasm failed";}catch(a){B(a)}}function Qa(){return F||!ca&&!y||"function"!==typeof fetch||Ma("file://")?new Promise(function(a){a(Pa())}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Pa()})}Fa.push({xa:function(){Ra()}});function Sa(){return 0<Sa.ka}
function Ta(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ua=void 0;function P(a){for(var b="";H[a];)b+=Ua[H[a++]];return b}var Q={},R={},Va={};function Wa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Xa(a,b){a=Wa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ya(a){var b=Error,c=Xa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Za=void 0;function S(a){throw new Za(a);}var $a=void 0;function ab(a){throw new $a(a);}function bb(a,b,c){function d(k){k=c(k);k.length!==a.length&&ab("Mismatched type converter count");for(var h=0;h<a.length;++h)T(a[h],k[h])}a.forEach(function(k){Va[k]=b});var f=Array(b.length),g=[],l=0;b.forEach(function(k,h){R.hasOwnProperty(k)?f[h]=R[k]:(g.push(k),Q.hasOwnProperty(k)||(Q[k]=[]),Q[k].push(function(){f[h]=R[k];++l;l===g.length&&d(f)}))});0===g.length&&d(f)}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(c.Aa)return;S("Cannot register type '"+d+"' twice")}R[a]=b;delete Va[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(function(f){f()}))}function cb(a){return{count:a.count,ja:a.ja,la:a.la,Z:a.Z,aa:a.aa,ba:a.ba,da:a.da}}
function db(a){S(a.Y.aa.$.name+" instance already deleted")}var eb=!1;function fb(){}function gb(a){--a.count.value;0===a.count.value&&(a.ba?a.da.ia(a.ba):a.aa.$.ia(a.Z))}function hb(a){if("undefined"===typeof FinalizationGroup)return hb=function(b){return b},a;eb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.Z?gb(c):console.warn("object already deleted: "+c.Z)});hb=function(b){eb.register(b,b.Y,b.Y);return b};fb=function(b){eb.unregister(b.Y)};return hb(a)}
var ib=void 0,jb=[];function kb(){for(;jb.length;){var a=jb.pop();a.Y.ja=!1;a["delete"]()}}function U(){}var lb={};function mb(a,b){var c=e;if(void 0===c[a].fa){var d=c[a];c[a]=function(){c[a].fa.hasOwnProperty(arguments.length)||S("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].fa+")!");return c[a].fa[arguments.length].apply(this,arguments)};c[a].fa=[];c[a].fa[d.ua]=d}}
function nb(a,b,c){e.hasOwnProperty(a)?((void 0===c||void 0!==e[a].fa&&void 0!==e[a].fa[c])&&S("Cannot register public name '"+a+"' twice"),mb(a,a),e.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),e[a].fa[c]=b):(e[a]=b,void 0!==c&&(e[a].Ga=c))}function ob(a,b,c,d,f,g,l,k){this.name=a;this.constructor=b;this.ha=c;this.ia=d;this.ea=f;this.ya=g;this.ma=l;this.wa=k}
function pb(a,b,c){for(;b!==c;)b.ma||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.ma(a),b=b.ea;return a}function qb(a,b){if(null===b)return this.qa&&S("null is not a valid "+this.name),0;b.Y||S('Cannot pass "'+V(b)+'" as a '+this.name);b.Y.Z||S("Cannot pass deleted object as a pointer of type "+this.name);return pb(b.Y.Z,b.Y.aa.$,this.$)}
function rb(a,b){if(null===b){this.qa&&S("null is not a valid "+this.name);if(this.oa){var c=this.Ca();null!==a&&a.push(this.ia,c);return c}return 0}b.Y||S('Cannot pass "'+V(b)+'" as a '+this.name);b.Y.Z||S("Cannot pass deleted object as a pointer of type "+this.name);!this.na&&b.Y.aa.na&&S("Cannot convert argument of type "+(b.Y.da?b.Y.da.name:b.Y.aa.name)+" to parameter type "+this.name);c=pb(b.Y.Z,b.Y.aa.$,this.$);if(this.oa)switch(void 0===b.Y.ba&&S("Passing raw pointer to smart pointer is illegal"),
this.Ea){case 0:b.Y.da===this?c=b.Y.ba:S("Cannot convert argument of type "+(b.Y.da?b.Y.da.name:b.Y.aa.name)+" to parameter type "+this.name);break;case 1:c=b.Y.ba;break;case 2:if(b.Y.da===this)c=b.Y.ba;else{var d=b.clone();c=this.Da(c,sb(function(){d["delete"]()}));null!==a&&a.push(this.ia,c)}break;default:S("Unsupporting sharing policy")}return c}
function tb(a,b){if(null===b)return this.qa&&S("null is not a valid "+this.name),0;b.Y||S('Cannot pass "'+V(b)+'" as a '+this.name);b.Y.Z||S("Cannot pass deleted object as a pointer of type "+this.name);b.Y.aa.na&&S("Cannot convert argument of type "+b.Y.aa.name+" to parameter type "+this.name);return pb(b.Y.Z,b.Y.aa.$,this.$)}function vb(a){return this.fromWireType(L[a>>2])}function wb(a,b,c){if(b===c)return a;if(void 0===c.ea)return null;a=wb(a,b,c.ea);return null===a?null:c.wa(a)}var xb={};
function yb(a,b){for(void 0===b&&S("ptr should not be undefined");a.ea;)b=a.ma(b),a=a.ea;return xb[b]}function zb(a,b){b.aa&&b.Z||ab("makeClassHandle requires ptr and ptrType");!!b.da!==!!b.ba&&ab("Both smartPtrType and smartPtr must be specified");b.count={value:1};return hb(Object.create(a,{Y:{value:b}}))}
function W(a,b,c,d){this.name=a;this.$=b;this.qa=c;this.na=d;this.oa=!1;this.ia=this.Da=this.Ca=this.ta=this.Ea=this.Ba=void 0;void 0!==b.ea?this.toWireType=rb:(this.toWireType=d?qb:tb,this.ga=null)}function Ab(a,b,c){e.hasOwnProperty(a)||ab("Replacing nonexistant public symbol");void 0!==e[a].fa&&void 0!==c?e[a].fa[c]=b:(e[a]=b,e[a].ua=c)}
function X(a,b){a=P(a);var c=e["dynCall_"+a];for(var d=[],f=1;f<a.length;++f)d.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Bb=void 0;function Cb(a){a=Db(a);var b=P(a);Y(a);return b}
function Eb(a,b){function c(g){f[g]||R[g]||(Va[g]?Va[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Bb(a+": "+d.map(Cb).join([", "]));}function Fb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Gb(a,b,c){a instanceof Object||S(c+' with invalid "this": '+a);a instanceof b.$.constructor||S(c+' incompatible with "this" of type '+a.constructor.name);a.Y.Z||S("cannot call emscripten binding method "+c+" on deleted object");return pb(a.Y.Z,a.Y.aa.$,b.$)}
var Hb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Ib(a){4<a&&0===--Z[a].ra&&(Z[a]=void 0,Hb.push(a))}function sb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Hb.length?Hb.pop():Z.length;Z[b]={ra:1,value:a};return b}}function V(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Jb(a,b){switch(b){case 2:return function(c){return this.fromWireType(za[c>>2])};case 3:return function(c){return this.fromWireType(Aa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Kb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Xa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Lb(a,b){for(var c=[],d=0;d<a;d++)c.push(J[(b>>2)+d]);return c}function Mb(a,b,c){switch(b){case 0:return c?function(d){return ya[d]}:function(d){return H[d]};case 1:return c?function(d){return I[d>>1]}:function(d){return sa[d>>1]};case 2:return c?function(d){return J[d>>2]}:function(d){return L[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var Nb=[null,[],[]],Ob=Array(256),Pb=0;256>Pb;++Pb)Ob[Pb]=String.fromCharCode(Pb);Ua=Ob;Za=e.BindingError=Ya("BindingError");
$a=e.InternalError=Ya("InternalError");U.prototype.isAliasOf=function(a){if(!(this instanceof U&&a instanceof U))return!1;var b=this.Y.aa.$,c=this.Y.Z,d=a.Y.aa.$;for(a=a.Y.Z;b.ea;)c=b.ma(c),b=b.ea;for(;d.ea;)a=d.ma(a),d=d.ea;return b===d&&c===a};U.prototype.clone=function(){this.Y.Z||db(this);if(this.Y.la)return this.Y.count.value+=1,this;var a=hb(Object.create(Object.getPrototypeOf(this),{Y:{value:cb(this.Y)}}));a.Y.count.value+=1;a.Y.ja=!1;return a};
U.prototype["delete"]=function(){this.Y.Z||db(this);this.Y.ja&&!this.Y.la&&S("Object already scheduled for deletion");fb(this);gb(this.Y);this.Y.la||(this.Y.ba=void 0,this.Y.Z=void 0)};U.prototype.isDeleted=function(){return!this.Y.Z};U.prototype.deleteLater=function(){this.Y.Z||db(this);this.Y.ja&&!this.Y.la&&S("Object already scheduled for deletion");jb.push(this);1===jb.length&&ib&&ib(kb);this.Y.ja=!0;return this};W.prototype.za=function(a){this.ta&&(a=this.ta(a));return a};
W.prototype.sa=function(a){this.ia&&this.ia(a)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=vb;W.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
W.prototype.fromWireType=function(a){function b(){return this.oa?zb(this.$.ha,{aa:this.Ba,Z:c,da:this,ba:a}):zb(this.$.ha,{aa:this,Z:a})}var c=this.za(a);if(!c)return this.sa(a),null;var d=yb(this.$,c);if(void 0!==d){if(0===d.Y.count.value)return d.Y.Z=c,d.Y.ba=a,d.clone();d=d.clone();this.sa(a);return d}d=this.$.ya(c);d=lb[d];if(!d)return b.call(this);d=this.na?d.va:d.pointerType;var f=wb(c,this.$,d.$);return null===f?b.call(this):this.oa?zb(d.$.ha,{aa:d,Z:f,da:this,ba:a}):zb(d.$.ha,{aa:d,Z:f})};
e.getInheritedInstanceCount=function(){return Object.keys(xb).length};e.getLiveInheritedInstances=function(){var a=[],b;for(b in xb)xb.hasOwnProperty(b)&&a.push(xb[b]);return a};e.flushPendingDeletes=kb;e.setDelayFunction=function(a){ib=a;jb.length&&ib&&ib(kb)};Bb=e.UnboundTypeError=Ya("UnboundTypeError");e.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};e.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Rb={t:function(a){return Qb(a)},s:function(a){"uncaught_exception"in Sa?Sa.ka++:Sa.ka=1;throw a;},y:function(a,b,c,d,f){var g=Ta(c);b=P(b);T(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=ya;else if(2===c)k=I;else if(4===c)k=J;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>g])},ga:null})},u:function(a,b,c,d,f,g,l,k,h,p,m,q,t){m=P(m);g=X(f,g);k&&(k=X(l,
k));p&&(p=X(h,p));t=X(q,t);var u=Wa(m);nb(u,function(){Eb("Cannot construct "+m+" due to unbound types",[d])});bb([a,b,c],d?[d]:[],function(n){n=n[0];if(d){var D=n.$;var v=D.ha}else v=U.prototype;n=Xa(u,function(){if(Object.getPrototypeOf(this)!==x)throw new Za("Use 'new' to construct "+m);if(void 0===C.ka)throw new Za(m+" has no accessible constructor");var ub=C.ka[arguments.length];if(void 0===ub)throw new Za("Tried to invoke ctor of "+m+" with invalid number of parameters ("+arguments.length+") - expected ("+
Object.keys(C.ka).toString()+") parameters instead!");return ub.apply(this,arguments)});var x=Object.create(v,{constructor:{value:n}});n.prototype=x;var C=new ob(m,n,x,t,D,g,k,p);D=new W(m,C,!0,!1);v=new W(m+"*",C,!1,!1);var fa=new W(m+" const*",C,!1,!0);lb[a]={pointerType:v,va:fa};Ab(u,n);return[D,v,fa]})},f:function(a,b,c,d,f,g,l,k,h,p){b=P(b);f=X(d,f);bb([],[a],function(m){m=m[0];var q=m.name+"."+b,t={get:function(){Eb("Cannot access "+q+" due to unbound types",[c,l])},enumerable:!0,configurable:!0};
h?t.set=function(){Eb("Cannot access "+q+" due to unbound types",[c,l])}:t.set=function(){S(q+" is a read-only property")};Object.defineProperty(m.$.ha,b,t);bb([],h?[c,l]:[c],function(u){var n=u[0],D={get:function(){var x=Gb(this,m,q+" getter");return n.fromWireType(f(g,x))},enumerable:!0};if(h){h=X(k,h);var v=u[1];D.set=function(x){var C=Gb(this,m,q+" setter"),fa=[];h(p,C,v.toWireType(fa,x));Fb(fa)}}Object.defineProperty(m.$.ha,b,D);return[]});return[]})},x:function(a,b){b=P(b);T(a,{name:b,fromWireType:function(c){var d=
Z[c].value;Ib(c);return d},toWireType:function(c,d){return sb(d)},argPackAdvance:8,readValueFromPointer:vb,ga:null})},n:function(a,b,c){c=Ta(c);b=P(b);T(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+V(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Jb(b,c),ga:null})},j:function(a,b,c,d,f,g){var l=Lb(b,c);a=P(a);f=X(d,f);nb(a,function(){Eb("Cannot call "+a+" due to unbound types",
l)},b-1);bb([],l,function(k){var h=[k[0],null].concat(k.slice(1)),p=k=a,m=f,q=h.length;2>q&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var t=null!==h[1]&&!1,u=!1,n=1;n<h.length;++n)if(null!==h[n]&&void 0===h[n].ga){u=!0;break}var D="void"!==h[0].name,v="",x="";for(n=0;n<q-2;++n)v+=(0!==n?", ":"")+"arg"+n,x+=(0!==n?", ":"")+"arg"+n+"Wired";p="return function "+Wa(p)+"("+v+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+
(q-2)+" args!');\n}\n";u&&(p+="var destructors = [];\n");var C=u?"destructors":"null";v="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[S,m,g,Fb,h[0],h[1]];t&&(p+="var thisWired = classParam.toWireType("+C+", this);\n");for(n=0;n<q-2;++n)p+="var arg"+n+"Wired = argType"+n+".toWireType("+C+", arg"+n+"); // "+h[n+2].name+"\n",v.push("argType"+n),m.push(h[n+2]);t&&(x="thisWired"+(0<x.length?", ":"")+x);p+=(D?"var rv = ":"")+"invoker(fn"+(0<x.length?", ":"")+x+");\n";if(u)p+=
"runDestructors(destructors);\n";else for(n=t?1:2;n<h.length;++n)q=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==h[n].ga&&(p+=q+"_dtor("+q+"); // "+h[n].name+"\n",v.push(q+"_dtor"),m.push(h[n].ga));D&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");v.push(p+"}\n");h=Kb(v).apply(null,m);Ab(k,h,b-1);return[]})},b:function(a,b,c,d,f){function g(p){return p}b=P(b);-1===f&&(f=4294967295);var l=Ta(c);if(0===d){var k=32-8*c;g=function(p){return p<<k>>>k}}var h=-1!=b.indexOf("unsigned");T(a,{name:b,
fromWireType:g,toWireType:function(p,m){if("number"!==typeof m&&"boolean"!==typeof m)throw new TypeError('Cannot convert "'+V(m)+'" to '+this.name);if(m<d||m>f)throw new TypeError('Passing a number "'+V(m)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return h?m>>>0:m|0},argPackAdvance:8,readValueFromPointer:Mb(b,l,0!==d),ga:null})},a:function(a,b,c){function d(g){g>>=2;var l=L;return new f(K,l[g+1],l[g])}var f=[Int8Array,Uint8Array,
Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);T(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Aa:!0})},o:function(a,b){b=P(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(d){var f=L[d>>2];if(c)for(var g=d+4,l=0;l<=f;++l){var k=d+4+l;if(l==f||0==H[k]){g=g?oa(H,g,k-g):"";if(void 0===h)var h=g;else h+=String.fromCharCode(0),h+=g;g=k+1}}else{h=Array(f);for(l=0;l<f;++l)h[l]=String.fromCharCode(H[d+4+l]);h=h.join("")}Y(d);return h},
toWireType:function(d,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||S("Cannot pass non-string to std::string");var l=(c&&g?function(){for(var p=0,m=0;m<f.length;++m){var q=f.charCodeAt(m);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|f.charCodeAt(++m)&1023);127>=q?++p:p=2047>=q?p+2:65535>=q?p+3:p+4}return p}:function(){return f.length})(),k=Qb(4+l+1);L[k>>2]=l;if(c&&g)pa(f,k+4,l+1);else if(g)for(g=
0;g<l;++g){var h=f.charCodeAt(g);255<h&&(Y(k),S("String has UTF-16 code units that do not fit in 8 bits"));H[k+4+g]=h}else for(g=0;g<l;++g)H[k+4+g]=f[g];null!==d&&d.push(Y,k);return k},argPackAdvance:8,readValueFromPointer:vb,ga:function(d){Y(d)}})},g:function(a,b,c){c=P(c);if(2===b){var d=ra;var f=ta;var g=ua;var l=function(){return sa};var k=1}else 4===b&&(d=va,f=wa,g=xa,l=function(){return L},k=2);T(a,{name:c,fromWireType:function(h){for(var p=L[h>>2],m=l(),q,t=h+4,u=0;u<=p;++u){var n=h+4+u*b;
if(u==p||0==m[n>>k])t=d(t,n-t),void 0===q?q=t:(q+=String.fromCharCode(0),q+=t),t=n+b}Y(h);return q},toWireType:function(h,p){"string"!==typeof p&&S("Cannot pass non-string to C++ string type "+c);var m=g(p),q=Qb(4+m+b);L[q>>2]=m>>k;f(p,q+4,m+b);null!==h&&h.push(Y,q);return q},argPackAdvance:8,readValueFromPointer:vb,ga:function(h){Y(h)}})},z:function(a,b){b=P(b);T(a,{Fa:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},d:Ib,h:function(a){4<a&&(Z[a].ra+=1)},i:function(a,
b){var c=R[a];void 0===c&&S("_emval_take_value has unknown type "+Cb(a));a=c.readValueFromPointer(b);return sb(a)},l:function(){B()},w:function(a,b,c){H.copyWithin(a,b,b+c)},c:function(a){a>>>=0;var b=H.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{G.grow(Math.min(2147483648,d)-K.byteLength+65535>>>16);Ba(G.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},m:function(a,
b,c,d){for(var f=0,g=0;g<c;g++){for(var l=J[b+8*g>>2],k=J[b+(8*g+4)>>2],h=0;h<k;h++){var p=H[l+h],m=Nb[a];0===p||10===p?((1===a?ka:E)(oa(m,0)),m.length=0):m.push(p)}f+=k}J[d>>2]=f;return 0},memory:G,p:function(){return 0},r:function(){return 0},q:function(){},B:function(){return 6},A:function(){},k:function(a){a=+a;return 0<=a?+Ka(a+.5):+Ja(a-.5)},e:function(a){a=+a;return 0<=a?+Ka(a+.5):+Ja(a-.5)},v:function(){},table:la};
(function(){function a(f){e.asm=f.exports;M--;e.monitorRunDependencies&&e.monitorRunDependencies(M);0==M&&(null!==La&&(clearInterval(La),La=null),N&&(f=N,N=null,f()))}function b(f){a(f.instance)}function c(f){return Qa().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){E("failed to asynchronously prepare wasm: "+g);B(g)})}var d={a:Rb};M++;e.monitorRunDependencies&&e.monitorRunDependencies(M);if(e.instantiateWasm)try{return e.instantiateWasm(d,a)}catch(f){return E("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(F||"function"!==typeof WebAssembly.instantiateStreaming||Na()||Ma("file://")||"function"!==typeof fetch)return c(b);fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,d).then(b,function(g){E("wasm streaming compile failed: "+g);E("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Ra=e.___wasm_call_ctors=function(){return(Ra=e.___wasm_call_ctors=e.asm.C).apply(null,arguments)},Qb=e._malloc=function(){return(Qb=e._malloc=e.asm.D).apply(null,arguments)},Y=e._free=function(){return(Y=e._free=e.asm.E).apply(null,arguments)},Db=e.___getTypeName=function(){return(Db=e.___getTypeName=e.asm.F).apply(null,arguments)};e.___embind_register_native_and_builtin_types=function(){return(e.___embind_register_native_and_builtin_types=e.asm.G).apply(null,arguments)};
e.dynCall_ii=function(){return(e.dynCall_ii=e.asm.H).apply(null,arguments)};e.dynCall_vi=function(){return(e.dynCall_vi=e.asm.I).apply(null,arguments)};e.dynCall_iii=function(){return(e.dynCall_iii=e.asm.J).apply(null,arguments)};e.dynCall_viii=function(){return(e.dynCall_viii=e.asm.K).apply(null,arguments)};e.dynCall_vii=function(){return(e.dynCall_vii=e.asm.L).apply(null,arguments)};e.dynCall_v=function(){return(e.dynCall_v=e.asm.M).apply(null,arguments)};
e.dynCall_viiiiiiii=function(){return(e.dynCall_viiiiiiii=e.asm.N).apply(null,arguments)};e.dynCall_viiiiiii=function(){return(e.dynCall_viiiiiii=e.asm.O).apply(null,arguments)};e.dynCall_viiiiiiiii=function(){return(e.dynCall_viiiiiiiii=e.asm.P).apply(null,arguments)};e.dynCall_viiii=function(){return(e.dynCall_viiii=e.asm.Q).apply(null,arguments)};e.dynCall_viiiiii=function(){return(e.dynCall_viiiiii=e.asm.R).apply(null,arguments)};
e.dynCall_iidiiii=function(){return(e.dynCall_iidiiii=e.asm.S).apply(null,arguments)};e.dynCall_viiiii=function(){return(e.dynCall_viiiii=e.asm.T).apply(null,arguments)};e.dynCall_iiiiii=function(){return(e.dynCall_iiiiii=e.asm.U).apply(null,arguments)};e.dynCall_iiii=function(){return(e.dynCall_iiii=e.asm.V).apply(null,arguments)};e.dynCall_iiiii=function(){return(e.dynCall_iiiii=e.asm.W).apply(null,arguments)};e.dynCall_jiji=function(){return(e.dynCall_jiji=e.asm.X).apply(null,arguments)};var Sb;
N=function Tb(){Sb||Ub();Sb||(N=Tb)};
function Ub(){function a(){if(!Sb&&(Sb=!0,e.calledRun=!0,!ma)){Da(Fa);Da(Ga);aa(e);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var b=e.postRun.shift();Ha.unshift(b)}Da(Ha)}}if(!(0<M)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ia();Da(Ea);0<M||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}
e.run=Ub;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();noExitRuntime=!0;Ub();


  return wp2_dec.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = wp2_dec;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return wp2_dec; });
    else if (typeof exports === 'object')
      exports["wp2_dec"] = wp2_dec;
    