
var wp2_dec = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(wp2_dec) {
  wp2_dec = wp2_dec || {};


var d;d||(d=typeof wp2_dec !== 'undefined' ? wp2_dec : {});var aa,ba;d.ready=new Promise(function(a,b){aa=a;ba=b});var r={},w;for(w in d)d.hasOwnProperty(w)&&(r[w]=d[w]);var ca=!1,y=!1,da=!1,ea=!1;ca="object"===typeof window;y="function"===typeof importScripts;da="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ea=!ca&&!da&&!y;var z="",ha,A,ia,ja;
if(da)z=y?require("path").dirname(z)+"/":__dirname+"/",ha=function(a,b){ia||(ia=require("fs"));ja||(ja=require("path"));a=ja.normalize(a);return ia.readFileSync(a,b?null:"utf8")},A=function(a){a=ha(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||B("Assertion failed: undefined");return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",B),d.inspect=function(){return"[Emscripten Module object]"};
else if(ea)"undefined"!=typeof read&&(ha=function(a){return read(a)}),A=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||B("Assertion failed: undefined");return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ca||y)y?z=self.location.href:document.currentScript&&(z=document.currentScript.src),_scriptDir&&
(z=_scriptDir),0!==z.indexOf("blob:")?z=z.substr(0,z.lastIndexOf("/")+1):z="",ha=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},y&&(A=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ka=d.print||console.log.bind(console),E=d.printErr||console.warn.bind(console);for(w in r)r.hasOwnProperty(w)&&(d[w]=r[w]);r=null;var F;d.wasmBinary&&(F=d.wasmBinary);var noExitRuntime;
d.noExitRuntime&&(noExitRuntime=d.noExitRuntime);"object"!==typeof WebAssembly&&B("no native wasm support detected");var G,la=new WebAssembly.Table({initial:305,maximum:305,element:"anyfunc"}),ma=!1,na="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function oa(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&na)return na.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}
function pa(a,b,c){var e=H;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;e[b++]=g}else{if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63}e[b++]=128|g>>6&63}e[b++]=128|g&63}}e[b]=0}}var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function ra(a,b){var c=a>>1;for(var e=c+b/2;!(c>=e)&&sa[c];)++c;c<<=1;if(32<c-a&&qa)return qa.decode(H.subarray(a,c));c=0;for(e="";;){var f=I[a+2*c>>1];if(0==f||c==b/2)return e;++c;e+=String.fromCharCode(f)}}function ta(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var e=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)I[b>>1]=a.charCodeAt(f),b+=2;I[b>>1]=0;return b-e}function ua(a){return 2*a.length}
function va(a,b){for(var c=0,e="";!(c>=b/4);){var f=J[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e}function wa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}J[b>>2]=g;b+=4;if(b+4>c)break}J[b>>2]=0;return b-e}
function xa(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&++c;b+=4}return b}var K,ya,H,I,sa,J,L,za,Aa;function Ba(a){K=a;d.HEAP8=ya=new Int8Array(a);d.HEAP16=I=new Int16Array(a);d.HEAP32=J=new Int32Array(a);d.HEAPU8=H=new Uint8Array(a);d.HEAPU16=sa=new Uint16Array(a);d.HEAPU32=L=new Uint32Array(a);d.HEAPF32=za=new Float32Array(a);d.HEAPF64=Aa=new Float64Array(a)}var Ca=d.INITIAL_MEMORY||16777216;
d.wasmMemory?G=d.wasmMemory:G=new WebAssembly.Memory({initial:Ca/65536,maximum:32768});G&&(K=G.buffer);Ca=K.byteLength;Ba(K);J[33292]=5376208;function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.za;"number"===typeof c?void 0===b.ra?d.dynCall_v(c):d.dynCall_vi(c,b.ra):c(void 0===b.ra?null:b.ra)}}}var Ea=[],Fa=[],Ga=[],Ha=[];function Ia(){var a=d.preRun.shift();Ea.unshift(a)}var Ja=Math.ceil,Ka=Math.floor,M=0,La=null,N=null;d.preloadedImages={};
d.preloadedAudios={};function B(a){if(d.onAbort)d.onAbort(a);E(a);ma=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Ma(a){var b=O;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Na(){return Ma("data:application/octet-stream;base64,")}var O="wp2_dec.wasm";if(!Na()){var Oa=O;O=d.locateFile?d.locateFile(Oa,z):z+Oa}
function Pa(){try{if(F)return new Uint8Array(F);if(A)return A(O);throw"both async and sync fetching of the wasm failed";}catch(a){B(a)}}function Qa(){return F||!ca&&!y||"function"!==typeof fetch||Ma("file://")?new Promise(function(a){a(Pa())}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Pa()})}Fa.push({za:function(){Ra()}});function Sa(){return 0<Sa.ma}
function Ta(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ua=void 0;function P(a){for(var b="";H[a];)b+=Ua[H[a++]];return b}var Q={},R={},Va={};function Wa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Xa(a,b){a=Wa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ya(a){var b=Error,c=Xa(a,function(e){this.name=a;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Za=void 0;function S(a){throw new Za(a);}var $a=void 0;function ab(a){throw new $a(a);}function bb(a,b,c){function e(k){k=c(k);k.length!==a.length&&ab("Mismatched type converter count");for(var h=0;h<a.length;++h)T(a[h],k[h])}a.forEach(function(k){Va[k]=b});var f=Array(b.length),g=[],l=0;b.forEach(function(k,h){R.hasOwnProperty(k)?f[h]=R[k]:(g.push(k),Q.hasOwnProperty(k)||(Q[k]=[]),Q[k].push(function(){f[h]=R[k];++l;l===g.length&&e(f)}))});0===g.length&&e(f)}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||S('type "'+e+'" must have a positive integer typeid pointer');if(R.hasOwnProperty(a)){if(c.Ca)return;S("Cannot register type '"+e+"' twice")}R[a]=b;delete Va[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(function(f){f()}))}function cb(a){return{count:a.count,la:a.la,na:a.na,aa:a.aa,da:a.da,ea:a.ea,fa:a.fa}}
function db(a){S(a.$.da.ba.name+" instance already deleted")}var eb=!1;function fb(){}function gb(a){--a.count.value;0===a.count.value&&(a.ea?a.fa.ka(a.ea):a.da.ba.ka(a.aa))}
function hb(a){if("undefined"===typeof FinalizationGroup)return hb=function(b){return b},a;eb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.aa?gb(c):console.warn("object already deleted: "+c.aa)});hb=function(b){eb.register(b,b.$,b.$);return b};fb=function(b){eb.unregister(b.$)};return hb(a)}var ib=void 0,jb=[];function kb(){for(;jb.length;){var a=jb.pop();a.$.la=!1;a["delete"]()}}function U(){}var lb={};
function mb(a,b){var c=d;if(void 0===c[a].ha){var e=c[a];c[a]=function(){c[a].ha.hasOwnProperty(arguments.length)||S("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].ha+")!");return c[a].ha[arguments.length].apply(this,arguments)};c[a].ha=[];c[a].ha[e.wa]=e}}
function nb(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].ha&&void 0!==d[a].ha[c])&&S("Cannot register public name '"+a+"' twice"),mb(a,a),d.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].ha[c]=b):(d[a]=b,void 0!==c&&(d[a].Ia=c))}function ob(a,b,c,e,f,g,l,k){this.name=a;this.constructor=b;this.ja=c;this.ka=e;this.ga=f;this.Aa=g;this.oa=l;this.ya=k}
function pb(a,b,c){for(;b!==c;)b.oa||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.oa(a),b=b.ga;return a}function qb(a,b){if(null===b)return this.sa&&S("null is not a valid "+this.name),0;b.$||S('Cannot pass "'+V(b)+'" as a '+this.name);b.$.aa||S("Cannot pass deleted object as a pointer of type "+this.name);return pb(b.$.aa,b.$.da.ba,this.ba)}
function rb(a,b){if(null===b){this.sa&&S("null is not a valid "+this.name);if(this.qa){var c=this.Ea();null!==a&&a.push(this.ka,c);return c}return 0}b.$||S('Cannot pass "'+V(b)+'" as a '+this.name);b.$.aa||S("Cannot pass deleted object as a pointer of type "+this.name);!this.pa&&b.$.da.pa&&S("Cannot convert argument of type "+(b.$.fa?b.$.fa.name:b.$.da.name)+" to parameter type "+this.name);c=pb(b.$.aa,b.$.da.ba,this.ba);if(this.qa)switch(void 0===b.$.ea&&S("Passing raw pointer to smart pointer is illegal"),
this.Ga){case 0:b.$.fa===this?c=b.$.ea:S("Cannot convert argument of type "+(b.$.fa?b.$.fa.name:b.$.da.name)+" to parameter type "+this.name);break;case 1:c=b.$.ea;break;case 2:if(b.$.fa===this)c=b.$.ea;else{var e=b.clone();c=this.Fa(c,sb(function(){e["delete"]()}));null!==a&&a.push(this.ka,c)}break;default:S("Unsupporting sharing policy")}return c}
function tb(a,b){if(null===b)return this.sa&&S("null is not a valid "+this.name),0;b.$||S('Cannot pass "'+V(b)+'" as a '+this.name);b.$.aa||S("Cannot pass deleted object as a pointer of type "+this.name);b.$.da.pa&&S("Cannot convert argument of type "+b.$.da.name+" to parameter type "+this.name);return pb(b.$.aa,b.$.da.ba,this.ba)}function vb(a){return this.fromWireType(L[a>>2])}function wb(a,b,c){if(b===c)return a;if(void 0===c.ga)return null;a=wb(a,b,c.ga);return null===a?null:c.ya(a)}var xb={};
function yb(a,b){for(void 0===b&&S("ptr should not be undefined");a.ga;)b=a.oa(b),a=a.ga;return xb[b]}function zb(a,b){b.da&&b.aa||ab("makeClassHandle requires ptr and ptrType");!!b.fa!==!!b.ea&&ab("Both smartPtrType and smartPtr must be specified");b.count={value:1};return hb(Object.create(a,{$:{value:b}}))}
function W(a,b,c,e){this.name=a;this.ba=b;this.sa=c;this.pa=e;this.qa=!1;this.ka=this.Fa=this.Ea=this.va=this.Ga=this.Da=void 0;void 0!==b.ga?this.toWireType=rb:(this.toWireType=e?qb:tb,this.ia=null)}function Ab(a,b,c){d.hasOwnProperty(a)||ab("Replacing nonexistant public symbol");void 0!==d[a].ha&&void 0!==c?d[a].ha[c]=b:(d[a]=b,d[a].wa=c)}
function X(a,b){a=P(a);var c=d["dynCall_"+a];for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function dynCall_"+(a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall","rawFunction",f+"};\n"))(c,b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Bb=void 0;function Cb(a){a=Db(a);var b=P(a);Y(a);return b}
function Eb(a,b){function c(g){f[g]||R[g]||(Va[g]?Va[g].forEach(c):(e.push(g),f[g]=!0))}var e=[],f={};b.forEach(c);throw new Bb(a+": "+e.map(Cb).join([", "]));}function Fb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Gb(a,b,c){a instanceof Object||S(c+' with invalid "this": '+a);a instanceof b.ba.constructor||S(c+' incompatible with "this" of type '+a.constructor.name);a.$.aa||S("cannot call emscripten binding method "+c+" on deleted object");return pb(a.$.aa,a.$.da.ba,b.ba)}
var Hb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Ib(a){4<a&&0===--Z[a].ta&&(Z[a]=void 0,Hb.push(a))}function sb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Hb.length?Hb.pop():Z.length;Z[b]={ta:1,value:a};return b}}function V(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Jb(a,b){switch(b){case 2:return function(c){return this.fromWireType(za[c>>2])};case 3:return function(c){return this.fromWireType(Aa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Kb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Xa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Lb(a,b){for(var c=[],e=0;e<a;e++)c.push(J[(b>>2)+e]);return c}function Mb(a,b,c){switch(b){case 0:return c?function(e){return ya[e]}:function(e){return H[e]};case 1:return c?function(e){return I[e>>1]}:function(e){return sa[e>>1]};case 2:return c?function(e){return J[e>>2]}:function(e){return L[e>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var Nb=[null,[],[]],Ob=Array(256),Pb=0;256>Pb;++Pb)Ob[Pb]=String.fromCharCode(Pb);Ua=Ob;Za=d.BindingError=Ya("BindingError");
$a=d.InternalError=Ya("InternalError");U.prototype.isAliasOf=function(a){if(!(this instanceof U&&a instanceof U))return!1;var b=this.$.da.ba,c=this.$.aa,e=a.$.da.ba;for(a=a.$.aa;b.ga;)c=b.oa(c),b=b.ga;for(;e.ga;)a=e.oa(a),e=e.ga;return b===e&&c===a};U.prototype.clone=function(){this.$.aa||db(this);if(this.$.na)return this.$.count.value+=1,this;var a=hb(Object.create(Object.getPrototypeOf(this),{$:{value:cb(this.$)}}));a.$.count.value+=1;a.$.la=!1;return a};
U.prototype["delete"]=function(){this.$.aa||db(this);this.$.la&&!this.$.na&&S("Object already scheduled for deletion");fb(this);gb(this.$);this.$.na||(this.$.ea=void 0,this.$.aa=void 0)};U.prototype.isDeleted=function(){return!this.$.aa};U.prototype.deleteLater=function(){this.$.aa||db(this);this.$.la&&!this.$.na&&S("Object already scheduled for deletion");jb.push(this);1===jb.length&&ib&&ib(kb);this.$.la=!0;return this};W.prototype.Ba=function(a){this.va&&(a=this.va(a));return a};
W.prototype.ua=function(a){this.ka&&this.ka(a)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=vb;W.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
W.prototype.fromWireType=function(a){function b(){return this.qa?zb(this.ba.ja,{da:this.Da,aa:c,fa:this,ea:a}):zb(this.ba.ja,{da:this,aa:a})}var c=this.Ba(a);if(!c)return this.ua(a),null;var e=yb(this.ba,c);if(void 0!==e){if(0===e.$.count.value)return e.$.aa=c,e.$.ea=a,e.clone();e=e.clone();this.ua(a);return e}e=this.ba.Aa(c);e=lb[e];if(!e)return b.call(this);e=this.pa?e.xa:e.pointerType;var f=wb(c,this.ba,e.ba);return null===f?b.call(this):this.qa?zb(e.ba.ja,{da:e,aa:f,fa:this,ea:a}):zb(e.ba.ja,
{da:e,aa:f})};d.getInheritedInstanceCount=function(){return Object.keys(xb).length};d.getLiveInheritedInstances=function(){var a=[],b;for(b in xb)xb.hasOwnProperty(b)&&a.push(xb[b]);return a};d.flushPendingDeletes=kb;d.setDelayFunction=function(a){ib=a;jb.length&&ib&&ib(kb)};Bb=d.UnboundTypeError=Ya("UnboundTypeError");d.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};d.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Rb={s:function(a){return Qb(a)},r:function(a){"uncaught_exception"in Sa?Sa.ma++:Sa.ma=1;throw a;},x:function(a,b,c,e,f){var g=Ta(c);b=P(b);T(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?e:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=ya;else if(2===c)k=I;else if(4===c)k=J;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>g])},ia:null})},t:function(a,b,c,e,f,g,l,k,h,p,m,q,t){m=P(m);g=X(f,g);k&&(k=X(l,
k));p&&(p=X(h,p));t=X(q,t);var u=Wa(m);nb(u,function(){Eb("Cannot construct "+m+" due to unbound types",[e])});bb([a,b,c],e?[e]:[],function(n){n=n[0];if(e){var D=n.ba;var v=D.ja}else v=U.prototype;n=Xa(u,function(){if(Object.getPrototypeOf(this)!==x)throw new Za("Use 'new' to construct "+m);if(void 0===C.ma)throw new Za(m+" has no accessible constructor");var ub=C.ma[arguments.length];if(void 0===ub)throw new Za("Tried to invoke ctor of "+m+" with invalid number of parameters ("+arguments.length+
") - expected ("+Object.keys(C.ma).toString()+") parameters instead!");return ub.apply(this,arguments)});var x=Object.create(v,{constructor:{value:n}});n.prototype=x;var C=new ob(m,n,x,t,D,g,k,p);D=new W(m,C,!0,!1);v=new W(m+"*",C,!1,!1);var fa=new W(m+" const*",C,!1,!0);lb[a]={pointerType:v,xa:fa};Ab(u,n);return[D,v,fa]})},e:function(a,b,c,e,f,g,l,k,h,p){b=P(b);f=X(e,f);bb([],[a],function(m){m=m[0];var q=m.name+"."+b,t={get:function(){Eb("Cannot access "+q+" due to unbound types",[c,l])},enumerable:!0,
configurable:!0};h?t.set=function(){Eb("Cannot access "+q+" due to unbound types",[c,l])}:t.set=function(){S(q+" is a read-only property")};Object.defineProperty(m.ba.ja,b,t);bb([],h?[c,l]:[c],function(u){var n=u[0],D={get:function(){var x=Gb(this,m,q+" getter");return n.fromWireType(f(g,x))},enumerable:!0};if(h){h=X(k,h);var v=u[1];D.set=function(x){var C=Gb(this,m,q+" setter"),fa=[];h(p,C,v.toWireType(fa,x));Fb(fa)}}Object.defineProperty(m.ba.ja,b,D);return[]});return[]})},w:function(a,b){b=P(b);
T(a,{name:b,fromWireType:function(c){var e=Z[c].value;Ib(c);return e},toWireType:function(c,e){return sb(e)},argPackAdvance:8,readValueFromPointer:vb,ia:null})},l:function(a,b,c){c=Ta(c);b=P(b);T(a,{name:b,fromWireType:function(e){return e},toWireType:function(e,f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+V(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:Jb(b,c),ia:null})},g:function(a,b,c,e,f,g){var l=Lb(b,c);a=P(a);f=X(e,f);nb(a,function(){Eb("Cannot call "+
a+" due to unbound types",l)},b-1);bb([],l,function(k){var h=[k[0],null].concat(k.slice(1)),p=k=a,m=f,q=h.length;2>q&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var t=null!==h[1]&&!1,u=!1,n=1;n<h.length;++n)if(null!==h[n]&&void 0===h[n].ia){u=!0;break}var D="void"!==h[0].name,v="",x="";for(n=0;n<q-2;++n)v+=(0!==n?", ":"")+"arg"+n,x+=(0!==n?", ":"")+"arg"+n+"Wired";p="return function "+Wa(p)+"("+v+") {\nif (arguments.length !== "+(q-2)+") {\nthrowBindingError('function "+
p+" called with ' + arguments.length + ' arguments, expected "+(q-2)+" args!');\n}\n";u&&(p+="var destructors = [];\n");var C=u?"destructors":"null";v="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[S,m,g,Fb,h[0],h[1]];t&&(p+="var thisWired = classParam.toWireType("+C+", this);\n");for(n=0;n<q-2;++n)p+="var arg"+n+"Wired = argType"+n+".toWireType("+C+", arg"+n+"); // "+h[n+2].name+"\n",v.push("argType"+n),m.push(h[n+2]);t&&(x="thisWired"+(0<x.length?", ":"")+x);p+=(D?
"var rv = ":"")+"invoker(fn"+(0<x.length?", ":"")+x+");\n";if(u)p+="runDestructors(destructors);\n";else for(n=t?1:2;n<h.length;++n)q=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==h[n].ia&&(p+=q+"_dtor("+q+"); // "+h[n].name+"\n",v.push(q+"_dtor"),m.push(h[n].ia));D&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");v.push(p+"}\n");h=Kb(v).apply(null,m);Ab(k,h,b-1);return[]})},b:function(a,b,c,e,f){function g(p){return p}b=P(b);-1===f&&(f=4294967295);var l=Ta(c);if(0===e){var k=32-8*c;g=function(p){return p<<
k>>>k}}var h=-1!=b.indexOf("unsigned");T(a,{name:b,fromWireType:g,toWireType:function(p,m){if("number"!==typeof m&&"boolean"!==typeof m)throw new TypeError('Cannot convert "'+V(m)+'" to '+this.name);if(m<e||m>f)throw new TypeError('Passing a number "'+V(m)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return h?m>>>0:m|0},argPackAdvance:8,readValueFromPointer:Mb(b,l,0!==e),ia:null})},a:function(a,b,c){function e(g){g>>=2;var l=L;return new f(K,
l[g+1],l[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);T(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{Ca:!0})},m:function(a,b){b=P(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(e){var f=L[e>>2];if(c)for(var g=e+4,l=0;l<=f;++l){var k=e+4+l;if(l==f||0==H[k]){g=g?oa(H,g,k-g):"";if(void 0===h)var h=g;else h+=String.fromCharCode(0),h+=g;g=k+1}}else{h=Array(f);for(l=0;l<f;++l)h[l]=String.fromCharCode(H[e+
4+l]);h=h.join("")}Y(e);return h},toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||S("Cannot pass non-string to std::string");var l=(c&&g?function(){for(var p=0,m=0;m<f.length;++m){var q=f.charCodeAt(m);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|f.charCodeAt(++m)&1023);127>=q?++p:p=2047>=q?p+2:65535>=q?p+3:p+4}return p}:function(){return f.length})(),k=Qb(4+l+1);L[k>>
2]=l;if(c&&g)pa(f,k+4,l+1);else if(g)for(g=0;g<l;++g){var h=f.charCodeAt(g);255<h&&(Y(k),S("String has UTF-16 code units that do not fit in 8 bits"));H[k+4+g]=h}else for(g=0;g<l;++g)H[k+4+g]=f[g];null!==e&&e.push(Y,k);return k},argPackAdvance:8,readValueFromPointer:vb,ia:function(e){Y(e)}})},f:function(a,b,c){c=P(c);if(2===b){var e=ra;var f=ta;var g=ua;var l=function(){return sa};var k=1}else 4===b&&(e=va,f=wa,g=xa,l=function(){return L},k=2);T(a,{name:c,fromWireType:function(h){for(var p=L[h>>2],
m=l(),q,t=h+4,u=0;u<=p;++u){var n=h+4+u*b;if(u==p||0==m[n>>k])t=e(t,n-t),void 0===q?q=t:(q+=String.fromCharCode(0),q+=t),t=n+b}Y(h);return q},toWireType:function(h,p){"string"!==typeof p&&S("Cannot pass non-string to C++ string type "+c);var m=g(p),q=Qb(4+m+b);L[q>>2]=m>>k;f(p,q+4,m+b);null!==h&&h.push(Y,q);return q},argPackAdvance:8,readValueFromPointer:vb,ia:function(h){Y(h)}})},y:function(a,b){b=P(b);T(a,{Ha:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},k:Ib,B:function(a){4<
a&&(Z[a].ta+=1)},o:function(a,b){var c=R[a];void 0===c&&S("_emval_take_value has unknown type "+Cb(a));a=c.readValueFromPointer(b);return sb(a)},i:function(){B()},v:function(a,b,c){H.copyWithin(a,b,b+c)},c:function(a){a>>>=0;var b=H.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(16777216,a,e);0<e%65536&&(e+=65536-e%65536);a:{try{G.grow(Math.min(2147483648,e)-K.byteLength+65535>>>16);Ba(G.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},
j:function(a,b,c,e){for(var f=0,g=0;g<c;g++){for(var l=J[b+8*g>>2],k=J[b+(8*g+4)>>2],h=0;h<k;h++){var p=H[l+h],m=Nb[a];0===p||10===p?((1===a?ka:E)(oa(m,0)),m.length=0):m.push(p)}f+=k}J[e>>2]=f;return 0},memory:G,n:function(){return 0},q:function(){return 0},p:function(){},A:function(){return 6},z:function(){},h:function(a){a=+a;return 0<=a?+Ka(a+.5):+Ja(a-.5)},d:function(a){a=+a;return 0<=a?+Ka(a+.5):+Ja(a-.5)},u:function(){},table:la};
(function(){function a(f){d.asm=f.exports;M--;d.monitorRunDependencies&&d.monitorRunDependencies(M);0==M&&(null!==La&&(clearInterval(La),La=null),N&&(f=N,N=null,f()))}function b(f){a(f.instance)}function c(f){return Qa().then(function(g){return WebAssembly.instantiate(g,e)}).then(f,function(g){E("failed to asynchronously prepare wasm: "+g);B(g)})}var e={a:Rb};M++;d.monitorRunDependencies&&d.monitorRunDependencies(M);if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return E("Module.instantiateWasm callback failed with error: "+
f),!1}(function(){if(F||"function"!==typeof WebAssembly.instantiateStreaming||Na()||Ma("file://")||"function"!==typeof fetch)return c(b);fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(g){E("wasm streaming compile failed: "+g);E("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
var Ra=d.___wasm_call_ctors=function(){return(Ra=d.___wasm_call_ctors=d.asm.C).apply(null,arguments)},Qb=d._malloc=function(){return(Qb=d._malloc=d.asm.D).apply(null,arguments)},Y=d._free=function(){return(Y=d._free=d.asm.E).apply(null,arguments)},Db=d.___getTypeName=function(){return(Db=d.___getTypeName=d.asm.F).apply(null,arguments)};d.___embind_register_native_and_builtin_types=function(){return(d.___embind_register_native_and_builtin_types=d.asm.G).apply(null,arguments)};
d.dynCall_ii=function(){return(d.dynCall_ii=d.asm.H).apply(null,arguments)};d.dynCall_vi=function(){return(d.dynCall_vi=d.asm.I).apply(null,arguments)};d.dynCall_iii=function(){return(d.dynCall_iii=d.asm.J).apply(null,arguments)};d.dynCall_viii=function(){return(d.dynCall_viii=d.asm.K).apply(null,arguments)};d.dynCall_vii=function(){return(d.dynCall_vii=d.asm.L).apply(null,arguments)};d.dynCall_v=function(){return(d.dynCall_v=d.asm.M).apply(null,arguments)};
d.dynCall_viiiiiii=function(){return(d.dynCall_viiiiiii=d.asm.N).apply(null,arguments)};d.dynCall_viiiiiiiii=function(){return(d.dynCall_viiiiiiiii=d.asm.O).apply(null,arguments)};d.dynCall_viiiiiiii=function(){return(d.dynCall_viiiiiiii=d.asm.P).apply(null,arguments)};d.dynCall_viiii=function(){return(d.dynCall_viiii=d.asm.Q).apply(null,arguments)};d.dynCall_viiiiii=function(){return(d.dynCall_viiiiii=d.asm.R).apply(null,arguments)};
d.dynCall_iidiiii=function(){return(d.dynCall_iidiiii=d.asm.S).apply(null,arguments)};d.dynCall_iiiii=function(){return(d.dynCall_iiiii=d.asm.T).apply(null,arguments)};d.dynCall_iiiiii=function(){return(d.dynCall_iiiiii=d.asm.U).apply(null,arguments)};d.dynCall_fi=function(){return(d.dynCall_fi=d.asm.V).apply(null,arguments)};d.dynCall_fii=function(){return(d.dynCall_fii=d.asm.W).apply(null,arguments)};d.dynCall_viiiii=function(){return(d.dynCall_viiiii=d.asm.X).apply(null,arguments)};
d.dynCall_iiii=function(){return(d.dynCall_iiii=d.asm.Y).apply(null,arguments)};d.dynCall_jiji=function(){return(d.dynCall_jiji=d.asm.Z).apply(null,arguments)};var Sb;N=function Tb(){Sb||Ub();Sb||(N=Tb)};
function Ub(){function a(){if(!Sb&&(Sb=!0,d.calledRun=!0,!ma)){Da(Fa);Da(Ga);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();Ha.unshift(b)}Da(Ha)}}if(!(0<M)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)Ia();Da(Ea);0<M||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}
d.run=Ub;if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();noExitRuntime=!0;Ub();


  return wp2_dec.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = wp2_dec;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return wp2_dec; });
    else if (typeof exports === 'object')
      exports["wp2_dec"] = wp2_dec;
    