name: 'Bug report'
title: "[BUG] - YOUR_ISSUE_TITLE_HERE_REPLACE_ME"
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue :pray:.

        This issue tracker is for reporting bugs found in [Squoosh github repository](https://github.com/GoogleChromeLabs/squoosh)
        If you have a question about how to achieve something and are struggling, please post a question
        inside Squoosh's [Discussion's tab](https://github.com/GoogleChromeLabs/squooshdiscussions)

        Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
         - Squoosh's [Issue's tab](https://github.com/GoogleChromeLabs/squooshpulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)
         - Squoosh's [closed issues tab](https://github.com/GoogleChromeLabs/squooshissues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
         - Squoosh's [Discussions tab](https://github.com/GoogleChromeLabs/squooshdiscussions)

        Lastly please our short Wiki document of Frequently Asked Questions (FAQ), as it may help answer your questions:
          - https://github.com/GoogleChromeLabs/squoosh/wiki/FAQ

        The more information you fill in, the better the community can help you.
  - type: dropdown
    id: squoosh_app_type
    attributes:
      label: Squoosh App Type (squoosh.app or squoosh CLI)
      description: Are you experiencing a bug with our web application (https://squoosh.app/) or with Squoosh CLI (https://github.com/GoogleChromeLabs/squoosh/tree/dev/cli)?
      options:
        - Squoosh Web app
        - Squoosh CLI
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the challenge you are running into.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Bug or Issue
      description: Describe the steps we have to take to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.
      placeholder: |
        As a user, I expected ___ behavior but i am seeing ___
    validations:
      required: true
  - type: dropdown
    id: operating_system_version
    attributes:
      label: Operating System
      description: Select the Operating System you are used while experiencing the issue
      options:
        - "MacOS"
        - "Windows"
        - "iOS (mobile)"
        - "Android (mobile)"
        - "Other (add additonal context)"
    validations:
      required: true
  - type: dropdown
    id: browser_type
    attributes:
      label: Browser
      description: Select the browsers where the issue can be reproduced (that you know of).
      options:
        - "Chrome"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "Opera"
        - "Other (add additonal context)"
    validations:
      required: true
  - type: input
    id: nodejs_version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using? (_type `node --version` in your terminal_)
      placeholder: Your Node.js Version
    validations:
      required: false
  - type: textarea
      id: screenshots_or_videos
      attributes:
        label: Screenshots or Videos
        description: |
          If applicable, add screenshots or a video to help explain your problem.
          For more information on the supported file image/file types and the file size limits, please refer
          to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
        placeholder: |
          You can drag your video or image files inside of this editor ↓
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.