
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var t={},w;for(w in g)g.hasOwnProperty(w)&&(t[w]=g[w]);var ca="./this.program",y="",da;y=self.location.href;_scriptDir&&(y=_scriptDir);0!==y.indexOf("blob:")?y=y.substr(0,y.lastIndexOf("/")+1):y="";da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};
var ea=g.print||console.log.bind(console),z=g.printErr||console.warn.bind(console);for(w in t)t.hasOwnProperty(w)&&(g[w]=t[w]);t=null;g.thisProgram&&(ca=g.thisProgram);var A;g.wasmBinary&&(A=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&C("no native wasm support detected");var fa,ha=!1,ia=new TextDecoder("utf8");function ja(a,b){if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&D[c];)++c;return ia.decode(D.subarray(a,c))}
function ka(a,b,c,d){if(0<d){d=c+d-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var m=a.charCodeAt(++h);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0}}
function la(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var ma=new TextDecoder("utf-16le");function na(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&E[c];)++c;return ma.decode(D.subarray(a,c<<1))}function oa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var h=0;h<c;++h)F[b>>1]=a.charCodeAt(h),b+=2;F[b>>1]=0;return b-d}
function pa(a){return 2*a.length}function qa(a,b){for(var c=0,d="";!(c>=b/4);){var h=G[a+4*c>>2];if(0==h)break;++c;65536<=h?(h-=65536,d+=String.fromCharCode(55296|h>>10,56320|h&1023)):d+=String.fromCharCode(h)}return d}function ra(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var m=a.charCodeAt(++h);f=65536+((f&1023)<<10)|m&1023}G[b>>2]=f;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ta,H,D,F,E,G,I,ua,va;function wa(){var a=fa.buffer;ta=a;g.HEAP8=H=new Int8Array(a);g.HEAP16=F=new Int16Array(a);g.HEAP32=G=new Int32Array(a);g.HEAPU8=D=new Uint8Array(a);g.HEAPU16=E=new Uint16Array(a);g.HEAPU32=I=new Uint32Array(a);g.HEAPF32=ua=new Float32Array(a);g.HEAPF64=va=new Float64Array(a)}var J,xa=[],ya=[],za=[];function Aa(){var a=g.preRun.shift();xa.unshift(a)}
var K=0,Ba=null,L=null;g.preloadedImages={};g.preloadedAudios={};function C(a){if(g.onAbort)g.onAbort(a);z(a);ha=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}var M=(new URL("jxl_enc.wasm",import.meta.url)).toString();function Ca(){try{if(M==M&&A)return new Uint8Array(A);if(da)return da(M);throw"both async and sync fetching of the wasm failed";}catch(a){C(a)}}
function Da(){return A||"function"!==typeof fetch?Promise.resolve().then(function(){return Ca()}):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ca()})}function Ea(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.xa;"number"===typeof c?void 0===b.$?J.get(c)():J.get(c)(b.$):c(void 0===b.$?null:b.$)}}}
function Fa(a){this.V=a-16;this.pa=function(b){G[this.V+8>>2]=b};this.ma=function(b){G[this.V+0>>2]=b};this.na=function(){G[this.V+4>>2]=0};this.la=function(){H[this.V+12>>0]=0};this.oa=function(){H[this.V+13>>0]=0};this.ia=function(b,c){this.pa(b);this.ma(c);this.na();this.la();this.oa()}}var Ga=0,N={};function Ha(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function O(a){return this.fromWireType(I[a>>2])}var P={},Q={},R={};
function Ia(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ja(a,b){a=Ia(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Ka(a){var b=Error,c=Ja(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var La=void 0;
function Ma(a,b,c){function d(k){k=c(k);if(k.length!==a.length)throw new La("Mismatched type converter count");for(var n=0;n<a.length;++n)S(a[n],k[n])}a.forEach(function(k){R[k]=b});var h=Array(b.length),f=[],m=0;b.forEach(function(k,n){Q.hasOwnProperty(k)?h[n]=Q[k]:(f.push(k),P.hasOwnProperty(k)||(P[k]=[]),P[k].push(function(){h[n]=Q[k];++m;m===f.length&&d(h)}))});0===f.length&&d(h)}
function Na(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Oa=void 0;function U(a){for(var b="";D[a];)b+=Oa[D[a++]];return b}var Pa=void 0;function V(a){throw new Pa(a);}
function S(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(Q.hasOwnProperty(a)){if(c.ha)return;V("Cannot register type '"+d+"' twice")}Q[a]=b;delete R[a];P.hasOwnProperty(a)&&(b=P[a],delete P[a],b.forEach(function(h){h()}))}var Qa=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Ra(a){4<a&&0===--W[a].aa&&(W[a]=void 0,Qa.push(a))}function X(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Qa.length?Qa.pop():W.length;W[b]={aa:1,value:a};return b}}function Sa(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Ta(a,b){switch(b){case 2:return function(c){return this.fromWireType(ua[c>>2])};case 3:return function(c){return this.fromWireType(va[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}function Ua(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ja(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Va(a,b){var c=g;if(void 0===c[a].S){var d=c[a];c[a]=function(){c[a].S.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].S+")!");return c[a].S[arguments.length].apply(this,arguments)};c[a].S=[];c[a].S[d.ca]=d}}
function Wa(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].S&&void 0!==g[a].S[c])&&V("Cannot register public name '"+a+"' twice"),Va(a,a),g.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].S[c]=b):(g[a]=b,void 0!==c&&(g[a].za=c))}function Xa(a,b){for(var c=[],d=0;d<a;d++)c.push(G[(b>>2)+d]);return c}
function Ya(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=J.get(b).apply(null,c);return d}}function Y(a,b){a=U(a);var c=a.includes("j")?Ya(a,b):J.get(b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var Za=void 0;function $a(a){a=ab(a);var b=U(a);Z(a);return b}
function bb(a,b){function c(f){h[f]||Q[f]||(R[f]?R[f].forEach(c):(d.push(f),h[f]=!0))}var d=[],h={};b.forEach(c);throw new Za(a+": "+d.map($a).join([", "]));}function cb(a,b,c){switch(b){case 0:return c?function(d){return H[d]}:function(d){return D[d]};case 1:return c?function(d){return F[d>>1]}:function(d){return E[d>>1]};case 2:return c?function(d){return G[d>>2]}:function(d){return I[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var db={};
function eb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function fb(a,b){var c=Q[a];void 0===c&&V(b+" has unknown type "+$a(a));return c}var gb={},hb={};function ib(){if(!jb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in hb)a[b]=hb[b];var c=[];for(b in a)c.push(b+"="+a[b]);jb=c}return jb}
var jb,kb=[null,[],[]];function lb(a){return 0===a%4&&(0!==a%100||0===a%400)}function mb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var nb=[31,29,31,30,31,30,31,31,30,31,30,31],ob=[31,28,31,30,31,30,31,31,30,31,30,31];function pb(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(lb(a.getFullYear())?nb:ob)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function qb(a,b,c,d){function h(e,l,u){for(e="number"===typeof e?e.toString():e||"";e.length<l;)e=u[0]+e;return e}function f(e,l){return h(e,l,"0")}function m(e,l){function u(B){return 0>B?-1:0<B?1:0}var v;0===(v=u(e.getFullYear()-l.getFullYear()))&&0===(v=u(e.getMonth()-l.getMonth()))&&(v=u(e.getDate()-l.getDate()));return v}function k(e){switch(e.getDay()){case 0:return new Date(e.getFullYear()-1,11,29);case 1:return e;case 2:return new Date(e.getFullYear(),0,3);case 3:return new Date(e.getFullYear(),
0,2);case 4:return new Date(e.getFullYear(),0,1);case 5:return new Date(e.getFullYear()-1,11,31);case 6:return new Date(e.getFullYear()-1,11,30)}}function n(e){e=pb(new Date(e.R+1900,0,1),e.Z);var l=new Date(e.getFullYear()+1,0,4),u=k(new Date(e.getFullYear(),0,4));l=k(l);return 0>=m(u,e)?0>=m(l,e)?e.getFullYear()+1:e.getFullYear():e.getFullYear()-1}var p=G[d+40>>2];d={va:G[d>>2],ua:G[d+4>>2],X:G[d+8>>2],W:G[d+12>>2],U:G[d+16>>2],R:G[d+20>>2],Y:G[d+24>>2],Z:G[d+28>>2],Aa:G[d+32>>2],ta:G[d+36>>2],
wa:p?ja(p):""};c=ja(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in p)c=c.replace(new RegExp(q,"g"),p[q]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
x="January February March April May June July August September October November December".split(" ");p={"%a":function(e){return r[e.Y].substring(0,3)},"%A":function(e){return r[e.Y]},"%b":function(e){return x[e.U].substring(0,3)},"%B":function(e){return x[e.U]},"%C":function(e){return f((e.R+1900)/100|0,2)},"%d":function(e){return f(e.W,2)},"%e":function(e){return h(e.W,2," ")},"%g":function(e){return n(e).toString().substring(2)},"%G":function(e){return n(e)},"%H":function(e){return f(e.X,2)},"%I":function(e){e=
e.X;0==e?e=12:12<e&&(e-=12);return f(e,2)},"%j":function(e){return f(e.W+mb(lb(e.R+1900)?nb:ob,e.U-1),3)},"%m":function(e){return f(e.U+1,2)},"%M":function(e){return f(e.ua,2)},"%n":function(){return"\n"},"%p":function(e){return 0<=e.X&&12>e.X?"AM":"PM"},"%S":function(e){return f(e.va,2)},"%t":function(){return"\t"},"%u":function(e){return e.Y||7},"%U":function(e){var l=new Date(e.R+1900,0,1),u=0===l.getDay()?l:pb(l,7-l.getDay());e=new Date(e.R+1900,e.U,e.W);return 0>m(u,e)?f(Math.ceil((31-u.getDate()+
(mb(lb(e.getFullYear())?nb:ob,e.getMonth()-1)-31)+e.getDate())/7),2):0===m(u,l)?"01":"00"},"%V":function(e){var l=new Date(e.R+1901,0,4),u=k(new Date(e.R+1900,0,4));l=k(l);var v=pb(new Date(e.R+1900,0,1),e.Z);return 0>m(v,u)?"53":0>=m(l,v)?"01":f(Math.ceil((u.getFullYear()<e.R+1900?e.Z+32-u.getDate():e.Z+1-u.getDate())/7),2)},"%w":function(e){return e.Y},"%W":function(e){var l=new Date(e.R,0,1),u=1===l.getDay()?l:pb(l,0===l.getDay()?1:7-l.getDay()+1);e=new Date(e.R+1900,e.U,e.W);return 0>m(u,e)?f(Math.ceil((31-
u.getDate()+(mb(lb(e.getFullYear())?nb:ob,e.getMonth()-1)-31)+e.getDate())/7),2):0===m(u,l)?"01":"00"},"%y":function(e){return(e.R+1900).toString().substring(2)},"%Y":function(e){return e.R+1900},"%z":function(e){e=e.ta;var l=0<=e;e=Math.abs(e)/60;return(l?"+":"-")+String("0000"+(e/60*100+e%60)).slice(-4)},"%Z":function(e){return e.wa},"%%":function(){return"%"}};for(q in p)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),p[q](d)));q=rb(c);if(q.length>b)return 0;H.set(q,a);return q.length-1}
La=g.InternalError=Ka("InternalError");for(var sb=Array(256),tb=0;256>tb;++tb)sb[tb]=String.fromCharCode(tb);Oa=sb;Pa=g.BindingError=Ka("BindingError");g.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};Za=g.UnboundTypeError=Ka("UnboundTypeError");function rb(a){var b=Array(la(a)+1);ka(a,b,0,b.length);return b}
var vb={o:function(a){return ub(a+16)+16},D:function(){},n:function(a,b,c){(new Fa(a)).ia(b,c);Ga++;throw a;},k:function(a){var b=N[a];delete N[a];var c=b.ja,d=b.ka,h=b.ba,f=h.map(function(m){return m.ga}).concat(h.map(function(m){return m.ra}));Ma([a],f,function(m){var k={};h.forEach(function(n,p){var q=m[p],r=n.ea,x=n.fa,e=m[p+h.length],l=n.qa,u=n.sa;k[n.da]={read:function(v){return q.fromWireType(r(x,v))},write:function(v,B){var T=[];l(u,v,e.toWireType(T,B));Ha(T)}}});return[{name:b.name,fromWireType:function(n){var p=
{},q;for(q in k)p[q]=k[q].read(n);d(n);return p},toWireType:function(n,p){for(var q in k)if(!(q in p))throw new TypeError('Missing field:  "'+q+'"');var r=c();for(q in k)k[q].write(r,p[q]);null!==n&&n.push(d,r);return r},argPackAdvance:8,readValueFromPointer:O,T:d}]})},q:function(){},z:function(a,b,c,d,h){var f=Na(c);b=U(b);S(a,{name:b,fromWireType:function(m){return!!m},toWireType:function(m,k){return k?d:h},argPackAdvance:8,readValueFromPointer:function(m){if(1===c)var k=H;else if(2===c)k=F;else if(4===
c)k=G;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[m>>f])},T:null})},y:function(a,b){b=U(b);S(a,{name:b,fromWireType:function(c){var d=W[c].value;Ra(c);return d},toWireType:function(c,d){return X(d)},argPackAdvance:8,readValueFromPointer:O,T:null})},h:function(a,b,c){c=Na(c);b=U(b);S(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,h){if("number"!==typeof h&&"boolean"!==typeof h)throw new TypeError('Cannot convert "'+Sa(h)+'" to '+this.name);
return h},argPackAdvance:8,readValueFromPointer:Ta(b,c),T:null})},j:function(a,b,c,d,h,f){var m=Xa(b,c);a=U(a);h=Y(d,h);Wa(a,function(){bb("Cannot call "+a+" due to unbound types",m)},b-1);Ma([],m,function(k){var n=a,p=a;k=[k[0],null].concat(k.slice(1));var q=h,r=k.length;2>r&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var x=null!==k[1]&&!1,e=!1,l=1;l<k.length;++l)if(null!==k[l]&&void 0===k[l].T){e=!0;break}var u="void"!==k[0].name,v="",B="";for(l=0;l<
r-2;++l)v+=(0!==l?", ":"")+"arg"+l,B+=(0!==l?", ":"")+"arg"+l+"Wired";p="return function "+Ia(p)+"("+v+") {\nif (arguments.length !== "+(r-2)+") {\nthrowBindingError('function "+p+" called with ' + arguments.length + ' arguments, expected "+(r-2)+" args!');\n}\n";e&&(p+="var destructors = [];\n");var T=e?"destructors":"null";v="throwBindingError invoker fn runDestructors retType classParam".split(" ");q=[V,q,f,Ha,k[0],k[1]];x&&(p+="var thisWired = classParam.toWireType("+T+", this);\n");for(l=0;l<
r-2;++l)p+="var arg"+l+"Wired = argType"+l+".toWireType("+T+", arg"+l+"); // "+k[l+2].name+"\n",v.push("argType"+l),q.push(k[l+2]);x&&(B="thisWired"+(0<B.length?", ":"")+B);p+=(u?"var rv = ":"")+"invoker(fn"+(0<B.length?", ":"")+B+");\n";if(e)p+="runDestructors(destructors);\n";else for(l=x?1:2;l<k.length;++l)r=1===l?"thisWired":"arg"+(l-2)+"Wired",null!==k[l].T&&(p+=r+"_dtor("+r+"); // "+k[l].name+"\n",v.push(r+"_dtor"),q.push(k[l].T));u&&(p+="var ret = retType.fromWireType(rv);\nreturn ret;\n");
v.push(p+"}\n");k=Ua(v).apply(null,q);l=b-1;if(!g.hasOwnProperty(n))throw new La("Replacing nonexistant public symbol");void 0!==g[n].S&&void 0!==l?g[n].S[l]=k:(g[n]=k,g[n].ca=l);return[]})},c:function(a,b,c,d,h){function f(p){return p}b=U(b);-1===h&&(h=4294967295);var m=Na(c);if(0===d){var k=32-8*c;f=function(p){return p<<k>>>k}}var n=b.includes("unsigned");S(a,{name:b,fromWireType:f,toWireType:function(p,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Sa(q)+
'" to '+this.name);if(q<d||q>h)throw new TypeError('Passing a number "'+Sa(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+h+"]!");return n?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:cb(b,m,0!==d),T:null})},b:function(a,b,c){function d(f){f>>=2;var m=I;return new h(ta,m[f+1],m[f])}var h=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=U(c);S(a,{name:c,fromWireType:d,argPackAdvance:8,
readValueFromPointer:d},{ha:!0})},i:function(a,b){b=U(b);var c="std::string"===b;S(a,{name:b,fromWireType:function(d){var h=I[d>>2];if(c)for(var f=d+4,m=0;m<=h;++m){var k=d+4+m;if(m==h||0==D[k]){f=ja(f,k-f);if(void 0===n)var n=f;else n+=String.fromCharCode(0),n+=f;f=k+1}}else{n=Array(h);for(m=0;m<h;++m)n[m]=String.fromCharCode(D[d+4+m]);n=n.join("")}Z(d);return n},toWireType:function(d,h){h instanceof ArrayBuffer&&(h=new Uint8Array(h));var f="string"===typeof h;f||h instanceof Uint8Array||h instanceof
Uint8ClampedArray||h instanceof Int8Array||V("Cannot pass non-string to std::string");var m=(c&&f?function(){return la(h)}:function(){return h.length})(),k=ub(4+m+1);I[k>>2]=m;if(c&&f)ka(h,D,k+4,m+1);else if(f)for(f=0;f<m;++f){var n=h.charCodeAt(f);255<n&&(Z(k),V("String has UTF-16 code units that do not fit in 8 bits"));D[k+4+f]=n}else for(f=0;f<m;++f)D[k+4+f]=h[f];null!==d&&d.push(Z,k);return k},argPackAdvance:8,readValueFromPointer:O,T:function(d){Z(d)}})},g:function(a,b,c){c=U(c);if(2===b){var d=
na;var h=oa;var f=pa;var m=function(){return E};var k=1}else 4===b&&(d=qa,h=ra,f=sa,m=function(){return I},k=2);S(a,{name:c,fromWireType:function(n){for(var p=I[n>>2],q=m(),r,x=n+4,e=0;e<=p;++e){var l=n+4+e*b;if(e==p||0==q[l>>k])x=d(x,l-x),void 0===r?r=x:(r+=String.fromCharCode(0),r+=x),x=l+b}Z(n);return r},toWireType:function(n,p){"string"!==typeof p&&V("Cannot pass non-string to C++ string type "+c);var q=f(p),r=ub(4+q+b);I[r>>2]=q>>k;h(p,r+4,q+b);null!==n&&n.push(Z,r);return r},argPackAdvance:8,
readValueFromPointer:O,T:function(n){Z(n)}})},l:function(a,b,c,d,h,f){N[a]={name:U(b),ja:Y(c,d),ka:Y(h,f),ba:[]}},d:function(a,b,c,d,h,f,m,k,n,p){N[a].ba.push({da:U(b),ga:c,ea:Y(d,h),fa:f,ra:m,qa:Y(k,n),sa:p})},A:function(a,b){b=U(b);S(a,{ya:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},e:Ra,C:function(a){if(0===a)return X(eb());var b=db[a];a=void 0===b?U(a):b;return X(eb()[a])},B:function(a){4<a&&(W[a].aa+=1)},m:function(a,b,c,d){a||V("Cannot use deleted val. handle = "+
a);a=W[a].value;var h=gb[b];if(!h){h="";for(var f=0;f<b;++f)h+=(0!==f?", ":"")+"arg"+f;var m="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)m+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";h=(new Function("requireRegisteredType","Module","__emval_register",m+("var obj = new constructor("+h+");\nreturn __emval_register(obj);\n}\n")))(fb,
g,X);gb[b]=h}return h(a,c,d)},a:function(){C()},s:function(a,b,c){D.copyWithin(a,b,b+c)},f:function(a){var b=D.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{fa.grow(Math.min(2147483648,d)-ta.byteLength+65535>>>16);wa();var h=1;break a}catch(f){}h=void 0}if(h)return!0}return!1},u:function(a,b){var c=0;ib().forEach(function(d,h){var f=b+c;h=G[a+4*h>>2]=f;for(f=0;f<d.length;++f)H[h++>>0]=d.charCodeAt(f);
H[h>>0]=0;c+=d.length+1});return 0},v:function(a,b){var c=ib();G[a>>2]=c.length;var d=0;c.forEach(function(h){d+=h.length+1});G[b>>2]=d;return 0},x:function(){return 0},p:function(){},w:function(a,b,c,d){for(var h=0,f=0;f<c;f++){for(var m=G[b+8*f>>2],k=G[b+(8*f+4)>>2],n=0;n<k;n++){var p=D[m+n],q=kb[a];if(0===p||10===p){for(p=0;q[p]&&!(NaN<=p);)++p;p=ia.decode(q.subarray?q.subarray(0,p):new Uint8Array(q.slice(0,p)));(1===a?ea:z)(p);q.length=0}else q.push(p)}h+=k}G[d>>2]=h;return 0},r:function(){},
t:function(a,b,c,d){return qb(a,b,c,d)}};
(function(){function a(h){g.asm=h.exports;fa=g.asm.E;wa();J=g.asm.K;ya.unshift(g.asm.F);K--;g.monitorRunDependencies&&g.monitorRunDependencies(K);0==K&&(null!==Ba&&(clearInterval(Ba),Ba=null),L&&(h=L,L=null,h()))}function b(h){a(h.instance)}function c(h){return Da().then(function(f){return WebAssembly.instantiate(f,d)}).then(h,function(f){z("failed to asynchronously prepare wasm: "+f);C(f)})}var d={a:vb};K++;g.monitorRunDependencies&&g.monitorRunDependencies(K);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(h){return z("Module.instantiateWasm callback failed with error: "+h),!1}(function(){return A||"function"!==typeof WebAssembly.instantiateStreaming||M.startsWith("data:application/octet-stream;base64,")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,d).then(b,function(f){z("wasm streaming compile failed: "+f);z("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.F).apply(null,arguments)};var ub=g._malloc=function(){return(ub=g._malloc=g.asm.G).apply(null,arguments)},Z=g._free=function(){return(Z=g._free=g.asm.H).apply(null,arguments)},ab=g.___getTypeName=function(){return(ab=g.___getTypeName=g.asm.I).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.J).apply(null,arguments)};
g.dynCall_viijii=function(){return(g.dynCall_viijii=g.asm.L).apply(null,arguments)};g.dynCall_iiji=function(){return(g.dynCall_iiji=g.asm.M).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.N).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.O).apply(null,arguments)};g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.P).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.Q).apply(null,arguments)};
var wb;L=function xb(){wb||yb();wb||(L=xb)};
function yb(){function a(){if(!wb&&(wb=!0,g.calledRun=!0,!ha)){Ea(ya);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();za.unshift(b)}Ea(za)}}if(!(0<K)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();Ea(xa);0<K||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=yb;
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();yb();


  return Module.ready
}
);
})();
export default Module;