
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


function e(){m.buffer!=n&&u(m.buffer);return aa}function v(){m.buffer!=n&&u(m.buffer);return ba}function x(){m.buffer!=n&&u(m.buffer);return ca}function ea(){m.buffer!=n&&u(m.buffer);return fa}function A(){m.buffer!=n&&u(m.buffer);return ha}function B(){m.buffer!=n&&u(m.buffer);return ia}function ja(){m.buffer!=n&&u(m.buffer);return ka}var D;D||(D=typeof Module !== 'undefined' ? Module : {});var la,ma;D.ready=new Promise(function(a,b){la=a;ma=b});var E={},F;
for(F in D)D.hasOwnProperty(F)&&(E[F]=D[F]);var na="./this.program";function oa(a,b){throw b;}var G=D.ENVIRONMENT_IS_PTHREAD||!1,H="",pa;H=self.location.href;_scriptDir&&(H=_scriptDir);0!==H.indexOf("blob:")?H=H.substr(0,H.lastIndexOf("/")+1):H="";pa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var qa=D.print||console.log.bind(console),J=D.printErr||console.warn.bind(console);
for(F in E)E.hasOwnProperty(F)&&(D[F]=E[F]);E=null;D.thisProgram&&(na=D.thisProgram);D.quit&&(oa=D.quit);var ra;D.wasmBinary&&(ra=D.wasmBinary);var noExitRuntime=D.noExitRuntime||!0;"object"!==typeof WebAssembly&&K("no native wasm support detected");var m,sa,ta=!1;
function ua(a,b,c){c=b+c;for(var d="";!(b>=c);){var f=a[b++];if(!f)break;if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|l:(f&7)<<18|g<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function L(a,b){return a?ua(v(),a,b):""}
function va(a,b,c,d){if(0<d){d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0}}function wa(a,b,c){va(a,v(),b,c)}
function xa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ya(a,b){for(var c="",d=0;!(d>=b/2);++d){var f=x()[a+2*d>>1];if(0==f)break;c+=String.fromCharCode(f)}return c}function za(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f){var g=a.charCodeAt(f);x()[b>>1]=g;b+=2}x()[b>>1]=0;return b-d}
function Aa(a){return 2*a.length}function Ba(a,b){for(var c=0,d="";!(c>=b/4);){var f=A()[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023)):d+=String.fromCharCode(f)}return d}function Ca(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}A()[b>>2]=g;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d}
function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Ea(a,b){e().set(a,b)}var n,aa,ba,ca,fa,ha,ia,Fa,ka;G&&(n=D.buffer);function u(a){n=a;D.HEAP8=aa=new Int8Array(a);D.HEAP16=ca=new Int16Array(a);D.HEAP32=ha=new Int32Array(a);D.HEAPU8=ba=new Uint8Array(a);D.HEAPU16=fa=new Uint16Array(a);D.HEAPU32=ia=new Uint32Array(a);D.HEAPF32=Fa=new Float32Array(a);D.HEAPF64=ka=new Float64Array(a)}var Ga=D.INITIAL_MEMORY||16777216;
if(G)m=D.wasmMemory,n=D.buffer;else if(D.wasmMemory)m=D.wasmMemory;else if(m=new WebAssembly.Memory({initial:Ga/65536,maximum:32768,shared:!0}),!(m.buffer instanceof SharedArrayBuffer))throw J("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),Error("bad memory");m&&(n=m.buffer);Ga=n.byteLength;u(n);var M,Ha=[],Ia=[],Ja=[];
function Ka(){var a=D.preRun.shift();Ha.unshift(a)}var N=0,La=null,Ma=null;D.preloadedImages={};D.preloadedAudios={};function K(a){if(D.onAbort)D.onAbort(a);G&&console.error("Pthread aborting at "+Error().stack);J(a);ta=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ma(a);throw a;}var O=(new URL("jxl_enc_mt_simd.wasm",import.meta.url)).toString();
function Na(){try{if(O==O&&ra)return new Uint8Array(ra);if(pa)return pa(O);throw"both async and sync fetching of the wasm failed";}catch(a){K(a)}}function Oa(){return ra||"function"!==typeof fetch?Promise.resolve().then(function(){return Na()}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Na()})}
var Qa={59668:function(){throw"Canceled!";},59686:function(a,b){setTimeout(function(){Pa(a,b)},0)}};function Ra(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(D);else{var c=b.Yb;"number"===typeof c?void 0===b.Ia?M.get(c)():M.get(c)(b.Ia):c(void 0===b.Ia?null:b.Ia)}}}
function Sa(a,b){if(0>=a||a>e().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(A(),Ta>>2),d=0;if(c==a&&Atomics.compareExchange(A(),Ta>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(A(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}D._emscripten_futex_wake=Sa;
function Ua(a){if(G)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=P.Ba[a];b&&(A()[a+12>>2]=0,P.Qa(b.worker))}
var P={za:[],Ea:[],Ya:[],sb:function(){for(var a=navigator.hardwareConcurrency,b=0;b<a;++b)P.Za()},tb:function(){for(var a=Q(228),b=0;57>b;++b)B()[a/4+b]=0;A()[a+12>>2]=a;b=a+152;A()[b>>2]=b;var c=Q(512);for(b=0;128>b;++b)B()[c/4+b]=0;Atomics.store(B(),a+100>>2,c);Atomics.store(B(),a+40>>2,a);Va(a,!1,1);Wa(a)},ub:function(){P.receiveObjectTransfer=P.yb;P.threadInit=P.Ob;P.threadCancel=P.Mb;P.threadExit=P.Nb;P.setExitStatus=P.Bb},Ba:{},Xa:[],zb:function(){for(;0<P.Xa.length;)P.Xa.pop()();G&&R()&&Xa()},
gb:function(a,b){Atomics.store(B(),a+56>>2,1);Atomics.store(B(),a+60>>2,0);P.zb();Atomics.store(B(),a+4>>2,b);Atomics.store(B(),a+0>>2,1);Sa(a+0,2147483647);Va(0,0,0)},Bb:function(){},Nb:function(a){var b=R();b&&(P.gb(b,a),G&&postMessage({cmd:"exit"}))},Mb:function(){P.gb(R(),-1);postMessage({cmd:"cancelDone"})},Lb:function(){for(var a in P.Ba){var b=P.Ba[a];b&&b.worker&&P.Qa(b.worker)}P.Ba={};for(a=0;a<P.za.length;++a){var c=P.za[a];c.terminate()}P.za=[];for(a=0;a<P.Ea.length;++a)c=P.Ea[a],b=c.ya,
P.Va(b),c.terminate();P.Ea=[]},Va:function(a){if(a){if(a.Ca){var b=A()[a.Ca+100>>2];A()[a.Ca+100>>2]=0;S(b);S(a.Ca)}a.Ca=0;a.Ua&&a.Fa&&S(a.Fa);a.Fa=0;a.worker&&(a.worker.ya=null)}},Qa:function(a){P.Ab(function(){delete P.Ba[a.ya.Ca];P.za.push(a);P.Ea.splice(P.Ea.indexOf(a),1);P.Va(a.ya);a.ya=void 0})},Ab:function(a){A()[Ya>>2]=0;try{a()}finally{A()[Ya>>2]=1}},yb:function(){},Ob:function(){for(var a in P.Ya)P.Ya[a]()},eb:function(a,b){a.onmessage=function(c){var d=c.data,f=d.cmd;a.ya&&(P.ib=a.ya.Ca);
if(d.targetThread&&d.targetThread!=R()){var g=P.Ba[d.fc];g?g.worker.postMessage(c.data,d.transferList):console.error('Internal error! Worker sent a message "'+f+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===f)Za();else if("spawnThread"===f)$a(c.data);else if("cleanupThread"===f)Ua(d.thread);else if("killThread"===f){c=d.thread;if(G)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";
A()[c+12>>2]=0;c=P.Ba[c];c.worker.terminate();P.Va(c);P.Ea.splice(P.Ea.indexOf(c.worker),1);c.worker.ya=void 0}else if("cancelThread"===f){c=d.thread;if(G)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";P.Ba[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===f)a.loaded=!0,b&&b(a),a.Ka&&(a.Ka(),delete a.Ka);else if("print"===f)qa("Thread "+d.threadId+": "+d.text);else if("printErr"===f)J("Thread "+
d.threadId+": "+d.text);else if("alert"===f)alert("Thread "+d.threadId+": "+d.text);else if("exit"===f)a.ya&&Atomics.load(B(),a.ya.Ca+64>>2)&&P.Qa(a);else if("exitProcess"===f)try{g=d.returnCode;if(G)throw postMessage({cmd:"exitProcess",returnCode:g}),new ab(g);if(!bb()){P.Lb();if(D.onExit)D.onExit(g);ta=!0}oa(g,new ab(g))}catch(l){if(l instanceof ab)return;throw l;}else"cancelDone"===f?P.Qa(a):"objectTransfer"!==f&&("setimmediate"===c.data.target?a.postMessage(c.data):J("worker sent an unknown command "+
f));P.ib=void 0};a.onerror=function(c){J("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};a.postMessage({cmd:"load",urlOrBlob:D.mainScriptUrlOrBlob,wasmMemory:m,wasmModule:sa})},Za:function(){if(D.locateFile){var a=D.locateFile?D.locateFile("jxl_enc_mt_simd.worker.js",H):H+"jxl_enc_mt_simd.worker.js";P.za.push(new Worker(a))}else P.za.push(new Worker(new URL("jxl_enc_mt_simd.worker.js",import.meta.url)))},lb:function(){0==P.za.length&&(P.Za(),P.eb(P.za[0]));return P.za.pop()},
Ub:function(a){for(a=performance.now()+a;performance.now()<a;);}};D.establishStackSpace=function(a,b){cb(a,b);db(a)};D.invokeEntryPoint=function(a,b){return M.get(a)(b)};var eb=0;function bb(){return noExitRuntime||0<eb}D.keepRuntimeAlive=bb;var fb;fb=G?function(){return performance.now()-D.__performance_now_clock_drift}:function(){return performance.now()};function gb(a,b){P.Xa.push(function(){M.get(a)(b)})}
function hb(a){this.Ja=a-16;this.Gb=function(b){A()[this.Ja+8>>2]=b};this.Db=function(b){A()[this.Ja+0>>2]=b};this.Eb=function(){A()[this.Ja+4>>2]=0};this.Cb=function(){var b=0;e()[this.Ja+12>>0]=b};this.Fb=function(){var b=0;e()[this.Ja+13>>0]=b};this.qb=function(b,c){this.Gb(b);this.Db(c);this.Eb();this.Cb();this.Fb()}}var ib=0,jb={};function kb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function lb(a){return this.fromWireType(B()[a>>2])}var T={},U={},mb={};
function nb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function ob(a,b){a=nb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function pb(a){var b=Error,c=ob(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var qb=void 0;
function rb(a,b,c){function d(k){k=c(k);if(k.length!==a.length)throw new qb("Mismatched type converter count");for(var q=0;q<a.length;++q)V(a[q],k[q])}a.forEach(function(k){mb[k]=b});var f=Array(b.length),g=[],l=0;b.forEach(function(k,q){U.hasOwnProperty(k)?f[q]=U[k]:(g.push(k),T.hasOwnProperty(k)||(T[k]=[]),T[k].push(function(){f[q]=U[k];++l;l===g.length&&d(f)}))});0===g.length&&d(f)}
function sb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var tb=void 0;function W(a){for(var b="";v()[a];)b+=tb[v()[a++]];return b}var ub=void 0;function X(a){throw new ub(a);}
function V(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||X('type "'+d+'" must have a positive integer typeid pointer');if(U.hasOwnProperty(a)){if(c.pb)return;X("Cannot register type '"+d+"' twice")}U[a]=b;delete mb[a];T.hasOwnProperty(a)&&(b=T[a],delete T[a],b.forEach(function(f){f()}))}var vb=[],Y=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function wb(a){4<a&&0===--Y[a].Wa&&(Y[a]=void 0,vb.push(a))}function xb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=vb.length?vb.pop():Y.length;Y[b]={Wa:1,value:a};return b}}function yb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function zb(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;m.buffer!=n&&u(m.buffer);return d.call(this,Fa[c>>2])};case 3:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Ab(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=ob(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Bb(a,b){var c=D;if(void 0===c[a].Aa){var d=c[a];c[a]=function(){c[a].Aa.hasOwnProperty(arguments.length)||X("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].Aa+")!");return c[a].Aa[arguments.length].apply(this,arguments)};c[a].Aa=[];c[a].Aa[d.hb]=d}}
function Cb(a,b,c){D.hasOwnProperty(a)?((void 0===c||void 0!==D[a].Aa&&void 0!==D[a].Aa[c])&&X("Cannot register public name '"+a+"' twice"),Bb(a,a),D.hasOwnProperty(c)&&X("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),D[a].Aa[c]=b):(D[a]=b,void 0!==c&&(D[a].cc=c))}function Db(a,b){for(var c=[],d=0;d<a;d++)c.push(A()[(b>>2)+d]);return c}
function Eb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=D["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=M.get(b).apply(null,c);return d}}function Fb(a,b){a=W(a);var c=a.includes("j")?Eb(a,b):M.get(b);"function"!==typeof c&&X("unknown function pointer with signature "+a+": "+b);return c}var Gb=void 0;function Hb(a){a=Ib(a);var b=W(a);S(a);return b}
function Jb(a,b){function c(g){f[g]||U[g]||(mb[g]?mb[g].forEach(c):(d.push(g),f[g]=!0))}var d=[],f={};b.forEach(c);throw new Gb(a+": "+d.map(Hb).join([", "]));}function Kb(a,b,c){switch(b){case 0:return c?function(d){return e()[d]}:function(d){return v()[d]};case 1:return c?function(d){return x()[d>>1]}:function(d){return ea()[d>>1]};case 2:return c?function(d){return A()[d>>2]}:function(d){return B()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Lb={};
function Mb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Nb(a,b){var c=U[a];void 0===c&&X(b+" has unknown type "+Hb(a));return c}var Ob={},Pb=[];function Qb(a,b,c){if(0>=a||a>e().length||a&1)return-28;a=Atomics.wait(A(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+a;}
function Z(a,b){for(var c=arguments.length-2,d=Rb(),f=Sb(8*c),g=f>>3,l=0;l<c;l++){var k=arguments[2+l];ja()[g+l]=k}c=Tb(a,c,f,b);db(d);return c}var Ub=[],Vb=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function Wb(a){a=2<a?L(a):a;return Vb[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function Xb(a,b,c){var d=Wb(a);if(!d)return-4;d.Oa&&(A()[d.Oa>>2]=b,A()[d.Oa+4>>2]=c);if(d.fb||!d.Wb)d.fb&&(d=d.fb),a=!1,d.Na&&d.Na.Ma&&(a=d.Na.Ma.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Na.Ma.viewport(0,0,b,c);else{if(d.Oa){d=A()[d.Oa+8>>2];a=a?L(a):"";var f=Rb(),g=Sb(12),l=0;if(a){l=xa(a)+1;var k=Q(l);wa(a,k,l);l=k}A()[g>>2]=l;A()[g+4>>2]=b;A()[g+8>>2]=c;Yb(0,d,657457152,0,l,g);db(f);return 1}return-4}return 0}
function Zb(a,b,c){return G?Z(2,1,a,b,c):Xb(a,b,c)}function $b(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,f,g){b.drawArraysInstancedANGLE(c,d,f,g)},a.drawElementsInstanced=function(c,d,f,g,l){b.drawElementsInstancedANGLE(c,d,f,g,l)})}
function ac(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function bc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function cc(a,b){a.cb||(a.cb=a.getContext,a.getContext=function(d,f){f=a.cb(d,f);return"webgl"==d==f instanceof WebGLRenderingContext?f:null});var c=a.getContext("webgl",b);return c?dc(c,b):0}function dc(a,b){var c=Q(8);A()[c+4>>2]=R();var d={Zb:c,attributes:b,version:b.vb,Ma:a};a.canvas&&(a.canvas.Na=d);("undefined"===typeof b.ab||b.ab)&&ec(d);return c}
function ec(a){a||(a=fc);if(!a.rb){a.rb=!0;var b=a.Ma;$b(b);ac(b);bc(b);b.Xb=b.getExtension("EXT_disjoint_timer_query");b.bc=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var fc,gc=["default","low-power","high-performance"],hc={};
function ic(){if(!jc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:na||"./this.program"},b;for(b in hc)a[b]=hc[b];var c=[];for(b in a)c.push(b+"="+a[b]);jc=c}return jc}var jc,kc=[null,[],[]];
function lc(a,b){if(G)return Z(3,1,a,b);var c=0;ic().forEach(function(d,f){var g=b+c;f=A()[a+4*f>>2]=g;for(g=0;g<d.length;++g)e()[f++>>0]=d.charCodeAt(g);e()[f>>0]=0;c+=d.length+1});return 0}function mc(a,b){if(G)return Z(4,1,a,b);var c=ic();A()[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});A()[b>>2]=d;return 0}function nc(a){return G?Z(5,1,a):0}function oc(a,b,c,d,f){if(G)return Z(6,1,a,b,c,d,f)}
function pc(a,b,c,d){if(G)return Z(7,1,a,b,c,d);for(var f=0,g=0;g<c;g++){for(var l=A()[b+8*g>>2],k=A()[b+(8*g+4)>>2],q=0;q<k;q++){var r=v()[l+q],t=kc[a];0===r||10===r?((1===a?qa:J)(ua(t,0)),t.length=0):t.push(r)}f+=k}A()[d>>2]=f;return 0}
function $a(a){if(G)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=P.lb();if(!b)return 6;if(void 0!==b.ya)throw"Internal error!";if(!a.Pa)throw"Internal error, no pthread ptr!";P.Ea.push(b);for(var c=Q(512),d=0;128>d;++d)A()[c+4*d>>2]=0;var f=a.Fa+a.Ga;d=P.Ba[a.Pa]={worker:b,Fa:a.Fa,Ga:a.Ga,Ua:a.Ua,Ca:a.Pa};var g=d.Ca>>2;Atomics.store(B(),g+16,a.$a);Atomics.store(B(),g+25,c);Atomics.store(B(),g+10,d.Ca);Atomics.store(B(),g+20,a.Ga);Atomics.store(B(),
g+19,f);Atomics.store(B(),g+26,a.Ga);Atomics.store(B(),g+28,f);Atomics.store(B(),g+29,a.$a);c=qc()+40;Atomics.store(B(),g+43,c);b.ya=d;var l={cmd:"run",start_routine:a.Kb,arg:a.Ia,threadInfoStruct:a.Pa,stackBase:a.Fa,stackSize:a.Ga};b.Ka=function(){l.time=performance.now();b.postMessage(l,a.Tb)};b.loaded&&(b.Ka(),delete b.Ka);return 0}
function rc(a,b){if(!a)return J("pthread_join attempted on a null thread pointer!"),71;if(G&&R()==a)return J("PThread "+a+" is attempting to join to itself!"),16;if(!G&&sc()==a)return J("Main thread "+a+" is attempting to join to itself!"),16;if(A()[a+12>>2]!==a)return J("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(B(),a+64>>2))return J("Attempted to join thread "+a+", which was already detached!"),28;for(;;){var c=
Atomics.load(B(),a+0>>2);if(1==c)return c=Atomics.load(B(),a+4>>2),b&&(A()[b>>2]=c),Atomics.store(B(),a+64>>2,1),G?postMessage({cmd:"cleanupThread",thread:a}):Ua(a),0;if(G){var d=R();if(d&&!Atomics.load(B(),d+56>>2)&&2==Atomics.load(B(),d+0>>2))throw"Canceled!";}G||Za();Qb(a+0,c,G?100:1)}}function tc(a){return 0===a%4&&(0!==a%100||0===a%400)}function uc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var vc=[31,29,31,30,31,30,31,31,30,31,30,31],wc=[31,28,31,30,31,30,31,31,30,31,30,31];
function xc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(tc(a.getFullYear())?vc:wc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function yc(a,b,c,d){function f(h,p,y){for(h="number"===typeof h?h.toString():h||"";h.length<p;)h=y[0]+h;return h}function g(h,p){return f(h,p,"0")}function l(h,p){function y(I){return 0>I?-1:0<I?1:0}var z;0===(z=y(h.getFullYear()-p.getFullYear()))&&0===(z=y(h.getMonth()-p.getMonth()))&&(z=y(h.getDate()-p.getDate()));return z}function k(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function q(h){h=xc(new Date(h.xa+1900,0,1),h.Ta);var p=new Date(h.getFullYear()+1,0,4),y=k(new Date(h.getFullYear(),0,4));p=k(p);return 0>=l(y,h)?0>=l(p,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var r=A()[d+40>>2];d={Rb:A()[d>>2],Qb:A()[d+4>>2],Ra:A()[d+8>>2],La:A()[d+12>>2],Ha:A()[d+16>>2],xa:A()[d+20>>2],Sa:A()[d+24>>2],Ta:A()[d+28>>2],hc:A()[d+
32>>2],Pb:A()[d+36>>2],Sb:r?L(r):""};c=L(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in r)c=c.replace(new RegExp(t,"g"),r[t]);var w="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
C="January February March April May June July August September October November December".split(" ");r={"%a":function(h){return w[h.Sa].substring(0,3)},"%A":function(h){return w[h.Sa]},"%b":function(h){return C[h.Ha].substring(0,3)},"%B":function(h){return C[h.Ha]},"%C":function(h){return g((h.xa+1900)/100|0,2)},"%d":function(h){return g(h.La,2)},"%e":function(h){return f(h.La,2," ")},"%g":function(h){return q(h).toString().substring(2)},"%G":function(h){return q(h)},"%H":function(h){return g(h.Ra,
2)},"%I":function(h){h=h.Ra;0==h?h=12:12<h&&(h-=12);return g(h,2)},"%j":function(h){return g(h.La+uc(tc(h.xa+1900)?vc:wc,h.Ha-1),3)},"%m":function(h){return g(h.Ha+1,2)},"%M":function(h){return g(h.Qb,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.Ra&&12>h.Ra?"AM":"PM"},"%S":function(h){return g(h.Rb,2)},"%t":function(){return"\t"},"%u":function(h){return h.Sa||7},"%U":function(h){var p=new Date(h.xa+1900,0,1),y=0===p.getDay()?p:xc(p,7-p.getDay());h=new Date(h.xa+1900,h.Ha,h.La);return 0>
l(y,h)?g(Math.ceil((31-y.getDate()+(uc(tc(h.getFullYear())?vc:wc,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(y,p)?"01":"00"},"%V":function(h){var p=new Date(h.xa+1901,0,4),y=k(new Date(h.xa+1900,0,4));p=k(p);var z=xc(new Date(h.xa+1900,0,1),h.Ta);return 0>l(z,y)?"53":0>=l(p,z)?"01":g(Math.ceil((y.getFullYear()<h.xa+1900?h.Ta+32-y.getDate():h.Ta+1-y.getDate())/7),2)},"%w":function(h){return h.Sa},"%W":function(h){var p=new Date(h.xa,0,1),y=1===p.getDay()?p:xc(p,0===p.getDay()?1:7-p.getDay()+1);h=
new Date(h.xa+1900,h.Ha,h.La);return 0>l(y,h)?g(Math.ceil((31-y.getDate()+(uc(tc(h.getFullYear())?vc:wc,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(y,p)?"01":"00"},"%y":function(h){return(h.xa+1900).toString().substring(2)},"%Y":function(h){return h.xa+1900},"%z":function(h){h=h.Pb;var p=0<=h;h=Math.abs(h)/60;return(p?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Sb},"%%":function(){return"%"}};for(t in r)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),r[t](d)));t=zc(c);
if(t.length>b)return 0;Ea(t,a);return t.length-1}G||P.sb();qb=D.InternalError=pb("InternalError");for(var Ac=Array(256),Bc=0;256>Bc;++Bc)Ac[Bc]=String.fromCharCode(Bc);tb=Ac;ub=D.BindingError=pb("BindingError");D.count_emval_handles=function(){for(var a=0,b=5;b<Y.length;++b)void 0!==Y[b]&&++a;return a};D.get_first_emval=function(){for(var a=5;a<Y.length;++a)if(void 0!==Y[a])return Y[a];return null};Gb=D.UnboundTypeError=pb("UnboundTypeError");
var Cc=[null,function(a,b){if(G)return Z(1,1,a,b)},Zb,lc,mc,nc,oc,pc];function zc(a){var b=Array(xa(a)+1);va(a,b,0,b.length);return b}
var Fc={e:function(a,b,c,d){K("Assertion failed: "+L(a)+", at: "+[b?L(b):"unknown filename",c,d?L(d):"unknown function"])},J:function(a){return Q(a+16)+16},q:function(a,b){return gb(a,b)},B:function(a,b,c){(new hb(a)).qb(b,c);ib++;throw a;},s:function(a){var b=jb[a];delete jb[a];var c=b.wb,d=b.xb,f=b.bb,g=f.map(function(l){return l.ob}).concat(f.map(function(l){return l.Ib}));rb([a],g,function(l){var k={};f.forEach(function(q,r){var t=l[r],w=q.mb,C=q.nb,h=l[r+f.length],p=q.Hb,y=q.Jb;k[q.kb]={read:function(z){return t.fromWireType(w(C,
z))},write:function(z,I){var da=[];p(y,z,h.toWireType(da,I));kb(da)}}});return[{name:b.name,fromWireType:function(q){var r={},t;for(t in k)r[t]=k[t].read(q);d(q);return r},toWireType:function(q,r){for(var t in k)if(!(t in r))throw new TypeError('Missing field:  "'+t+'"');var w=c();for(t in k)k[t].write(w,r[t]);null!==q&&q.push(d,w);return w},argPackAdvance:8,readValueFromPointer:lb,Da:d}]})},w:function(){},Q:function(a,b,c,d,f){var g=sb(c);b=W(b);V(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,
k){return k?d:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=e();else if(2===c)k=x();else if(4===c)k=A();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>g])},Da:null})},P:function(a,b){b=W(b);V(a,{name:b,fromWireType:function(c){var d=Y[c].value;wb(c);return d},toWireType:function(c,d){return xb(d)},argPackAdvance:8,readValueFromPointer:lb,Da:null})},o:function(a,b,c){c=sb(c);b=W(b);V(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,
f){if("number"!==typeof f&&"boolean"!==typeof f)throw new TypeError('Cannot convert "'+yb(f)+'" to '+this.name);return f},argPackAdvance:8,readValueFromPointer:zb(b,c),Da:null})},r:function(a,b,c,d,f,g){var l=Db(b,c);a=W(a);f=Fb(d,f);Cb(a,function(){Jb("Cannot call "+a+" due to unbound types",l)},b-1);rb([],l,function(k){var q=a,r=a;k=[k[0],null].concat(k.slice(1));var t=f,w=k.length;2>w&&X("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var C=null!==k[1]&&!1,
h=!1,p=1;p<k.length;++p)if(null!==k[p]&&void 0===k[p].Da){h=!0;break}var y="void"!==k[0].name,z="",I="";for(p=0;p<w-2;++p)z+=(0!==p?", ":"")+"arg"+p,I+=(0!==p?", ":"")+"arg"+p+"Wired";r="return function "+nb(r)+"("+z+") {\nif (arguments.length !== "+(w-2)+") {\nthrowBindingError('function "+r+" called with ' + arguments.length + ' arguments, expected "+(w-2)+" args!');\n}\n";h&&(r+="var destructors = [];\n");var da=h?"destructors":"null";z="throwBindingError invoker fn runDestructors retType classParam".split(" ");
t=[X,t,g,kb,k[0],k[1]];C&&(r+="var thisWired = classParam.toWireType("+da+", this);\n");for(p=0;p<w-2;++p)r+="var arg"+p+"Wired = argType"+p+".toWireType("+da+", arg"+p+"); // "+k[p+2].name+"\n",z.push("argType"+p),t.push(k[p+2]);C&&(I="thisWired"+(0<I.length?", ":"")+I);r+=(y?"var rv = ":"")+"invoker(fn"+(0<I.length?", ":"")+I+");\n";if(h)r+="runDestructors(destructors);\n";else for(p=C?1:2;p<k.length;++p)w=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==k[p].Da&&(r+=w+"_dtor("+w+"); // "+k[p].name+
"\n",z.push(w+"_dtor"),t.push(k[p].Da));y&&(r+="var ret = retType.fromWireType(rv);\nreturn ret;\n");z.push(r+"}\n");k=Ab(z).apply(null,t);p=b-1;if(!D.hasOwnProperty(q))throw new qb("Replacing nonexistant public symbol");void 0!==D[q].Aa&&void 0!==p?D[q].Aa[p]=k:(D[q]=k,D[q].hb=p);return[]})},d:function(a,b,c,d,f){function g(r){return r}b=W(b);-1===f&&(f=4294967295);var l=sb(c);if(0===d){var k=32-8*c;g=function(r){return r<<k>>>k}}var q=b.includes("unsigned");V(a,{name:b,fromWireType:g,toWireType:function(r,
t){if("number"!==typeof t&&"boolean"!==typeof t)throw new TypeError('Cannot convert "'+yb(t)+'" to '+this.name);if(t<d||t>f)throw new TypeError('Passing a number "'+yb(t)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+f+"]!");return q?t>>>0:t|0},argPackAdvance:8,readValueFromPointer:Kb(b,l,0!==d),Da:null})},c:function(a,b,c){function d(g){g>>=2;var l=B();return new f(n,l[g+1],l[g])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,
Uint32Array,Float32Array,Float64Array][b];c=W(c);V(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{pb:!0})},p:function(a,b){b=W(b);var c="std::string"===b;V(a,{name:b,fromWireType:function(d){var f=B()[d>>2];if(c)for(var g=d+4,l=0;l<=f;++l){var k=d+4+l;if(l==f||0==v()[k]){g=L(g,k-g);if(void 0===q)var q=g;else q+=String.fromCharCode(0),q+=g;g=k+1}}else{q=Array(f);for(l=0;l<f;++l)q[l]=String.fromCharCode(v()[d+4+l]);q=q.join("")}S(d);return q},toWireType:function(d,f){f instanceof
ArrayBuffer&&(f=new Uint8Array(f));var g="string"===typeof f;g||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||X("Cannot pass non-string to std::string");var l=(c&&g?function(){return xa(f)}:function(){return f.length})(),k=Q(4+l+1);B()[k>>2]=l;if(c&&g)wa(f,k+4,l+1);else if(g)for(g=0;g<l;++g){var q=f.charCodeAt(g);255<q&&(S(k),X("String has UTF-16 code units that do not fit in 8 bits"));v()[k+4+g]=q}else for(g=0;g<l;++g)v()[k+4+g]=f[g];null!==d&&d.push(S,k);return k},
argPackAdvance:8,readValueFromPointer:lb,Da:function(d){S(d)}})},k:function(a,b,c){c=W(c);if(2===b){var d=ya;var f=za;var g=Aa;var l=function(){return ea()};var k=1}else 4===b&&(d=Ba,f=Ca,g=Da,l=function(){return B()},k=2);V(a,{name:c,fromWireType:function(q){for(var r=B()[q>>2],t=l(),w,C=q+4,h=0;h<=r;++h){var p=q+4+h*b;if(h==r||0==t[p>>k])C=d(C,p-C),void 0===w?w=C:(w+=String.fromCharCode(0),w+=C),C=p+b}S(q);return w},toWireType:function(q,r){"string"!==typeof r&&X("Cannot pass non-string to C++ string type "+
c);var t=g(r),w=Q(4+t+b);B()[w>>2]=t>>k;f(r,w+4,t+b);null!==q&&q.push(S,w);return w},argPackAdvance:8,readValueFromPointer:lb,Da:function(q){S(q)}})},t:function(a,b,c,d,f,g){jb[a]={name:W(b),wb:Fb(c,d),xb:Fb(f,g),bb:[]}},f:function(a,b,c,d,f,g,l,k,q,r){jb[a].bb.push({kb:W(b),ob:c,mb:Fb(d,f),nb:g,Ib:l,Hb:Fb(k,q),Jb:r})},R:function(a,b){b=W(b);V(a,{$b:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},I:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});
else if(G)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=P.Ba[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},i:wb,U:function(a){if(0===a)return xb(Mb());var b=Lb[a];a=void 0===b?W(a):b;return xb(Mb()[a])},T:function(a){4<a&&(Y[a].Wa+=1)},u:function(a,b,c,d){a||X("Cannot use deleted val. handle = "+a);a=Y[a].value;var f=Ob[b];if(!f){f="";for(var g=0;g<b;++g)f+=(0!==g?", ":"")+"arg"+g;var l="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";
for(g=0;g<b;++g)l+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";f=(new Function("requireRegisteredType","Module","__emval_register",l+("var obj = new constructor("+f+");\nreturn __emval_register(obj);\n}\n")))(Nb,D,xb);Ob[b]=f}return f(a,c,d)},b:function(){K()},n:function(a,b,c){Pb.length=0;var d;for(c>>=2;d=v()[b++];)(d=105>d)&&c&1&&c++,
Pb.push(d?ja()[c++>>1]:A()[c]),++c;return Qa[a].apply(null,Pb)},E:function(){},m:function(){},h:Qb,g:Sa,j:fb,z:function(a,b,c){v().copyWithin(a,b,b+c)},D:function(){return navigator.hardwareConcurrency},F:function(a,b,c){Ub.length=b;c>>=3;for(var d=0;d<b;d++)Ub[d]=ja()[c+d];return(0>a?Qa[-a-1]:Cc[a]).apply(null,Ub)},A:function(a){var b=v().length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{m.grow(Math.min(2147483648,
d)-n.byteLength+65535>>>16);u(m.buffer);var f=1;break a}catch(g){}f=void 0}if(f)return!0}return!1},G:function(a,b,c){return Wb(a)?Xb(a,b,c):Zb(a,b,c)},l:function(){},H:function(a,b){b>>=2;var c=A()[b+6];b={alpha:!!A()[b],depth:!!A()[b+1],stencil:!!A()[b+2],antialias:!!A()[b+3],premultipliedAlpha:!!A()[b+4],preserveDrawingBuffer:!!A()[b+5],powerPreference:gc[c],failIfMajorPerformanceCaveat:!!A()[b+7],vb:A()[b+8],ac:A()[b+9],ab:A()[b+10],jb:A()[b+11],dc:A()[b+12],ec:A()[b+13]};a=Wb(a);return!a||b.jb?
0:cc(a,b)},L:lc,M:mc,N:nc,v:oc,O:pc,y:function(){P.tb()},a:m||D.wasmMemory,S:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return J("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return J("pthread_create called with a null thread pointer!"),28;var f=[];if(G&&0===f.length)return Dc(687865856,a,b,c,d);var g=0,l=0;if(b&&-1!=b){var k=A()[b>>2];k+=81920;g=A()[b+8>>2];l=0!==A()[b+12>>2]}else k=2097152;(b=0==g)?g=Ec(16,k):(g-=k,0<g||K("Assertion failed: undefined"));
for(var q=Q(228),r=0;57>r;++r)B()[(q>>2)+r]=0;A()[a>>2]=q;A()[q+12>>2]=q;a=q+152;A()[a>>2]=a;c={Fa:g,Ga:k,Ua:b,$a:l,Kb:c,Pa:q,Ia:d,Tb:f};return G?(c.Vb="spawnThread",postMessage(c,f),0):$a(c)},C:function(a,b){return rc(a,b)},x:function(){},K:function(a,b,c,d){return yc(a,b,c,d)}};
(function(){function a(f,g){D.asm=f.exports;M=D.asm.Z;Ia.unshift(D.asm.V);P.Ya.push(D.asm.Y);sa=g;if(!G){var l=P.za.length;P.za.forEach(function(k){P.eb(k,function(){if(!--l&&(N--,D.monitorRunDependencies&&D.monitorRunDependencies(N),0==N&&(null!==La&&(clearInterval(La),La=null),Ma))){var q=Ma;Ma=null;q()}})})}}function b(f){a(f.instance,f.module)}function c(f){return Oa().then(function(g){return WebAssembly.instantiate(g,d)}).then(f,function(g){J("failed to asynchronously prepare wasm: "+g);K(g)})}
var d={a:Fc};G||(!G||K("Assertion failed: addRunDependency cannot be used in a pthread worker"),N++,D.monitorRunDependencies&&D.monitorRunDependencies(N));if(D.instantiateWasm)try{return D.instantiateWasm(d,a)}catch(f){return J("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return ra||"function"!==typeof WebAssembly.instantiateStreaming||O.startsWith("data:application/octet-stream;base64,")||"function"!==typeof fetch?c(b):fetch(O,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,
d).then(b,function(g){J("wasm streaming compile failed: "+g);J("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ma);return{}})();D.___wasm_call_ctors=function(){return(D.___wasm_call_ctors=D.asm.V).apply(null,arguments)};var Q=D._malloc=function(){return(Q=D._malloc=D.asm.W).apply(null,arguments)},S=D._free=function(){return(S=D._free=D.asm.X).apply(null,arguments)};D._emscripten_tls_init=function(){return(D._emscripten_tls_init=D.asm.Y).apply(null,arguments)};
var Ib=D.___getTypeName=function(){return(Ib=D.___getTypeName=D.asm._).apply(null,arguments)};D.___embind_register_native_and_builtin_types=function(){return(D.___embind_register_native_and_builtin_types=D.asm.$).apply(null,arguments)};D._emscripten_current_thread_process_queued_calls=function(){return(D._emscripten_current_thread_process_queued_calls=D.asm.aa).apply(null,arguments)};
var Wa=D._emscripten_register_main_browser_thread_id=function(){return(Wa=D._emscripten_register_main_browser_thread_id=D.asm.ba).apply(null,arguments)},sc=D._emscripten_main_browser_thread_id=function(){return(sc=D._emscripten_main_browser_thread_id=D.asm.ca).apply(null,arguments)},Pa=D.__emscripten_do_dispatch_to_thread=function(){return(Pa=D.__emscripten_do_dispatch_to_thread=D.asm.da).apply(null,arguments)},Dc=D._emscripten_sync_run_in_main_thread_4=function(){return(Dc=D._emscripten_sync_run_in_main_thread_4=
D.asm.ea).apply(null,arguments)},Za=D._emscripten_main_thread_process_queued_calls=function(){return(Za=D._emscripten_main_thread_process_queued_calls=D.asm.fa).apply(null,arguments)},Tb=D._emscripten_run_in_main_runtime_thread_js=function(){return(Tb=D._emscripten_run_in_main_runtime_thread_js=D.asm.ga).apply(null,arguments)},Yb=D.__emscripten_call_on_thread=function(){return(Yb=D.__emscripten_call_on_thread=D.asm.ha).apply(null,arguments)},Va=D.__emscripten_thread_init=function(){return(Va=D.__emscripten_thread_init=
D.asm.ia).apply(null,arguments)},R=D._pthread_self=function(){return(R=D._pthread_self=D.asm.ja).apply(null,arguments)},Xa=D.___pthread_tsd_run_dtors=function(){return(Xa=D.___pthread_tsd_run_dtors=D.asm.ka).apply(null,arguments)},qc=D._emscripten_get_global_libc=function(){return(qc=D._emscripten_get_global_libc=D.asm.la).apply(null,arguments)},Rb=D.stackSave=function(){return(Rb=D.stackSave=D.asm.ma).apply(null,arguments)},db=D.stackRestore=function(){return(db=D.stackRestore=D.asm.na).apply(null,
arguments)},Sb=D.stackAlloc=function(){return(Sb=D.stackAlloc=D.asm.oa).apply(null,arguments)},cb=D._emscripten_stack_set_limits=function(){return(cb=D._emscripten_stack_set_limits=D.asm.pa).apply(null,arguments)},Ec=D._memalign=function(){return(Ec=D._memalign=D.asm.qa).apply(null,arguments)};D.dynCall_viijii=function(){return(D.dynCall_viijii=D.asm.ra).apply(null,arguments)};D.dynCall_iiji=function(){return(D.dynCall_iiji=D.asm.sa).apply(null,arguments)};
D.dynCall_jiji=function(){return(D.dynCall_jiji=D.asm.ta).apply(null,arguments)};D.dynCall_iiiiij=function(){return(D.dynCall_iiiiij=D.asm.ua).apply(null,arguments)};D.dynCall_iiiiijj=function(){return(D.dynCall_iiiiijj=D.asm.va).apply(null,arguments)};D.dynCall_iiiiiijj=function(){return(D.dynCall_iiiiiijj=D.asm.wa).apply(null,arguments)};var Ya=D.__emscripten_allow_main_runtime_queued_calls=59656,Ta=D.__emscripten_main_thread_futex=72492;D.PThread=P;D.PThread=P;D.wasmMemory=m;D.ExitStatus=ab;var Gc;
function ab(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ma=function Hc(){Gc||Ic();Gc||(Ma=Hc)};
function Ic(){function a(){if(!Gc&&(Gc=!0,D.calledRun=!0,!ta)){G||Ra(Ia);la(D);if(D.onRuntimeInitialized)D.onRuntimeInitialized();if(!G){if(D.postRun)for("function"==typeof D.postRun&&(D.postRun=[D.postRun]);D.postRun.length;){var b=D.postRun.shift();Ja.unshift(b)}Ra(Ja)}}}if(!(0<N))if(G)la(D),G||Ra(Ia),postMessage({cmd:"loaded"});else{if(!G){if(D.preRun)for("function"==typeof D.preRun&&(D.preRun=[D.preRun]);D.preRun.length;)Ka();Ra(Ha)}0<N||(D.setStatus?(D.setStatus("Running..."),setTimeout(function(){setTimeout(function(){D.setStatus("")},
1);a()},1)):a())}}D.run=Ic;if(D.preInit)for("function"==typeof D.preInit&&(D.preInit=[D.preInit]);0<D.preInit.length;)D.preInit.pop()();G&&(noExitRuntime=!1,P.ub());Ic();


  return Module.ready
}
);
})();
export default Module;