
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var f;f||(f=typeof Module !== 'undefined' ? Module : {});var aa,ba;f.ready=new Promise(function(a,b){aa=a;ba=b});var r={},x;for(x in f)f.hasOwnProperty(x)&&(r[x]=f[x]);var ca,da,ea,fa;ca=function(a){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);return ea.readFileSync(a,null)};da=function(a){a=ca(a);a.buffer||(a=new Uint8Array(a));a.buffer||y("Assertion failed: undefined");return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);
process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",y);f.inspect=function(){return"[Emscripten Module object]"};var ha=f.print||console.log.bind(console),A=f.printErr||console.warn.bind(console);for(x in r)r.hasOwnProperty(x)&&(f[x]=r[x]);r=null;var ia;f.wasmBinary&&(ia=f.wasmBinary);var noExitRuntime=f.noExitRuntime||!0;"object"!==typeof WebAssembly&&y("no native wasm support detected");var ja,ka=!1,la=new TextDecoder("utf8");
function ma(a,b){if(!a)return"";b=a+b;for(var c=a;!(c>=b)&&B[c];)++c;return la.decode(B.subarray(a,c))}
function na(a,b,c){var d=B;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}}var oa=new TextDecoder("utf-16le");
function pa(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&qa[c];)++c;return oa.decode(B.subarray(a,c<<1))}function ra(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)C[b>>1]=a.charCodeAt(e),b+=2;C[b>>1]=0;return b-d}function sa(a){return 2*a.length}function ta(a,b){for(var c=0,d="";!(c>=b/4);){var e=D[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function ua(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var l=a.charCodeAt(++e);g=65536+((g&1023)<<10)|l&1023}D[b>>2]=g;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d}function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var wa,E,B,C,qa,D,F,xa,ya;
function za(){var a=ja.buffer;wa=a;f.HEAP8=E=new Int8Array(a);f.HEAP16=C=new Int16Array(a);f.HEAP32=D=new Int32Array(a);f.HEAPU8=B=new Uint8Array(a);f.HEAPU16=qa=new Uint16Array(a);f.HEAPU32=F=new Uint32Array(a);f.HEAPF32=xa=new Float32Array(a);f.HEAPF64=ya=new Float64Array(a)}var H,Aa=[],Ba=[],Ca=[];function Da(){var a=f.preRun.shift();Aa.unshift(a)}var I=0,Ea=null,J=null;f.preloadedImages={};f.preloadedAudios={};
function y(a){if(f.onAbort)f.onAbort(a);A(a);ka=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}var Fa=(new URL("visdif.wasm",import.meta.url)).toString();function Ga(){return Promise.resolve().then(function(){a:{try{if(Fa==Fa&&ia){var a=new Uint8Array(ia);break a}if(da){a=da(Fa);break a}throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}a=void 0}return a})}
function Ha(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.ra;"number"===typeof c?void 0===b.W?H.get(c)():H.get(c)(b.W):c(void 0===b.W?null:b.W)}}}function Ia(a){this.D=a-16;this.pa=function(b){D[this.D+8>>2]=b};this.ma=function(b){D[this.D+0>>2]=b};this.na=function(){D[this.D+4>>2]=0};this.la=function(){E[this.D+12>>0]=0};this.oa=function(){E[this.D+13>>0]=0};this.fa=function(b,c){this.pa(b);this.ma(c);this.na();this.la();this.oa()}}var Ja=0;
function Ka(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var La=void 0;function K(a){for(var b="";B[a];)b+=La[B[a++]];return b}var N={},O={},Ma={};function Na(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Oa(a,b){a=Na(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Pa(a){var b=Error,c=Oa(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var P=void 0;function Q(a){throw new P(a);}var Qa=void 0;function Ra(a){throw new Qa(a);}function Sa(a,b,c){function d(h){h=c(h);h.length!==a.length&&Ra("Mismatched type converter count");for(var n=0;n<a.length;++n)R(a[n],h[n])}a.forEach(function(h){Ma[h]=b});var e=Array(b.length),g=[],l=0;b.forEach(function(h,n){O.hasOwnProperty(h)?e[n]=O[h]:(g.push(h),N.hasOwnProperty(h)||(N[h]=[]),N[h].push(function(){e[n]=O[h];++l;l===g.length&&d(e)}))});0===g.length&&d(e)}
function R(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(O.hasOwnProperty(a)){if(c.ea)return;Q("Cannot register type '"+d+"' twice")}O[a]=b;delete Ma[a];N.hasOwnProperty(a)&&(b=N[a],delete N[a],b.forEach(function(e){e()}))}function Ta(a){Q(a.C.G.F.name+" instance already deleted")}var Ua=!1;function Va(){}
function Wa(a){--a.count.value;0===a.count.value&&(a.H?a.I.N(a.H):a.G.F.N(a.D))}function Xa(a){if("undefined"===typeof FinalizationGroup)return Xa=function(b){return b},a;Ua=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.D?Wa(c):console.warn("object already deleted: "+c.D)});Xa=function(b){Ua.register(b,b.C,b.C);return b};Va=function(b){Ua.unregister(b.C)};return Xa(a)}var Ya=void 0,Za=[];function $a(){for(;Za.length;){var a=Za.pop();a.C.O=!1;a["delete"]()}}
function S(){}var ab={};function bb(a,b,c){if(void 0===a[b].K){var d=a[b];a[b]=function(){a[b].K.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].K+")!");return a[b].K[arguments.length].apply(this,arguments)};a[b].K=[];a[b].K[d.T]=d}}
function cb(a,b){f.hasOwnProperty(a)?(Q("Cannot register public name '"+a+"' twice"),bb(f,a,a),f.hasOwnProperty(void 0)&&Q("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),f[a].K[void 0]=b):f[a]=b}function db(a,b,c,d,e,g,l,h){this.name=a;this.constructor=b;this.P=c;this.N=d;this.J=e;this.ba=g;this.S=l;this.aa=h;this.ha=[]}
function eb(a,b,c){for(;b!==c;)b.S||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.S(a),b=b.J;return a}function fb(a,b){if(null===b)return this.X&&Q("null is not a valid "+this.name),0;b.C||Q('Cannot pass "'+V(b)+'" as a '+this.name);b.C.D||Q("Cannot pass deleted object as a pointer of type "+this.name);return eb(b.C.D,b.C.G.F,this.F)}
function ib(a,b){if(null===b){this.X&&Q("null is not a valid "+this.name);if(this.V){var c=this.ia();null!==a&&a.push(this.N,c);return c}return 0}b.C||Q('Cannot pass "'+V(b)+'" as a '+this.name);b.C.D||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.U&&b.C.G.U&&Q("Cannot convert argument of type "+(b.C.I?b.C.I.name:b.C.G.name)+" to parameter type "+this.name);c=eb(b.C.D,b.C.G.F,this.F);if(this.V)switch(void 0===b.C.H&&Q("Passing raw pointer to smart pointer is illegal"),this.qa){case 0:b.C.I===
this?c=b.C.H:Q("Cannot convert argument of type "+(b.C.I?b.C.I.name:b.C.G.name)+" to parameter type "+this.name);break;case 1:c=b.C.H;break;case 2:if(b.C.I===this)c=b.C.H;else{var d=b.clone();c=this.ja(c,jb(function(){d["delete"]()}));null!==a&&a.push(this.N,c)}break;default:Q("Unsupporting sharing policy")}return c}
function kb(a,b){if(null===b)return this.X&&Q("null is not a valid "+this.name),0;b.C||Q('Cannot pass "'+V(b)+'" as a '+this.name);b.C.D||Q("Cannot pass deleted object as a pointer of type "+this.name);b.C.G.U&&Q("Cannot convert argument of type "+b.C.G.name+" to parameter type "+this.name);return eb(b.C.D,b.C.G.F,this.F)}function lb(a){return this.fromWireType(F[a>>2])}function mb(a,b,c){if(b===c)return a;if(void 0===c.J)return null;a=mb(a,b,c.J);return null===a?null:c.aa(a)}var nb={};
function ob(a,b){for(void 0===b&&Q("ptr should not be undefined");a.J;)b=a.S(b),a=a.J;return nb[b]}function pb(a,b){b.G&&b.D||Ra("makeClassHandle requires ptr and ptrType");!!b.I!==!!b.H&&Ra("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Xa(Object.create(a,{C:{value:b}}))}function W(a,b,c,d){this.name=a;this.F=b;this.X=c;this.U=d;this.V=!1;this.N=this.ja=this.ia=this.Z=this.qa=this.ga=void 0;void 0!==b.J?this.toWireType=ib:(this.toWireType=d?fb:kb,this.L=null)}
function qb(a,b){f.hasOwnProperty(a)||Ra("Replacing nonexistant public symbol");f[a]=b;f[a].T=void 0}function rb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=f["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=H.get(b).apply(null,c);return d}}
function X(a,b){a=K(a);var c=a.includes("j")?rb(a,b):H.get(b);"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var sb=void 0;function tb(a){a=ub(a);var b=K(a);Y(a);return b}function vb(a,b){function c(g){e[g]||O[g]||(Ma[g]?Ma[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new sb(a+": "+d.map(tb).join([", "]));}function wb(a,b){for(var c=[],d=0;d<a;d++)c.push(D[(b>>2)+d]);return c}function xb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function yb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Oa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}var zb=[],Z=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function jb(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=zb.length?zb.pop():Z.length;Z[b]={ka:1,value:a};return b}}function V(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Ab(a,b){switch(b){case 2:return function(c){return this.fromWireType(xa[c>>2])};case 3:return function(c){return this.fromWireType(ya[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Bb(a,b,c){switch(b){case 0:return c?function(d){return E[d]}:function(d){return B[d]};case 1:return c?function(d){return C[d>>1]}:function(d){return qa[d>>1]};case 2:return c?function(d){return D[d>>2]}:function(d){return F[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}for(var Cb=[null,[],[]],Db=Array(256),Eb=0;256>Eb;++Eb)Db[Eb]=String.fromCharCode(Eb);La=Db;P=f.BindingError=Pa("BindingError");Qa=f.InternalError=Pa("InternalError");
S.prototype.isAliasOf=function(a){if(!(this instanceof S&&a instanceof S))return!1;var b=this.C.G.F,c=this.C.D,d=a.C.G.F;for(a=a.C.D;b.J;)c=b.S(c),b=b.J;for(;d.J;)a=d.S(a),d=d.J;return b===d&&c===a};S.prototype.clone=function(){this.C.D||Ta(this);if(this.C.R)return this.C.count.value+=1,this;var a=Xa,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.C;a=a(c.call(b,d,{C:{value:{count:e.count,O:e.O,R:e.R,D:e.D,G:e.G,H:e.H,I:e.I}}}));a.C.count.value+=1;a.C.O=!1;return a};
S.prototype["delete"]=function(){this.C.D||Ta(this);this.C.O&&!this.C.R&&Q("Object already scheduled for deletion");Va(this);Wa(this.C);this.C.R||(this.C.H=void 0,this.C.D=void 0)};S.prototype.isDeleted=function(){return!this.C.D};S.prototype.deleteLater=function(){this.C.D||Ta(this);this.C.O&&!this.C.R&&Q("Object already scheduled for deletion");Za.push(this);1===Za.length&&Ya&&Ya($a);this.C.O=!0;return this};W.prototype.da=function(a){this.Z&&(a=this.Z(a));return a};
W.prototype.Y=function(a){this.N&&this.N(a)};W.prototype.argPackAdvance=8;W.prototype.readValueFromPointer=lb;W.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
W.prototype.fromWireType=function(a){function b(){return this.V?pb(this.F.P,{G:this.ga,D:c,I:this,H:a}):pb(this.F.P,{G:this,D:a})}var c=this.da(a);if(!c)return this.Y(a),null;var d=ob(this.F,c);if(void 0!==d){if(0===d.C.count.value)return d.C.D=c,d.C.H=a,d.clone();d=d.clone();this.Y(a);return d}d=this.F.ba(c);d=ab[d];if(!d)return b.call(this);d=this.U?d.$:d.pointerType;var e=mb(c,this.F,d.F);return null===e?b.call(this):this.V?pb(d.F.P,{G:d,D:e,I:this,H:a}):pb(d.F.P,{G:d,D:e})};
f.getInheritedInstanceCount=function(){return Object.keys(nb).length};f.getLiveInheritedInstances=function(){var a=[],b;for(b in nb)nb.hasOwnProperty(b)&&a.push(nb[b]);return a};f.flushPendingDeletes=$a;f.setDelayFunction=function(a){Ya=a;Za.length&&Ya&&Ya($a)};sb=f.UnboundTypeError=Pa("UnboundTypeError");f.count_emval_handles=function(){for(var a=0,b=5;b<Z.length;++b)void 0!==Z[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<Z.length;++a)if(void 0!==Z[a])return Z[a];return null};
var Gb={d:function(a,b,c,d){y("Assertion failed: "+ma(a)+", at: "+[b?ma(b):"unknown filename",c,d?ma(d):"unknown function"])},t:function(a){return Fb(a+16)+16},n:function(a,b,c){(new Ia(a)).fa(b,c);Ja++;throw a;},o:function(){},i:function(a,b,c,d,e){var g=Ka(c);b=K(b);R(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var h=E;else if(2===c)h=C;else if(4===c)h=D;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(h[l>>g])},L:null})},m:function(a,b,c,d,e,g,l,h,n,k,m,p,u){m=K(m);g=X(e,g);h&&(h=X(l,h));k&&(k=X(n,k));u=X(p,u);var z=Na(m);cb(z,function(){vb("Cannot construct "+m+" due to unbound types",[d])});Sa([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var v=t.F;var q=v.P}else q=S.prototype;t=Oa(z,function(){if(Object.getPrototypeOf(this)!==G)throw new P("Use 'new' to construct "+m);if(void 0===w.M)throw new P(m+" has no accessible constructor");var L=w.M[arguments.length];if(void 0===
L)throw new P("Tried to invoke ctor of "+m+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(w.M).toString()+") parameters instead!");return L.apply(this,arguments)});var G=Object.create(q,{constructor:{value:t}});t.prototype=G;var w=new db(m,t,G,u,v,g,h,k);v=new W(m,w,!0,!1);q=new W(m+"*",w,!1,!1);var T=new W(m+" const*",w,!1,!0);ab[a]={pointerType:q,$:T};qb(z,t);return[v,q,T]})},l:function(a,b,c,d,e,g){0<b||y("Assertion failed: undefined");var l=wb(b,c);e=X(d,
e);var h=[g],n=[];Sa([],[a],function(k){k=k[0];var m="constructor "+k.name;void 0===k.F.M&&(k.F.M=[]);if(void 0!==k.F.M[b-1])throw new P("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+k.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");k.F.M[b-1]=function(){vb("Cannot construct "+k.name+" due to unbound types",l)};Sa([],l,function(p){k.F.M[b-1]=function(){arguments.length!==b-1&&Q(m+" called with "+
arguments.length+" arguments, expected "+(b-1));n.length=0;h.length=b;for(var u=1;u<b;++u)h[u]=p[u].toWireType(n,arguments[u-1]);u=e.apply(null,h);xb(n);return p[0].fromWireType(u)};return[]});return[]})},k:function(a,b,c,d,e,g,l,h){var n=wb(c,d);b=K(b);g=X(e,g);Sa([],[a],function(k){function m(){vb("Cannot call "+p+" due to unbound types",n)}k=k[0];var p=k.name+"."+b;h&&k.F.ha.push(b);var u=k.F.P,z=u[b];void 0===z||void 0===z.K&&z.className!==k.name&&z.T===c-2?(m.T=c-2,m.className=k.name,u[b]=m):
(bb(u,b,p),u[b].K[c-2]=m);Sa([],n,function(t){var v=p,q=k,G=g,w=t.length;2>w&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var T=null!==t[1]&&null!==q,L=!1;for(q=1;q<t.length;++q)if(null!==t[q]&&void 0===t[q].L){L=!0;break}var gb="void"!==t[0].name,M="",U="";for(q=0;q<w-2;++q)M+=(0!==q?", ":"")+"arg"+q,U+=(0!==q?", ":"")+"arg"+q+"Wired";v="return function "+Na(v)+"("+M+") {\nif (arguments.length !== "+(w-2)+") {\nthrowBindingError('function "+v+" called with ' + arguments.length + ' arguments, expected "+
(w-2)+" args!');\n}\n";L&&(v+="var destructors = [];\n");var hb=L?"destructors":"null";M="throwBindingError invoker fn runDestructors retType classParam".split(" ");G=[Q,G,l,xb,t[0],t[1]];T&&(v+="var thisWired = classParam.toWireType("+hb+", this);\n");for(q=0;q<w-2;++q)v+="var arg"+q+"Wired = argType"+q+".toWireType("+hb+", arg"+q+"); // "+t[q+2].name+"\n",M.push("argType"+q),G.push(t[q+2]);T&&(U="thisWired"+(0<U.length?", ":"")+U);v+=(gb?"var rv = ":"")+"invoker(fn"+(0<U.length?", ":"")+U+");\n";
if(L)v+="runDestructors(destructors);\n";else for(q=T?1:2;q<t.length;++q)w=1===q?"thisWired":"arg"+(q-2)+"Wired",null!==t[q].L&&(v+=w+"_dtor("+w+"); // "+t[q].name+"\n",M.push(w+"_dtor"),G.push(t[q].L));gb&&(v+="var ret = retType.fromWireType(rv);\nreturn ret;\n");M.push(v+"}\n");t=yb(M).apply(null,G);void 0===u[b].K?(t.T=c-2,u[b]=t):u[b].K[c-2]=t;return[]});return[]})},s:function(a,b){b=K(b);R(a,{name:b,fromWireType:function(c){var d=Z[c].value;4<c&&0===--Z[c].ka&&(Z[c]=void 0,zb.push(c));return d},
toWireType:function(c,d){return jb(d)},argPackAdvance:8,readValueFromPointer:lb,L:null})},h:function(a,b,c){c=Ka(c);b=K(b);R(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+V(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Ab(b,c),L:null})},c:function(a,b,c,d,e){function g(k){return k}b=K(b);-1===e&&(e=4294967295);var l=Ka(c);if(0===d){var h=32-8*c;g=function(k){return k<<
h>>>h}}var n=b.includes("unsigned");R(a,{name:b,fromWireType:g,toWireType:function(k,m){if("number"!==typeof m&&"boolean"!==typeof m)throw new TypeError('Cannot convert "'+V(m)+'" to '+this.name);if(m<d||m>e)throw new TypeError('Passing a number "'+V(m)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return n?m>>>0:m|0},argPackAdvance:8,readValueFromPointer:Bb(b,l,0!==d),L:null})},b:function(a,b,c){function d(g){g>>=2;var l=F;return new e(wa,
l[g+1],l[g])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=K(c);R(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ea:!0})},g:function(a,b){b=K(b);var c="std::string"===b;R(a,{name:b,fromWireType:function(d){var e=F[d>>2];if(c)for(var g=d+4,l=0;l<=e;++l){var h=d+4+l;if(l==e||0==B[h]){g=ma(g,h-g);if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=h+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(B[d+
4+l]);n=n.join("")}Y(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||Q("Cannot pass non-string to std::string");var l=(c&&g?function(){for(var k=0,m=0;m<e.length;++m){var p=e.charCodeAt(m);55296<=p&&57343>=p&&(p=65536+((p&1023)<<10)|e.charCodeAt(++m)&1023);127>=p?++k:k=2047>=p?k+2:65535>=p?k+3:k+4}return k}:function(){return e.length})(),h=Fb(4+l+1);F[h>>
2]=l;if(c&&g)na(e,h+4,l+1);else if(g)for(g=0;g<l;++g){var n=e.charCodeAt(g);255<n&&(Y(h),Q("String has UTF-16 code units that do not fit in 8 bits"));B[h+4+g]=n}else for(g=0;g<l;++g)B[h+4+g]=e[g];null!==d&&d.push(Y,h);return h},argPackAdvance:8,readValueFromPointer:lb,L:function(d){Y(d)}})},f:function(a,b,c){c=K(c);if(2===b){var d=pa;var e=ra;var g=sa;var l=function(){return qa};var h=1}else 4===b&&(d=ta,e=ua,g=va,l=function(){return F},h=2);R(a,{name:c,fromWireType:function(n){for(var k=F[n>>2],
m=l(),p,u=n+4,z=0;z<=k;++z){var t=n+4+z*b;if(z==k||0==m[t>>h])u=d(u,t-u),void 0===p?p=u:(p+=String.fromCharCode(0),p+=u),u=t+b}Y(n);return p},toWireType:function(n,k){"string"!==typeof k&&Q("Cannot pass non-string to C++ string type "+c);var m=g(k),p=Fb(4+m+b);F[p>>2]=m>>h;e(k,p+4,m+b);null!==n&&n.push(Y,p);return p},argPackAdvance:8,readValueFromPointer:lb,L:function(n){Y(n)}})},j:function(a,b){b=K(b);R(a,{sa:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},a:function(){y()},
q:function(a,b,c){B.copyWithin(a,b,b+c)},e:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ja.grow(Math.min(2147483648,d)-wa.byteLength+65535>>>16);za();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},r:function(a,b,c,d){for(var e=0,g=0;g<c;g++){for(var l=D[b+8*g>>2],h=D[b+(8*g+4)>>2],n=0;n<h;n++){var k=B[l+n],m=Cb[a];if(0===k||10===k){k=1===a?ha:A;var p;for(p=
0;m[p]&&!(NaN<=p);)++p;p=la.decode(m.subarray?m.subarray(0,p):new Uint8Array(m.slice(0,p)));k(p);m.length=0}else m.push(k)}e+=h}D[d>>2]=e;return 0},p:function(){}};
(function(){function a(e){f.asm=e.exports;ja=f.asm.u;za();H=f.asm.A;Ba.unshift(f.asm.v);I--;f.monitorRunDependencies&&f.monitorRunDependencies(I);0==I&&(null!==Ea&&(clearInterval(Ea),Ea=null),J&&(e=J,J=null,e()))}function b(e){a(e.instance)}function c(e){return Ga().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){A("failed to asynchronously prepare wasm: "+g);y(g)})}var d={a:Gb};I++;f.monitorRunDependencies&&f.monitorRunDependencies(I);if(f.instantiateWasm)try{return f.instantiateWasm(d,
a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ia||"function"!==typeof WebAssembly.instantiateStreaming||Fa.startsWith("data:application/octet-stream;base64,")||"function"!==typeof fetch?c(b):fetch(Fa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){A("wasm streaming compile failed: "+g);A("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
f.___wasm_call_ctors=function(){return(f.___wasm_call_ctors=f.asm.v).apply(null,arguments)};var Fb=f._malloc=function(){return(Fb=f._malloc=f.asm.w).apply(null,arguments)},Y=f._free=function(){return(Y=f._free=f.asm.x).apply(null,arguments)},ub=f.___getTypeName=function(){return(ub=f.___getTypeName=f.asm.y).apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return(f.___embind_register_native_and_builtin_types=f.asm.z).apply(null,arguments)};
f.dynCall_jiji=function(){return(f.dynCall_jiji=f.asm.B).apply(null,arguments)};var Hb;J=function Ib(){Hb||Jb();Hb||(J=Ib)};
function Jb(){function a(){if(!Hb&&(Hb=!0,f.calledRun=!0,!ka)){Ha(Ba);aa(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Ca.unshift(b)}Ha(Ca)}}if(!(0<I)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Da();Ha(Aa);0<I||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=Jb;
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();Jb();


  return Module.ready
}
);
})();
export default Module;