
var webp_enc = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(webp_enc) {
  webp_enc = webp_enc || {};

var d;d||(d=typeof webp_enc !== 'undefined' ? webp_enc : {});var n={},q;for(q in d)d.hasOwnProperty(q)&&(n[q]=d[q]);var r=!1,t=!1,aa=!1,ba=!1,ca=!1;r="object"===typeof window;t="function"===typeof importScripts;aa=(ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!r&&!t;ca=!r&&!aa&&!t;var u="",v,x,fa,ha;
if(aa)u=__dirname+"/",v=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,b?null:"utf8")},x=function(a){a=v(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||y("Assertion failed: undefined");return a},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),process.on("uncaughtException",function(a){throw a;}),process.on("unhandledRejection",y),d.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=
typeof read&&(v=function(a){return read(a)}),x=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||y("Assertion failed: undefined");return a},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(r||t)t?u=self.location.href:document.currentScript&&(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?
u=u.substr(0,u.lastIndexOf("/")+1):u="",v=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},t&&(x=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ia=d.print||console.log.bind(console),z=d.printErr||console.warn.bind(console);for(q in n)n.hasOwnProperty(q)&&(d[q]=n[q]);n=null;var ja={"f64-rem":function(a,b){return a%b},"debugger":function(){}},A;d.wasmBinary&&(A=d.wasmBinary);
"object"!==typeof WebAssembly&&z("no native wasm support detected");var C,ka=new WebAssembly.Table({initial:256,maximum:256,element:"anyfunc"}),la=!1,ma="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&ma)return ma.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|g);else{var k=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|k:(f&7)<<18|g<<12|k<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e}
function oa(a,b,c){var e=D;if(0<c){c=b+c-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(b>=c)break;e[b++]=g}else{if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63}e[b++]=128|g>>6&63}e[b++]=128|g&63}}e[b]=0}}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");
function pa(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,E,D,F,G,H,I,qa,ra;function ta(a){buffer=a;d.HEAP8=E=new Int8Array(a);d.HEAP16=F=new Int16Array(a);d.HEAP32=H=new Int32Array(a);d.HEAPU8=D=new Uint8Array(a);d.HEAPU16=G=new Uint16Array(a);d.HEAPU32=I=new Uint32Array(a);d.HEAPF32=qa=new Float32Array(a);d.HEAPF64=ra=new Float64Array(a)}var ua=d.TOTAL_MEMORY||16777216;d.wasmMemory?C=d.wasmMemory:C=new WebAssembly.Memory({initial:ua/65536});C&&(buffer=C.buffer);ua=buffer.byteLength;ta(buffer);
H[9180]=5279792;function K(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.ja;"number"===typeof c?void 0===b.da?d.dynCall_v(c):d.dynCall_vi(c,b.da):c(void 0===b.da?null:b.da)}}}var va=[],wa=[],xa=[],ya=[];function za(){var a=d.preRun.shift();va.unshift(a)}var M=0,Aa=null,N=null;d.preloadedImages={};d.preloadedAudios={};
function y(a){if(d.onAbort)d.onAbort(a);ia(a);z(a);la=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ba(){var a=O;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var O="webp_enc.wasm";if(!Ba()){var Ca=O;O=d.locateFile?d.locateFile(Ca,u):u+Ca}
function Da(){try{if(A)return new Uint8Array(A);if(x)return x(O);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}function Ea(){return A||!r&&!t||"function"!==typeof fetch?new Promise(function(a){a(Da())}):fetch(O,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+O+"'";return a.arrayBuffer()}).catch(function(){return Da()})}
d.asm=function(){function a(a){d.asm=a.exports;M--;d.monitorRunDependencies&&d.monitorRunDependencies(M);0==M&&(null!==Aa&&(clearInterval(Aa),Aa=null),N&&(a=N,N=null,a()))}function b(b){a(b.instance)}function c(a){return Ea().then(function(a){return WebAssembly.instantiate(a,e)}).then(a,function(a){z("failed to asynchronously prepare wasm: "+a);y(a)})}var e={env:Fa,wasi_unstable:Fa,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ja};M++;d.monitorRunDependencies&&d.monitorRunDependencies(M);
if(d.instantiateWasm)try{return d.instantiateWasm(e,a)}catch(f){return z("Module.instantiateWasm callback failed with error: "+f),!1}(function(){if(A||"function"!==typeof WebAssembly.instantiateStreaming||Ba()||"function"!==typeof fetch)return c(b);fetch(O,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,e).then(b,function(a){z("wasm streaming compile failed: "+a);z("falling back to ArrayBuffer instantiation");c(b)})})})();return{}};wa.push({ja:function(){Ga()}});
var Ha=[null,[],[]];function Ia(){return 0}function Ja(){return 0}function Ka(a,b,c,e){try{for(var f=0,g=0;g<c;g++){for(var k=H[b+8*g>>2],h=H[b+(8*g+4)>>2],p=0;p<h;p++){var l=D[k+p],w=Ha[a];0===l||10===l?((1===a?ia:z)(na(w,0)),w.length=0):w.push(l)}f+=h}H[e>>2]=f;return 0}catch(B){return"undefined"!==typeof FS&&B instanceof FS.ta||y(B),B.ua}}var P={};function La(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Q(a){return this.fromWireType(I[a>>2])}var R={},S={},Ma={};
function Na(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Oa(a,b){a=Na(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Pa(a){var b=Error,c=Oa(a,function(b){this.name=a;this.message=b;b=Error(b).stack;void 0!==b&&(this.stack=this.toString()+"\n"+b.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Qa=void 0;
function Ra(a,b,c){function e(b){b=c(b);if(b.length!==a.length)throw new Qa("Mismatched type converter count");for(var e=0;e<a.length;++e)T(a[e],b[e])}a.forEach(function(a){Ma[a]=b});var f=Array(b.length),g=[],k=0;b.forEach(function(a,b){S.hasOwnProperty(a)?f[b]=S[a]:(g.push(a),R.hasOwnProperty(a)||(R[a]=[]),R[a].push(function(){f[b]=S[a];++k;k===g.length&&e(f)}))});0===g.length&&e(f)}
function Sa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ta=void 0;function U(a){for(var b="";D[a];)b+=Ta[D[a++]];return b}var Ua=void 0;function V(a){throw new Ua(a);}
function T(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var e=b.name;a||V('type "'+e+'" must have a positive integer typeid pointer');if(S.hasOwnProperty(a)){if(c.na)return;V("Cannot register type '"+e+"' twice")}S[a]=b;delete Ma[a];R.hasOwnProperty(a)&&(b=R[a],delete R[a],b.forEach(function(a){a()}))}var Va=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Wa(a){4<a&&0===--W[a].ea&&(W[a]=void 0,Va.push(a))}function Ya(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Va.length?Va.pop():W.length;W[b]={ea:1,value:a};return b}}
function Za(a,b){var c=d;if(void 0===c[a].ba){var e=c[a];c[a]=function(){c[a].ba.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].ba+")!");return c[a].ba[arguments.length].apply(this,arguments)};c[a].ba=[];c[a].ba[e.ha]=e}}
function $a(a,b,c){d.hasOwnProperty(a)?((void 0===c||void 0!==d[a].ba&&void 0!==d[a].ba[c])&&V("Cannot register public name '"+a+"' twice"),Za(a,a),d.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),d[a].ba[c]=b):(d[a]=b,void 0!==c&&(d[a].wa=c))}
function ab(a,b,c){switch(b){case 0:return function(a){return this.fromWireType((c?E:D)[a])};case 1:return function(a){return this.fromWireType((c?F:G)[a>>1])};case 2:return function(a){return this.fromWireType((c?H:I)[a>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function bb(a){a=cb(a);var b=U(a);X(a);return b}function db(a,b){var c=S[a];void 0===c&&V(b+" has unknown type "+bb(a));return c}
function eb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function fb(a,b){switch(b){case 2:return function(a){return this.fromWireType(qa[a>>2])};case 3:return function(a){return this.fromWireType(ra[a>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function gb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Oa(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}function hb(a,b){for(var c=[],e=0;e<a;e++)c.push(H[(b>>2)+e]);return c}
function Y(a,b){a=U(a);if(void 0!==d["FUNCTION_TABLE_"+a])var c=d["FUNCTION_TABLE_"+a][b];else if("undefined"!==typeof FUNCTION_TABLE)c=FUNCTION_TABLE[b];else{c=d["dynCall_"+a];void 0===c&&(c=d["dynCall_"+a.replace(/f/g,"d")],void 0===c&&V("No dynCall invoker for signature: "+a));for(var e=[],f=1;f<a.length;++f)e.push("a"+f);f="return function "+("dynCall_"+a+"_"+b)+"("+e.join(", ")+") {\n";f+="    return dynCall(rawFunction"+(e.length?", ":"")+e.join(", ")+");\n";c=(new Function("dynCall","rawFunction",
f+"};\n"))(c,b)}"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var ib=void 0;function jb(a,b){function c(a){f[a]||S[a]||(Ma[a]?Ma[a].forEach(c):(e.push(a),f[a]=!0))}var e=[],f={};b.forEach(c);throw new ib(a+": "+e.map(bb).join([", "]));}
function kb(a,b,c){switch(b){case 0:return c?function(a){return E[a]}:function(a){return D[a]};case 1:return c?function(a){return F[a>>1]}:function(a){return G[a>>1]};case 2:return c?function(a){return H[a>>2]}:function(a){return I[a>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function lb(){return E.length}Qa=d.InternalError=Pa("InternalError");for(var mb=Array(256),nb=0;256>nb;++nb)mb[nb]=String.fromCharCode(nb);Ta=mb;Ua=d.BindingError=Pa("BindingError");
d.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};d.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};ib=d.UnboundTypeError=Pa("UnboundTypeError");
var Fa={j:function(a){return ob(a)},g:function(a){"uncaught_exception"in pb?pb.ga++:pb.ga=1;throw a;},q:function(){return Ia.apply(null,arguments)},r:function(){return Ja.apply(null,arguments)},p:function(){return Ka.apply(null,arguments)},o:function(a){var b=P[a];delete P[a];var c=b.oa,e=b.pa,f=b.fa,g=f.map(function(a){return a.ma}).concat(f.map(function(a){return a.ra}));Ra([a],g,function(a){var g={};f.forEach(function(b,c){var e=a[c],l=b.ka,p=b.la,h=a[c+f.length],k=b.qa,ea=b.sa;g[b.ia]={read:function(a){return e.fromWireType(l(p,
a))},write:function(a,b){var c=[];k(ea,a,h.toWireType(c,b));La(c)}}});return[{name:b.name,fromWireType:function(a){var b={},c;for(c in g)b[c]=g[c].read(a);e(a);return b},toWireType:function(a,b){for(var f in g)if(!(f in b))throw new TypeError("Missing field");var h=c();for(f in g)g[f].write(h,b[f]);null!==a&&a.push(e,h);return h},argPackAdvance:8,readValueFromPointer:Q,aa:e}]})},n:function(a,b,c,e,f){var g=Sa(c);b=U(b);T(a,{name:b,fromWireType:function(a){return!!a},toWireType:function(a,b){return b?
e:f},argPackAdvance:8,readValueFromPointer:function(a){if(1===c)var e=E;else if(2===c)e=F;else if(4===c)e=H;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(e[a>>g])},aa:null})},m:function(a,b){b=U(b);T(a,{name:b,fromWireType:function(a){var b=W[a].value;Wa(a);return b},toWireType:function(a,b){return Ya(b)},argPackAdvance:8,readValueFromPointer:Q,aa:null})},l:function(a,b,c,e){function f(){}c=Sa(c);b=U(b);f.values={};T(a,{name:b,constructor:f,fromWireType:function(a){return this.constructor.values[a]},
toWireType:function(a,b){return b.value},argPackAdvance:8,readValueFromPointer:ab(b,c,e),aa:null});$a(b,f)},k:function(a,b,c){var e=db(a,"enum");b=U(b);a=e.constructor;e=Object.create(e.constructor.prototype,{value:{value:c},constructor:{value:Oa(e.name+"_"+b,function(){})}});a.values[c]=e;a[b]=e},i:function(a,b,c){c=Sa(c);b=U(b);T(a,{name:b,fromWireType:function(a){return a},toWireType:function(a,b){if("number"!==typeof b&&"boolean"!==typeof b)throw new TypeError('Cannot convert "'+eb(b)+'" to '+
this.name);return b},argPackAdvance:8,readValueFromPointer:fb(b,c),aa:null})},e:function(a,b,c,e,f,g){var k=hb(b,c);a=U(a);f=Y(e,f);$a(a,function(){jb("Cannot call "+a+" due to unbound types",k)},b-1);Ra([],k,function(c){var e=[c[0],null].concat(c.slice(1)),l=c=a,k=f,h=e.length;2>h&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var sa=null!==e[1]&&!1,da=!1,m=1;m<e.length;++m)if(null!==e[m]&&void 0===e[m].aa){da=!0;break}var ea="void"!==e[0].name,J="",L="";
for(m=0;m<h-2;++m)J+=(0!==m?", ":"")+"arg"+m,L+=(0!==m?", ":"")+"arg"+m+"Wired";l="return function "+Na(l)+"("+J+") {\nif (arguments.length !== "+(h-2)+") {\nthrowBindingError('function "+l+" called with ' + arguments.length + ' arguments, expected "+(h-2)+" args!');\n}\n";da&&(l+="var destructors = [];\n");var Xa=da?"destructors":"null";J="throwBindingError invoker fn runDestructors retType classParam".split(" ");k=[V,k,g,La,e[0],e[1]];sa&&(l+="var thisWired = classParam.toWireType("+Xa+", this);\n");
for(m=0;m<h-2;++m)l+="var arg"+m+"Wired = argType"+m+".toWireType("+Xa+", arg"+m+"); // "+e[m+2].name+"\n",J.push("argType"+m),k.push(e[m+2]);sa&&(L="thisWired"+(0<L.length?", ":"")+L);l+=(ea?"var rv = ":"")+"invoker(fn"+(0<L.length?", ":"")+L+");\n";if(da)l+="runDestructors(destructors);\n";else for(m=sa?1:2;m<e.length;++m)h=1===m?"thisWired":"arg"+(m-2)+"Wired",null!==e[m].aa&&(l+=h+"_dtor("+h+"); // "+e[m].name+"\n",J.push(h+"_dtor"),k.push(e[m].aa));ea&&(l+="var ret = retType.fromWireType(rv);\nreturn ret;\n");
J.push(l+"}\n");e=gb(J).apply(null,k);m=b-1;if(!d.hasOwnProperty(c))throw new Qa("Replacing nonexistant public symbol");void 0!==d[c].ba&&void 0!==m?d[c].ba[m]=e:(d[c]=e,d[c].ha=m);return[]})},c:function(a,b,c,e,f){function g(a){return a}b=U(b);-1===f&&(f=4294967295);var k=Sa(c);if(0===e){var h=32-8*c;g=function(a){return a<<h>>>h}}var p=-1!=b.indexOf("unsigned");T(a,{name:b,fromWireType:g,toWireType:function(a,c){if("number"!==typeof c&&"boolean"!==typeof c)throw new TypeError('Cannot convert "'+
eb(c)+'" to '+this.name);if(c<e||c>f)throw new TypeError('Passing a number "'+eb(c)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+e+", "+f+"]!");return p?c>>>0:c|0},argPackAdvance:8,readValueFromPointer:kb(b,k,0!==e),aa:null})},b:function(a,b,c){function e(a){a>>=2;var b=I;return new f(b.buffer,b[a+1],b[a])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=U(c);T(a,{name:c,fromWireType:e,argPackAdvance:8,
readValueFromPointer:e},{na:!0})},h:function(a,b){b=U(b);var c="std::string"===b;T(a,{name:b,fromWireType:function(a){var b=I[a>>2];if(c){var e=D[a+4+b],k=0;0!=e&&(k=e,D[a+4+b]=0);var h=a+4;for(e=0;e<=b;++e){var p=a+4+e;if(0==D[p]){h=h?na(D,h,void 0):"";if(void 0===l)var l=h;else l+=String.fromCharCode(0),l+=h;h=p+1}}0!=k&&(D[a+4+b]=k)}else{l=Array(b);for(e=0;e<b;++e)l[e]=String.fromCharCode(D[a+4+e]);l=l.join("")}X(a);return l},toWireType:function(a,b){b instanceof ArrayBuffer&&(b=new Uint8Array(b));
var e="string"===typeof b;e||b instanceof Uint8Array||b instanceof Uint8ClampedArray||b instanceof Int8Array||V("Cannot pass non-string to std::string");var f=(c&&e?function(){for(var a=0,c=0;c<b.length;++c){var e=b.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|b.charCodeAt(++c)&1023);127>=e?++a:a=2047>=e?a+2:65535>=e?a+3:a+4}return a}:function(){return b.length})(),h=ob(4+f+1);I[h>>2]=f;if(c&&e)oa(b,h+4,f+1);else if(e)for(e=0;e<f;++e){var p=b.charCodeAt(e);255<p&&(X(h),V("String has UTF-16 code units that do not fit in 8 bits"));
D[h+4+e]=p}else for(e=0;e<f;++e)D[h+4+e]=b[e];null!==a&&a.push(X,h);return h},argPackAdvance:8,readValueFromPointer:Q,aa:function(a){X(a)}})},C:function(a,b,c){c=U(c);if(2===b){var e=function(){return G};var f=1}else 4===b&&(e=function(){return I},f=2);T(a,{name:c,fromWireType:function(a){for(var b=e(),c=I[a>>2],g=Array(c),l=a+4>>f,w=0;w<c;++w)g[w]=String.fromCharCode(b[l+w]);X(a);return g.join("")},toWireType:function(a,c){var g=c.length,k=ob(4+g*b),l=e();I[k>>2]=g;for(var w=k+4>>f,B=0;B<g;++B)l[w+
B]=c.charCodeAt(B);null!==a&&a.push(X,k);return k},argPackAdvance:8,readValueFromPointer:Q,aa:function(a){X(a)}})},B:function(a,b,c,e,f,g){P[a]={name:U(b),oa:Y(c,e),pa:Y(f,g),fa:[]}},d:function(a,b,c,e,f,g,k,h,p,l){P[a].fa.push({ia:U(b),ma:c,ka:Y(e,f),la:g,ra:k,qa:Y(h,p),sa:l})},A:function(a,b){b=U(b);T(a,{va:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},z:Wa,y:function(a){4<a&&(W[a].ea+=1)},x:function(a,b){a=db(a,"_emval_take_value");a=a.readValueFromPointer(b);
return Ya(a)},__memory_base:1024,__table_base:0,f:function(){y()},w:lb,v:function(a,b,c){D.set(D.subarray(b,b+c),a)},u:function(a){if(2147418112<a)return!1;for(var b=Math.max(lb(),16777216);b<a;)536870912>=b?b=pa(2*b):b=Math.min(pa((3*b+2147483648)/4),2147418112);a:{try{C.grow(b-buffer.byteLength+65535>>16);ta(C.buffer);var c=1;break a}catch(e){}c=void 0}return c?!0:!1},t:function(a){return Math.log(a)/Math.LN10},a:y,memory:C,s:function(){},table:ka},qb=d.asm({},Fa,buffer);d.asm=qb;
var pb=d.__ZSt18uncaught_exceptionv=function(){return d.asm.D.apply(null,arguments)};d.___embind_register_native_and_builtin_types=function(){return d.asm.E.apply(null,arguments)};var cb=d.___getTypeName=function(){return d.asm.F.apply(null,arguments)},X=d._free=function(){return d.asm.G.apply(null,arguments)},ob=d._malloc=function(){return d.asm.H.apply(null,arguments)},Ga=d.globalCtors=function(){return d.asm.$.apply(null,arguments)};d.dynCall_diiii=function(){return d.asm.I.apply(null,arguments)};
d.dynCall_fii=function(){return d.asm.J.apply(null,arguments)};d.dynCall_i=function(){return d.asm.K.apply(null,arguments)};d.dynCall_ii=function(){return d.asm.L.apply(null,arguments)};d.dynCall_iidiiii=function(){return d.asm.M.apply(null,arguments)};d.dynCall_iii=function(){return d.asm.N.apply(null,arguments)};d.dynCall_iiii=function(){return d.asm.O.apply(null,arguments)};d.dynCall_iiiiii=function(){return d.asm.P.apply(null,arguments)};
d.dynCall_iiiiiii=function(){return d.asm.Q.apply(null,arguments)};d.dynCall_jiji=function(){return d.asm.R.apply(null,arguments)};d.dynCall_v=function(){return d.asm.S.apply(null,arguments)};d.dynCall_vi=function(){return d.asm.T.apply(null,arguments)};d.dynCall_vii=function(){return d.asm.U.apply(null,arguments)};d.dynCall_viif=function(){return d.asm.V.apply(null,arguments)};d.dynCall_viii=function(){return d.asm.W.apply(null,arguments)};d.dynCall_viiii=function(){return d.asm.X.apply(null,arguments)};
d.dynCall_viiiii=function(){return d.asm.Y.apply(null,arguments)};d.dynCall_viiiiii=function(){return d.asm.Z.apply(null,arguments)};d.dynCall_viiiiiiiii=function(){return d.asm._.apply(null,arguments)};d.asm=qb;var Z;d.then=function(a){if(Z)a(d);else{var b=d.onRuntimeInitialized;d.onRuntimeInitialized=function(){b&&b();a(d)}}return d};N=function rb(){Z||sb();Z||(N=rb)};
function sb(){function a(){if(!Z&&(Z=!0,!la)){K(wa);K(xa);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var a=d.postRun.shift();ya.unshift(a)}K(ya)}}if(!(0<M)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)za();K(va);0<M||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}d.run=sb;
if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();sb();


  return webp_enc
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = webp_enc;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return webp_enc; });
    else if (typeof exports === 'object')
      exports["webp_enc"] = webp_enc;
    