declare module '@webcomponents/custom-elements';

// Patch Worker to ignore `importScripts("x.css")` generated by Parcel:
const W = self.Worker;
self.Worker = function (url: string | URL, options?: WorkerOptions) {
  const code = `importScripts = (function(){return this.apply(self,[].slice.call(arguments).filter(function(x){return !/\\.css$/i.test(x)}))}).bind(importScripts)\nimportScripts(${JSON.stringify(url)})`;
  return new W(URL.createObjectURL(new Blob([code], { type: 'text/javascript' })), options);
} as any as (typeof Worker);

function init() {
  require('./init-app.tsx');
}

if (!('customElements' in self)) {
  import('@webcomponents/custom-elements').then(init);
} else {
  init();
}

if (typeof process.env.PRERENDER === 'undefined') {
  // Determine the current display mode.
  let displayMode = 'browser';
  const mqStandAlone = '(display-mode: standalone)';
  if (navigator.standalone || window.matchMedia(mqStandAlone).matches) {
    displayMode = 'standalone';
  }
  // Setup analytics
  window.ga = window.ga || ((...args) => (ga.q = ga.q || []).push(args));
  ga('create', 'UA-128752250-1', 'auto');
  ga('set', 'transport', 'beacon');
  ga('set', 'dimension1', displayMode);
  ga('send', 'pageview', '/index.html', { title: 'Squoosh' });
  // Load the GA script
  const s = document.createElement('script');
  s.src = 'https://www.google-analytics.com/analytics.js';
  document.head!.appendChild(s);
}
