
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa,ca;g.ready=new Promise(function(a,b){aa=a;ca=b});var r={},t;for(t in g)g.hasOwnProperty(t)&&(r[t]=g[t]);var u="",da;u=self.location.href;_scriptDir&&(u=_scriptDir);0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="";da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var v=g.printErr||console.warn.bind(console);
for(t in r)r.hasOwnProperty(t)&&(g[t]=r[t]);r=null;var z;g.wasmBinary&&(z=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&A("no native wasm support detected");var ea,fa=!1,ha=new TextDecoder("utf8");
function ia(a,b,c){var d=B;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}}var ja=new TextDecoder("utf-16le");
function ka(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&C[c];)++c;return ja.decode(B.subarray(a,c<<1))}function la(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function ma(a){return 2*a.length}function na(a,b){for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function oa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var k=a.charCodeAt(++e);f=65536+((f&1023)<<10)|k&1023}F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function pa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var qa,G,B,D,C,F,H,ra,sa;
function ta(){var a=ea.buffer;qa=a;g.HEAP8=G=new Int8Array(a);g.HEAP16=D=new Int16Array(a);g.HEAP32=F=new Int32Array(a);g.HEAPU8=B=new Uint8Array(a);g.HEAPU16=C=new Uint16Array(a);g.HEAPU32=H=new Uint32Array(a);g.HEAPF32=ra=new Float32Array(a);g.HEAPF64=sa=new Float64Array(a)}var I,ua=[],va=[],wa=[];function xa(){var a=g.preRun.shift();ua.unshift(a)}var J=0,ya=null,K=null;g.preloadedImages={};g.preloadedAudios={};
function A(a){if(g.onAbort)g.onAbort(a);v(a);fa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ca(a);throw a;}var L=(new URL("webp_enc.wasm",import.meta.url)).toString();function za(){try{if(L==L&&z)return new Uint8Array(z);if(da)return da(L);throw"both async and sync fetching of the wasm failed";}catch(a){A(a)}}
function Aa(){return z||"function"!==typeof fetch?Promise.resolve().then(function(){return za()}):fetch(L,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+L+"'";return a.arrayBuffer()}).catch(function(){return za()})}function Ba(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.W;"number"===typeof c?void 0===b.H?I.get(c)():I.get(c)(b.H):c(void 0===b.H?null:b.H)}}}var M={};
function Ca(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function N(a){return this.fromWireType(H[a>>2])}var O={},P={},Q={};function Da(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ea(a,b){a=Da(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Fa(a){var b=Error,c=Ea(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Ga=void 0;
function Ha(a,b,c){function d(h){h=c(h);if(h.length!==a.length)throw new Ga("Mismatched type converter count");for(var n=0;n<a.length;++n)R(a[n],h[n])}a.forEach(function(h){Q[h]=b});var e=Array(b.length),f=[],k=0;b.forEach(function(h,n){P.hasOwnProperty(h)?e[n]=P[h]:(f.push(h),O.hasOwnProperty(h)||(O[h]=[]),O[h].push(function(){e[n]=P[h];++k;k===f.length&&d(e)}))});0===f.length&&d(e)}
function T(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ia=void 0;function U(a){for(var b="";B[a];)b+=Ia[B[a++]];return b}var Ja=void 0;function V(a){throw new Ja(a);}
function R(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||V('type "'+d+'" must have a positive integer typeid pointer');if(P.hasOwnProperty(a)){if(c.P)return;V("Cannot register type '"+d+"' twice")}P[a]=b;delete Q[a];O.hasOwnProperty(a)&&(b=O[a],delete O[a],b.forEach(function(e){e()}))}var Ka=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function La(a){4<a&&0===--W[a].I&&(W[a]=void 0,Ka.push(a))}function X(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ka.length?Ka.pop():W.length;W[b]={I:1,value:a};return b}}
function Ma(a,b){var c=g;if(void 0===c[a].G){var d=c[a];c[a]=function(){c[a].G.hasOwnProperty(arguments.length)||V("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].G+")!");return c[a].G[arguments.length].apply(this,arguments)};c[a].G=[];c[a].G[d.K]=d}}
function Na(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].G&&void 0!==g[a].G[c])&&V("Cannot register public name '"+a+"' twice"),Ma(a,a),g.hasOwnProperty(c)&&V("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].G[c]=b):(g[a]=b,void 0!==c&&(g[a].Y=c))}
function Oa(a,b,c){switch(b){case 0:return function(d){return this.fromWireType((c?G:B)[d])};case 1:return function(d){return this.fromWireType((c?D:C)[d>>1])};case 2:return function(d){return this.fromWireType((c?F:H)[d>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function Pa(a){a=Qa(a);var b=U(a);Y(a);return b}function Ra(a,b){var c=P[a];void 0===c&&V(b+" has unknown type "+Pa(a));return c}
function Sa(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Ta(a,b){switch(b){case 2:return function(c){return this.fromWireType(ra[c>>2])};case 3:return function(c){return this.fromWireType(sa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Ua(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ea(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}function Va(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function Wa(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=I.get(b).apply(null,c);return d}}function Z(a,b){a=U(a);var c=a.includes("j")?Wa(a,b):I.get(b);"function"!==typeof c&&V("unknown function pointer with signature "+a+": "+b);return c}var Xa=void 0;
function Ya(a,b){function c(f){e[f]||P[f]||(Q[f]?Q[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Xa(a+": "+d.map(Pa).join([", "]));}function Za(a,b,c){switch(b){case 0:return c?function(d){return G[d]}:function(d){return B[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return C[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return H[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var $a={};
function ab(){return"object"===typeof globalThis?globalThis:Function("return this")()}var bb={};Ga=g.InternalError=Fa("InternalError");for(var cb=Array(256),db=0;256>db;++db)cb[db]=String.fromCharCode(db);Ia=cb;Ja=g.BindingError=Fa("BindingError");g.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};Xa=g.UnboundTypeError=Fa("UnboundTypeError");
var fb={w:function(){},l:function(a){var b=M[a];delete M[a];var c=b.R,d=b.S,e=b.J,f=e.map(function(k){return k.O}).concat(e.map(function(k){return k.U}));Ha([a],f,function(k){var h={};e.forEach(function(n,l){var m=k[l],q=n.M,w=n.N,x=k[l+e.length],p=n.T,ba=n.V;h[n.L]={read:function(y){return m.fromWireType(q(w,y))},write:function(y,E){var S=[];p(ba,y,x.toWireType(S,E));Ca(S)}}});return[{name:b.name,fromWireType:function(n){var l={},m;for(m in h)l[m]=h[m].read(n);d(n);return l},toWireType:function(n,
l){for(var m in h)if(!(m in l))throw new TypeError('Missing field:  "'+m+'"');var q=c();for(m in h)h[m].write(q,l[m]);null!==n&&n.push(d,q);return q},argPackAdvance:8,readValueFromPointer:N,F:d}]})},p:function(){},s:function(a,b,c,d,e){var f=T(c);b=U(b);R(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var h=G;else if(2===c)h=D;else if(4===c)h=F;else throw new TypeError("Unknown boolean type size: "+b);
return this.fromWireType(h[k>>f])},F:null})},r:function(a,b){b=U(b);R(a,{name:b,fromWireType:function(c){var d=W[c].value;La(c);return d},toWireType:function(c,d){return X(d)},argPackAdvance:8,readValueFromPointer:N,F:null})},n:function(a,b,c,d){function e(){}c=T(c);b=U(b);e.values={};R(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:function(f,k){return k.value},argPackAdvance:8,readValueFromPointer:Oa(b,c,d),F:null});Na(b,e)},d:function(a,b,c){var d=
Ra(a,"enum");b=U(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ea(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},j:function(a,b,c){c=T(c);b=U(b);R(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Sa(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Ta(b,c),F:null})},h:function(a,b,c,d,e,f){var k=Va(b,c);a=U(a);e=Z(d,e);Na(a,
function(){Ya("Cannot call "+a+" due to unbound types",k)},b-1);Ha([],k,function(h){var n=a,l=a;h=[h[0],null].concat(h.slice(1));var m=e,q=h.length;2>q&&V("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var w=null!==h[1]&&!1,x=!1,p=1;p<h.length;++p)if(null!==h[p]&&void 0===h[p].F){x=!0;break}var ba="void"!==h[0].name,y="",E="";for(p=0;p<q-2;++p)y+=(0!==p?", ":"")+"arg"+p,E+=(0!==p?", ":"")+"arg"+p+"Wired";l="return function "+Da(l)+"("+y+") {\nif (arguments.length !== "+
(q-2)+") {\nthrowBindingError('function "+l+" called with ' + arguments.length + ' arguments, expected "+(q-2)+" args!');\n}\n";x&&(l+="var destructors = [];\n");var S=x?"destructors":"null";y="throwBindingError invoker fn runDestructors retType classParam".split(" ");m=[V,m,f,Ca,h[0],h[1]];w&&(l+="var thisWired = classParam.toWireType("+S+", this);\n");for(p=0;p<q-2;++p)l+="var arg"+p+"Wired = argType"+p+".toWireType("+S+", arg"+p+"); // "+h[p+2].name+"\n",y.push("argType"+p),m.push(h[p+2]);w&&(E=
"thisWired"+(0<E.length?", ":"")+E);l+=(ba?"var rv = ":"")+"invoker(fn"+(0<E.length?", ":"")+E+");\n";if(x)l+="runDestructors(destructors);\n";else for(p=w?1:2;p<h.length;++p)q=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==h[p].F&&(l+=q+"_dtor("+q+"); // "+h[p].name+"\n",y.push(q+"_dtor"),m.push(h[p].F));ba&&(l+="var ret = retType.fromWireType(rv);\nreturn ret;\n");y.push(l+"}\n");h=Ua(y).apply(null,m);p=b-1;if(!g.hasOwnProperty(n))throw new Ga("Replacing nonexistant public symbol");void 0!==g[n].G&&
void 0!==p?g[n].G[p]=h:(g[n]=h,g[n].K=p);return[]})},c:function(a,b,c,d,e){function f(l){return l}b=U(b);-1===e&&(e=4294967295);var k=T(c);if(0===d){var h=32-8*c;f=function(l){return l<<h>>>h}}var n=b.includes("unsigned");R(a,{name:b,fromWireType:f,toWireType:function(l,m){if("number"!==typeof m&&"boolean"!==typeof m)throw new TypeError('Cannot convert "'+Sa(m)+'" to '+this.name);if(m<d||m>e)throw new TypeError('Passing a number "'+Sa(m)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+
d+", "+e+"]!");return n?m>>>0:m|0},argPackAdvance:8,readValueFromPointer:Za(b,k,0!==d),F:null})},b:function(a,b,c){function d(f){f>>=2;var k=H;return new e(qa,k[f+1],k[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=U(c);R(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{P:!0})},k:function(a,b){b=U(b);var c="std::string"===b;R(a,{name:b,fromWireType:function(d){var e=H[d>>2];if(c)for(var f=d+4,k=0;k<=e;++k){var h=d+4+
k;if(k==e||0==B[h]){if(f){for(var n=f+(h-f),l=f;!(l>=n)&&B[l];)++l;f=ha.decode(B.subarray(f,l))}else f="";if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=h+1}}else{m=Array(e);for(k=0;k<e;++k)m[k]=String.fromCharCode(B[d+4+k]);m=m.join("")}Y(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||V("Cannot pass non-string to std::string");var k=(c&&
f?function(){for(var l=0,m=0;m<e.length;++m){var q=e.charCodeAt(m);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|e.charCodeAt(++m)&1023);127>=q?++l:l=2047>=q?l+2:65535>=q?l+3:l+4}return l}:function(){return e.length})(),h=eb(4+k+1);H[h>>2]=k;if(c&&f)ia(e,h+4,k+1);else if(f)for(f=0;f<k;++f){var n=e.charCodeAt(f);255<n&&(Y(h),V("String has UTF-16 code units that do not fit in 8 bits"));B[h+4+f]=n}else for(f=0;f<k;++f)B[h+4+f]=e[f];null!==d&&d.push(Y,h);return h},argPackAdvance:8,readValueFromPointer:N,
F:function(d){Y(d)}})},g:function(a,b,c){c=U(c);if(2===b){var d=ka;var e=la;var f=ma;var k=function(){return C};var h=1}else 4===b&&(d=na,e=oa,f=pa,k=function(){return H},h=2);R(a,{name:c,fromWireType:function(n){for(var l=H[n>>2],m=k(),q,w=n+4,x=0;x<=l;++x){var p=n+4+x*b;if(x==l||0==m[p>>h])w=d(w,p-w),void 0===q?q=w:(q+=String.fromCharCode(0),q+=w),w=p+b}Y(n);return q},toWireType:function(n,l){"string"!==typeof l&&V("Cannot pass non-string to C++ string type "+c);var m=f(l),q=eb(4+m+b);H[q>>2]=m>>
h;e(l,q+4,m+b);null!==n&&n.push(Y,q);return q},argPackAdvance:8,readValueFromPointer:N,F:function(n){Y(n)}})},m:function(a,b,c,d,e,f){M[a]={name:U(b),R:Z(c,d),S:Z(e,f),J:[]}},a:function(a,b,c,d,e,f,k,h,n,l){M[a].J.push({L:U(b),O:c,M:Z(d,e),N:f,U:k,T:Z(h,n),V:l})},t:function(a,b){b=U(b);R(a,{X:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},f:La,v:function(a){if(0===a)return X(ab());var b=$a[a];a=void 0===b?U(a):b;return X(ab()[a])},u:function(a){4<a&&(W[a].I+=1)},o:function(a,
b,c,d){a||V("Cannot use deleted val. handle = "+a);a=W[a].value;var e=bb[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var k="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)k+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",
k+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Ra,g,X);bb[b]=e}return e(a,c,d)},i:function(){A()},q:function(a,b,c){B.copyWithin(a,b,b+c)},e:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ea.grow(Math.min(2147483648,d)-qa.byteLength+65535>>>16);ta();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1}};
(function(){function a(e){g.asm=e.exports;ea=g.asm.x;ta();I=g.asm.D;va.unshift(g.asm.y);J--;g.monitorRunDependencies&&g.monitorRunDependencies(J);0==J&&(null!==ya&&(clearInterval(ya),ya=null),K&&(e=K,K=null,e()))}function b(e){a(e.instance)}function c(e){return Aa().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){v("failed to asynchronously prepare wasm: "+f);A(f)})}var d={a:fb};J++;g.monitorRunDependencies&&g.monitorRunDependencies(J);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return v("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||L.startsWith("data:application/octet-stream;base64,")||"function"!==typeof fetch?c(b):fetch(L,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){v("wasm streaming compile failed: "+f);v("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ca);return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.y).apply(null,arguments)};var eb=g._malloc=function(){return(eb=g._malloc=g.asm.z).apply(null,arguments)},Y=g._free=function(){return(Y=g._free=g.asm.A).apply(null,arguments)},Qa=g.___getTypeName=function(){return(Qa=g.___getTypeName=g.asm.B).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.C).apply(null,arguments)};var gb;
K=function hb(){gb||ib();gb||(K=hb)};
function ib(){function a(){if(!gb&&(gb=!0,g.calledRun=!0,!fa)){Ba(va);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();wa.unshift(b)}Ba(wa)}}if(!(0<J)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)xa();Ba(ua);0<J||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=ib;
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();ib();


  return Module.ready
}
);
})();
export default Module;