
var Module = (function() {
  var _scriptDir = import.meta.url;
  
  return (
function(Module) {
  Module = Module || {};


var g;g||(g=typeof Module !== 'undefined' ? Module : {});var ba,ca;g.ready=new Promise(function(a,b){ba=a;ca=b});var r={},t;for(t in g)g.hasOwnProperty(t)&&(r[t]=g[t]);var da,ea,fa,ha;da=function(a){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);return fa.readFileSync(a,null)};ea=function(a){a=da(a);a.buffer||(a=new Uint8Array(a));a.buffer||u("Assertion failed: undefined");return a};1<process.argv.length&&process.argv[1].replace(/\\/g,"/");process.argv.slice(2);
process.on("uncaughtException",function(a){throw a;});process.on("unhandledRejection",u);g.inspect=function(){return"[Emscripten Module object]"};g.print||console.log.bind(console);var v=g.printErr||console.warn.bind(console);for(t in r)r.hasOwnProperty(t)&&(g[t]=r[t]);r=null;var z;g.wasmBinary&&(z=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&u("no native wasm support detected");var ia,ja=!1,ka=new TextDecoder("utf8");
function la(a,b,c){var d=A;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0}}var ma=new TextDecoder("utf-16le");
function na(a,b){var c=a>>1;for(b=c+b/2;!(c>=b)&&B[c];)++c;return ma.decode(A.subarray(a,c<<1))}function oa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)C[b>>1]=a.charCodeAt(e),b+=2;C[b>>1]=0;return b-d}function pa(a){return 2*a.length}function qa(a,b){for(var c=0,d="";!(c>=b/4);){var e=D[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function ra(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}D[b>>2]=f;b+=4;if(b+4>c)break}D[b>>2]=0;return b-d}function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}var ta,F,A,C,B,D,G,ua,va;
function wa(){var a=ia.buffer;ta=a;g.HEAP8=F=new Int8Array(a);g.HEAP16=C=new Int16Array(a);g.HEAP32=D=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=B=new Uint16Array(a);g.HEAPU32=G=new Uint32Array(a);g.HEAPF32=ua=new Float32Array(a);g.HEAPF64=va=new Float64Array(a)}var H,xa=[],ya=[],za=[];function Aa(){var a=g.preRun.shift();xa.unshift(a)}var I=0,Ba=null,J=null;g.preloadedImages={};g.preloadedAudios={};
function u(a){if(g.onAbort)g.onAbort(a);v(a);ja=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ca(a);throw a;}var K=(new URL("webp_node_enc.wasm",import.meta.url)).toString();function Ca(){return Promise.resolve().then(function(){a:{try{if(K==K&&z){var a=new Uint8Array(z);break a}if(ea){a=ea(K);break a}throw"both async and sync fetching of the wasm failed";}catch(b){u(b)}a=void 0}return a})}
function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.W;"number"===typeof c?void 0===b.H?H.get(c)():H.get(c)(b.H):c(void 0===b.H?null:b.H)}}}var L={};function Ea(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function M(a){return this.fromWireType(G[a>>2])}var N={},O={},P={};function Fa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function Ga(a,b){a=Fa(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function Ha(a){var b=Error,c=Ga(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var Ia=void 0;function Ja(a,b,c){function d(h){h=c(h);if(h.length!==a.length)throw new Ia("Mismatched type converter count");for(var k=0;k<a.length;++k)Q(a[k],h[k])}a.forEach(function(h){P[h]=b});var e=Array(b.length),f=[],l=0;b.forEach(function(h,k){O.hasOwnProperty(h)?e[k]=O[h]:(f.push(h),N.hasOwnProperty(h)||(N[h]=[]),N[h].push(function(){e[k]=O[h];++l;l===f.length&&d(e)}))});0===f.length&&d(e)}
function S(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ka=void 0;function T(a){for(var b="";A[a];)b+=Ka[A[a++]];return b}var La=void 0;function U(a){throw new La(a);}
function Q(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||U('type "'+d+'" must have a positive integer typeid pointer');if(O.hasOwnProperty(a)){if(c.P)return;U("Cannot register type '"+d+"' twice")}O[a]=b;delete P[a];N.hasOwnProperty(a)&&(b=N[a],delete N[a],b.forEach(function(e){e()}))}var Ma=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];
function Na(a){4<a&&0===--V[a].I&&(V[a]=void 0,Ma.push(a))}function W(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Ma.length?Ma.pop():V.length;V[b]={I:1,value:a};return b}}
function Oa(a,b){var c=g;if(void 0===c[a].G){var d=c[a];c[a]=function(){c[a].G.hasOwnProperty(arguments.length)||U("Function '"+b+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+c[a].G+")!");return c[a].G[arguments.length].apply(this,arguments)};c[a].G=[];c[a].G[d.K]=d}}
function Pa(a,b,c){g.hasOwnProperty(a)?((void 0===c||void 0!==g[a].G&&void 0!==g[a].G[c])&&U("Cannot register public name '"+a+"' twice"),Oa(a,a),g.hasOwnProperty(c)&&U("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),g[a].G[c]=b):(g[a]=b,void 0!==c&&(g[a].Y=c))}
function Qa(a,b,c){switch(b){case 0:return function(d){return this.fromWireType((c?F:A)[d])};case 1:return function(d){return this.fromWireType((c?C:B)[d>>1])};case 2:return function(d){return this.fromWireType((c?D:G)[d>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function Ra(a){a=Sa(a);var b=T(a);X(a);return b}function Ta(a,b){var c=O[a];void 0===c&&U(b+" has unknown type "+Ra(a));return c}
function Ua(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Va(a,b){switch(b){case 2:return function(c){return this.fromWireType(ua[c>>2])};case 3:return function(c){return this.fromWireType(va[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Wa(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ga(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}function Xa(a,b){for(var c=[],d=0;d<a;d++)c.push(D[(b>>2)+d]);return c}
function Ya(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=H.get(b).apply(null,c);return d}}function Y(a,b){a=T(a);var c=a.includes("j")?Ya(a,b):H.get(b);"function"!==typeof c&&U("unknown function pointer with signature "+a+": "+b);return c}var Za=void 0;
function $a(a,b){function c(f){e[f]||O[f]||(P[f]?P[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Za(a+": "+d.map(Ra).join([", "]));}function ab(a,b,c){switch(b){case 0:return c?function(d){return F[d]}:function(d){return A[d]};case 1:return c?function(d){return C[d>>1]}:function(d){return B[d>>1]};case 2:return c?function(d){return D[d>>2]}:function(d){return G[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var bb={};
function cb(){return"object"===typeof globalThis?globalThis:Function("return this")()}var db={};Ia=g.InternalError=Ha("InternalError");for(var eb=Array(256),Z=0;256>Z;++Z)eb[Z]=String.fromCharCode(Z);Ka=eb;La=g.BindingError=Ha("BindingError");g.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};Za=g.UnboundTypeError=Ha("UnboundTypeError");
var gb={w:function(){},l:function(a){var b=L[a];delete L[a];var c=b.R,d=b.S,e=b.J,f=e.map(function(l){return l.O}).concat(e.map(function(l){return l.U}));Ja([a],f,function(l){var h={};e.forEach(function(k,m){var n=l[m],q=k.M,w=k.N,x=l[m+e.length],p=k.T,aa=k.V;h[k.L]={read:function(y){return n.fromWireType(q(w,y))},write:function(y,E){var R=[];p(aa,y,x.toWireType(R,E));Ea(R)}}});return[{name:b.name,fromWireType:function(k){var m={},n;for(n in h)m[n]=h[n].read(k);d(k);return m},toWireType:function(k,
m){for(var n in h)if(!(n in m))throw new TypeError('Missing field:  "'+n+'"');var q=c();for(n in h)h[n].write(q,m[n]);null!==k&&k.push(d,q);return q},argPackAdvance:8,readValueFromPointer:M,F:d}]})},p:function(){},s:function(a,b,c,d,e){var f=S(c);b=T(b);Q(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var h=F;else if(2===c)h=C;else if(4===c)h=D;else throw new TypeError("Unknown boolean type size: "+b);
return this.fromWireType(h[l>>f])},F:null})},r:function(a,b){b=T(b);Q(a,{name:b,fromWireType:function(c){var d=V[c].value;Na(c);return d},toWireType:function(c,d){return W(d)},argPackAdvance:8,readValueFromPointer:M,F:null})},n:function(a,b,c,d){function e(){}c=S(c);b=T(b);e.values={};Q(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:function(f,l){return l.value},argPackAdvance:8,readValueFromPointer:Qa(b,c,d),F:null});Pa(b,e)},d:function(a,b,c){var d=
Ta(a,"enum");b=T(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ga(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},j:function(a,b,c){c=S(c);b=T(b);Q(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Ua(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Va(b,c),F:null})},h:function(a,b,c,d,e,f){var l=Xa(b,c);a=T(a);e=Y(d,e);Pa(a,
function(){$a("Cannot call "+a+" due to unbound types",l)},b-1);Ja([],l,function(h){var k=[h[0],null].concat(h.slice(1)),m=h=a,n=e,q=k.length;2>q&&U("argTypes array size mismatch! Must at least get return value and 'this' types!");for(var w=null!==k[1]&&!1,x=!1,p=1;p<k.length;++p)if(null!==k[p]&&void 0===k[p].F){x=!0;break}var aa="void"!==k[0].name,y="",E="";for(p=0;p<q-2;++p)y+=(0!==p?", ":"")+"arg"+p,E+=(0!==p?", ":"")+"arg"+p+"Wired";m="return function "+Fa(m)+"("+y+") {\nif (arguments.length !== "+
(q-2)+") {\nthrowBindingError('function "+m+" called with ' + arguments.length + ' arguments, expected "+(q-2)+" args!');\n}\n";x&&(m+="var destructors = [];\n");var R=x?"destructors":"null";y="throwBindingError invoker fn runDestructors retType classParam".split(" ");n=[U,n,f,Ea,k[0],k[1]];w&&(m+="var thisWired = classParam.toWireType("+R+", this);\n");for(p=0;p<q-2;++p)m+="var arg"+p+"Wired = argType"+p+".toWireType("+R+", arg"+p+"); // "+k[p+2].name+"\n",y.push("argType"+p),n.push(k[p+2]);w&&(E=
"thisWired"+(0<E.length?", ":"")+E);m+=(aa?"var rv = ":"")+"invoker(fn"+(0<E.length?", ":"")+E+");\n";if(x)m+="runDestructors(destructors);\n";else for(p=w?1:2;p<k.length;++p)q=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==k[p].F&&(m+=q+"_dtor("+q+"); // "+k[p].name+"\n",y.push(q+"_dtor"),n.push(k[p].F));aa&&(m+="var ret = retType.fromWireType(rv);\nreturn ret;\n");y.push(m+"}\n");k=Wa(y).apply(null,n);p=b-1;if(!g.hasOwnProperty(h))throw new Ia("Replacing nonexistant public symbol");void 0!==g[h].G&&
void 0!==p?g[h].G[p]=k:(g[h]=k,g[h].K=p);return[]})},c:function(a,b,c,d,e){function f(m){return m}b=T(b);-1===e&&(e=4294967295);var l=S(c);if(0===d){var h=32-8*c;f=function(m){return m<<h>>>h}}var k=b.includes("unsigned");Q(a,{name:b,fromWireType:f,toWireType:function(m,n){if("number"!==typeof n&&"boolean"!==typeof n)throw new TypeError('Cannot convert "'+Ua(n)+'" to '+this.name);if(n<d||n>e)throw new TypeError('Passing a number "'+Ua(n)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+
d+", "+e+"]!");return k?n>>>0:n|0},argPackAdvance:8,readValueFromPointer:ab(b,l,0!==d),F:null})},b:function(a,b,c){function d(f){f>>=2;var l=G;return new e(ta,l[f+1],l[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=T(c);Q(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{P:!0})},k:function(a,b){b=T(b);var c="std::string"===b;Q(a,{name:b,fromWireType:function(d){var e=G[d>>2];if(c)for(var f=d+4,l=0;l<=e;++l){var h=d+4+
l;if(l==e||0==A[h]){if(f){for(var k=f+(h-f),m=f;!(m>=k)&&A[m];)++m;f=ka.decode(A.subarray(f,m))}else f="";if(void 0===n)var n=f;else n+=String.fromCharCode(0),n+=f;f=h+1}}else{n=Array(e);for(l=0;l<e;++l)n[l]=String.fromCharCode(A[d+4+l]);n=n.join("")}X(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||U("Cannot pass non-string to std::string");var l=(c&&
f?function(){for(var m=0,n=0;n<e.length;++n){var q=e.charCodeAt(n);55296<=q&&57343>=q&&(q=65536+((q&1023)<<10)|e.charCodeAt(++n)&1023);127>=q?++m:m=2047>=q?m+2:65535>=q?m+3:m+4}return m}:function(){return e.length})(),h=fb(4+l+1);G[h>>2]=l;if(c&&f)la(e,h+4,l+1);else if(f)for(f=0;f<l;++f){var k=e.charCodeAt(f);255<k&&(X(h),U("String has UTF-16 code units that do not fit in 8 bits"));A[h+4+f]=k}else for(f=0;f<l;++f)A[h+4+f]=e[f];null!==d&&d.push(X,h);return h},argPackAdvance:8,readValueFromPointer:M,
F:function(d){X(d)}})},g:function(a,b,c){c=T(c);if(2===b){var d=na;var e=oa;var f=pa;var l=function(){return B};var h=1}else 4===b&&(d=qa,e=ra,f=sa,l=function(){return G},h=2);Q(a,{name:c,fromWireType:function(k){for(var m=G[k>>2],n=l(),q,w=k+4,x=0;x<=m;++x){var p=k+4+x*b;if(x==m||0==n[p>>h])w=d(w,p-w),void 0===q?q=w:(q+=String.fromCharCode(0),q+=w),w=p+b}X(k);return q},toWireType:function(k,m){"string"!==typeof m&&U("Cannot pass non-string to C++ string type "+c);var n=f(m),q=fb(4+n+b);G[q>>2]=n>>
h;e(m,q+4,n+b);null!==k&&k.push(X,q);return q},argPackAdvance:8,readValueFromPointer:M,F:function(k){X(k)}})},m:function(a,b,c,d,e,f){L[a]={name:T(b),R:Y(c,d),S:Y(e,f),J:[]}},a:function(a,b,c,d,e,f,l,h,k,m){L[a].J.push({L:T(b),O:c,M:Y(d,e),N:f,U:l,T:Y(h,k),V:m})},t:function(a,b){b=T(b);Q(a,{X:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},f:Na,v:function(a){if(0===a)return W(cb());var b=bb[a];a=void 0===b?T(a):b;return W(cb()[a])},u:function(a){4<a&&(V[a].I+=1)},o:function(a,
b,c,d){a||U("Cannot use deleted val. handle = "+a);a=V[a].value;var e=db[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var l="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)l+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",
l+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Ta,g,W);db[b]=e}return e(a,c,d)},i:function(){u()},q:function(a,b,c){A.copyWithin(a,b,b+c)},e:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ia.grow(Math.min(2147483648,d)-ta.byteLength+65535>>>16);wa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1}};
(function(){function a(e){g.asm=e.exports;ia=g.asm.x;wa();H=g.asm.D;ya.unshift(g.asm.y);I--;g.monitorRunDependencies&&g.monitorRunDependencies(I);0==I&&(null!==Ba&&(clearInterval(Ba),Ba=null),J&&(e=J,J=null,e()))}function b(e){a(e.instance)}function c(e){return Ca().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){v("failed to asynchronously prepare wasm: "+f);u(f)})}var d={a:gb};I++;g.monitorRunDependencies&&g.monitorRunDependencies(I);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return v("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return z||"function"!==typeof WebAssembly.instantiateStreaming||K.startsWith("data:application/octet-stream;base64,")||"function"!==typeof fetch?c(b):fetch(K,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){v("wasm streaming compile failed: "+f);v("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ca);return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.y).apply(null,arguments)};var fb=g._malloc=function(){return(fb=g._malloc=g.asm.z).apply(null,arguments)},X=g._free=function(){return(X=g._free=g.asm.A).apply(null,arguments)},Sa=g.___getTypeName=function(){return(Sa=g.___getTypeName=g.asm.B).apply(null,arguments)};g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.C).apply(null,arguments)};var hb;
J=function ib(){hb||jb();hb||(J=ib)};
function jb(){function a(){if(!hb&&(hb=!0,g.calledRun=!0,!ja)){Da(ya);ba(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();za.unshift(b)}Da(za)}}if(!(0<I)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();Da(xa);0<I||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}g.run=jb;
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();jb();


  return Module.ready
}
);
})();
export default Module;